openrewrite/rewrite

- rewrite-core/src/main/java/org/openrewrite/Environment.java
- rewrite-core/src/main/java/org/openrewrite/Recipe.java
- rewrite-core/src/main/java/org/openrewrite/config/RecipeConfiguration.java
Downgraded ValidationException if recipe name not unique to a warning and created getter for Recipe so that the discover task I created could access the include and exclude values for a given recipe.
> Discover modifications

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11RefactorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/utilities/SpansMultipleLines.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaRefactorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/utilities/SpansMultipleLinesTest.kt
Created new Utilities folder because SpansMultipleLines because it didn't fit particularly well anywhere else since:
- You don't use it to find or search for things the way the stuff in org.openrewrite.java.search does
- It doesn't transform java code itself and it isn't a refactoring visitor like the visitors in org.openrewrite.java
> Moved SpansMultipleLines to new Utilities folder

- rewrite-core/src/main/java/org/openrewrite/Refactor.java
- rewrite-test/src/main/java/org/openrewrite/Assertions.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/RefactorTest.kt
Hey @jkschneider I was thinking that it might be convenient if `Refactor` would fail early only when being run by JUnit.
What do you think about this?
> Eagerly throw exceptions when running under junit

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11ParserVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
In some case, J.NewClass.encl can be Expression, not J.Ident. For
example,
getSomeInstance().new InnerClass();
MyClass.this.new InnerClass();
myClass.myField.new InnerClass();
> Change type of J.NewClass.encl to Expression

- .gitignore
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/CompilationUnitTest.kt
getSourceSet() includes first token of the package name since not jumping over the java source file name.
(Includes .gitignore changes for project imported into Eclipse)
> CU getSourceSet() should skip over java file name

- rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/AddImportTest.kt
This PR adds logic to correctly find method invocations in a compilation unit that belong to a statically imported class/method.
> Fix AddImport to handle static method imports better

- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
> Adding an instance check to reduce the work done in "deepEquals" checks.

- rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
- rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
- rewrite-maven/src/main/java/org/openrewrite/maven/MavenRefactorVisitor.java
- rewrite-maven/src/main/java/org/openrewrite/maven/MavenSettings.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeParentVersion.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenDownloader.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawMavenResolver.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawRepositories.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/Maven.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/MavenSettingsTest.kt
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/internal/RawPomTest.kt
I'm going to do some more testing, but I thought I'd get feedback on the basic approach. 
Essentially the mirrors information from settings.xml has to end up in `MavenDownloader` for it to matter, but `MavenDownloader`s can be freely instantiated anywhere, including places where settings.xml information isn't available. So I added a `MavenDownloader` field to `Maven` so that any visitors which might want to download something can access that per-constructed downloader rather than creating a new one.
> Add support for Maven repository mirrors in settings.xml

- rewrite-yaml/src/main/java/org/openrewrite/yaml/internal/YamlPrinter.java
part of: https://github.com/openrewrite/rewrite/issues/153
see: https://github.com/openrewrite/rewrite/blob/a1cbc9b257b669d3251b61fd80457095194aa932/rewrite-yaml/src/main/java/org/openrewrite/yaml/internal/PrintYaml.java#L24
Note that in 6.x in PrintYaml we haven't overridden the implementation of visitSequence and visitMapping leaving them to default, preventing the printing of their prefix and post in the same fashion. We've done the same thing here as in 6.x. So, at least for the time being, removing the comments from source and instead leaving out the assessment through issue-tracking. If anything this means there's something off about how prefixing is assigned to a mapping vs. mappingEntry. But, again, pulling the comments for the time being.
> Tidy YamlPrinter comments

- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/internal/YamlPrinter.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/tree/Yaml.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/DocumentTest.kt
Adds parsing and rendering logic to the Yaml.Document.End token, as described by the yaml spec (https://yaml.org/spec/1.1/#c-document-end). Is it rare to see? Yeah, it's a bit rare to see it in the wild, but it's out there.
example:
```yml
---
some: document
...
---
more: 
- documents
- go
- here
...
```
This additionally functions as the equivalent of a whitespace `suffix' for the end of documents.
> Yaml.Document.End document separators

- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlProcessor.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/CoalescePropertiesTest.kt
Small detail; the `group` test for CoalesceProperties in rewrite-yaml has always been commented out, but for the sake of keeping things up-to-date, just placing an `ignored` annotation on it
> un-comment-out rewrite-yaml test and move to ignored

- rewrite-java/src/main/java/org/openrewrite/java/OrderImports.java
While the Lombok `@With`-generated method should be smart enough to always return the same object when the given list of imports is the same object, there is no need to loop over all imports.
> Small optimization for OrderImports recipe

- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/ClassDeclTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/MethodDeclTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/VariableDeclsTest.kt
In 6.x, modifiers were extensions of Modifier, so [having the stream -> anyMatch -> getClass -> simpleName worked](https://github.com/openrewrite/rewrite/blob/292b9fc4fab400aaddfc85d8b4840a2dd03b5ead/rewrite-java/src/main/java/org/openrewrite/java/tree/J.java#L2247); now in 7.x that Modifier Type is an enum, this same logic causes the `getClass -> getSimpleName` to evaluate to just `Modifier`.
No obligation to merge this / keep the tests / keep the implementation, etc., as they're just included to show what I mean.
**As a sidenote**, it may be better to either replace `hasModifier` with a typesafe implementation (`hasModifier(Collection<J.Modifier>, J.Modifier)`, or just... removing it? As in, having to pass an actual `J.Modifier.Type.{Private,Public,etc.}`, etc., since in most other …
> hasModifier("...") only evaluates true when "Modifier"

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesVisitor.java
see https://github.com/openrewrite/rewrite/pull/204
It feels like this is a more appropriate means of traversing to check if immediately enclosed by parentheses, rather than using `getParent(2)` to cut through Container types?
> Cleaner parent cursoring on UnnecessaryParentheses

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanReturn.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanReturnVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/AutoFormatVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/MinimumViableSpacingVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/SimplifyBooleanReturnTest.kt
part of https://github.com/openrewrite/rewrite/issues/197
- Adapted `SimplifyBooleanReturn` recipe for 7.x. 
- Includes `visitReturn` for `MinimumViableSpacingVisitor` for autoformat calls
- adds `MinimumViableSpacingVisitor` to autoformat; appears it hasn't been part of the autoformat chain before?
> SimplifyBooleanReturn

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpression.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/SimplifyBooleanExpressionTest.kt
part of https://github.com/openrewrite/rewrite/issues/197
- Tried writing this in such a way that there was a single return on each `visitX` rather than multiple returns within the body.
- Doesn't have to be this way, though I do personally think it's easier to debug and follow the logic on.
- It's a bit harder to do with non-iso visitors, since the eventual return type will be different and may need to be cast around
- Performs a `maybeAutoFormat` on the compilation unit, due formatting being removed when we replace the entire `unary` or `binary`-- in lieu of being able to perform autoformat on the subtree being replaced, it's being formatted on the compilation unit. 
- Note, I feel like there's probably a better way of doing this than running autoformat on the entire CU.
> SimplifyBooleanExpression

- rewrite-java/src/main/java/org/openrewrite/java/RemoveImport.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveImportTest.kt
This is to resolve an issue with the `RemoveImport` where it does not remove a non-referenced static import.
> Remove import visitor deletes static named import

- rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
- rewrite-maven/src/main/java/org/openrewrite/maven/AddDependencyVisitor.java
- rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
- rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawMavenResolver.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/MavenParserTest.kt
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/internal/RawPomTest.kt
This doesn't include any behavioral changes to dependency resolution in the presence of pom-type dependencies. Maybe it should? At worst I expect the lack of special behavior for pom-type dependencies would result in an extra jar in the final list of dependencies.
Also remove unneeded continueOnError functionality which has been supplanted by onError.
Closes #227
>  Add missing Maven model elements: Add type to Pom.Dependency, add packaging to Pom 

- rewrite-test/src/main/kotlin/org/openrewrite/java/format/MinimumViableSpacingTest.kt
unit test for minimum viable spacing on return expressions which was introduced in https://github.com/openrewrite/rewrite/pull/217
minor, but, noticed a test for this was never introduced while doing other work with minimal viable spacing
also minor, but, this removes an unnecessary `,` in these unit tests which was causing minor warning
> MinimumViableSpacing unit test on return expressions

- rewrite-java/src/main/java/org/openrewrite/java/format/MinimumViableSpacingVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/MinimumViableSpacingTest.kt
closes https://github.com/openrewrite/rewrite/issues/268
Noticed this while working on https://github.com/openrewrite/rewrite/issues/197
This places at least one minimal spaces between `J.Modifier`'s and `TypeExpressions` on a variable declaration, as well as between the `typeExpression` and the variable identifier(s).
> MinimumViableSpacing on VariableDeclarations

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizeLocalVariables.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizeLocalVariablesVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/FinalizeLocalVariablesTest.kt
part of https://github.com/openrewrite/rewrite/issues/197
drafting issue body
- Tested with `RewriteJavaProjectOnDisk`
- Does NOT add `final` to MethodDeclarationParameterVariables, since those are not the same as a "true" `LocalVariable` (https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html)
- Does NOT add `final` for a Class `Field`s, since a `Field` != `LocalVariable`. That's not the technical term for it, dangit.
- ~~I feel like this may be more appropriate to rename to something besides `FinalLocalVariables`, since I feel like it may add confusion.~~ Renamed to `FinalizeLocalVariables`
> FinalizeLocalVariables recipe

- rewrite-core/src/main/java/org/openrewrite/config/Environment.java
- rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
This fix will:
- Identify by name Recipes having a null 'recipeList'.  Before the `YamlResourceLoader` would throw a Null Pointer Exception with out any context.
- Identify `activeRecipes` which are not associated with any loaded Recipes.  Before the invalid `activeRecipe` would be silently ignored.
> Declaritive and Active Recipe validation

- rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/SemanticallyEqualTest.kt
SemanticallyEqual would always be false when arguments are null
> SemanticallyEqual-No-Args-BugFix

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11ParserVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/CovariantEqualsVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizeLocalVariablesVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/HideUtilityClassConstructorVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/BlankLinesVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/MinimumViableSpacingVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeFormatVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/WrappingAndBracesVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/ClassDeclarationToString.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/MethodDeclarationToString.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/InsertAtCoordinates.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplatePrinter.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/Coordinates.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/SemanticallyEqualTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/AnnotationTest.kt
Annotations may occur mixed with modifiers and between type parameters and return type
in method declarations. Support this in rewrite's java parser and AST with a minimum
of incompatible change.
> issue #254: annotation locations

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/gradle-wrapper-validation.yml
- .github/workflows/publish.yml.disabled
see: https://github.com/openrewrite/rewrite/issues/324
Tested this on these two repositories:
- https://github.com/slugstack/slugstack-rewrite-java-definitions
- https://github.com/slugstack/slugstack-publishing-test
Will come back to activate the rest, e.g. pushing snapshots and actual build content, will need to do that after the `build.gradle.kts` has been updated, credentials added, and told circle-ci to not try to take command on publishing.
For now this is simply performs `build` and `test` in conjunction with circle-ci. You could release using normal practices and it'd be fine.
> github actions scaffolding precursor to direct releasing

- rewrite-java/src/main/java/org/openrewrite/java/internal/template/ExtractTrees.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt
JavaTemplate ExtractTrees.extract should remove any element not in the same scope as the one having the ending marker.
> JavaTemplate ExtractTrees.extract remove non-scope elements

- rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
- rewrite-java/src/test/kotlin/org/openrewrite/java/tree/SpaceTest.kt
fixing index out of bounds exception when double slash comment on first line
> multiline comment handles double slash comment on first line

- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Instantiating the classes via reflection is unnecessary given that their fully qualified names are compared.
> Remove reflective check in `TypeUtils.isAssignableTo`

- rewrite-maven/build.gradle.kts
- rewrite-maven/src/main/java/org/openrewrite/maven/cache/RocksdbMavenPomCache.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawMaven.java
Adding an implementation of Rewrite's Maven POM cache that leverages [Rocksdb](https://github.com/facebook/rocksdb) to store poms on the file system. This implementation has zero transitive dependencies because it is a JNI wrapper around a C++ library. This cache would be a good default for the rewrite-maven-plugin and will significantly speed up rewrite operations once the pom files have been cached. In one, unscientific, sample the time to run `mvn rewrite:fix` was reduced from 85 seconds to 19 seconds once pom files were cached.
> Adding an implementation of Maven Cache using rocksdb.

- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeParentVersion.java
After `UpgradeDependencyVersion` or `UpgradeParentVersion`, we want to delete any redundant versions specified further down by using `RemoveRedundantDependencyVersions`.
Fixes #344
> Add RemoveRedundantDependencyVersions as a do-next to the upgrade version recipes

- rewrite-yaml/src/main/java/org/openrewrite/yaml/FormatPreservingReader.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/internal/YamlPrinter.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/MappingTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/SequenceTest.kt
- ArrayIndexOutOfBoundsException fix in FormatPreservingReader
- Use a sliding buffer of characters in FormatPreservingReader to preserve prefixes, moving forward a prefixes are consumed, to avoid buffer overrun issues with large scalars
- fixes for extra delimiter characters (- and :) in mixtures of sequences containing mappings and vice versa
> fixes for several yaml parsing issues

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
- rewrite-maven/src/main/java/org/openrewrite/maven/RemoveDependency.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/RemoveDependencyTest.kt
When removing dependencies with a specific scope, the effective scope of the dependency related to the scope constraint is also evaluated. Fixes #422
> Removing dependencies with a specific scope considers the dependencies effective scope

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11Parser.java
- context.put(JavaFileManager.class, this.pfm); // happens in the javaFileManager when register is set to true.
- pfm.setLocation(StandardLocation.CLASS_PATH, classpath.stream().map(Path::toFile).collect(toList())); // #setLocation immediately calls asPaths and converts the files back to paths.
> reduced unnecessary operations.

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11ParserVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/SemanticallyEqualTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/MethodDeclarationTest.kt
> handle utf surrogate character literals

- rewrite-core/src/main/java/org/openrewrite/style/NamedStyles.java
- rewrite-core/src/main/java/org/openrewrite/style/Style.java
- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/style/BlankLinesStyle.java
- rewrite-java/src/main/java/org/openrewrite/java/style/SpacesStyle.java
- rewrite-java/src/main/java/org/openrewrite/java/style/StyleHelper.java
- rewrite-java/src/main/java/org/openrewrite/java/style/TabsAndIndentsStyle.java
- rewrite-java/src/main/java/org/openrewrite/java/style/UnnecessaryParenthesesStyle.java
- rewrite-java/src/test/kotlin/org/openrewrite/java/style/StyleHelperTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
resolves #212
- merge appropriate java styles with IntelliJ defaults at recipe run time
- TabsAndIndentsVisitor now handles mixed spaces and tabs in the original source, converting to the appropriate indentation character
> Style merging

- rewrite-java-11/build.gradle.kts
- rewrite-java-11/src/main/java/org/openrewrite/java/Java11Parser.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavaParserTest.kt
- Jonathan added byte aware classes.
- Adjusted the Stream concatenation to prioritize the byte array classes when provided.
- Overrode JavacFileManager#inferBinaryName so that type attributions work correctly.
- Explicitly tested only using the byte array classes for the test to ensure types were attributed in the tree without existing on the class path.
> Java parser byte classpath

- rewrite-maven/build.gradle.kts
- rewrite-maven/src/integTest/kotlin/org/openrewrite/maven/cache/RocksdbMavenPomCacheTest.kt
- rewrite-maven/src/main/java/org/openrewrite/maven/cache/RocksdbMavenPomCache.java
Enhancements RocksdbMavenPomCache to better manage the underlying rocksdb file cache:
Resource Cleanup:
- The Rocksdb library uses JNI to interact with the underlying file system and only one instance of the database may be pointed to the same workspace directory. To accommodate multiple cache instances using the same folder, the first cache will create the underlying RocksDB instance and any subsequent caches will use the same, thread-safe instance. However, closing the database can be a bit tricky because multiple caches may be using it. This PR adds a system shutdown hook to correctly close the underlying database when the process completes normally. It will also gracefully release any resources managed by the native (JNI) RocksDB library.  Killing the process in mid-operation does not …
> Management enhancements to the rocksdb maven cache

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/XmlParserXXEVulnerabilityFix.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/XmlParserXXEVulnerabilityFixTest.kt
Add Recipe for Sonar RSPEC-2755 - XML parsers should not be vulnerable to XXE attacks. Fixes #453
> Add Recipe - XML parsers should not be vulnerable to XXE attacks

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11ParserVisitor.java
When mapping javac's ASTs to rewrite's ASTs, care must be taken to ensure we do not invoke `complete()` on the symbol.  Most of the accessor methods on the ClassSymbol will implicitly call `complete()` and therefore, we must make sure to use the underlying fields of the symbol directly.
> Fix issue where parser fails when symbol is not on the class path

- rewrite-maven/src/integTest/kotlin/org/openrewrite/maven/MavenDependencyDownloadIntegTest.kt
- rewrite-maven/src/integTest/kotlin/org/openrewrite/maven/ParseMavenProjectOnDisk.kt
- rewrite-maven/src/main/java/org/openrewrite/maven/cache/ReadOnlyLocalMavenArtifactCache.java
- rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenArtifactHelper.java
If the `$USER_HOME/.m2/repository` directory is unwritable, it prevents `ReadOnlyLocalMavenArtifactCache` from initializing. To circumvent this, allow clients to pass a Path.
> Handle unwritable directory in MavenArtifactHelper by allowing client to specify maven local path

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseDiamondOperator.java
bugFix: prevents a new J.Empty with a different it from being created if J.Empty already exists.
> Add condition to check if the type is already J.Empty.

- rewrite-java/src/main/java/org/openrewrite/java/JavaIsoVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/TryCatchTest.kt
This PR fixes the navigation for resources in a try-with-resource code block. This has been resolved by overriding the `accept()` method in `J.Try.Resource` and adding a `visitTryResource` to JavaVisitor.
> Fixes #530 Fix Try-With-Resource Navigation

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/HideUtilityClassConstructorVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/HideUtilityClassConstructorTest.kt
see: https://github.com/openrewrite/rewrite/issues/538
see also: https://github.com/openrewrite/rewrite/issues/383
The unit test for identifying a main method was passing because the test was not labeled as being within a `package` (see: https://github.com/openrewrite/rewrite/issues/383). The test was updated to have a package declaration, and the method matcher was updated to use the fully-qualified enclosing class name directly.
> Fix hide-utility-cleanup visitor to identify main methods

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorTest.kt
This is to fix a null pointer exception thrown by the `JavaVisitor` when visiting a JLeftPadded or JRightPadded element having a null element.
> JavaVisitor handles JRightPadded and JLeftPadded having null element.

- rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java
In cases where a `Recipe` is being run in a multi-threaded context, it's not necessary to use a secondary pool, as the calling thread is already a worker thread. In this case passing `null` as the ForkJoinPool will result in directly executing the visitor.
> Add option to pass a null ForkJoinPool for direct execution

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FallThrough.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FallThroughStyle.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FallThroughVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/FallThroughTest.kt
https://github.com/openrewrite/rewrite/issues/197
Checks for fall-through in switch statements. Finds locations where a case contains Java code but lacks a break, return, throw or continue statement.
> FallThrough cleanup

- rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/RenameVariableTest.kt
fixes #533 refactors RenameVariable to rename identifiers in the same name scope as the target variable.
> Rewrite RenameVariable recipe that respects name scope.

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/HiddenField.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/HiddenFieldStyle.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/HiddenFieldVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/HiddenFieldTest.kt
part of https://github.com/openrewrite/rewrite/issues/197
Refactor local variables or parameters which shadow a field defined in the same class.
> HiddenField cleanup recipe

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11ParserVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavaTypeSerializerTest.kt
This change backs out the wildcard type and maps wildcards to their bound types.
> Mapping Wildcards into their bound types.

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
- rewrite-maven/src/main/java/org/openrewrite/maven/RemovePlugin.java
As the title implies-- same functional logic as `isDependencyTag`, etc., but matching on `plugin` tags within a pom.xml
> `isPluginTag` convenience for MavenVisitor

- rewrite-core/src/main/java/org/openrewrite/semver/VersionComparator.java
- rewrite-core/src/test/kotlin/org/openrewrite/semver/LatestReleaseTest.kt
- rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenArtifactHelper.java
Allow MavenArtifactHelper to coalesce latest.integration and
latest.release to an actual version from all repositories passed into
it.
> feat: Allow usage of latest.release and integration

- rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt
When looking at a method invocation alone you don't have enough information to construct a complete `JavaType.Method`. So attempt to lookup the type from the `JavaType.Method` flyweights map. This approach fails if there's a recipe which is creating new methods, or altering existing method signatures, and attempts to update invocations _before_ the new entry has ended up in the flyweights map. So this is on a best-effort basis, but it is at least _more_ correct than what we currently have. 
An approach would surmount this limitation would probably require users of this sort of template having to specify the full & exact method signature they're updating the invocation to have. 
I know we've shied away from providing a lookup into the contents of the JavaType.Method flyweights before and …
> Make a best-effort attempt to update the type of method invocations when updating their argument list with JavaTemplate

- rewrite-maven/src/main/java/org/openrewrite/maven/AddDependencyVisitor.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/AddDependencyTest.kt
If `AddDependency` is used in combination with a version selector, the visitor was incorrectly updating the pom model with the selector `2.3.x` instead of resolving the version to `2.3.3`. This can manifest later as an exception when other recipes expect the pom model to only contain fully-formed semantic versions. A specific example of where this fails is if you attempt to use both `AddDependency` and `UpgradeDependency` over the same artifact.
> Fixing AddDependency when using partial version selector

- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/UpgradePluginVersionTest.kt
see: https://github.com/openrewrite/rewrite/issues/570
see downstream issue which prompted this: https://github.com/openrewrite/rewrite-quarkus/issues/6
see: https://github.com/openrewrite/rewrite/issues/585
**This code looks wonky, I know. It's loosely based on upgradePluginDependency. Would be enhanced by virtue of having `pom` and `maven` model supports pluginManagement**
In order to enable upgrading a maven plugin to a different version, include a recipe for specifying a `version` to upgrade a plugin to a later version.
> `UpgradePluginVersion` -- ability to upgrade maven plugin version

- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
> Prevent index out of bound in TabsAndIndentsVisitor#shift(). fixes #521

- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaRecipeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/TypeValidator.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/CovariantEqualsTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/HiddenFieldTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/PrimitiveWrapperClassConstructorToValueOfTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
There are a lot more invariants we can enforce with this approach. This is just the start.
> Add validation to JavaRecipeTest that method invocations are type attributed

- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
This PR adds formatting for java docs and block comments. The whitespace is shifted separately to prevent characters in the text from being truncated. Fixes #652
> Adds formatting for javadocs and block comments.

- rewrite-maven/src/integTest/kotlin/org/openrewrite/maven/MavenArtifactHelperIntegTest.kt
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenMetadata.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
- rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenArtifactHelper.java
Allow MavenArtifactHelper to pull all information, not just the list of paths.
Also, allow MavenPomDownloader to return the latest dated version (snapshot or otherwise).
> feat: Refactor MavenArtifactHelper to include necessary data

- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
fixes https://github.com/openrewrite/rewrite/issues/660
> Set continuation indent when lambda body is a block with closing bracket is on a newline

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseDiamondOperator.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/UseDiamondOperatorTest.kt
This fix prevents the diamond operator from being applied when the "new" operation is a method invocation's receiver. 
```
class Test {
public static void test() {
ResponseBuilder<String> response = new ResponseBuilder<String>().entity("hello");
}
public static class ResponseBuilder<T> {
public ResponseBuilder<T> entity(T entity) {
return this;
}
}
}
```
This cannot be converted to : 
```
ResponseBuilder<String> response = new ResponseBuilder<>.entity("hello");
```
This would not compile because the type returned by "entity" would be `ResponseBuilder<Object>`
> Do not apply diamond operator in a method receiver.

- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
fixes https://github.com/openrewrite/rewrite/issues/679
> handle indents on lambdas when bodies are more invocations [#679]

- rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java
- rewrite-xml/src/main/java/org/openrewrite/xml/XmlParser.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
Currently parsing errors in resource parsers like XML, YAML, and Properties files will fail with the message of the error but not give specifics about which file caused the error making troubleshooting difficult.
This change adds the filename being parsed to the error message to aid troubleshooting.
> Add filename into the error message

- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
Added conditions to preserve the whitespace length in block comments if all the lines do not start with `*`.
Added clean up to JavaDoc comments that don't start with `*`
Fixes an issue that caused multiple cycles that surfaced after preventing String Index out of bounds.
Fixes an issue where the CRLF was being detected in the wrong order. 
The code is pretty complicated, since it prioritizes one sweep through the text of a JavaDoc/Block comment.
It was a challenge to convert tabs/space to the style, preserve whitespace length in a block, and maintain referential equality whenever possible in one pass.
> Preserve the whitespace length in Block Comments.

- rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangeKey.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangeValue.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/CopyValue.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteKey.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteProperty.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/InsertYaml.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangeKeyTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangePropertyKeyTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangeValueTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/CopyValueTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/DeleteKeyTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/DeletePropertyKeyTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/InsertYamlTest.kt
See #656
So we have feature parity between properties and yaml. 
I looked at existing XML recipes, but none seems to really need this option.
I think this will cover most needs for changing YAML and properties in projects.
> Optional fileMatcher option for YAML recipes

- rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodName.java
- rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Move J.FieldAccess#isFullyQualifiedReference(MethodMatcher) from J.FieldAccess to MethodMatcher
> fix: Move FQ ref check from J.FieldAccess to MethodMatcher

- rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYamlVisitor.java
- rewrite-yaml/src/test/kotlin/MergeYamlTest.kt
In order to accommodate use cases where we need to make complex changes to YAML, it is needed to have a `MergeYamlVisitor` that perform a deep merge on an object.
> Perform deep merge on YAML with a merge visitor

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RenameLocalVariablesToCamelCase.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RenameLocalVariablesToCamelCaseTest.kt
[While testing rename](https://github.com/openrewrite/rewrite-testing-frameworks/compare/refactor/reformat-local-variable-names-to-camel-case-Un436?w=1) local variables to camel test, discovered that recipe was making changes to instance variables in anonymous inner classes.
Exclude rewriting variables if within anon. inner class
> fix(camelcase): do not rewrite instance variables of anonymous inner classes

- rewrite-java/src/main/java/org/openrewrite/java/RemoveAnnotationVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveAnnotationTest.kt
Adds preservation of existing whitespace while removing a leading annotation if the list is > 1. fixes #728.
> Remove annotations from a list with size greater than 1.

- rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java
- rewrite-core/src/test/kotlin/org/openrewrite/internal/StringUtilsTest.kt
In order to do glob matching in recipe options we need to encapsulate the non-trivial task of evaluating two strings to see if they match based on a glob expression. Internally, this uses the JDK's `PathMatcher` and only supports the `glob:` syntax. 
This makes it possible to specify recipe options as:
`somevalue-*` and when you visit the scalar in the recipe, use this check to evaluate if the value matches the pattern.
> Add a StringUtils method to match two strings with a glob pattern

- rewrite-core/src/main/java/org/openrewrite/artifacts/ContainerImage.java
- rewrite-core/src/main/java/org/openrewrite/text/ContainerImage.java
This helper parses a text string into the constituent components of a container image name so they can be easily deconstructed and re-constructed.
> Add ContainerImage helper

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/StringLiteralEquality.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/StringLiteralEqualityTest.kt
Use `String.equals()` for value equality
see: http://cwe.mitre.org/data/definitions/597.html
see: https://rules.sonarsource.com/java/tag/suspicious/RSPEC-1698
Note: changing this from the original implementation to have the left-hand and right-hand operators remain in the same position. E.g., `str == "string"` should be `str.equals("string")`, and not change it to `"string".equals(str)`-- that may not necessarily be desired by end-users, and the functionality can be activated using `EqualsAvoidNull`. Additionally, fixing when the operator is notequals. This didn't handle != previously, but now it does, all good
> String Literal Equality cleanup

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoFinalizer.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/NoFinalizerTest.kt
Removes overridden/implemented method declarations of https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Object.html#finalize()
> No Finalizer cleanup

- rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/SpacesTest.kt
fixes https://github.com/openrewrite/rewrite/issues/785
> SpacesStyle.withBeforeParentheses.withMethodCall controls spacing on class constructors

- rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/AddImportTest.kt
This fixes how `addImports()` selects its insertion point to make minimal changes to a file's existing imports.
> Fixing the logic in addImports

- rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
- rewrite-java/src/main/java/org/openrewrite/java/style/IntelliJ.java
- rewrite-java/src/main/java/org/openrewrite/java/style/TabsAndIndentsStyle.java
- rewrite-java/src/test/kotlin/org/openrewrite/java/style/StyleHelperTest.kt
fixes #789
Added new line character counts of CRLF and LF to TabsAndIndentsStyle in Autodetect.
Similar to tabs and indents the code defaults to `\n` or prioritizes the more common practice of using `\n` if the counts are equal.
Note: the changes can't directly be tested, since IDEs normalize the new line characters automatically.
The new line count is primarily based on:
```
if (c == '\n') {
if (i == 0 || chars[i - 1] != '\r') {
```
> Added new line character stats to TabsAndIndentsStyle in Autodetect.

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/IndexOfReplaceableByContains.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/IndexOfReplaceableByContainsTest.kt
Inspired by https://github.com/openrewrite/rewrite/pull/814
>If the intent is merely to check inclusion of a value in a String or a List, the contains method is better suited to express this intent.
> String#indexOf and List#indexOf replaceable by contains

- rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/style/AutodetectTest.kt
- Added generation of longest common prefix across all imported packages.
- Autodetect#FindImportLayout will create new blocks based on the block pattern.
- Refactored Autodetect#getImportLayoutStyle.
fixes #796
> Refactored Autodetect#ImportLayoutStyleStatistics.

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnusedLocalVariables.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedLocalVariablesTest.kt
closes https://github.com/openrewrite/rewrite/issues/822
Following up with other related recipes, like https://github.com/openrewrite/rewrite/issues/821 -- will follow-up with an issue later for some of the search-related recipes we're seeing recurring in these recipes (e.g. `FindReadReferences`, etc.). For now erring on the side of caution with duplication in order to not make API exposures quite yet.
> Removed unused local variables

- rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/ChangePackageTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeTypeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaRecipeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/PadEmptyForLoopComponentsTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/RenameVariableTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/TypeValidator.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/BooleanChecksNotInvertedTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/MinimumSwitchCasesTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/SpacesTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
New way to configure more granular type validation suppression for `JavaRecipeTest.assertChanged()`.
I haven't merged TypeValidator and FindMissingTypes yet, but I will in the future
> TypeValidator also validates that Identifiers have type information. Fixes #868

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11TreeDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8TreeDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodParamPad.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodParamPadStyle.java
- rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java
- rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java
- rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTreeCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/MethodParamPadTest.kt
See #797 
I've included the formatting logic for `allowLineBreak` to remove newline characters in `MethodParamPadVisitor`. The alternative is to add this as a configurable style parameter to WrappingAndBracesStyle and have WrappingAndBracesVisitor take care of it. But it feels like it may be niche enough at the moment to allow it to stay in MethodParamPadVisitor. 
I'm happy to place the style/logic in `WrappingAndBraces` instead, though.
(Also note, I've placed this in the `cleanup` package, though I suppose there's no reason it couldn't go anywhere else such as format.)
> [#797] MethodParamPad

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/TypecastParenPad.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/TypecastParenPadStyle.java
- rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java
- rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java
- rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/TypecastParenPadTest.kt
See: https://github.com/openrewrite/rewrite/issues/797
Handles whitespace formatting between typecast parenthesis as configured by the TypecastParenPad checkstyle module.
> [#797] TypecastParenPad

- rewrite-test/src/main/kotlin/org/openrewrite/RecipeTest.kt
RecipeTest `assertUnchanged` now runs every source through the test recipe.  Fixes #878
> RecipeTest `assertUnchanged` now runs every source through the test recipe.

- rewrite-hcl/src/test/kotlin/org/openrewrite/hcl/HclTemplateTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/RecipeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/AddImportTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeFieldNameTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeFieldTypeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/InvertConditionTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateSubstitutionsTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/LineCounterTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveImportTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/RenameVariableTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/SameClassNameTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/UseStaticImportTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/MinimumViableSpacingTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/NormalizeFormatTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/WrappingAndBracesTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/MaybeUsesImportTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/UsesMethodTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/UsesTypeTest.kt
- rewrite-xml/src/test/kotlin/org/openrewrite/xml/AddToTagTest.kt
- rewrite-xml/src/test/kotlin/org/openrewrite/xml/ChangeTagValueVisitorTest.kt
- rewrite-xml/src/test/kotlin/org/openrewrite/xml/RemoveContentTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/format/IndentsTest.kt
The recipe test harness provides a mechanism for creating an ad-hoc recipe from a visitor. This resulted in the same visitor instance being used for all source files, leading to concurrency issues with the cursor state.
This PR changes the harness to accept a visitor supplier, this requires a sweep for all recipes that were using the `toRecipe` method.
> Fix concurrency issue in recipe test harness

- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/UpgradeDependencyVersionTest.kt
Fixes #891
(testing against `lukas-krecan/ShedLock` real quick to validate)
> Check against resolved artifactId for dependencies when updating the dependency version tag

- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/UpgradeDependencyVersionTest.kt
Without this, if a `dependencyManagement` `dependency` has its `version` specified as a property, it won't be upgraded.
Noticed this as part of https://github.com/openrewrite/rewrite-micronaut/blob/8a4a9d08f39a6c80037ce972c907dcf80f64ab1e/src/main/resources/META-INF/rewrite/micronaut2-to-3.yml#L34-L41
> UpgradeDependencyVersion handling of dependencies within dependencyManagement

- rewrite-json/src/main/java/org/openrewrite/json/JsonParser.java
As an example, `package.json` was not being recognized unless they were renamed to `package.Json`
Use lowercase `.json` when testing file path.  Follows convention from YML/ XML `accept` methods
> fix: use lowercase `json` for accept check

- rewrite-maven/build.gradle.kts
Due to https://github.com/resilience4j/resilience4j/issues/1472, `resilience4j-all:1.7.1` pom is broken and there is no `resilience4j-bom:1.7.1` released either. Does it make sense to stay on a healthy version instead of this partially broken release?
> Pin resilience4j-retry version temporarily

- .github/workflows/publish.yml
- build.gradle.kts
- rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
- rewrite-core/src/main/java/org/openrewrite/config/Environment.java
- rewrite-core/src/main/java/org/openrewrite/config/RecipeExampleDescriptor.java
- rewrite-core/src/main/java/org/openrewrite/config/ResourceLoader.java
- rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
- rewrite-test/src/main/kotlin/org/openrewrite/RecipeTest.kt
With this we'll be publishing new (small) jars for each project containing properties files that detail successful invocations of `RecipeTest.assertChanged()`.
This information can then be read out of `Environment` and used to generate documentation.
>  Produce examples of Recipe execution for use in documentation. CLoses #893 

- rewrite-core/src/main/java/org/openrewrite/text/CreateTextFile.java
- rewrite-test/src/test/kotlin/org/openrewrite/text/CreateTextFileTest.kt
There was no imperative recipe for creating plain text files. As an example, this would be useful for creating a declarative recipe in the future for applying best practices to GitHub projects wherein we could create `CODEOWNERS` files.
Add a `CreateTextFile` recipe that creates a plain text file. Optionally, this recipe can be enabled to overwrite an existing file should one exist.
> feat(core): add CreateTextFile recipe

- rewrite-core/src/main/java/org/openrewrite/scheduling/DirectScheduler.java
- rewrite-test/src/main/kotlin/org/openrewrite/RecipeTest.kt
Helps with readability of stack traces.
> Add DirectScheduler for tests

- rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawMavenResolver.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
- rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenProjectParser.java
This PR introduced flyweights for Pom model objects.
To enable the re-use of existing Pom instances, the `effectiveProperties` were replaced with `propertyOverrides`.  The RawMavenResolver still computes `effectiveProperties` when building the partial maven results. However, when creating the final Pom model, the resolver will look at the keys for the original properties defined in the raw maven file and only populated `propertyOverrides` if that key's effective value is different than its original value. The `getValue` method on the Pom will now correctly use property overrides, the original properties, and if not found, it will recursively call its parent.
An overloaded `build()` method allows relaxed matching using just the GAV coordinates and datedSnapshotVersion.
> Introduce Maven Pom flyweights

- rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeTypeTest.kt
Noticed while fixing tests in rewrite-migrate-java involving types under `java.lang.management..*`.
Only wrapper types such as `java.lang.{Integer,String,etc.}` are auto-imported. `getPackage()` will return `java.lang` for `java.lang.Integer`, and returns `java.lang.management` as the package for `java.lang.management.Foo`, meaning `getPackage()` should be able to be used directly without needing the `startsWith` qualifier.
> ChangeType should allow nested java.lang package imports

- rewrite-core/src/main/java/org/openrewrite/style/GeneralFormatStyle.java
- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/format/AutoFormatVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeLineBreaks.java
- rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeLineBreaksVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
- rewrite-java/src/main/java/org/openrewrite/java/style/IntelliJ.java
- rewrite-java/src/main/java/org/openrewrite/java/style/TabsAndIndentsStyle.java
- rewrite-java/src/test/kotlin/org/openrewrite/java/style/StyleHelperTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/NormalizeLineBreaksTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/style/AutodetectTest.kt
Move `useCLRFNewLines` from `TabsAndIndentsStyle` to new `FormatStyle` and update AutoDetect. Closes #973
> Add NormalizeLineBreaks along with new general FormatStyle

- rewrite-test/src/main/kotlin/org/openrewrite/json/JsonRecipeTest.kt
Noticed while working on other issues that json syntax highlighting was not being applied on JsonRecipeTest. This appears to be because the syntax language was set to javascript rather than json. Minor thing, but if it's gonna be set, set it right, you feel me?
> Use @Language injection "json" rather than javascript for JsonRecipeTest

- rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
Co-authored-by: Moderne <team@moderne.io>
> refactor: Add missing `@Override` to overriding and implementing methods

- rewrite-hcl/src/test/kotlin/org/openrewrite/hcl/format/SpacesTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/hcl/HclRecipeTest.kt
When using the JetBrains-sponsored "terraform and HCL" plugin (https://plugins.jetbrains.com/plugin/7808-terraform-and-hcl), the `@Language("HCL")` annotation provides syntax highlighting similar to our other recipe tests. If a user doesn't have the plugin installed, nothing different happens (as in, it's not like you get visible errors or anything). So, it's all good.
Note, the plugin provides both "HCL" and "HCL-Terraform" as language options. I put down "HCL", since it's a slightly more generalized form of HCL vs. some specific details of HCL-Terraform (though I'm not sure about _what_ specifically). It felt like a safer option.
Before/after:
> Add HCL language annotation to HCLRecipeTest

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaTypeVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FixSerializableFields.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/CoordinateBuilder.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/FixSerializableFieldsTest.kt
Recipe to address RSPEC01948. Fields in a `Serializable` class should either be transient or serializable
This PR also adds coordinates to add an interface to a class declaration's implements clause.
> Recipe to fix fields of a Serializable class.

- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
> Preserve whitespace before HTML tags in ReloadableJava8JavadocVisitor.

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
Removed appending \r on javadocContent in init.
Added multiline javaDoc tests with CRLF.
Tested on Windows and MacOs using CRLF/LF settings in the IDE. fixes #976
> Fixed parsing error while processing multiline javaDoc with CRLF.

- rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java
- rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/HiddenFieldTest.kt
IMO there's no reason to treat differently classic setters and fluent setters
> Change default value for HiddenFieldStyle.setterCanReturnItsClass

- rewrite-maven/src/main/java/org/openrewrite/maven/ChangePropertyValue.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/ChangePropertyValueTest.kt
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/UpgradeDependencyVersionTest.kt
`UpgradeDependencyVersion` should detect if a managed dependency's version is expressed as a property and should either update or add a property to a pom that will override the property value.
`ChangePropertyValue` has been modified to include a flag `addIfMissing` with the default value being `false`
fixes #1157
> Upgrade dependency adds an overridden version property

- rewrite-java-11/src/main/java/org/openrewrite/java/TypeMapping.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableTypeMapping.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/UsesMethodTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/UsesTypeTest.kt
fix: Update TypeMapping also check for `Type.ForAll` when building JavaType.Method. Fixes: #1169
> Update TypeMapping also check for `Type.ForAll` when building JavaType.Method

- rewrite-core/src/main/java/org/openrewrite/internal/NameCaseConvention.java
- rewrite-core/src/test/kotlin/org/openrewrite/internal/NameCaseConventionTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RenameLocalVariablesToCamelCase.java
This is a prelude to https://github.com/openrewrite/rewrite/pull/1182 with downstream implications for https://github.com/openrewrite/rewrite/issues/1168
Name case convention utilities for matching and formatting strings according to a standard pattern. Took inspiration from `RenameLocalVariablesToCamelCase`, and used this as an opportunity to move the `isCamelCase` function into this `NameCaseConvention` util. Implemented the case format options as standard in https://github.com/google/guava/blob/master/guava/src/com/google/common/base/CaseFormat.java as they're fairly ubiquitous.
> Name case convention utilities

- rewrite-properties/src/main/java/org/openrewrite/properties/internal/PropertiesPrinter.java
- rewrite-properties/src/test/kotlin/org/openrewrite/properties/search/FindPropertiesTest.kt
Ensure `visitMarkers` occurs to allow printing of included markers on `properties`
> FindProperties in rewrite-properties missing visitMarkers

- rewrite-core/src/main/java/org/openrewrite/internal/NameCaseConvention.java
- rewrite-properties/src/main/java/org/openrewrite/properties/AddProperty.java
- rewrite-properties/src/main/java/org/openrewrite/properties/ChangePropertyKey.java
- rewrite-properties/src/main/java/org/openrewrite/properties/ChangePropertyValue.java
- rewrite-properties/src/main/java/org/openrewrite/properties/DeleteProperty.java
- rewrite-properties/src/main/java/org/openrewrite/properties/search/FindProperties.java
- rewrite-properties/src/test/kotlin/org/openrewrite/properties/ChangePropertyKeyTest.kt
- rewrite-properties/src/test/kotlin/org/openrewrite/properties/ChangePropertyValueTest.kt
- rewrite-properties/src/test/kotlin/org/openrewrite/properties/DeletePropertyTest.kt
- rewrite-properties/src/test/kotlin/org/openrewrite/properties/Issue1020.kt
- rewrite-properties/src/test/kotlin/org/openrewrite/properties/search/FindPropertiesTest.kt
- rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteProperty.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/search/FindProperty.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangePropertyKeyTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/DeletePropertyKeyTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/search/FindPropertyTest.kt
See https://github.com/openrewrite/rewrite/issues/1168
Changes the default `property` matching to use "relaxed binding". In Micronaut this is referred to as [`property value normalization`](https://docs.micronaut.io/3.1.0/guide/index.html#_property_value_binding), and in Spring it's referred to as... well, [`relaxed binding`](https://docs.spring.io/spring-boot/docs/2.5.6/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding).
This changes `rewrite-properties` recipes and `rewrite-yaml` "properties"-related recipes to use relaxed binding by default.
Users can explicitly opt-out of relaxed binding and use _exact_ matching instead by explicitly specifying `relaxedBinding: false` when configuring the recipe.
> Relaxed binding on yaml and properties

- rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
- rewrite-java/src/test/kotlin/org/openrewrite/java/style/ImportLayoutStyleTest.kt
Added `without subpackages` if the option is set to false.
IntelliJ defaults to true on imports in the layout.
The builder in changes required in 1191 will follow the same pattern for a cleaner API.
Changes:
Serialize and deserialize withSubpackages option.
Added condition to tests.
fixes #1206
> Added serialization and deserialization of sub packages option to ImportLayoutStyle

- rewrite-java/src/main/java/org/openrewrite/java/search/FindMethods.java
"Find Methods" sounds like it should include method declarations as well. Reduce confusion and explicitly say "invocations".
> FindMethods description should explicitly say find method usages

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodNameCasing.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/MethodNameCasingTest.kt
MethodNameCasing should not rename overridden methods _unless the parent method is being renamed_, in which case, the parent is who should drive the renaming.
Breaking out the MethodMatcher code into a separate PR.
Closes https://github.com/openrewrite/rewrite/issues/1213
> MethodNameCasing should not rename overridden methods

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/EmptyBlockVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/EmptyBlockTest.kt
Fix #1210. EmptyBlock recipe should not add throw RuntimeException.
- Do not remove empty catch or synchronized blocks.
- Also check for the `TEXT` Checkstyle#BlockPolicy when removing empty blocks.
- Set the `TEXT` as the default Checkstyle#BlockPolicy.
> Fix #1210. EmptyBlock recipe should not add throw RuntimeException.

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodNameCasing.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/MissingOverrideAnnotation.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UnnecessaryThrows.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/UnnecessaryThrowsTest.kt
Reworked the rules for the `UnnecessaryThrows` recipe based on[ RSPEC-1130 documentation.](https://jira.sonarsource.com/browse/RSPEC-1130)
This recipe will only remove unused, checked exception if:
- The declaring class or method declaration is final
- The method declaration is static or private
- If the method is an override and a thrown exception is not defined in the overridden method's declaration
- If the method is public or protected and the exception is not documented via a JavaDoc as a @throws tag
> Refactor UnnecessaryThrows recipe. fixes #1207

- rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodName.java
- rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoFinalizer.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RenameMethodsNamedHashcodeEqualOrTostring.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindDeprecatedMethods.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeMethodNameTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/MethodMatcherTest.kt
Closes https://github.com/openrewrite/rewrite/issues/1215
Currently, MethodMatcher will match against supertypes regardless of whether `matchOverrides` is provided. This means you cannot do an exact match.
Regardless of what the expected default is, the current behavior of MethodMatcher is that it will always match on overrides. The current de-facto value of `matchOverride` is `true`, even if `matchOverride` is being passed `null` or `false`. Currently, the only situation where `matchOverride` has an effect is if the target type to match against is an interface.
> MethodMatcher should acknowledge matchOverrides

- rewrite-java/src/main/java/org/openrewrite/java/RemoveImport.java
- rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
- rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
- rewrite-java/src/test/kotlin/org/openrewrite/java/style/ImportLayoutStyleTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/AddImportTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/OrderImportsTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveImportTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveUnusedImportsTest.kt
Added blocks in ImportLayoutStyle to specify packages to fold.
Updated builders, constructors, serialization, deserialization, and tests.
Updated RemoveUnusedImports to not unfold specified packages and/or sub-packages if a type is in use.
Updated RemoveImports to not unfold specified packages and/or sub-packages if a type is in use.
Updated AddImport to automatically fold specified packages and/or sub-packages.
Updated OrderImports to automatically fold specified packages and/or sub-packages.
fixes #1191
> Add support to ImportLayoutStyle for specific packages to fold.

- rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangePropertyKeyTest.kt
Update ChangePropertyKey to prevent moving entries to nonscalar nodes or those nested under a sequence. Fixes #1249
> Update ChangePropertyKey to prevent moving entries to nonscalar nodes or those nested under a sequence

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenSettings.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawRepositories.java
Enables a different way of building MavenSettings rather than currently only requiring it be through parsing an actual settings.xml _file_.
See, specifically, for: openrewrite/rewrite-maven-plugin#152
> MavenSettings constructors visibility for building MavenSettings

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11JavadocVisitor.java
- rewrite-java-11/src/main/java/org/openrewrite/java/Java11ParserVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
Use the appropriate class symbol to fix missing type info on identifiers in JavaDoc references from imports existing in a different package than the compilation unit.
fixes #1255
> Fix type attribution on references in JavaDocs

- rewrite-java/src/main/java/org/openrewrite/java/internal/template/AnnotationTemplateGenerator.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
Changed the cache keys for those templates using either the statement generator or the annotation generator. In the case of statements, the key consists of any added imports plus the template. (The initially generated stub is used to create/extract the AST representation of the template. Thereafter, the same imports+templates can re-use the generated ASTs.)
Fixes #1228
> Fix to better re-use Java templates and reduce heap pressure

- build.gradle.kts
- rewrite-java-11/build.gradle.kts
- rewrite-java-8/build.gradle.kts
This will make the JavaCompile tasks cacheable and should still retain the target/source compatibility that was configured previously.
> Refactor build scripts to use toolchain instead of javac executable

- rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
- rewrite-java/src/main/java/org/openrewrite/java/RemoveImport.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindTypes.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Substitutions update to handle JavaType.FullyQualified inner and nested class fqns having `$`
AddImport uses `JavaType.ShallowClass` to build classType.
> Updates to handle JavaType.FullyQualified inner and nested class fqns having `$` delimiters

- rewrite-java/src/main/java/org/openrewrite/java/internal/ClassgraphTypeMapping.java
Added missing default flag to bitmap.
Added missing abstract flag to bitmap.
fixes #1321
> Sync the flags bitmap on methods between Javac and Classgraph TypeMapping

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/AddSerialVersionUidToSerializable.java
- Excluding Enum classes from getting serialVersionUid
- https://stackoverflow.com/questions/3057751/how-to-ensure-consistency-of-enums-in-java-serialization/3057790
- https://www.infoworld.com/article/2072870/java-enums-are-inherently-serializable.html
> fix(rewrite-java): excluding Enum classess from getting serialVersionUid

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11TypeMapping.java
- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11TypeMappingTest.kt
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java
- rewrite-test/src/main/java/org/openrewrite/java/JavaTypeGoat.java
- rewrite-test/src/main/java/org/openrewrite/java/JavaTypeSignatureBuilderTest.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTypeMappingTest.kt
- rewrite-test/src/main/resources/JavaTypeGoat.java
Changes:
- Added check for a generic type's intersection supertype.
- Added supertype to the `GenericTypeVariable` bounds if it exists.
Code clean up.
fixes #1364
> Add super type to bounds of Generic IntersectionTypes in JavacTypeMapping

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
Cause:
The cursor isn't set properly, since the init expects the margin to already be null.
Changes:
- Continue to build the margin when a new line is found, but the margin is not null.
Fixes #1374
> Fix parsing exception in JavaDocVisitor.

- rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java
- rewrite-core/src/test/kotlin/org/openrewrite/marker/GitProvenanceTest.kt
Given a bitbucket origin of `http://localhost:7990/scm/organization/spring-demo.git`
The GitProvenance was not correctly reporting the organization (`organization`)
> Support origin that has a base path in the URI

- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaParserTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/UpdateSourcePositionsTest.kt
Fixes #1380 
The point is keep AST the same if visitor doesn't change it. This includes `LeftPadded`, i.e. `value=` (incomplete AST branch) should remain the same after blank java visitor goes through it.
> Leave leftpadded AST unchanged if visitor does not change it

- rewrite-core/src/main/java/org/openrewrite/tree/ParsingEventListener.java
- rewrite-core/src/main/java/org/openrewrite/tree/ParsingExecutionContextView.java
- rewrite-core/src/main/java/org/openrewrite/tree/package-info.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
- rewrite-hcl/src/main/java/org/openrewrite/hcl/HclParser.java
- rewrite-java-11/src/main/java/org/openrewrite/java/Java11Parser.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java
- rewrite-json/src/main/java/org/openrewrite/json/JsonParser.java
- rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/parsing.kt
- rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java
- rewrite-xml/src/main/java/org/openrewrite/xml/XmlParser.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
Just a quick event hook after parsing each source file input. We're intending to use this to generate diagnostic information on heap consumption in the parsing phase in the build plugins.
> Parsing listener

- rewrite-test/src/main/kotlin/org/openrewrite/RecipeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/groovy/GroovyRecipeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/hcl/HclRecipeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/AddImportTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaRecipeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/OrderImportsTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/json/JsonRecipeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/maven/MavenRecipeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/properties/PropertiesRecipeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/xml/XmlRecipeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/yaml/YamlRecipeTest.kt
Each test class has the ability to override the executionContext, however, this override is applied to all tests in the class. This change allows an individual test to override the context. This pattern is used in AddImportTest and OrderImportsTest to speed up those suites of tests.
See https://github.com/openrewrite/rewrite/pull/1388/files#diff-f052a9d904f415be4f7c03be4ab8b1d2c8bf92d1cf54932d2cb6433794823a88
> Add `executionContext` as named parameter in base test classes

- rewrite-java/src/main/java/org/openrewrite/java/UpdateSourcePositions.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/UpdateSourcePositionsTest.kt
There are some nodes on which JavaPrinter visitor does not call `visit(Tree, ExecutionContext)`. Those won't have a range therefore and doesn't look like it's a problem thus lets not fail the visitor with an NPE on adding `null` `Range` marker.
> NPE in Positions visitor with lambda parameters

- rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java
- rewrite-core/src/main/java/org/openrewrite/text/PlainTextVisitor.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyVisitor.java
- rewrite-hcl/src/main/java/org/openrewrite/hcl/HclVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-json/src/main/java/org/openrewrite/json/JsonVisitor.java
- rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/AddDependencyTest.kt
- rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesVisitor.java
- rewrite-xml/src/main/java/org/openrewrite/xml/XmlVisitor.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlVisitor.java
This problem manifests in the following issue : https://github.com/openrewrite/rewrite-maven-plugin/issues/297
Need to make sure both the Tree accepts the Visitor and the Visitor accepts the Tree.
> Fix TreeVisitor.isApplicable test

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
The DocTreeScanner parses whitespace differently based on what is being visited. I.E. text or param.
Fix:
Added `linebreaks` and handle whitespace appropriately when a new line is parsed that only contains whitespace.
Updated `javadocContent` so that indexes are set correctly.
Updated previous newline detection to account for CRLF.
Note:
The whitespace will be added as `JavaDoc$Text` rather than added in the margin of the linebreak if it's represented in the node as ` Text followed by a new line with only whitespace\n  {whitespace here}  \n ...`.
fixes #1397
> Update JavaDocVisitors to parse new lines that only contain whitespace

- rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java
Changes:
- Added `maybeUpdateModel()` in `ChangeParentPom` after changes.
- Update parent of `MavenResolutionResult` in `UpdateMavenModel`.
fixes #1402
> Update MavenResolutionResult after changes in ChangeParentPom

- rewrite-maven/src/main/java/org/openrewrite/maven/AddDependencyVisitor.java
- rewrite-maven/src/main/java/org/openrewrite/maven/ChangeProperty.java
- rewrite-maven/src/main/java/org/openrewrite/maven/ManageDependencies.java
- rewrite-maven/src/main/java/org/openrewrite/maven/MavenTagInsertionComparator.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/InsertDependencyComparator.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/AddDependencyTest.kt
- rewrite-xml/src/main/java/org/openrewrite/xml/AddToTagVisitor.java
- rewrite-xml/src/main/java/org/openrewrite/xml/TagNameComparator.java
- rewrite-xml/src/test/kotlin/org/openrewrite/xml/AddToTagTest.kt
**Issue**
`AddToTagVisitor` filters out non-tag content like comments, processing instructions, cdata, and entity references.
**Changes:
_contains breaking changes_**
- `InsertDependencyComparator` and `MavenTagInsertionComparator` implement `Comparator<Content>` instead of `Xml.Tag`. 
- Updated instantiations of `InsertDependencyComparator` and `MavenTagInsertionComparator` to use `Xml.Tag#getContent()` instead of `Xml.Tag#getChildren()`
- Added `TagNameComparator` to replace `Comparator.comparing(Xml.Tag::getName)`.
Note:
- Added executionContext to `AddDependencyTest` to reduce runtime by preventing the `JavaSourceSet` from being generated.
fixes #1392
> Updated AddToTagVisitor to preserve non-tag content.

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
Updated detection of a newline character in JavadocVisitors for new lines without a '*'.
fixes #1411
> Fix for new lines without '*' ending with CRLF in Javadoc Visitors

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
- Updated conditions to always add trailing whitespace if it exists in JavaDocVisitors.
fixes #1094
> Add trailing whitespace to body in JavaDocVisitors.

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
> Add whitespace before equals of attributes in javadoc visitors.

- rewrite-xml/src/main/java/org/openrewrite/xml/ChangeXMLAttribute.java
- rewrite-xml/src/main/java/org/openrewrite/xml/ChangeXMLAttributeVisitor.java
- rewrite-xml/src/test/kotlin/org/openrewrite/xml/ChangeXMLAttributeTest.kt
This PR is meant to provide the ability to alter the value of a named Xml attribute within a specified element, and can also be restricted to operate only on matched file names.
The recipe parameters are:
`elementName` the name of the element to look for matching attributes
`attributeName` the name of the attribute whose value should be altered
`newValue`        the value to replace the old value of the attribute if found
`oldValue`         the value of the attribute to search for. This is an optional parameter. If supplied, the starting part of the attribute value matching this will be replaced by the `newValue`, leaving the trailing part intact. If not supplied, all attributes with a matching name inside a matching element will have their values set to `newValue` overwriting whatever …
> Alter xml attribute

- rewrite-core/build.gradle.kts
- rewrite-groovy/build.gradle.kts
- rewrite-hcl/build.gradle.kts
- rewrite-java/build.gradle.kts
- rewrite-json/build.gradle.kts
- rewrite-maven/build.gradle.kts
- rewrite-properties/build.gradle.kts
- rewrite-protobuf/build.gradle.kts
- rewrite-xml/build.gradle.kts
- rewrite-yaml/build.gradle.kts
There is an open [issue](https://github.com/FasterXML/jackson-module-kotlin/issues/550) that prevents the release of `jackson-module-kotlin:2.13.2`.
Temporarily pinning back the Jackson dependencies to 2.13.1 until the issue is fixed.
> Temporarily pin jackson dependencies to 2.13.1

- rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/HclParserVisitor.java
- rewrite-hcl/src/main/java/org/openrewrite/hcl/tree/Space.java
- rewrite-hcl/src/test/kotlin/org/openrewrite/hcl/format/AutoFormatTest.kt
- rewrite-hcl/src/test/kotlin/org/openrewrite/hcl/format/SpacesTest.kt
Changes:
- Updated Hcl Space to add hash style comments
- Updated single-line comment to consume all characters until a new line.
fixes #974
> Updated Hcl `Space` to add hash style comments.

- rewrite-maven/src/main/java/org/openrewrite/maven/internal/InsertDependencyComparator.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/AddDependencyTest.kt
Changes:
- Extract the `Xml.Tag`s from `List<? extends Content> existingDependencies` for sorting.
- Only sort `Xml.Tag`s in `InsertDependencyComparator#dependencyComparator`.
- Apply ideally sorted position to the list of content.
Note:
- The bug only occurred on large sets of dependencies. Maven parsing took 10s-15s, so the test has not been added. 
fixes #1442
> Only compare the Xml.Tags in InsertDependencyComparator

- rewrite-java/build.gradle.kts
Per [docs](https://checkstyle.sourceforge.io/#JRE_and_JDK) checkstyle 10.x does not support java 8.
fixes #1451
> Pin `com.puppycrawl.tools:checkstyle` to 9.+

- rewrite-groovy/src/main/resources/GroovyTypeGoat.groovy
- rewrite-java-11/src/main/java/org/openrewrite/java/Java11TypeMapping.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/JavaReflectionTypeMapping.java
- rewrite-test/src/main/java/org/openrewrite/java/JavaTypeGoat.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTypeMappingTest.kt
- rewrite-test/src/main/resources/JavaTypeGoat.java
Changes:
- Added method to check for type attributed generics. I.E. `List<Integer>` vs `List<E>`
- Updated javac type mapping to set enum super type based on source code when the generic `E` is type attributed.
- Filter out synthetic parameters in `JavaReflectionTypeMapping`.
- Added an Enum with a constructor param to JavaTypeGoat.
fixes #1438
> Fix javac and java reflection type mapping for constructors and super-type of enums.

- rewrite-maven/src/test/kotlin/org/openrewrite/maven/UpgradeDependencyVersionTest.kt
- rewrite-xml/src/main/java/org/openrewrite/xml/AddToTagVisitor.java
- rewrite-xml/src/test/kotlin/org/openrewrite/xml/AddToTagTest.kt
Inserting a new tag within an existing list of content tags was causing all children within the parent tag to sort (if a comparator was used with the `AddToTagVisitor`). This change will iterate over the list of existing child tags and find the first place (according to the comparator) in which the new tag will be inserted.
> Use comparator to find the best location for xml tag. fixes #1473

- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
- rewrite-groovy/src/test/kotlin/org/openrewrite/groovy/tree/BinaryTest.kt
- rewrite-groovy/src/test/kotlin/org/openrewrite/groovy/tree/UnaryTest.kt
Changes:
- fixed `-=` mapping.
- fixed `&=` mapping.
- fixed `|=` mapping.
- fixed `^=` mapping.
Added disabled tests for negation and unary plus operators.
fixes #1520
> Fixed a handful of binary operator mappings in GroovyParserVisitor.

- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
- rewrite-groovy/src/test/kotlin/org/openrewrite/groovy/tree/UnaryTest.kt
Changes:
- `!` operators will not be removed during Groovy parsing.
- Added visitNotExpression in GroovyParserVisitor.
fixes #1524
> Fixed unary not operator in GroovyParserVisitor.

- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
- rewrite-groovy/src/test/kotlin/org/openrewrite/groovy/tree/AssignmentTest.kt
Changes:
- Base-n numbers that start with a 0 will retain their values in the AST.
- Check the metadata for base-n conversion.
fixes #1533
> Fix base-n conversion in GradleParser.

- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
Changes:
- Autformatting from TabsAndIndentsVisitor will not format single line comments at column 0.
fixes #1526
> Do not shift single line comments at column 0 in TabsAndIndentsVisitor.

- rewrite-json/src/main/java/org/openrewrite/json/JsonPathMatcher.java
- rewrite-json/src/test/kotlin/org/openrewrite/json/JsonPathMatcherTest.kt
- rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/JsonPathMatcherTest.kt
Changes:
- Return all matches in `binaryExpression` when a list of potential matches is returned.
- Updated logical operators `&&` and `||` to account for empty lists.
fixes #1567
> Return all matches from binaryExpression in JsonPathMatches.

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/EmptyBlockVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnneededBlock.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyConstantIfBranchExecution.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/EmptyBlockTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnneededBlockTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/SimplifyConstantIfBranchExecutionTest.kt
There were several cases where the `SimplifyConstantIfBranchExecution`
recipie was incorrect.
This fixes those cases and simplifies removing unneeded blocks into
it's own visitor.
> Fix SimplifyConstantIfBranchExecution Bugs

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
- rewrite-maven/src/main/java/org/openrewrite/maven/security/UseHttpsForRepositories.java
- rewrite-maven/src/main/java/org/openrewrite/maven/security/package-info.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/security/UseHttpsForRepositoriesTest.kt
Finds all `url` tags within Maven POM repositories blocks and rewrites them to use HTTPS instead of HTTP.
Also supports looking up properties and replacing URLS there as well.
> Add Maven Security Recipe Converting HTTP -> HTTPS

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnusedPrivateMethods.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedPrivateMethodsTest.kt
Changes:
- RemoveUnusedPrivateMethods will not remove private method declarations with a generic type.
fixes #1536
> Prevent RemoveUnusedPrivateMethods from removing methods with generic types.

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenResolutionResult.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.kt
@jkschneider @pway99 I had a hard time tracking this one but I think I got to the bottom of it. In this case, I think using the same pattern for the modules as for the parent is safe enough and not creating a copy is the way to go.
In any case, you have a test showing the issue if you think this fix is not correct.
====
Creating a copy is problematic as we are then pointing to stale objects
that do not contain the whole updated information.
In the case of the test, the project in the middle of the hierarchy
loses its parent in the process.
Then when maybeUpdateModel() is called, the pom file cannot be
downloaded and an exception is thrown, resulting in the document not
being updated.
This uses the same pattern for modules as what is currently used to set
the parent.
Related to the issues …
> Fix parent/module resolution in MavenParser

- rewrite-json/src/main/java/org/openrewrite/json/JsonPathMatcher.java
- rewrite-json/src/test/kotlin/org/openrewrite/json/JsonPathMatcherTest.kt
- rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/JsonPathMatcherTest.kt
Changes:
- JsonPathMatcher will return the correct scope when a binary expression is used on a model object with a key-value pair.
fixes #1590
> Updated JsonPathMatchers to cache the scope before evaluating a binaryExpression

- rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/RenameVariableTest.kt
Currently there is a compilation error, when a variable with field access is renamed.
With this pull request the variables with field access will be renamed as expected.
> rename fieldAccess when variable is renamed

- rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt
- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RenamePrivateFieldsToCamelCase.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RenamePrivateFieldsToCamelCaseTest.kt
In addition to the RenameLocalVariablesToCamelCase recipe, i created a new recipe called RenamePrivateFieldsToCamelCase. Stated in the name, this receipe will reformat private field names to camelCase to comply with Java naming convention.
Further details see https://jira.sonarsource.com/browse/RSPEC-116 and https://jira.sonarsource.com/browse/RSPEC-3008
> introduce RenamePrivateFieldsToCamelCase recipe

- rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
Changes
- `WatchableExecutionContext` will not set `hasNewMessages` to true if the message is `ExecutionContext.CURRENT_RECIPE`.
fixes #1617
> Updated WatchableExecutionContext to account for `ExecutionContext.CURRENT_RECIPE`

- rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteKey.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlVisitor.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/cleanup/RemoveUnused.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/cleanup/RemoveUnusedVisitor.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/DeleteKeyTest.kt
Changes:
- Added a nullable Cursor to limit the scope of removed entries in `RemoveUnusedVisitor`.
- Updated `DeleteKey` to only remove empty yaml in the scope of the removed key.
fixes #1175
> Do not remove unrelated empty entries in `yaml/DeleteKey`.

- rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/AddImportTest.kt
Changes:
- Set `ImportLayoutStyle#layout` to IntelliJ default settings if an ImportLayoutStyle is provided without a `layout`.
fixes #1687
> Default `ImportLayoutStyle#layout` to IntelliJ settings if `layout` is empty

- rewrite-test/src/main/kotlin/org/openrewrite/java/DeleteStatementTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/SimplifyConstantIfBranchExecutionTest.kt
I need a non-iso version of `DeleteStatement`. I figure that instead of having another copy of the code, it would be better to make `DeleteStatement` non-iso:
https://github.com/openrewrite/rewrite-java-security/pull/19/files#diff-9398f78788834295d06b2a0c3b37ebd41b70fb4f8d67b2581d02d8235b3ce16aR288
> Cleanups: Add Tests

- rewrite-core/src/main/java/org/openrewrite/internal/EncodingDetectingInputStream.java
- rewrite-core/src/test/java/org/openrewrite/internal/EncodingDetectingInputStreamTest.java
Changes:
- Detects characters in a range of a UTF-8 2, 3, or 4-byte sequence.
- Sets the encoding to Windows-1252 if the previous bytes do not match a valid UTF-8 sequence.
> Updated encoding detection in `EncodingDetectingInputStream`.

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnneededBlock.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnneededBlockTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/SimplifyConstantIfBranchExecutionTest.kt
`RemoveUnneededBlock` was reformatting the entire block instead of only formatting the lines of code changed.
> Fix RemoveUnneededBlock formatting more than is strictly required

- rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangePropertyKeyTest.kt
Changes:
- `ChangePropertyKey` will change the `old key` to the `new key` if a mapping already exists.
fixes #1744
> Change property key with existing mapping.

- rewrite-java/src/main/java/org/openrewrite/java/ReplaceConstant.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/ReplaceConstantTest.kt
Changes:
- `ReplaceConstant` will not attempt to change the identifier of variable declarations in the owning class.
fixes #1752
> Prevent cast cast exception in `ReplaceConstant`

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11TypeMapping.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java
Changes:
- Prevent ClassCastException in `TypeMapping#methodInvocationType`.
Note: The cause is similar to commit [c36ef805](https://github.com/openrewrite/rewrite/commit/c36ef8058760f17b3a6f5ff16937fe2f182dd1c1). The commit ensures type attribution is on the classpath because Java 8 is more strict about missing type attribution.
Similarly, in the users reported case, type attribution is missing, which caused a lambda variable, o in `stream().map(o -> ...)` to have an unknown type. 
fixes #1762
> Prevent cast class exception if the symbol.type is `Type.Unknown`

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseCollectionInterfaces.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/UseCollectionInterfacesTest.kt
Changes:
- UseCollectionInterfaces will not change variable declarations with type `var`.
fixes #1771
> Do not change var from Java 10 in UseCollectionInterfaces.

- rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8TypeMappingTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaParserTypeMappingTest.kt
Changes:
- Added Java8TypeMappingTest
- Added JavaParserTypeMappingTest for type mapping tests specific to the JavaParsers.
- Moved `Type.Unknown` test to `JavaParserTypeMappingTest`.
- Added test for issue https://github.com/openrewrite/rewrite/issues/1762.
fixes #1766
> Added java 8 type mapping tests.

- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDelegatesToGradleApi.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveRedundantTypeCast.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/TypeUtilsTest.kt
Changes:
- `TypeUtils#isOfType(..)` will check if each type parameter matches on `JavaType$ParameterizedType`s.
- `TypeUtils#isOffType(..)` will check if `Variance` matches on `JavaType$GenericTypeVariable`s.
- Added support for `JavaType$Array` in `TypeUtils#isOfClassType(..)`.
- Added support for `JavaType$Primitive` in `TypeUtils#isOfClassType(..)`.
fixes #1788
> Updated `TypeUtils` with model changes from type mapping enhancements.

- rewrite-java/src/main/java/org/openrewrite/java/dataflow/analysis/ForwardFlow.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/dataflow/FindLocalFlowPathsStringTest.kt
The previous PR broke the ability to use a J.MethodInvocation as a flow source since it was filtered out during the call to computeVariableAssignment.
> Fix: The ability to use a J.MethodInvocation as a flow source

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ExplicitLambdaArgumentTypes.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/ExplicitLambdaArgumentTypesTest.kt
This recipe uses Rewrite's type information to construct a type expression for each lambda argument. This is actually quite tricky because the expression may include parameterizes types, wildcards, arrays, primitives, and identifiers.
> ExplicitLambdaArgumentTypes should create correctly-formed type expressions

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseLambdaForFunctionalInterface.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/TypesInUse.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveUnusedImportsTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/UseLambdaForFunctionalInterfaceTest.kt
I identified and added a few related details along the way, which the new test cases should explain.
I did touch `TypesInUse`, which I expect has pretty broad reach, but the change didn't cause any test failures.
#1844
> UseLambdaForFunctionalInterface should remove unused imports afterward

- rewrite-java/src/main/java/org/openrewrite/java/dataflow/LocalFlowSpec.java
- rewrite-java/src/main/java/org/openrewrite/java/dataflow/analysis/FlowGraph.java
- rewrite-java/src/main/java/org/openrewrite/java/dataflow/analysis/ForwardFlow.java
- rewrite-java/src/main/java/org/openrewrite/java/dataflow/analysis/SinkFlow.java
- rewrite-java/src/main/java/org/openrewrite/java/search/UriCreatedWithHttpScheme.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/UriCreatedWithHttpSchemeTest.kt
@pway99  and I did some pair programming on this one to add support for ad-hoc taint tracking leveraging data flow analysis as a basis.
This adds a new API to `LocalFlowSpec` called `isAdditionalFlowStep`. It takes an existing flow-step in the graph and offers a potential next flow step. The method can then decide if the offered potential next flow step should be considered a valid next flow step in the graph.
> Adding add hoc taint tracking support for local flow

- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeSignatureBuilder.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeSignatureBuilder.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeSignatureBuilder.java
Changes:
- `TypeSignatureBuilders#methodArgumentSignature()` will not thrown an NPE if the type is null via `sym.getParameters()`.
fixes #1825
> Guard against NPE from a null type in `Symbol.MethodSymbol` in the TypeSignatureBuilders.

- rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteProperty.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlVisitor.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangePropertyKeyTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/DeletePropertyKeyTest.kt
Removed coalescing from Yaml ChangePropertyKey, and deprecated coalescing in DeleteProperty and YamlVisitor (#1841)
Let me know if we want to adjust any details of the deprecation(s)
> Decreased yaml coalescing occurrences (#1841)

- rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/SemanticallyEqualTest.kt
Changes:
- `SemanticallyEqual` may be used to check for semantically equality on any `J` tree. 
fixes #1856
> Completed visitors in SemanticallyEqual

- rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/SemanticallyEqualTest.kt
Changes:
- Semantically equal will compare the invoked method invocation when possible to reduce false negatives.
- Incubating change: added type checks on identifiers back until we know the checks are unnecessary.
fixes #1870
> Compare the invoked method when possible in SemanticallyEqual.

- rewrite-java/src/main/java/org/openrewrite/java/dataflow/analysis/ForwardFlow.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/dataflow/FindLocalFlowPathsStringTest.kt
Data flow now traces data flow through ternary operators
```java
@Test
fun `a ternary operator is considered a data flow step`() = rewriteRun(
{ spec -> spec.expectedCyclesThatMakeChanges(1).cycles(1) },
java(
"""
class Test {
void test(boolean conditional) {
String n = conditional ? "42" : "100";
System.out.println(n);
}
}
""",
"""
class Test {
void test(boolean conditional) {
String n = /*~~>*/conditional ? /*~~>*/"42" : "100";
System.out.println(/*~~>*/n);
}
}
"""
)
)
@Test
fun `a ternary operator is considered a data flow step 2`() = rewriteRun(
{ spec -> spec.expectedCyclesThatMakeChanges(1).cycles(1) },
java(
"""
class Test {
void test(boolean conditional) {
String n = "42";
String m = conditional ? "100" : n;
System.out.println(m);
}
}
""",
"""
class Test {
void test(boolean …
```
> Add data flow support for ternary expressions

- rewrite-core/src/main/java/org/openrewrite/HttpSenderExecutionContextView.java
- rewrite-core/src/main/java/org/openrewrite/Recipe.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddGradleWrapper.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/GradleExecutionContextView.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
Problem: 
Validation doesn't use ExecutionContext on recipes. There is a need to be able to add customizations through the ExecutionContext during recipe validation. 
Solution: 
Enhance base recipe execution to allow for execution context. 
Outcome: 
Ability to use ExecutionContext for recipe validation.
> refactor: validate should allow for execution context

- rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/SpacesTest.kt
Changes:
- Auto format will apply spaces style before and after `|` in `J.MultiCatch` control parentheses. The formatting is based on `SpacesStyle$AroundOperators.bitwise`
fixes #1896
> Added support to auto format multi catch control parens

- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddGradleWrapper.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
- UpdateGradleWrapper now adds missing gradle files.
- Add/Update GradleWrapper recipes re-validates if version/distribution changes between recipe runs.
> fix: UpdateGradleWrapper now adds missing gradle files + re-validation 

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseLambdaForFunctionalInterface.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/UseLambdaForFunctionalInterfaceTest.kt
Changes:
- UseLambdaForFunctionalInterface will not convert lambdas that will introduce a namespace conflict with class fields or method declaration param names.
fixes #1915
> Prevent namespace conflicts on class fields and method decl params in UseLambdaForFunctionalInterface.

- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
- rewrite-java/src/main/java/org/openrewrite/java/style/IntelliJ.java
- rewrite-java/src/main/java/org/openrewrite/java/style/TabsAndIndentsStyle.java
- rewrite-java/src/test/kotlin/org/openrewrite/java/style/StyleHelperTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
Changes:
- Added support to align method parameters of multi-line method declaration parameters to the first argument.
- Added `TabsAndIndentStyle$MethodDeclarationParameters#alignWhenMultiple`.
- Added auto-detection for alignment setting. (defaults to true)
fixes #1913
> Align method parameters

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReference.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReferenceTest.kt
Fix:
- `ReplaceLambdaWithMethodReference` will not change lambdas with multiple linked method invocations.
fixes #1926
> Do not change lambda on chained method invocations.

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/CombineSemanticallyEqualCatchBlocks.java
- rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/CombineSemanticallyEqualCatchBlocksTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/SpacesTest.kt
Changes:
- Added semantically equivalent comparison to `SemanticallyEqual`.
- Added clean up recipe `CombineSemanticallyEqualCatchBlocks`.
> Added semantically equivalent comparison to SemanticallyEqual.

- rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlow.java
- rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowBasicBlockVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/dataflow/Dataflow.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/controlflow/ControlFlowTest.kt
Instead of throwing an exception when control flow can't be computed
return `Optional.empty`.
> Impossible Control Flow computation fails gracefully

- rewrite-benchmarks/src/jmh/java/org/openrewrite/benchmarks/java/ChangeTypeBenchmark.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
- rewrite-java/src/main/java/org/openrewrite/java/RenameClass.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeTypeTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/DoesNotUseRewriteSkipTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveImportTest.kt
Contains breaking API changes:
- Removed optional `ignoreDefinition` flag from `ChangeType` in favor of [RenameClass](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/RenameClass.java).
To use `RenameClass` instead of `ChangeType` with `ignoreDefinition = false`:
- Remove the `ignoreDefinition` flag and update `ChangeType` to `RenameClass`.
Changes:
- ChangeType will not rename class definitions.
fixes #1961
> Removed functionality to change class definitions from ChangeType in favor of RenameClass.

- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
Fix:
- The remaining linebreaks will be added to the body in numerical order in each JavaDocVisitor#`visitDocComment`.
fixes #1965
> Add remaining linebreaks in numerical order in JavaDocVisitors#visitDocComment.

- rewrite-java/src/main/java/org/openrewrite/java/format/BlankLinesVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/format/BlankLinesTest.kt
Fix:
- `J.ClassDeclaration` prefixes that exceed the `Style` will be appropriately auto-formatted.
fixes #1912
> Apply `BlankLinesStyle$KeepMaximum.inDeclarations` to format `J.ClassDeclaration` prefix.

- rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowNode.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/controlflow/ControlFlowTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/dataflow/FindLocalFlowPathsStringTest.kt
Logic like the following will be implicitly handled in the control flow reachability computation: 
```java
if (true)
System.out.println("This will always run");
if (false)
System.out.println("This will never run");
````
> Implicily Handle Boolean Literal 'true' & 'false' in control flow

- rewrite-java/src/main/java/org/openrewrite/java/VariableNameUtils.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/VariableNameUtilsTest.kt
Changes:
- VariableNameScopeVisitor will only add static field names to names in scope when type attribution is available.
fixes #1978.
> Only add imported static field names when possible in VariableNameScopeVisitor.

- rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseMapNotation.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseStringNotation.java
- rewrite-gradle/src/test/kotlin/org/openrewrite/gradle/DependencyUseStringNotationTest.kt
Also fixed up the `DependencyUseMapNotation` recipe to not drop the closure argument, if present.
> Add `DependencyUseStringNotation` recipe

- rewrite-java/src/main/java/org/openrewrite/java/search/UsesAllMethods.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/search/UsesAllMethodsTest.kt
Useful when `getSingleSourceApplicableTest()` requires an AND relationship instead of an OR relationship.
> Add `UsesAllMethods` visitor

- rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
Also, I added a try-with-resources to the httpSender setup; IntelliJsuggested it and it looked valid to me, reviewing the Response class.
(#1859)
> MavenPomDownloader now attempts anonymous authentication if the provided credentials yield 4xx response

- rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/ChangePackageTest.kt
Fixes in `ChangePackage`:
- Updates type information for bounds of `JavaType$GenericTypeVariable`, type of multi-dimensional `JavaType$Array`, and typeParameters of `JavaType.ParameterizedType`
- Types are updated appropriately for sub-packages when `recursive` is enabled.
- Only creates one new type per FQN.
- Will not remove an import when the package name does not match the package name of an imported class.
- Updated `afterCondition` to prevent regressions.
fixes #1997
> Various fixes in `ChangePackage`

- rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlow.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/controlflow/ControlFlowTest.kt
Control flow would throw an exception in the following case:
```java
for (int i : new int[]{1,2,3,5}) {
//...
}
```
This fixes that case
Related https://github.com/openrewrite/rewrite/issues/1985
> Fix control flow when `new int[]{1,2,3}` used in for each

- rewrite-java/src/main/java/org/openrewrite/java/dataflow/internal/InvocationMatcher.java
`InvocationMatcher` was looking too high for a `J.MethodInvocation` or `J.NewClass` when none would be present. For example, if the `Expression` passed was for an import statement.
> Fix `InvocationMatcher` bug looking too high for a call expression

- rewrite-java/src/main/java/org/openrewrite/java/dataflow/internal/InvocationMatcher.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/MethodCall.java
Take advantage of the new `MethodCall` interface in `InvocationMatcher`.
> Refactor and Optimize `InvocationMatcher`

- rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/dataflow/DataFlowInsanityTest.kt
This was because the visitors invoked in `doAfterVisit` did not have the correct cursor passed to them.
> Fix DataFlow & ControlFlow not working in doubly nested `doAfterVisit`

- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
Fix:
- Javadocs ending with multiple new lines with margins containing trailing whitespace will parse correctly.
fixes #2046
> Fix Javadoc parsing issue related to trailing whitespace.

- rewrite-java/src/main/java/org/openrewrite/java/dataflow/ExternalFlowModels.java
- rewrite-java/src/main/java/org/openrewrite/java/dataflow/ExternalSinkModels.java
Fix:
- ExternalSinkModels and ExternalFlowModels will not NPE when `JavaType$Method#declaringType` is null.
> Guard against null JavaType$Method declaringType in DataFlow models

- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java
- rewrite-java/src/main/java/org/openrewrite/java/JavadocVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/Javadoc.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
Changes:
- Added `JavaDoc.LineBreak` detection in a `J.*` and applied detection to `@link` and `@see`.
- Added `Javadoc.Reference` to wrap linebreaks associated with a `J`.
- Added `visitLineBreak` in `Javadoc.JavaVisitor`.
- Added support to print multiline `@param`.
- Added `LineBreak` printing in place of new lines in `Space` in the JavaDocJavaPrinter.
fixes #1078
> Print `JavaDoc.LineBreak` in place of new lines in `Space` for @link and @see

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveMethodCallVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnneededAssertion.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyConstantIfBranchExecution.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
- rewrite-test/build.gradle.kts
- rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveMethodCallVisitorTest.kt
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnneededAssertionTest.kt
For Junit Jupiter & Junit4 removes method invocations like:
- `assertTrue(true)`
- `assertFalse(false)`
Also removes assert statements like:
- `assert true`
Related https://github.com/openrewrite/rewrite-java-security/issues/33
> Add RemoveUnneededAssertion Recipe

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyConstantIfBranchExecution.java
- rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/SimplifyConstantIfBranchExecutionTest.kt
Previously this wasn't fixed:
```java
if (!(true && true)) {
throw new RuntimeException();
}
```
> Fix SimplifyConstantIfBranch not being exaustive

- rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangePropertyKeyTest.kt
First commit solves the `ChangePropertyKey` edge case with dot-separated values mentioned here: https://github.com/openrewrite/rewrite-spring/issues/189#issuecomment-1143992762
Second commit adds a new recipe option (`List<String> except`) which can be used in rewrite-spring to solve the original finding on the same issue: https://github.com/openrewrite/rewrite-spring/issues/189
(The diff is probably more intuitive if the two commits are reviewed individually)
> Yaml ChangePropertyKey enhancements

- rewrite-hcl/src/main/java/org/openrewrite/hcl/HclParser.java
This is minor change to support parsing of `.tfvars` files. According to the HCL Language specification, tfvars files are valid HCL files:
`.tfvars` files are a list of expressions - all `.tfvars` files are valid HCL files (vice-versa is not true)
https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md
```
ConfigFile   = Body;
Body         = (Attribute | Block | OneLineBlock)*;
Attribute    = Identifier "=" Expression Newline;
Block        = Identifier (StringLit|Identifier)* "{" Newline Body "}" Newline;
OneLineBlock = Identifier (StringLit|Identifier)* "{" (Identifier "=" Expression)? "}" Newline;
```
Although ideally, we would have a `VariableFile` type synonymous to `ConfigFile` with the corresponding grammar, this feels like an ok middleground atleast for the timebeing. …
> support tfvars files for HCL parsing

- rewrite-java-11/build.gradle.kts
- rewrite-java/src/main/java/org/openrewrite/java/RemoveImport.java
- rewrite-maven/build.gradle.kts
- rewrite-test/build.gradle.kts
- rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveImportTest.kt
The micrometer pins are in line with this commit: https://github.com/openrewrite/rewrite/commit/dc328c457a32806dc81bd2326221fba532a6feaa
> Bugfix - RemoveImports and non-static wildcards

- rewrite-core/src/main/java/org/openrewrite/semver/LatestRelease.java
- rewrite-core/src/main/java/org/openrewrite/semver/Semver.java
- rewrite-core/src/main/java/org/openrewrite/semver/VersionComparator.java
- rewrite-core/src/test/kotlin/org/openrewrite/semver/HyphenRangeTest.kt
- rewrite-core/src/test/kotlin/org/openrewrite/semver/LatestPatchTest.kt
- rewrite-core/src/test/kotlin/org/openrewrite/semver/LatestReleaseTest.kt
- rewrite-core/src/test/kotlin/org/openrewrite/semver/TildeRangeTest.kt
Fixing several issues in the semantic version comparators: 
- Found a case where there is a 5-digit semantic version in the wild and we need to support this use case. `2.10.1.1.11`. This required modifying the regular expression to capture an extra group. We did attempt to use an expression to capture n number of version parts, but this did not work. [Please see this stack overflow answer, as it reflects the behavior we encountered.](https://stackoverflow.com/a/37004214/3075815)
- `LatestRelease.countVersionParts()` was using a method introduced in Java 9, I am not even sure what would happen if one attempted to call this method on a Java 8 VM. Converted the method to use a scanner instead.
- `LatestRelease.countVersionParts()` was returning the number of dots, not the number of version …
> Fix semantic version comparators

- rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
Note: I can refactor `dependencies` to a `LinkedHashSet` if we're concerned about performance of those `contains` calls across many iterations.
Fixes #2151
> fixed case where ResolvedPom.resolveDependencies can return incomplete data (#2151)

- rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java
- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/MethodMatcherTest.kt
- rewrite-java/build.gradle.kts
- rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodTargetToStatic.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
Supports this PR: https://github.com/openrewrite/rewrite-testing-frameworks/pull/250
As mentioned in the javadocs, the new `matchUnknownTypes` option is a bit risky, but in scenarios which are extra vulnerable to missing type info, the risk can pay off. And I've added a slew of test cases to ensure that the `matchUnknownTypes` option is as clever as it can be (ie reducing risk of false positives), short of actually having the real type information.
> Introduced matchUnknownTypes option to MethodMatcher (for MethodInvocation) and ChangeMethodTargetToStatic

- rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java
- rewrite-maven/src/test/kotlin/org/openrewrite/maven/RemoveRedundantDependencyVersionsTest.kt
After some testing, it looks like the scope-checking in this recipe is actually not aligned with how Maven works (at least with 3.8.6). Maven only seems to care about the scope tag in `dependencyManagement` if it's an `import`; in any other case, it allows the declared version to apply to any scope.
Sample:
https://i.imgur.com/ASj8av5.png
Fixes #2131
> RemoveRedundantDependencyVersions no longer checks scope, in accordance with Maven behavior (fixes #2131)

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
Update BlockStatementTemplateGenerator to handle lambda bodies which are instances of J.Block (fixes #2181)
> Update BlockStatementTemplateGenerator to handle lambda bodies which are instances of J.Block  (fixes #2181)

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
Fix bug in the BlockStatementTemplateGenerator, which prevented the JavaTemplate from replacing variables and iterators within J.ForEach.Control nodes.
> JavaTemplate should support replacing variables and iterators within J.ForEachLoop.Control

- rewrite-core/src/main/java/org/openrewrite/semver/LatestRelease.java
- rewrite-core/src/test/kotlin/org/openrewrite/semver/LatestReleaseTest.kt
- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
- Fixes version comparison when there is no metadata pattern on the initial version but versions that are being compared have metadata patterns.
- UpgradeDependencyVersion will not attempt to upgrade a dependency if the artifact is mapped to a project pom.
> Refinements to UpgradeDependencyVersion

- rewrite-core/src/main/java/org/openrewrite/RecipeRunException.java
- rewrite-core/src/main/java/org/openrewrite/RecipeRunExceptionResult.java
- rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
- rewrite-core/src/main/java/org/openrewrite/Result.java
- rewrite-core/src/main/java/org/openrewrite/Tree.java
- rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java
- rewrite-core/src/main/java/org/openrewrite/internal/FindRecipeRunException.java
- rewrite-java-11/src/test/java/org/openrewrite/RecipeRunExceptionTest.java
- rewrite-java-11/src/test/java/org/openrewrite/internal/TreeVisitorAdapterTest.java
- Generalize the name of the exception and result that are attached as markers on Tree to `RecipeRunExecption` and `RecipeRunExceptionResult`
- add a wither method to `Tree` to allow exceptions to be quickly added as a marker.
> Request Result Exception

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/cleanup/UnnecessaryCatchTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UnnecessaryCatch.java
A refactoring operation may result in a checked exception that is no longer thrown from a `try` block. This recipe will find and remove unnecessary catch blocks.
> New recipe to remove unnecessary catch blocks

- rewrite-hcl/src/main/java/org/openrewrite/hcl/HclVisitor.java
Now that HCL attribute names can be a `QuotedTemplate` or an `Identifier` (https://github.com/openrewrite/rewrite/pull/2195), I missed updating the visitor to cast appropriately to an `Expression` instead
> fix issue with HCL attribute name casting to Identifier

- rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYamlVisitor.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/CopyValueTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/MergeYamlTest.kt
This solution expects Mappings to be identifiable through a single property. The name of this property should be provided as a recipe option.
Co-authored-by: Jelle Aret <jaret@vmware.com>
> Add support for merging Sequence of Mappings (#2157)

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/RemoveUnusedImportsTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
Currently inner class imports will be removed if a package matching wildcard import is present. This PR fixes this bug.
> fix: keep inner class imports (#2231)

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/MethodMatcherTest.kt
- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/cleanup/MethodNameCasingTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/HideUtilityClassConstructorVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodNameCasing.java
A convention I have seen is to prefix private method names with an underscore. The MethodNameCasing recipe currently treats this as a snake case name.
This diff changes the Patterns so that a leading underscore isn't treated as snake case. I added a test case and existing tests pass.
> don't treat leading underscore as snake case

- rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangeKey.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/CoalescePropertiesVisitor.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteProperty.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/ReplaceAliasWithAnchorValueVisitor.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/tree/Yaml.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/tree/YamlKey.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/ReplaceAliasWithAnchorValueTest.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangeValueTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/CoalescePropertiesTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/DeletePropertyKeyTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/JsonPathMatcherTest.kt
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/tree/MappingTest.kt
fixes: #1161
- Add a new `EntryKey` interface for `Mapping.Entry.key` values which are either scalar or alias blocks.
- Update `YamlParser` to handle `Mapping.Entry.key` as an instance of `EntryKey`
- New `ReplaceAliasWithAnchorValueVisitor`.
- Update `JsonPathMatcher` to replace alias trees with their associated anchor value before searching.
- Update `CoalesceProperties` to prevent transforming documents having anchor/alias pairs.
- Update `org.openrewrite.yaml.DeleteProperty` to prevent deleting properties from documents having anchor/alias pars.
> Add Anchor and Alias support to the Yaml model and JsonPathMatcher 

- rewrite-yaml/src/main/java/org/openrewrite/yaml/internal/YamlPrinter.java
- rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/tree/MappingTest.kt
Handled all supported sequences specified in YAML spec: https://github.com/yaml/yaml-grammar/blob/master/yaml-spec-1.2.txt#L1914
...except for \x20 (space) and arbitrary unicode escapes (eg \x00, \u0000, \U00000000), because they were causing tricky interactions
Fixes #2154
> Improved YamlPrinter behavior for scalars with double-quoted values containing escape sequences

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/cleanup/UseDiamondOperatorTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseDiamondOperator.java
- check MethodDeclaration.returnTypeExpression for context when the new class is a return expression.
- verify the parameterized types are equivalent
> Update UseDiamondOperator (fixes: #2274)

- rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
This is so that a proper selection based on project preference can be established. With tabs and spaces being mixed into one indentFrequencies collection and a project having mixed styles, it results in confusion when `java.AutoDetect` attempts to determine the best style to use.
> Adapt java.AutoDetect to separate spaces vs tabs

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/RenameVariableTest.kt
- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/cleanup/RenamePrivateFieldsToCamelCaseTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RenamePrivateFieldsToCamelCase.java
- inner-class variable references
- NamedVariable existing in multiple scopes
TODO:
- support for ParameterizedTypes
- RewriteTest conversions
> Fix RenameVariable and RenamePrivateFieldsToCamelCase (Issue: #2285)

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11Parser.java
- rewrite-java-11/src/main/java/org/openrewrite/java/Java11UnrestrictedClassLoader.java
- rewrite-java-11/src/test/java/org/openrewrite/java/Java11TypeSignatureBuilderTest.java
- rewrite-java-11/src/test/java/org/openrewrite/java/isolated/Java11TypeSignatureBuilderTestDelegate.java
- rewrite-java-17/src/main/java/org/openrewrite/java/Java17Parser.java
- rewrite-java-17/src/main/java/org/openrewrite/java/Java17UnrestrictedClassLoader.java
- rewrite-java-17/src/test/java/org/openrewrite/java/Java17TypeSignatureBuilderTest.java
- rewrite-java-17/src/test/java/org/openrewrite/java/isolated/Java17TypeSignatureBuilderTestDelegate.java
Reenable type signature builder tests in Java 11 and Java 17.
> TypeSignatureBuilder tests must use unrestricted class loader

- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeSignatureBuilder.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeSignatureBuilder.java
- rewrite-java-17/src/test/kotlin/org/openrewrite/java/Java17TypeMappingTest.kt
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeSignatureBuilder.java
- rewrite-java-tck/src/main/java/org/openrewrite/java/JavaTypeSignatureBuilderTest.java
- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/JavaParserTypeMappingTest.kt
Changes:
- Use the Symbol reference to distinguish variable names and generate a unique signature in the Java signature builders.
- Fixed Java17TypeMappingTest.
fixes #2118
> Generate a unique variable signature based on the Symbol reference.

- build-src/src/main/kotlin/org.openrewrite.java-library.gradle.kts
[CVE-2022-42003](https://nvd.nist.gov/vuln/detail/CVE-2022-42003) 
https://github.com/FasterXML/jackson-databind/issues/3590 
https://github.com/FasterXML/jackson/jackson-databind/issues/3627
> Update jackson bom for CVE-2022-42003

- rewrite-java/src/main/java/org/openrewrite/java/marker/JavaSourceSet.java
Made the condition a little more precise, and added the check to another spot where StringIndexOutOfBoundsExceptions were at risk
#2002
> Expanded fix for edge case with code obfuscaters and inner classes

- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/JavaParserTest.kt
There was a parser error that resulted in a modifier being places in a whitespace prefix when an annotation had a comment with no whitespace between the end of the annotation and the comment
> Fix parsing issue when annotation comments. Fixes #2313

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/cleanup/HiddenFieldTest.kt
- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/cleanup/RenameJavaDocParamNameVisitorTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/HiddenFieldVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/RenameJavaDocParamNameVisitor.java
Changes:
- Added `RenameJavaDocParamNameVisitor`. The `RenameJavaDocParamNameVisitor` will update a `@param` name in a JavaDoc.
- Updated `HiddenFieldVisitor` to rename Java doc params long with renamed fields.
Polish:
- Updated HiddenFieldTest to use RewriteTest.
fixes #2298
> Update JavaDoc params along with fields in HiddenField

- rewrite-hcl/src/main/java/org/openrewrite/hcl/format/TabsAndIndentsVisitor.java
I hit an issue trying to use this class to create a custom formatter that is different from default AutoFormatVisitor. 
I'm guessing this was unintentional. No reason to make this class package private.
> Add public qualifier to HCL TabsAndIndentsVisitor

- rewrite-maven/src/main/java/org/openrewrite/maven/RemoveExclusion.java
- rewrite-maven/src/test/java/org/openrewrite/maven/RemoveExclusionTest.java
Change `RemoveExclusion` recipe to use `Tag#getContent()` rather than `Tag#getChildren()` so that comments are preserved.
> Maven `RemoveExclusion` recipe should preserve comments

- rewrite-maven/src/main/java/org/openrewrite/maven/AddRepository.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java
- rewrite-maven/src/test/java/org/openrewrite/maven/AddRepositoryTest.java
Recently I've created a PR to add Maven Repository to the pom. However, I've noticed that although XML does appear the model sort of still misses the repo. I though I was missing `maybeUpdateModel()` but it didn't help.
Please see the test I have added. It'd be great if anyone could point me to what is missing. So far I think `UpdateMavenModel` visitor is likely missing the bit updating repositories.
> Add repo - model not changed. Also fixes #2398

- rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Support IDE multiprojects (including IntelliJ) so tests can be debugged even if they reside in the same multiproject as some of the artifacts they add to the classpath.
Solution: Don't just match on jars, but also on exploded artifact directories (regardless if they are maven or gradle format).
Fixes https://stackoverflow.com/questions/74386486/openrewrite-run-unit-test-in-the-ide-intellij-that-uses-classes-from-the-same
> Support multiproject builds from the IDE

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/search/UsesTypeTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/search/UsesType.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Changes:
- UsesType supports `JavaType$Primitive`.
- TypeUtils#isAssignableTo(Pattern, Type) supports `JavaType$Primitive`.
fixes #2427
> Added support for JavaType$Primitive in UsesType.

- rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
Changes
- JavaPrinter will print semi-colons based on the `terminatedWithSemiColon` flag.
fixes #2435
> Print semi-colons in J.Try.Resources based on AST in JavaPrinter.

- rewrite-hcl/src/main/java/org/openrewrite/hcl/format/AutoFormatVisitor.java
- rewrite-hcl/src/main/java/org/openrewrite/hcl/format/NormalizeFormatVisitor.java
- rewrite-hcl/src/test/java/org/openrewrite/hcl/format/AutoFormatTest.java
- rewrite-hcl/src/test/java/org/openrewrite/hcl/format/BracketSpacesTest.java
The way `NormalizeFormatVisitor` is moving spaces around the parts of for loops is causing the HCL to become invalid.
For example,
- `visitForIntro` is causing `a = [ for v in ["a", "b"] : v ]` to turn into `a = [ forv in ["a", "b"] : v ]`
- `visitForTuple` is causing `a = [ for v in ["a", "b"] : v ]` to turn into `a = [for v in ["a", "b"] : v ]`
This PR removes the offending blocks from NormalizeFormatVisitor. Also reodring the visitors in AutoFormatVisitor since I found a scenario where `SpacesVisitor` is dependent on the spaces created by `TabsAndIndentsVisitor`
> Fix for HCL AutoFormat issue where spaces around for-loop parts are moved incorrectly causing invalid HCL

- rewrite-java-17/src/test/java/org/openrewrite/java/tree/SwitchExpressionTest.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Changes:
- visiting a `J.SwitchExpression` will not cause a StackOverflowException.
- `J.SwitchExpression#getType()` will return the appropriate `JavaType.`
fixes #2357
> Fix SOE visiting switch expressions.

- rewrite-core/src/main/java/org/openrewrite/Result.java
- rewrite-core/src/test/kotlin/org/openrewrite/ResultTest.kt
There is currently no way to generate diffs that excludes (aka ignore) whitespace changes from recipes. This can be helpful when a recipe performs changes in addition to formatting, and the consumer wants to focus on the substantive changes.
Add an additional option to the `diff` method to control the formatting algorithm used by jgit
> feat: add option to ignore whitespace from diff

- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddGradleWrapper.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/util/DistributionInfos.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/util/GradleWrapper.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/util/GradleWrapperJar.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/AddGradleWrapperTest.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoteGradleWrapperJarTest.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/util/DistributionInfosTest.java
- Fix `gradle-wrapper.jar` location
Gradle distributions contain the `gradle-wrapper.jar` in different paths depending on
Gradle versions.
Because of this current Gradle Wrapper Add/Upgrade recipes for Gradle 7.5 is broken, this will fix it.
- Set `distributionSha256Sum` in gradle-wrapper.properties
Gradle validates a newly downloaded wrapper distribution if the `distributionSha256Sum` property is set in gradle-wrapper.properties (see [here](https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification) for more infos). This change will have the recipe fetch the checksum and add it or update it to the ù gradle-wrapper.properties`.
- Fetch the `gradle-wrapper.jar` checksum and associate it to the remote source file. I'm not sure though if it's checked at any …
> Fix various issues with Gradle Wrapper recipes

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenDownloadingExceptions.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UncheckedMavenDownloadingException.java
Fixes #2453 
- Silently ignore exception occurring during the preparation of the exception
- Make sure the download exception cause are kept in the stack trace
> Exception hiding the actual cause leads to unusable information, fixes #2453

- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
- rewrite-java-17/src/test/java/org/openrewrite/java/tree/RecordTest.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
- rewrite-java/src/main/java/org/openrewrite/java/marker/CompactConstructor.java
Changes:
- Added detection for CompactConstructors in ReloadableJava17ParserVisitor.
- Added CompactConstructor marker for records.
fixes #2455
> Added parsing support for CompactConstructors on records.

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/ChangePackageTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
**Problem**
Changing the package of a class files that does a static import of an enum _value_ for which the enum class resides in the same package (and also gets moved) creates uncompilable code.
**Why?**
In Java (Java Language Spec), you don't need to import classes from the same package explicitly.
But you do need to static import enum values from classes from the same package explicitly.
The same requirement applies to static import of methods.
**Proof**
The test fails locally as expected (see below). This PR is also includes a proposed fix.
> ChangePackage bug reproducer test + fix: static import enum same package

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/JavaTypeTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Changes:
- Updating the `J.MethodInvocation#name` will not create a new instance of `JavaType$Method` for changes unrelated to type info.
fixes #2493
> Update MethodInvocation type when applicable.

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenDownloadingException.java
Trivial change, but didn't want to do it silently because:
- I know this stuff was written recently and I've seen discussion in slack about UX of the exception handling
- I also considered removing this if-check altogether, or, trying to catch the MavenDownloadingException and calling `setRoot` somewhere in the `parseInputs -> resolveParentDependenciesRecursively` flow (it felt like an oversight that the root wasn't being set somewhere for download exceptions during parsing)
Excluding the `failedOn` seems like an optimization for the scenario where this message is getting printed as a marker on the offending pom element, but it's a bad experience when you get the exception message in isolation somewhere else.
Eg, for the test case described over in this issue …
> adjusted MavenDownloadingException getMessage

- rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesVisitor.java
`Property.Value` is a bit of an odd bird, in that it does not implement/extend from `Properties` even though it does have AST-like properties (It has a prefix and it has markers). 
Adding a `Properties.Value visitValue(Properties.Value)` method to the `PropertiesVisitor` to allow the visitor to navigate into the value and its markers.
Because `Value` does not extend a Tree, there is no `accept` method on `Value` and the method signature for `visitValue()` does NOT return a Properties instance.
> Add `visitValue()` to `PropertyVisitor`

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/ChangeTypeTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Changes:
- Classes declared in the CompilationUnit will not be imported.
fixes #2521.
> Do not import classes that are declared in the CU in the ChangeType recipe.

- rewrite-java-tck/src/main/kotlin/org/openrewrite/java/cleanup/FinalizeLocalVariablesTest.kt
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizeLocalVariables.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
The non-modifying unary operators (`-`, `+`, `~`, and `!`) must not prevent a local variable from being made final.
> Make `FinalizeLocalVariables` aware of non-modifying unary operators

- rewrite-gradle/src/main/java/org/openrewrite/gradle/ActivateStyle.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddProperty.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
- rewrite-properties/src/main/java/org/openrewrite/properties/AddProperty.java
- rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java
- rewrite-properties/src/main/java/org/openrewrite/properties/internal/PropertiesPrinter.java
- rewrite-properties/src/main/java/org/openrewrite/properties/tree/Properties.java
- rewrite-properties/src/test/java/org/openrewrite/properties/ChangePropertyTest.java
- rewrite-properties/src/test/java/org/openrewrite/properties/PropertiesParserTest.java
Changes:
- The PropertiesParser will preserve the delimiter in the source code.
- Properties support `=`, `:` or whitespace as delimiters between the key and value. Before the changes the delimiter was always set to `=`.
- Added Option to `AddProperty` recipe to set the desired property entry delimiter (defaults to `=`).
fixes #2532
> Preserve the source code delimiter of property entries in PropertiesParser.

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
- rewrite-maven/src/main/java/org/openrewrite/maven/RemoveDuplicateDependencies.java
- rewrite-maven/src/test/java/org/openrewrite/maven/RemoveDuplicateDependenciesTest.java
For now the recipe can only remove duplicates, but in the future it could maybe also sort dependencies (only by scope since sorting dependencies within a scope may have undesired effects due to Maven's dependency resolution).
Fixes #2381
> New Maven `RemoveDuplicateDependencies` recipe

- rewrite-core/src/main/java/org/eclipse/jgit/util/FS.java
When using the rewrite-gradle-plugin, JGit's FS class adds a Runtime shutdown hook that inadvertently creates a shadow reference to the RewriteClassLoader of the plugin's classpath isolation feature. This expands to effectively mean that each time the rewrite configuration is modified and a new RewriteClassLoader is created, the previous one is leaked on the heap without ever being able to be reclaimed by the garbage collector. The included patch here removes just the shutdown hook, so that we can stop leaking the classloader
> Patch JGit FS class to prevent classloader memory leak

- rewrite-core/src/main/java/org/openrewrite/internal/EncodingDetectingInputStream.java
- rewrite-core/src/main/java/org/openrewrite/text/PlainTextParser.java
Slightly improves the performance of `EncodingDetectingInputStream` by refactoring the `read()` method and avoiding the additional `byte[]` copy in `readFully()`.
Also make sure that `PlainTextParser#parseInputs()` reads the source text before the encoding, since the latter won't be correctly set otherwise.
> Improve performance of `EncodingDetectingInputStream`

- rewrite-gradle/build.gradle.kts
- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseStringNotation.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/internal/InsertDependencyComparator.java
- rewrite-gradle/src/main/resources/RewriteGradleProject.groovy
- rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyVisitor.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/format/MinimumViableSpacingVisitor.java
This also fixes a whitespace bug in the GroovyParser for `G.MapEntry` types. Essentially, the whitespace was being placed on the key element, but should have been placed upon the `G.MapEntry` itself.
> Add dependency support for gradle

- rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
This PR attempts to address issue https://github.com/openrewrite/rewrite/issues/1698
I added tests for "nonstandard" package names. So far I have only found issues with imports that:
- include a lower case class name in the package path 
- include multiple camel cased names in the package path
I attempted to investigate why this was happening but ultimately found that the underlying code in the JCTree was returning these values. What I have proposed here was something I found to work by trial and error.
> Issue 1698: adding additional check for nonstandard package names

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/HiddenFieldTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/HiddenFieldVisitor.java
By using a `LinkedHashSet` rather than a regular `HashSet` in `FindNameShadows#find()` to collect the shadowing variables, the renaming of the variables becomes predictable. I.e. the same variable always gets renamed to the same name if the recipe is tested multiple times. This is especially important for tests.
Fixes #2592
> Make `HiddenField` recipe predictable

- rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
This fix prevents a null timestamp from producing an invalid URI, resulting in `MavenDownloadingExceptions` and maven-parser failures.
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.39.0-SNAPSHOT:run (default-cli) on project ...: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.39.0-SNAPSHOT:run failed: Failed to download dependencies for .../pom.xml:
</dependency>
<dependency> 
at org.openrewrite.maven.MavenParser.parseInputs (MavenParser.java:127)
at org.openrewrite.Parser.parse (Parser.java:41)
at org.openrewrite.maven.MavenMojoProjectParser.parseMaven (MavenMojoProjectParser.java:309)
at org.openrewrite.maven.MavenMojoProjectParser.listSourceFiles …
```
> Null `MavenMetaData.Snapshot#timestamp` causes maven parser failures.

- rewrite-gradle/src/main/resources/META-INF/rewrite/gradle.yml
This also relocates `EnableGradleParallelExecution` so that it's not inappropriately located in the `Search` category.
> Add recipe to enable build cache

- rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
The `FindMissingTypes` recipe is typically used by `RewriteTest` which parse Java sources using `import static org.openrewrite.java.Assertions#java()`. Additionally, it is also used by the `NoMissingTypes` recipe, which in turn is used as a single-source applicability test by some recipes like `RemoveUnusedImports` and `RemoveUnusedPrivateMethods`.
By adding an overload `TypeUtils#isWellFormedType(JavaType, Set<JavaType>)`, the client can now check multiple types within a "session", as represented by the `Set<JavaType>` parameter, without having to transitively recheck the same types multiple times.
> Optimize and fix bug in `FindMissingTypes` recipe

- rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRepository.java
- rewrite-maven/src/test/java/org/openrewrite/maven/RemoveRepositoryTest.java
The corresponding test suite currently only contains tests that uses the id/url parameters (not repoName, layout, snapshotsEnabled, etc., which will be added soon!).
> Create RemoveRepository recipe

- rewrite-java-11/build.gradle.kts
- rewrite-java-17/build.gradle.kts
- rewrite-java-8/build.gradle.kts
- settings.gradle.kts
This initially presented only on Windows, but could easily have presented on any other operating system. Essentially, the `compatibilityTest` testing task was reaching into another project's configuration and specifically trying to get informaton about it's `sourceSet` configuration settings. However, if that project was not yet configured, then it would not have had the `JvmEcosystemPlugin` applied to it. Without the `JvmEcosystemPlugin`, this would mean that there was no `sourceSet` container to get information from ultimately leading to one of the rewrite-java-* projects failing to configure with a rather vague error messaging stating these same qualities. At first glance, it would appear that the `sourceSet` container was missing from the current project (ie. rewrite-java-*), while in …
> Fix issue with configuring rewrite-java-* Gradle projects

- rewrite-java-test/src/test/java/org/openrewrite/java/DeleteStatementTest.java
- rewrite-java/src/main/java/org/openrewrite/java/DeleteStatement.java
Closes https://github.com/moderneinc/support-public/issues/19
Related https://github.com/openrewrite/rewrite/pull/2627
> Fix `DeleteStatements` improperly deleting certain statements

- rewrite-java/src/main/java/org/openrewrite/java/TreeVisitingPrinter.java
Adds a visitor to print LST visiting order and hierarchy.
This visitor can help new developers (including me) to understand what the LST looks like, and what `visitX` method should use when implementing a recipe.
Skip unvisited elements like `JRightPadded` or `JLeftPadded` from the output, but keeps an option to print all elements which may be extensible in the future. 
An example:
input source code :
```
import java.io.BufferedReader;
class T {
public void doSomething(StringBuilder sb, BufferedReader br) {
String line;
try {
while ((line = br.readLine()) != null) {
sb.append(line);
}
} catch (Exception e) {
error("Exception", e);
}
}
private static void error(String s, Exception e) {
}
}
```
An example usage, add this code in any recipe visitor to print the LST to the console.
``` …
```
> Introduce tree visiting hierarchy printer

- rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java
- rewrite-core/src/main/java/org/openrewrite/internal/FindRecipeRunException.java
- rewrite-core/src/main/java/org/openrewrite/internal/RecipeRunException.java
- rewrite-core/src/main/java/org/openrewrite/marker/Markup.java
- rewrite-core/src/test/java/org/openrewrite/RecipeSchedulerTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaVisitorTest.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
Minimally, these exceptions will now include the visited file, and grammar-specific visitors can add more precise info (eg for JavaVisitor I've added quick logic to specify by class/method name).
Would be neat to expand with line numbers, but, I didn't see an obvious way to get that during a visit
#2655
> Adding visited-file details to unexpected exceptions

- rewrite-core/src/main/java/org/openrewrite/internal/NameCaseConvention.java
- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/RenamePrivateFieldsToCamelCaseTest.java
The internal method `NameCaseConvention#matches(NameCaseConvention, String)` should not do a regex match of the provided string, but rather an equality check.
There is a provided test case which otherwise fails. While a regex match would typically also work (although "overkill"), it fails if the variable name being matched contains a `$` character.
> Fix NameCaseConvention#matches(NameCaseConvention, String)

- rewrite-gradle/src/test/java/org/openrewrite/gradle/search/DependencyInsightTest.java
- rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java
- rewrite-maven/src/main/java/org/openrewrite/maven/MavenSettings.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawRepositories.java
- rewrite-maven/src/main/java/org/openrewrite/maven/table/MavenMetadataFailures.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/Dependency.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepository.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepositoryMirror.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedDependency.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
- rewrite-maven/src/test/java/org/openrewrite/maven/MavenDependencyFailuresTest.java
- rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeParentVersionTest.java
- rewrite-maven/src/test/java/org/openrewrite/maven/cache/RocksdbMavenCacheTest.java
- rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Previously, the maven model was using Boolean in three places where flags can be defined in the pom files. The problem with using Booleans is that these fields will fail to deserialize if a property placeholder is used for those flags: 
The three places this was an issue were: 
```
<repositories>
<repository>
<releases><enabled>${prop}</enabled></releases>
<snapshots><enabled>${prop}</enabled></snapshots>
</repository>
</repositories>
...
<dependencies>
<dependency>
<optional>${prop}</opitional>
</dependency>
</dependencies>
```
To address this issue, these three fields need to be represented as nullable strings in both the `RawPom`, `Dependency`, and `MavenRepository` data models. 
All references to these fields in the code base have been swept to treat them as null strings and when a …
> Change maven model flags to strings to support property placeholders

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizePrivateFieldsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizePrivateFields.java
@knutwannheden found a false positive case in[ this comment](https://github.com/openrewrite/rewrite/issues/2611#issuecomment-1396576672),  If the field is reassigned from some context using the `this` keyword like this, the `final` keyword will be added but it shouldn't.
```
@Test
void fieldReassignedByAMethodUsingThis() {
rewriteRun(
java(
"""
class A {
private String name = "ABC";
void func() {
this.name = "XYZ";
}
String getName() {
return name;
}
}
"""
)
);
}
```
also added more test cases of different `this` keyword usage, and multiple constructor cases.
> Fix one positive case of `FinalizePrivateField` recipe and add more test cases

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizePrivateFieldsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizePrivateFields.java
The recipe should distinguish between reading and modifying unary operators, as this may allow a few more fields to be made final.
> Fix handling of unary operator in `FinalizePrivateField`

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizePrivateFieldsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/TreeVisitingPrinter.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizePrivateFields.java
Fix uncovered lambda case by recipe `FinalizePrivateFields` found by @knutwannheden  at [here](https://github.com/openrewrite/rewrite/issues/2611#issuecomment-1397667017).
> Fix an uncovered lambda case of FinalizePrivateField recipe

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizePrivateFieldsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizePrivateFields.java
Fix an uncovered case of FinalizePrivateFields with `Lombok` `setter` annotation.
This is to address @timtebeek 's comment [here](https://github.com/openrewrite/rewrite/pull/2663#issuecomment-1399605676).
**Issue**
If any field has an annotation like `@Setter` from Lombok, a setter method will be automatically generated.
Finalizing that field could make compile error if somewhere else used the generated setter method.
An example use case, 
```
import lombok.Setter;
public class A {
private @Setter String name = "ABC";
static void test() {
A a = new A();
a.setName("XYZ");
}
}
```
**Solution:**
Skip all classes that have any annotation, or fields that have any annotation.
This solution will falsely skip some normal use cases and got a lot of classes uncovered, but technically, since we can …
> Fix an uncovered case of FinalizePrivateFields with `Lombok` `setter` annotation

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizePrivateFields.java
When running the `finalizePrivateFields` recipe in SAAS, saw an [error](https://public.moderne.io/results/MP9pW/details/eyJfX3R5cGVuYW1lIjoiR2l0SHViUmVwb3NpdG9yeSIsImlkIjoiR2l0SHViUmVwb3NpdG9yeX5+Z2l0aHViLmNvbX5+TmV0ZmxpeC9nZW5pZX5+bWFzdGVyIiwib3JpZ2luIjoiZ2l0aHViLmNvbSIsInBhdGgiOiJOZXRmbGl4L2dlbmllIiwiYnJhbmNoIjoibWFzdGVyIiwib3JnYW5pemF0aW9uIjoiTmV0ZmxpeCIsIm5hbWUiOiJnZW5pZSJ9?onlyShowErrors=true&referrer=%2Fresults%2FMP9pW) here.
The error message is `Duplicate key null` (see the below picture), it turns out that some private fields have null `variableType`. so adding a null check filter to fix this error.
> Adds filtering null fieldType to finalizePrivateRecipe to fix error

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyDurationCreationUnitsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyDurationCreationUnits.java
As requested in #2687; tests should fully illustrate the behavior.
I'm taking a stab at the condition covered by the last test case since it seems doable, but putting up a PR for this since it should be good-to-go without it.
> Simplify java.time.Duration creation units to be more readable

- rewrite-core/src/main/java/org/openrewrite/Result.java
- rewrite-core/src/test/java/org/openrewrite/ResultTest.java
`gradlew` could be changed from `0755` to `0644` because the `InMemoryDiffEntry` was assuming jgit
`FileMode.REGULAR_FILE` when the `SourceFile` had been marked as `executable`
> fix: use `FileAttributes` to drive `FileMode` on diffs

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizeLocalVariables.java
In the [last PR](https://github.com/openrewrite/rewrite/pull/2730) I fixed a comment that was incorrect. However, I didn't realize that the link in the comment added an import to the file. This removes the unused import.
> Remove unused import

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/MethodNameCasingTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodNameCasing.java
The Moderne SaaS appears to instantiate recipes using `null` values for `Boolean` options when the user doesn't explicitly select either the `true` or `false` radio button. In the case of `MethodNameCasing#renamePublicMethods` the `null` value had the same effect as `true`, which is now fixed.
Relates to: #2424
> Default `MethodNameCasing#renamePublicMethods` to `false`

- rewrite-hcl/src/main/java/org/openrewrite/hcl/format/TabsAndIndentsVisitor.java
- rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/format/IndentsVisitor.java
A problem with the logic in `TabsAndIndentsVisitor` which was observed with the `RemoveUnusedImports` recipe could lead to the whole or at least the beginning of compilation units with a copyright header getting indented. This problem may also affect other recipes using the `JavaVisitor#autoFormat()` method.
Fixes #2722
> Fix bug in `TabsAndIndentsVisitor`

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/NoDoubleBraceInitializationTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoDoubleBraceInitialization.java
To fix the issue https://github.com/openrewrite/rewrite/issues/2710
A bug example.
```java
import java.util.HashMap;
import java.util.Map;
class A {
void example() {
Map<String, String> bMap = new HashMap<String, String>() {
{
subClassMethod();
put("a", "A");
put("b", "B");
}
void subClassMethod() {
}
};
}
}
```
is turned into
```java
import java.util.HashMap;
import java.util.Map;
class A {
void example() {
Map<String, String> bMap = new HashMap<String, String>();
bMap.subClassMethod();
bMap.put("a", "A");
bMap.put("b", "B");
}
}
```
method `subClassMethod` missed and break compile.
Make sure for the double brace case,  there is only one statement in the first brace, not others like method declaration allowed.
> Fix a bug of  recipe `NoDoubleBraceInitialization` when there is any method declared in the anonymous subclass and be invoked.

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizePrivateFieldsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizePrivateFields.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Variable declaration modifiers are both stored as `J.Modifier` objects in the LST and as flags on the corresponding `JavaType.Variable` object. The recipe was only updating the former, which had the consequence that the recipe didn't play nicely with for example `RenamePrivateFieldsToCamelCase`, which is based on the latter.
Related to: #2611
> `FinalizePrivateFields` also needs to update the `JavaType`

- rewrite-core/src/main/java/org/openrewrite/Recipe.java
- rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
- rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
- rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java
- rewrite-core/src/test/java/org/openrewrite/config/YamlResourceLoaderTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/RecipeExceptionDemonstrationTest.java
- rewrite-test/src/main/java/org/openrewrite/test/RecipeSchedulerCheckingExpectedCycles.java
To fix Issue https://github.com/openrewrite/rewrite/issues/2711
Please see https://github.com/openrewrite/rewrite/issues/2711
> Currently yaml recipes with applicability tests aren't working right. The applicability test is being checked before each recipe in the recipe list, rather than once for the whole list. This can lead to unexpected results.
We use a stack of recipes to manage and run nested recipes, the current running recipe is the always on the top of the stack.
Before running a recipe, the applicability tests of each recipe in the stack are all performed, which is not expected.
For example, if a composite recipe looks like this 
```yaml
applicability:
singleSource:
- ApplicableTestRecipe:
recipeList:
- Recipe1
- Recipe2
```
The expected running order should be looks like …
> Fix the issue of applicable tests doesn't work as expected.

- rewrite-java-test/src/test/java/org/openrewrite/java/InstanceOfPatternMatchTest.java
- rewrite-java/src/main/java/org/openrewrite/java/InstanceOfPatternMatch.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Implement a recipe which for Java 17+ transforms `instanceof` expressions which have a corresponding type cast within their flow scope (see https://openjdk.org/jeps/394 for details) to an `instanceof` with a pattern variable and then also substitutes the type cast expressions accordingly.
> New `InstanceOfPatternMatch` recipe

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReferenceTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReference.java
The `ReplaceLambdaWithMethodReference` recipe now also handles instance methods, where the method select corresponds to the first lambda parameter.
So for example in a Stream a `map()` call like `map(o -> o.toString())` will now be rewritten as `map(Object::toString)`.
Also constructor calls are now replaced by method references. E.g. `ThreadLocal.withInitial(() -> new Object())` becomes `ThreadLocal.withInitial(Object::new)`.
> Handle instance methods and constructor calls in `ReplaceLambdaWithMethodReference`

- rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java
- rewrite-core/src/test/java/org/openrewrite/marker/GitProvenanceTest.java
Exceptions where hidden, making it tough to debug in Graal where an IllegalArgumentException wraps a NoSuchMethodException.
> Print stacktrace on IllegalArgumentException in JGit

- rewrite-gradle/src/main/java/org/openrewrite/gradle/util/GradleWrapper.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/AddGradleWrapperTest.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/util/GradleWrapperTest.java
issue: https://github.com/openrewrite/rewrite/issues/2746
`GradleWrapper.validate() ` returns an invalid if the input distribution is `bin`, but in the validation, it's expected to be `Bin` which is case-sensitive. Change to parse enums in a case-insensitive way.
error message: 
```
Recipe validation error in distributionType: must be a valid distribution type
```
> Fix validation failure of GradleWrapper caused by case-sensitive distribution type string

- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/ImplementInterface.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ExplicitLambdaArgumentTypes.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseCollectionInterfaces.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseLambdaForFunctionalInterface.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindFieldsOfType.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
This changes `J.ParameterizedType#getType()` to return a `JavaType.Parameterized` rather than always a `JavaType.Class` object by adding an explicit `type` field to the class which needs to be kept in sync with changes made to the LST.
Some recipes had to be changed as a consequence of this refactoring.
> Make `J.ParameterizedType#getType()` return a `JavaType.Parameterized`

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/InstanceOfPatternMatchTest.java
- rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
The implementation of `J.Unary#getSideEffects()` should always return the expression itself as a side effect if it is a modifying unary operator (e.g. postfix `++`).
Also, while implementing a test for this indirectly via `InstanceOfPatternMatchTest` I noticed that `SemanticallyEqual` doesn't allow comparing `J.Parentheses` and `J.ControlParentheses` instances. This is problematic in the case of the `InstanceOfPatternMatch` recipe, as in the `instanceof` it would be the former and in the type cast the latter type.
Further, a few more deficiencies in `SemanticallyEqual` have been fixed.
> Fix `J.Unary` side effects and `SemanticallyEqual`

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/InstanceOfPatternMatchTest.java
- rewrite-java/src/main/java/org/openrewrite/java/ImplementInterface.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/InstanceOfPatternMatch.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoDoubleBraceInitialization.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Both the types in the `instanceof` and the type cast expression can use generics or not. The recipe must be able to deal with this correctly by checking the type assignability.
> Fix handling of generics in `InstanceOfPatternMatch`

- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java
- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/RemoveUnusedLocalVariablesTest.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Add a new enum constant `JavaType.FullyQualified.Kind.RECORD` for `JavaType.Class` instances representing records. This is required so that  `FindMissingTypes.FindMissingTypesVisitor#visitClassDeclaration()` doesn't report an error (with message `J.ClassDeclaration kind Record does not match the kind in its type information Class`).
> Add `JavaType.FullyQualified.Kind.RECORD`

- rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ExplicitLambdaArgumentTypesTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/InstanceOfPatternMatchTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/RemoveUnusedPrivateMethodsTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/RenamePrivateFieldsToCamelCaseTest.java
Unless a test case explicitly tests that a recipe behaves correctly in the presence of unresolved type references or the recipe is purely syntactic (e.g. formatting), it makes sense if all type references can be resolved, as otherwise the test may inadvertently be incorrect.
> Fix type errors in a few before sources of tests

- rewrite-java-test/src/test/java/org/openrewrite/java/format/SpacesTest.java
- rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
Issue: https://github.com/openrewrite/rewrite/issues/2681
1. For spaces in method declaration, after the method name and before parentheses, there is a space style [BeforeParentheses.methodDeclaration](https://github.com/openrewrite/rewrite/blob/19df599e6612b1f2dfbe5cf57704eab7f4ee66ff/rewrite-java/src/main/java/org/openrewrite/java/style/SpacesStyle.java#L40), an example [here](https://github.com/openrewrite/rewrite/blob/c98e8a12cf41ec29536e3c65c6eacbe2c91cece5/rewrite-java-test/src/test/java/org/openrewrite/java/format/SpacesTest.java#L101).
However, this case is not supported well.
```java
class Test {
void method1    () {
}
}
```
```
expected: 
"class Test {
void method1() {
}
}"
but was: 
"class Test {
void method1    () {
}
}"
```
3. For spaces in the argument list, there is a space …
> Enhance the `Space` recipe to support transformation for multiple whitespaces

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/AvoidBoxedBooleanExpressionsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/CoordinateBuilder.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
A unary expression (like e.g. `!b`) cannot be used as a statement on its own like modifying unary expressions (like `i++`) can. As a result the `JavaTemplate` must use a corresponding coordinate when replacing a unary expression, as otherwise the Java code produced by the template compiler is incorrect.
This problem affects multiple recipes. So far `CompareEnumsWithEqualityOperator` and `AvoidBoxedBooleanExpressionsTest` have been identified.
> Fix the replacement coordinates for unary expressions

- rewrite-core/src/test/java/org/openrewrite/text/AppendToTextFileTest.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/AddGradleWrapperTest.java
- rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Fixes #2796
I found a defect that `RewriteTest.rewriteRun()` cannot detect unexpected newly generated files.
An example test is
```java
@Test
void demonstrateRewriteRunDefect() {
rewriteRun(
spec -> spec.recipe(new AppendToTextFile("file1.txt", "content1", "preamble1", true, "replace")
.doNext(new AppendToTextFile("file2.txt", "content2", "preamble2", true, "replace"))),
text(
"existing2",
"""
preamble2
content2
""",
spec -> spec.path("file2.txt").noTrim()
)
);
}
```
Recipe `AppendToTextFile` is expected to create new files `file1.txt` here, so the expected results are
```diff
Results = 
diff --git a/file1.txt b/file1.txt
new file mode 100644
index 0000000..0ece344
--- /dev/null
+++ b/file1.txt
@@ -0,0 +1,2 @@ org.openrewrite.text.AppendToTextFile
+preamble1
+content1
diff --git …
```
> Fix a defect of `RewriteTest.rewriteRun()`  that cannot detect unexpected newly generated files

- rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
Language Server <-> client comm is corrupted by sys out statements since standard in and out are used for JSON RPC message exchange only.
> No sys out print statements

- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/IsEmptyCallOnCollectionsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/IsEmptyCallOnCollections.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
Uses `JavaTemplate` to replace the `J.Binary` rather than the `J.MethodInvocation` as that is also what is the intention.
Fixes #2813
> Fix `IsEmptyCallOnCollections` in for loop control

- rewrite-java-test/src/test/java/org/openrewrite/java/UpdateSourcePositionsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/UpdateSourcePositions.java
Light performance improvements: ~15%
Was thinking about `includeMarkers` `boolean` option. If `false` won't attempt to visit `Markers` consequently no positions assigned to markers. Yields another 10%. However, compared to overall running time of the recipe felt like it is not worth it.
> Slight performance improvements to Source Positions recipe

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UnnecessaryExplicitTypeArgumentsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/UnnecessaryExplicitTypeArguments.java
When the initializer of a `var` declared variable calls a method with type arguments, these arguments should not be removed, as otherwise the type cannot be deduced and the Java code doesn't compile.
Fixes: #2818
> `UnnecessaryExplicitTypeArguments`: Don't apply to `var` variables

- rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java
- rewrite-core/src/test/java/org/openrewrite/internal/ListUtilsTest.java
In case the mapping function returned an `Iterable` for one or more elements, the `flatMap()` method will now return the input list if the elements are all identical.
> Improve the equality check in `ListUtils#flatMap()`

- rewrite-core/src/main/java/org/openrewrite/internal/RecipeIntrospectionUtils.java
- rewrite-core/src/main/java/org/openrewrite/text/AppendToTextFile.java
- rewrite-core/src/test/java/org/openrewrite/config/CategoryTreeTest.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
- rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/HclParserVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeStaticFieldToMethod.java
- rewrite-java/src/main/java/org/openrewrite/java/RemoveObjectsIsNull.java
- rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowSummaryDotVisualizer.java
- rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeTabsOrSpacesVisitor.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
- rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
- rewrite-xml/src/main/java/org/openrewrite/xml/format/NormalizeTabsOrSpacesVisitor.java
If IDEA hasn't been configured appropriately, sometimes the JetBrains nullness annotations slip in.
> Consistently use OpenRewrite nullness annotations

- rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
- rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
Closes https://github.com/openrewrite/rewrite/issues/2809
> fix: `AddImport` should allow static imports from `java.lang`

- rewrite-java/build.gradle.kts
- rewrite-java/src/main/java/org/openrewrite/java/ai/package-info.java
- rewrite-java/src/main/java/org/openrewrite/java/table/package-info.java
- rewrite-java/src/test/java/org/openrewrite/java/OpenRewriteArchitectureTest.java
ArchUnit can be used to enforce certain architectural constraints. Typically, these get checked by the build system by executing them as tests (using JUnit).
This first set of tests only applies to `rewrite-java` and only checks that all Java packages have a `package-info.java` including a `@NonNullApi` annotation and that the JetBrains nullness annotations are not used.
> Add first simple ArchUnit tests

- rewrite-core/src/main/java/org/openrewrite/SourceFile.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/format/OmitParenthesesFormat.java
- rewrite-java-test/src/test/java/org/openrewrite/java/MethodParamPadTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodParamPad.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/TypecastParenPad.java
- rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
The `MethodParamPad` recipe now uses the first method parameter (or corresponding `J.Empty` marker if there are none) as the stop criterion for the `SpacesVisitor` rather than the method declaration itself.
To get this to work in the context of the `MethodParamPad` the `SpacesVisitor` had to be changed to add the stop message to the root cursor, since when visiting a subtree there is not necessarily any cursor for the source file node.
> `MethodParamPad` no longer formats entire method body

- rewrite-core/openrewrite.json
This is a first draft of the JSON schema for OpenRewrite resource descriptors. Although the resource descriptor types themselves currently include a version "v1beta", this schema currently doesn't have any version number.
Fixes #2823
> First draft of JSON schema for OpenRewrite resources

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceTextBlockWithStringTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceTextBlockWithString.java
Maybe such a recipe will be useful, if it doesn't already exist.
> Add recipe to replace text blocks with strings

- rewrite-java-11/src/main/java/org/openrewrite/java/Java11Parser.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
- rewrite-java-17/src/main/java/org/openrewrite/java/Java17Parser.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
- rewrite-java-8/src/main/java/org/openrewrite/java/Java8Parser.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Partial reset of the JavaParser to avoid exception urging to call `reset()`
> Java parser partial reset

- rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
- rewrite-core/src/main/java/org/openrewrite/filter/RecipeApplicableTest.java
- rewrite-core/src/main/java/org/openrewrite/filter/RecipeSingleSourceApplicableTest.java
- rewrite-core/src/main/java/org/openrewrite/filter/package-info.java
- rewrite-java-test/src/test/java/org/openrewrite/java/filter/SourceApplicabilityFilterTest.java
- rewrite-java/src/main/java/org/openrewrite/java/filter/SourceApplicabilityFilter.java
This is a proposal based upon a discussion here:
https://linuxfoundation.slack.com/archives/C04HR6EJ38D/p1674840301966909
This allows any Recipe to influence the applicability test of later Recipes that are executed.
This allows Recipes to provide filter logic without requiring custom filter logic in every later recipe.
This PR obviously needs tests, but it demonstrates the general idea behind the proposal.
> Allow Recipes to influence later Recipe Applicability

- rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaRecipeLifecycleTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/search/IsOrIsNotLikelyTestTest.java
- rewrite-java/src/main/java/org/openrewrite/java/search/IsLikelyNotTest.java
- rewrite-java/src/main/java/org/openrewrite/java/search/IsLikelyTest.java
Enables applicability tests to be applied exclusively to, or excluding
test source.
Resolves https://github.com/openrewrite/rewrite/discussions/2849
Closes #2850
This enables the following which is exactly what is needed for security fixing vulnerabilities at-scale across OSS:
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.example.FilteringTestSources
displayName: Filtering Test Sources Test
description: Only apply a `FindMethods` recipe to all sources when non-test sources are modified.
applicability:
anySource:
- org.openrewrite.java.search.IsLikelyNotTest
- org.openrewrite.java.search.FindMethods: # Stand in for the security fix recipe to be executed
methodPattern: "java.io.PrintStream println(..)"
recipeList:
- org.openrewrite.java.search.FindMethods: # Stand in for …
```
> Add `IsLikelyTest` and `IsLikelyNotTest` Recipes

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceStreamToListWithCollectTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceStreamToListWithCollect.java
We use the recipe to downgrade Java 17 code to Java 11. I'm not sure whether it could be useful for somebody else.
Anyway, could you please help to fix `preservesFormatting` test? :) How to preserve spacing within method invocation after template application?
> Add recipe to replace Stream.toList() with Stream.collect()

- rewrite-core/src/main/java/org/openrewrite/marker/ci/GitlabBuildEnvironment.java
As per https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
Because GraalVM has issues resolving hostname.
```
JNA: Problems loading core IDs: java.lang.Object
Exception in thread "main" java.lang.NoClassDefFoundError: java/lang/Object
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.FindClass(JNIFunctions.java:343)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:71)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:132)
at …
```
> Use CI_SERVER_HOST to get GitLab host name

- rewrite-core/src/main/java/org/openrewrite/RecipeRunStats.java
- rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
- rewrite-core/src/main/java/org/openrewrite/marker/RecipesThatMadeChanges.java
- rewrite-test/src/main/java/org/openrewrite/test/RecipeSchedulerCheckingExpectedCycles.java
This reverts commit a8b2744ab6873ae213a5ecc994c2867afe010371.
> Revert "Revert "Cleanup `RecipeScheduler` and associated logic (#2860)""

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizePrivateFieldsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizePrivateFields.java
fixes #2865 
fixes #2869 
Fix a bug in recipe `FinalizePrivateFields` with multiple constructors, if any constructor does not initialize a field, it can not be final.
Skip rewriting if a class has multiple constructors.
> fix: Fix a bug of recipe FinalizePrivateFields with multiple constructors

- rewrite-core/src/main/java/org/openrewrite/ExecutionContext.java
- rewrite-core/src/main/java/org/openrewrite/Recipe.java
- rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
- rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
- rewrite-core/src/main/java/org/openrewrite/marker/Markup.java
- rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java
- rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/DoesNotUseRewriteSkipTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaRecipeLifecycleTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/RecipeExceptionDemonstrationTest.java
- rewrite-java/src/main/java/org/openrewrite/java/DoesNotUseRewriteSkip.java
- rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
- rewrite-test/src/main/java/org/openrewrite/test/AdHocRecipe.java
- rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Recipes used in applicability tests will have their own applicability tests invoked now.
This means that expensive recipes with light `singleSourceApplicableTest` can be used without incurring a performance overhead of invoking the recipe visitor every time.
> Actually support `Recipe` in `addApplicableTest` & `addSingleSourceApplicableTest`

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ChainStringBuilderAppendCallsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ChainStringBuilderAppendCalls.java
To fix an edge case of incorrectly grouping in `ChainStringBuilderAppendCalls`.
address comments [here](https://github.com/openrewrite/rewrite/pull/2882#discussion_r1115023005)
For example:
```java
sb.append(op + 'a' + 'b')
```
can not rewrite to 
```java
sb.append(op).append('a' + 'b') 
```
(where op is a variable of type String).
but should be 
```java
sb.append(op).append('a').append('b')
```
> fix: an edge case of grouping in `ChainStringBuilderAppendCalls` recipe

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ChainStringBuilderAppendCallsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ChainStringBuilderAppendCalls.java
Fix a tricky edge case of grouping when chaining `StringBuilder.append()` calls.
Example:
```java
StringBuilder sb = new StringBuilder();
String op = "+";
sb.append(1 + 2 + op + 3 + 4);
```
can not transform to 
```java
StringBuilder sb = new StringBuilder();
String op = "+";
sb.append(1).append(2).append(op).append(3).append(4);
```
but should be 
```java
StringBuilder sb = new StringBuilder();
String op = "+";
sb.append(1 + 2).append(op).append(3).append(4);
```
> fix: a tricky edge case of chain StringBuilder.append() calls

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceDeprecatedRuntimeExecMethodsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ChainStringBuilderAppendCalls.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceDeprecatedRuntimeExecMethods.java
Closes https://github.com/openrewrite/rewrite-migrate-java/issues/159
Replace `Runtime.exec(String)` methods to use exec(String[]) instead because the former is deprecated after java 18 and no longer recommended for use by the Java documentation.
Example:
Before
```java
Process process1 = runtime.exec("ls -a -l");
Process process2 = runtime.exec("ls -a -l", envp);
Process process3 = runtime.exec("ls -a -l", envp, dir);
Process process4 = runtime.exec(command);
Process process5 = runtime.exec(command, envp);
Process process6 = runtime.exec(command, envp, dir);
```
After
```java
Process process1 = runtime.exec(new String[]{"ls", "-a", "-l"});
Process process2 = runtime.exec(new String[]{"ls", "-a", "-l"}, envp);
Process process3 = runtime.exec(new String[]{"ls", "-a", "-l"}, envp, dir); …
```
> recipe: Replace deprecated `Runtime.Exec()` methods

- rewrite-gradle/build.gradle.kts
- rewrite-gradle/src/main/java/org/openrewrite/gradle/Assertions.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/GradleParser.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
This enables better alignment in terms of type attribution by utilizing the Gradle, Groovy, and (future) Kotlin versions as provided by the executing Gradle wrapper.
> Remove the gradle-api from being shaded into rewrite-gradle.

- rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java
- rewrite-core/src/main/java/org/openrewrite/marker/ci/BuildEnvironment.java
- rewrite-core/src/main/java/org/openrewrite/marker/ci/CircleCiBuildEnvironment.java
- rewrite-core/src/main/java/org/openrewrite/marker/ci/CustomBuildEnvironment.java
- rewrite-core/src/main/java/org/openrewrite/marker/ci/DroneBuildEnvironment.java
- rewrite-core/src/main/java/org/openrewrite/marker/ci/GithubActionsBuildEnvironment.java
- rewrite-core/src/main/java/org/openrewrite/marker/ci/IncompleteGitConfigException.java
- rewrite-core/src/main/java/org/openrewrite/marker/ci/JenkinsBuildEnvironment.java
- rewrite-core/src/main/java/org/openrewrite/marker/ci/TravisBuildEnvironment.java
- rewrite-core/src/test/java/org/openrewrite/marker/GitProvenanceTest.java
Currently, GitProvenance is mainly calculated using the information that is inside the .git config. Only there is a special behavior when Jenkins is the BuildEnvironment.
However, there is no .git config in GitLab, GitHub and Drone when a repository is checkout and the required Git metadata is on environment variables.
Therefore, this patch adds `BuildEnvironment#buildGitProvenance()` to force an implementation for CI BuildEnvironments. If they need .git config information, such as Jenkins or Travis, they throw `IncompleteGitConfigException`.
A new CustomBuildEnvironment class has also been added to support the use case of fetching external repositories from a GitHub repository.
> GitProvenance Support for non build environments without .git config

- rewrite-java-test/src/test/java/org/openrewrite/java/dataflow/FindLocalFlowPathsStringTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/dataflow/FindLocalTaintFlowTest.java
- rewrite-java/src/main/java/org/openrewrite/java/dataflow/ExternalFlowModels.java
- rewrite-java/src/main/java/org/openrewrite/java/dataflow/analysis/FlowGraph.java
- rewrite-java/src/main/java/org/openrewrite/java/dataflow/analysis/ForwardFlow.java
Supports cases like `StringBuilder` where methods like `append` taint the `StringBuilder` via the MethodInvocation subject
> DataFlow: Support for data/taint flow from arguments to subject

- rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java
- rewrite-core/src/test/java/org/openrewrite/marker/GitProvenanceTest.java
In GitHub, you can fetch repositories with a particular "depth". This creates a .config file with the Git metadata required to publish repositories.
Specially, this is useful for cases where the repository that is fetched is not the same than the one that runs GitHub Actions.
> Support for git fecth with depth > 0 from BuildEnv

- rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
The logic in `Substitutions#substitute()` fails for `J.NewClass` instantiating new anonymous classes because an anonymous class like `A$1` is replaced with `A.1` which isn't a legal class name.
> Fix substitution for anonymous class

- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceRedundantFormatWithPrintfTest.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
The type attribution of `#{any()}` template parameters (i.e. without any type attribution on the parameter) now also includes any generic type arguments that the corresponding argument may have.
> Properly type-attribute `#{any()}` template parameters

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceStringBuilderWithStringTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceStringBuilderWithString.java
fixes #2930
Add handling for two `StringBuilder` constructors with String as a parameter and ignore the capacity one.
> fix: fix a bug when replacing StringBuilder to strings if the constructor has parameters

- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateInstanceOfTest.java
- rewrite-java/build.gradle.kts
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/PatternVariables.java
- rewrite-java/src/test/java/org/openrewrite/java/internal/template/PatternVariablesTest.java
Using `instanceof` pattern matching an `if` statement can declare local variables which can be dereferenced in the condition itself, in the `then` block, the `else` block, or also in successor statements to the `if` statement. Therefore, it is important that `JavaTemplate` keeps these `instanceof` pattern matching expressions when generating the stub to extract the type attributed substitution of a template.
For any `if` statements which contain `instanceof` pattern variables the `if` statement is added in a reduced form to the stub. The flow scoping rules of the pattern variables require the then and else blocks to retain the same "completes normally" characteristics as in the original code, as this influences the scope of the pattern variable.
Additionally this PR fixes a few other …
> Support `instanceof` pattern variables in `JavaTemplate`

- .github/workflows/ci.yml
This will help detect any API breaking changes that the
`rewrite` tests don't cover but `rewrite-java-security` catches.
Example: https://github.com/openrewrite/rewrite-java-security/issues/83
> Run `rewrite-java-security` with core changes immediately

- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
- rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
`JavaTemplate` offers a new `matches(J)` method which can be used to check if the given tree matches the receiving `JavaTemplate`. This uses `SemanticallyEqual#matchesTemplate()` and will check if the tree at the cursor is identical to the tree represented by the template.
The template can also contain `#{any(...)}` parameters, which require the input subtree to contain a typed subtree at the given location with a type compatible to the type of the template parameter.
> Allow matching an LST subtree against a `JavaTemplate`

- rewrite-java/src/main/java/org/openrewrite/java/template/Primitive.java
- rewrite-java/src/main/java/org/openrewrite/java/template/package-info.java
When using `JavaTemplate#compile()` to build a template based on a Java lambda, there needs to be a way to create templates which refer to primitive template parameters.
Since the SAM types (`F0` through `F10`) don't allow for this, instead add an `@Primitive` annotation type with source retention. Any parameter annotated with this on the lambda will in the generated template string use the corresponding primitive type instead (e.g. `#{any(int)}`).
> Add a new `@Primitive` annotation for `JavaTemplate#compile()`

- rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
- rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java
fixes #2919
The issue here is if there are any nested single-source applicability tests. 
the outer single-source applicability test result could be overridden by an inner single-source applicability test result, so some files supposed to be skipped are made unexpected changes.
> fix: a bug of nested single source applicability tests

- rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/G.java
- rewrite-groovy/src/test/java/org/openrewrite/java/cleanup/ChangeTypeTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
- rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
- rewrite-java/src/main/java/org/openrewrite/java/RemoveImport.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaSourceFile.java
Changes:
- ChangeType will operate on java island grammars like `G` and `K`.
TODO:
- ~~Revise ChangeType#visitCompilationUnit so that it does not handle imports.~~
- ~~Change imports in postVisit (equivalent to super.visitCompilationUnit).~~
- ~~Update ChangeClassDefinition to work across other J implementations.~~
- ~~Update `RemoveImport` / `AddImport` to work across `J` island grammars.~~
- Issue: `visitCompilationUnit` will not be executed on other languages like `G` or `K.`
- `SourceFile` does not have access to `typesInUse.`
- `visitJavaSourceFile` is used to delegate to the language-specific `visitCompilationUnit.` So, overriding the method in place of `visitCompilationUnit` causes the `K` or `G` visitCompilationUnit not to be visited.
- ~~Implement `withImports` and `withClasses` …
> Updated ChangeType to change types in java island grammars.

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceTextBlockWithStringTest.java
- rewrite-java/src/main/java/org/openrewrite/java/Assertions.java
- rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java
- rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
- rewrite-test/src/main/java/org/openrewrite/test/SourceSpec.java
The `Assertions.javaVersion(int)` method is now public. Using this a `RewriteTest`-based test can now use `RecipeSpec.allSources()` to configure a default Java version for the sources:
```java
@Override
public void defaults(RecipeSpec spec) {
spec.recipe(new ReplaceTextBlockWithString()).allSources(s -> s.markers(javaVersion(14)));
}
```
> Allow tests to configure default Java version for sources

- rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
- rewrite-core/src/test/java/org/openrewrite/table/SourcesFileResultsTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/DataTableTest.java
- rewrite-test/src/main/java/org/openrewrite/test/RecipeSchedulerCheckingExpectedCycles.java
This is an alternate solution to PR #2981 (has been reverted), but removed `Recipe#isApplicableTest()` method since any recipe can potentially be an applicability test and a recipe can know about itself, especially for yaml recipes, the applicability test are recipes but not wrapping of visitors, so that PR doesn't cover yaml recipes.
------------------------------------------------------------
Currently, the results data table `SourcesFileResults` has two problems:
1. Include results for only one file and missed others.
2. Include tons of `AdHocRecipe` which is an applicability test recipe, regardless of whether the recipe modifies the file or not.
This PR is intended to fix the above two problems.
Here is an example, run `CommonStaticAnalysis` against one repo, and got this result …
> fix results data table

- rewrite-maven/src/main/java/org/openrewrite/maven/ChangePropertyKey.java
- rewrite-maven/src/test/java/org/openrewrite/maven/ChangePropertyKeyTest.java
- rewrite-xml/src/main/java/org/openrewrite/xml/ChangeTagNameVisitor.java
Enhancement to change a maven property key name.
Currently, OpenRewrite only support changing a maven property value, not a key.
> Maven ChangePropertyKey

- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceDuplicateStringLiterals.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
Simplifies the logic in `BlockStatementTemplateGenerator` for the generation of nested types, which had a problem with nested enums.
> Fix templating in presence of nested enums

- rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
- rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
As of Maven 3.5.0 version ranges are also supported in the parent reference (see https://issues.apache.org/jira/browse/MNG-2199 for details).
Fixes: openrewrite/rewrite-maven-plugin#530
> Support version ranges in parent reference

- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserInputFileObject.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserInputFileObject.java
- rewrite-java-8/src/main/java/org/openrewrite/java/Java8ParserInputFileObject.java
Change `*ParserInputFileObject` classes to use `Path.getFileName()` instead of `Path.toUri().getPath()`.
The `*ParserInputFileObject` classes use `Path.toUri().getPath()` to check the last element of a path. This is both awkward and not guaranteed to work on non-default file systems. [Path#toUri](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/Path.html#toUri()) makes no guarantees about the return value of `URI#getPath()` of the returned object. This breaks on the JAR file system and others. `Path.getFileName()` is a better option.
See also https://github.com/marschall/memoryfilesystem/issues/141
> Do not rely on Path.toUri().getPath()

- rewrite-core/src/main/java/org/openrewrite/Recipe.java
If a recipe is added to the list invalidate cached recipe descriptor. Test is here: https://github.com/openrewrite/rewrite-spring/pull/322
> Invalidate cached recipe descriptor

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizeLocalVariablesTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizeLocalVariables.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
For example in context switch-cases the scope is the whole switch statement even when a variable is declared in separate case branch. Before, we only took the parent scope into account which is solely the individual case branch.
Fixes #2953
> Execute lookup for declaring scope instead of parent scope

- rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java
- rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
Currently, If a file contains tab characters only (not any white space), the AutoDetect will detect tab size as 1.
which doesn't look correct, it should be the default 4.
This PR introduces a new way to calculate tab size and the `useTab` flag.
Here is the solution:
```
/**
* For each line, if the code follows an indentation style exactly,
* Assume :
*      nw = white space count in prefix
*      nt = tabs count in prefix
*      d = block depth
*      X = tabSize, which means  white space count per tab, unknown to be solved here.
* So theoretically the formula is:
*      d = nt + (nw / X)                                                                       (1)
*      X = nw / (d - nt)                                                                       (2)
* Because this is a linear …
```
> Fix `tabsize` inaccurate issue

- rewrite-core/build.gradle.kts
- rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java
This Glob matching utility was using Ant's `SelectorUtils#match()` method, which uses `String#toCharArray()`. Often it is however faster to work with `String#charAt()`. Performance measurements indicate that the implementation is now more than twice as fast and since it is used very intensively in `rewrite-maven` (to match GAVs), the boost will be visible in some recipes.
> Optimize `StringUtils#matchesGlob()`

- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDelegatesToGradleApi.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateSubstitutionsTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest3Test.java
- rewrite-java-test/src/test/java/org/openrewrite/java/recipes/UseJavaParserBuilderInJavaTemplateTest.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeStaticFieldToMethod.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReference.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
- rewrite-java/src/main/java/org/openrewrite/java/recipes/UseJavaParserBuilderInJavaTemplate.java
@knutwannheden this makes way for you to place your `JavaTypeCache` instance on the template's parser without having to add a setter to `JavaParser`.
The reason that this was initially `Supplier<JavaParser>` rather than `JavaParser.Builder` is we didn't have a `clone()` method on `JavaParser`.
> Use `JavaParser.Builder` when constructing `JavaTemplate`

- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaTemplateSemanticallyEqual.java
In order for a visitor to be able to extract the subtrees matched by the placeholders in the `JavaTemplate` pattern, there is now a new `JavaTemplate.Matcher` class along with a new `JavaTemplate#matcher()` method.
Using this `Matcher` the client code can call `find()` and subsequently `parameter(int)` to extract the matched parameters.
> Add `JavaTemplate.Matcher`

- rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
- rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java
This is just a start. More changes would be required to ensure that `singleSourceApplicableTest` visitors also shared that same cursor root, but not sure these changes are worthwhile at this point.
cc / @knutwannheden
> Shared cursor root on all `TreeVisitor` returned by `Recipe#getVisitor`

- rewrite-core/src/main/java/org/openrewrite/Recipe.java
- rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
- rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
- rewrite-core/src/main/java/org/openrewrite/config/Environment.java
- rewrite-core/src/main/java/org/openrewrite/config/RecipeDescriptor.java
- rewrite-core/src/main/java/org/openrewrite/config/RecipeExample.java
- rewrite-core/src/main/java/org/openrewrite/config/ResourceLoader.java
- rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
- rewrite-core/src/test/java/org/openrewrite/config/CategoryTreeTest.java
- rewrite-core/src/test/java/org/openrewrite/config/YamlResourceLoaderTest.java
Add recipe examples to recipe and recipe descriptors the same way as recipe contributors.
These recipe examples will be used to display on documents and saas.
This is the rewrite part change, and further work is needed to generate example yaml files in the building phase.
> Add recipe examples to recipe and recipe descriptors

- rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java
- rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
Add considering the largest frequency group to calculate tabSize to improve the confidence of tabSize calculation.
Before this PR, we use a way based on statistical means to calculate tab size.
This PR introduced a way to calculate the `tabSize` based on the biggest group, which has the benefit of being less susceptible to outliers.
> Add considering largest frequency group to calculate tabSize

- rewrite-core/src/main/java/org/openrewrite/semver/Semver.java
- rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
- rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
- rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
When an existing Maven dependency has a version which is non-semver-friendly (like `org.springframework.cloud:spring-cloud-dependencies:Camden.SR5`), the `UpgradeDependencyVersion` and `ChangeParentPom` recipes should be able to do the upgrade anyway.
Introduces a new `Semver#isVersion(String)` utility to check if a given version string is a valid semver version.
> Allow upgrading non-semver Maven dependencies

- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
- rewrite-java-test/src/test/java/org/openrewrite/java/format/BlankLinesTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/format/TabsAndIndentsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/BlankLinesVisitor.java
The problem here was basically that the `JavaVisitor` visited the annotations after the constant name.
Fixes: #3089
> Correctly format annotated enum constants

- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
- rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlow.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
This PR attempts to fix the issue https://github.com/openrewrite/rewrite/issues/3102
I think the issue was introduced by [this commit](https://github.com/openrewrite/rewrite/commit/626d8c645bb7b6b9d81e69a7985759701eb9b133#r108541429), 
This PR just patched against that specified problem, it can fix the template problem, but it's a patch fix. I don't know whether it's a correct change.  I think the issue needs @knutwannheden 's help to also take a look.
> Try to fix a template issue on `cucumber-jvm-migration`

- rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/Assertions.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java
- rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/OrderImportsTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/MethodNameCasingTest.java
- rewrite-java/src/main/java/org/openrewrite/java/Assertions.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
- rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
- rewrite-test/src/main/java/org/openrewrite/test/SourceSpec.java
The purpose of this chunk of work is to fully align the way that `SourceSet` handling is performed. Presently, there are many ways that `SourceSet` instances are being handled. Below is a list of the places where this is occurring:
* `Java*Parser` implementations
* `KotlinParser` implementation
* Gradle build plugin
* Maven build plugin
Additionally, in the `GroovyParser` there is no `SourceSet` handling.
This change is important, so that we can properly add `SourceSet` markers when they are truly necessary and leave them missing when they should not be present. The _only_ place where this determination can be performed presently is by the build plugins themselves. A few examples of places where a `SourceSet` marker should *NOT* be present are:
* Gradle Groovy DSL (`*.gradle`)
* Gradle …
> Remove automatic source set addition to compilation units

- rewrite-xml/src/main/java/org/openrewrite/xml/ChangeTagValue.java
The desired endpoint is to be able to change the value of a specific XML tag, defined by an XPath elementName parameter, and optional oldValue and fileMatcher parameters
> New recipe to utilise ChangeTagValueVisitor capabilities for general XML files

- rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java
- rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
This PR is to make `XPathMatcher ` support conditional tag match format well for this kind of (https://github.com/moderneinc/moderne-cli/blob/b765762b8a2cb83f739402b895066fe843d07626/src/main/java/io/moderne/cli/detect/java/FromPomXml.java#L49-L58),
like this
```java
"/project/build/plugins/plugin[artifactId='maven-compiler-plugin']/configuration/source"
```
And this feature will be used to upgrade the java version in maven pom which could be done in several different ways.
```java
private static final List<String> JAVA_VERSION_XPATHS = Arrays.asList(
"/project/properties/java.version",
"/project/properties/jdk.version",
"/project/properties/javaVersion",
"/project/properties/jdkVersion",
"/project/properties/maven.compiler.source",
"/project/properties/maven.compiler.target", …
```
> update `XPathMatcher` to support conditional tag match

- rewrite-core/src/main/java/org/openrewrite/config/RecipeExample.java
- rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
- rewrite-core/src/main/java/org/openrewrite/internal/DocumentExample.java
- rewrite-java-test/src/test/java/org/openrewrite/java/ExamplesExtractorTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ChainStringBuilderAppendCallsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/ExamplesExtractor.java
This PR creates a visitor to extract examples from a rewrite recipe unit test.
This will be used to support the recipe example feature.
The yaml files will be generated by `build-gradle-plugin`, got merged, and output recipe descriptor finally with recipe examples included.
> Introduce a visitor to extract examples from a rewrite recipe unit test.

- rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
Specifically for `java.lang.NoClassDefFoundError`
> ClasspathScanningLoader should catch Throwable not Exception to catch Error

- rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
The purpose here is to setup similar capabilities to that of the `UpgradeJavaVersion` migrations. Other recipes need to know what version of Gradle the project is on or has moved to.
> Update BuildTool marker with wrapper version changes

- rewrite-maven/src/main/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtension.java
- rewrite-maven/src/test/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtensionTest.java
closes https://github.com/openrewrite/rewrite/issues/3005
To implement the required recipe [here](https://github.com/openrewrite/rewrite/issues/3005) 
To integrate Gradle Enterprise Maven Extension into Maven projects, ensure that the `gradle-enterprise-maven-extension` is added to the `.mvn/extensions.xml` file if not already present. 
Additionally, configure the extension by adding the `.mvn/gradle-enterprise.xml` configuration file.
> Add recipe to add gradle enterprise maven extension to maven projects

- rewrite-java-test/src/test/java/org/openrewrite/java/RemoveAnnotationTest.java
Added some tests to cover case where annotations are used with fully qualified names (as opposed to import+simple name), both for "default" java.lang annotation and custom one.
> Add tests to cover additional cases: fully qualified names

- rewrite-core/src/main/java/org/openrewrite/internal/ExceptionUtils.java
- rewrite-core/src/main/java/org/openrewrite/marker/Markup.java
- rewrite-java-test/src/test/java/org/openrewrite/java/RecipeMarkupDemonstrationTest.java
This error appears when we build the rewrite repository with the Moderne CLI
```
Caused by: java.lang.RuntimeException: java.io.UncheckedIOException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Direct self-reference leading to cycle (through reference chain: java.util.ArrayList[272]->org.openrewrite.text.PlainText["markers"]->org.openrewrite.marker.Markers["markers"]->java.util.ArrayList[5]->org.openrewrite.marker.Markup$Warn["exception"]->java.lang.RuntimeException["cause"]->org.gradle.api.artifacts.ResolveException["cause"])
at io.moderne.gradle.DelegatingSerializingProjectParser.unwrapInvocationException(DelegatingSerializingProjectParser.java:172)
at io.moderne.gradle.DelegatingSerializingProjectParser.writeAstFile(DelegatingSerializingProjectParser.java:64)
at …
```
> Fixes circular references serializing markers

- rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
I've spent a bit too much time looking for whitespace changes on long before/after blocks. This ought to help, even if it's crude. Figured get feedback on if we want something like this first, and see from there how best to phrase this in the message.
> Show diff on RewriteTest comparison failures

- rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyArtifactId.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyGroupId.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyArtifactIdTest.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyGroupIdTest.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
This is a reproducer for #3227 Gradle change dependency groupId/artifactId ignores platform dependencies
It does not fix the issue.
@sambsnyd Tim said I should tag you as you might be working in this corner and might want to be aware of it.
> Reproducer for #3227 Gradle change dependency ignores platform

- rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
For https://github.com/openrewrite/rewrite/issues/3170
> Support 21-ea as value for java.version in JavaParser

- rewrite-maven/src/main/java/org/openrewrite/maven/RenamePropertyKey.java
- rewrite-maven/src/test/java/org/openrewrite/maven/RenamePropertyKeyTest.java
Without this PR (INCORRECT):
With this PR (CORRECT):
> Fixes #3144 RenamePropertyKey and ChangePropertyValue running together

- rewrite-maven/src/main/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtension.java
- rewrite-maven/src/test/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtensionTest.java
Follow up on https://github.com/openrewrite/rewrite/pull/3193#discussion_r1184183668
This PR adds some optional settings:
- `captureGoalInputFiles`
- `uploadInBackground`
- `publishCriteria`
An optional setting not set will not result in a xml element in the `gradle-enterprise.xml` configuration, this is implemented by using Jackson xml instead of plain string formatting.
> Add options to the Add Gradle Enterprise Maven recipe

- rewrite-java-test/src/test/java/org/openrewrite/java/AddLicenseHeaderTest.java
Related to https://github.com/openrewrite/rewrite/issues/3198
In this case invalid Javadoc gets changed in an unexpected way. I would expect OpenRewrite to either leave such JavaDoc unmodified or to bail out with a failure (like it would on regular Java code I suppose).
> Invalid Javadoc should remain unchanged

- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
Fixes #3222
Sets package to "" for classes in default package, not identical to class name.
> Support default package in `JavaParser.Builder.classpath(byte[][])`

- rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java
- rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
An enhancement of `AddOrUpdateAnnotationAttribute` recipe to support removing an attribute if set the value to `null`.
We probably need this feature as an request from the community [here](https://rewriteoss.slack.com/archives/C01A843MWG5/p1684343793424379)
> enhancement of AddOrUpdateAnnotationAttribute to support remove an attribute

- rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
- rewrite-core/src/main/java/org/openrewrite/text/AppendToTextFile.java
- rewrite-core/src/test/java/org/openrewrite/config/YamlResourceLoaderTest.java
- rewrite-core/src/test/java/org/openrewrite/text/AppendToTextFileTest.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddGradleEnterprise.java
To support case-insensitive enum deserialization  In `YamlResourceLoader`
Just 1 line of code change by config the JsonMapper
Slack discussion [here](https://moderneinc.slack.com/archives/C02JYCSNM4G/p1684507999745499)
> Support case-insensitive enum deserialization  In `YamlResourceLoader`

- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/Assertions.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
- rewrite-java/src/main/java/org/openrewrite/java/Assertions.java
We are using the Nebula test facets plugin (https://github.com/nebula-plugins/nebula-project-plugin#test-facets) to create `smokeTest` source set, if a class is only used in `smokeTest`, we'd like to add that as `smokeTestImplementation` dependency instead of `implementation` or `testImplementation` dependency. 
Currently, the openrewrite logic only handles `implementation` and `testImplementation` dependencies. If `onlyIfUsing` matches code in `smokeTest` source set, it would add that as `implementation`. 
With this change, it adds an additional optional config `testSourceSet`. If that's not specified, it will keep the existing behavior (any source sets other than `test` will add as `implementation` dependency). If that's specified, `main` source set will be `implementation`, and other …
> Support using different configurations for different test source sets when adding gradle dependency

- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
An instanceof check for JavaSourceFile is added to AddDependency.java.
Without this type check, the invocation of `UsesType` in `AddDependency`'s scanning visitor fails when encountering non-Java files such as a properties file.
> Fix for type cast error in Gradle AddDependency recipe.

- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
- rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyTypeSignatureBuilderTest.java
> Reduce GroovyParser memory retention

- rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
`Enviroment#listRecipes()` has empty `recipesList` fields starting from the second level. Recipes are there but not initialized.
> Recursively init Declarative Recipes

- rewrite-java/src/main/resources/META-INF/rewrite/migrate-rewrite.yml
The package of referenced recipes in `MigrateToRewrite8`.
I tried to run the `MigrateToRewrite8` recipe introduced in #3241, but saw these messages:
```
> Task :rewriteDryRun
Validating active recipes
Recipe validation error in org.openrewrite.java.upgrade.MigrateToRewrite8.recipeList[0] (in jar:file:/home/sghill/.gradle/caches/modules-2/files-2.1/org.openrewrite/rewrite-java/8.0.0/5846c136ff8dc89b163dbff7445633bd6bb4c9c2/rewrite-java-8.0.0.jar!/META-INF/rewrite/migrate-rewrite.yml): 
recipe 'org.openrewrite.java.upgrade.MigrateRecipeToRewrite8' does not exist.
Recipe validation error in org.openrewrite.java.upgrade.MigrateToRewrite8.recipeList[1] (in jar:file:/home/sghill/.gradle/caches/modules-2/files-2.1/org.openrewrite/rewrite-java/8.0.0/5846c136ff8dc89b163dbff7445633bd6bb4c9c2/rewrite …
```
> Update MigrateToRewrite8 referenced recipes

- rewrite-maven/src/main/java/org/openrewrite/maven/utilities/PrintMavenAsCycloneDxBom.java
- rewrite-maven/src/test/java/org/openrewrite/maven/utilities/PrintMavenAsCycloneDxBomTest.java
The packaging mentioned in the pURL qualifier was assumed to be a `jar`. The changes fix that. I produce a test that takes a pom for a maven project whose packaging is `pom`.
Fixes https://github.com/openrewrite/rewrite-maven-plugin/issues/579
@timtebeek
> fix: fetch correct maven packaging for purl qualifier

- rewrite-benchmarks/src/jmh/java/org/openrewrite/benchmarks/maven/MavenParserBenchmark.java
- rewrite-core/src/main/java/org/openrewrite/FindParseFailures.java
- rewrite-core/src/main/java/org/openrewrite/ParseExceptionResult.java
- rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java
- rewrite-core/src/main/java/org/openrewrite/table/ParseFailures.java
- rewrite-core/src/main/java/org/openrewrite/text/ChangeText.java
- rewrite-core/src/main/java/org/openrewrite/text/CreateTextFile.java
- rewrite-core/src/main/java/org/openrewrite/text/PlainText.java
- rewrite-core/src/main/java/org/openrewrite/text/PlainTextVisitor.java
- rewrite-core/src/test/java/org/openrewrite/FindParseFailuresTest.java
- rewrite-core/src/test/java/org/openrewrite/PreconditionsTest.java
- rewrite-core/src/test/java/org/openrewrite/table/RecipeRunStatsTest.java
- rewrite-java/src/test/java/org/openrewrite/java/TreeAdaptabilityTest.java
Allows us to remove the duplicate effort in `rewrite-all` that was also causing a cyclic dependency between language modules and rewrite-all
> More data in FindParseFailures

- rewrite-protobuf/src/main/java/org/openrewrite/protobuf/ProtoParser.java
- rewrite-protobuf/src/test/java/org/openrewrite/protobuf/ProtoParserTest.java
The `Parser` API contract requires the implementation to return a stream of non-`null` `SourceFile` objects.
Since `proto3` sources are not really erroneous, just currently not supported by the parser, it doesn't really make sense to return a `ParseError` object, so instead the parser simply skips these sources.
> The `ProtoParser` must not return `null` values

- rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
- rewrite-java/src/main/java/org/openrewrite/java/SimpleMethodMatcher.java
- rewrite-java/src/main/java/org/openrewrite/java/search/DeclaresMethod.java
- rewrite-java/src/main/java/org/openrewrite/java/search/UsesAllMethods.java
- rewrite-java/src/main/java/org/openrewrite/java/search/UsesMethod.java
Extracts a majority of the logic of `MethodMatcher` into an interface `SimpleMethodMatcher`.
Simplifies the `SimpleMethodMatcher` into 3 basic predicates:
- `matchesTargetType`
- `matchesMethodName`
- `matchesParameterTypes`
A custom implementation of `SimpleMethodMatcher` can implement those predicates however they choose.
> Refactor `MethodMatcher` and extract Interface

- rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
Match a dynamic Spring version in `UpgradeDependencyVersionTest.upgradeAllDependenciesToPatchReleases`.
Fixes #3325
Updating the version number with each release, or switching to a no longer maintained dependency range.
> Match a dynamic Spring version

- rewrite-core/src/main/java/org/openrewrite/InMemoryExecutionContext.java
The optional parameter runTimeout was not being used at all after some changes on RecipeScheduler. It no longer makes sense for it to be a function that returns the timeout depending on the number of inputs, so I changed it to a fixed value and pushed the message into the context that later on is read by the RecipeScheduler to trigger a timeout.
To fix the ignored parameter of runTimeout
We could also call the current function with a default value, to get the timeout, this way we wouldn't introduce any breaking change.
> Fixing runTimeout being ignored

- rewrite-java/src/main/java/org/openrewrite/java/JavaTypeMethodMatcher.java
- rewrite-java/src/main/java/org/openrewrite/java/search/DeclaresMethod.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindMethods.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindMethodsVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/search/UsesAllMethods.java
- rewrite-java/src/main/java/org/openrewrite/java/search/UsesMethod.java
Also adds a new incubating `JavaTypeMethodMatcher` interface that can be seen as `MethodMatcher` "light". A significantly smaller interface that consumers can rely upon over depending upon the entire `MethodMatcher` API. Thus decoupling the visitors away from the implementation details of how methods are actually matched against, and leaving them with the sole responsibility of performing the appropriate actions when matching occurs.
> Add `FindMethodsVisitor` and refactor `FindMethods`

- rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/JavaReflectionTypeMapping.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
When Jackson deserializes an array into a `List` it by default creates an `ArrayList` with the default capacity (10) and populates it with the values. For `JavaType.Method` that is typically quite wasteful, since it uses lists for parameter names, parameter types, thrown exceptions, and annotations and these lists are very often shorter.
One alternative is to register a custom `ValueInstantiator` for `ArrayList` which creates lists with a smaller capacity (e.g. 4 or even just 1).
Another alternative, as done in this commit, is to change the internal representation to use arrays and create a corresponding `@JsonCreator` annotated constructor.
> Reduce memory overhead of `JavaType` implementations

- rewrite-hcl/src/main/java/org/openrewrite/hcl/tree/Space.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
- rewrite-json/src/main/java/org/openrewrite/json/tree/Space.java
- rewrite-protobuf/src/main/java/org/openrewrite/protobuf/tree/Space.java
- tools/language-parser-builder/src/main/java/org/openrewrite/toml/tree/Space.java
The `Space#flyweights` implementations all had a memory leak due to the way the `WeakHashMap` was being used: The values all had a hard reference to the key. As a result these entries can never get collected. Additionally, there was no length limitation on the whitespace, so very long spaces could end up in the flyweights table with a very low probability of ever getting reused.
> Fix memory leak in `Space#flyweights` implementations

- rewrite-core/src/main/java/org/openrewrite/Tree.java
Since we no longer referentially deduplicate subtrees, this identity info only represents a cost.
> No JsonIdentityInfo on Tree

- rewrite-java-test/src/test/java/org/openrewrite/java/FindMissingTypesTest.java
- rewrite-java/src/main/java/org/openrewrite/java/Assertions.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java
The `FindMissingTypes` doesn't quite detect all missing types. This is an attempt at cleaning some of these cases up.
> More accurate type checking

- rewrite-core/src/main/java/org/openrewrite/semver/LatestRelease.java
Using `Scanner` has the downsides of using regexp and also allocating a 1KiB `HeapCharBuffer` every time.
> Optimize `LatestVersion#countVersionParts()`

- rewrite-core/src/main/java/org/openrewrite/Tree.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
During deserialization the `@c` property appears to be treated as an unknown property, which adds some extra overhead.
> Annotate `Tree` and `JavaType` with `@JsonIgnoreProperties`

- rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyTypeMapping.java
- rewrite-java/src/main/java/org/openrewrite/java/UnsafeJavaTypeVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
This allows to cut down on the allocations of lists and arrays, as the internal representation is now array-based.
> Add array-based `unsafeSet()` methods to `JavaType` implementations

- rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Extracts `MethodMatcher#matchesTargetType` into `TypeUtils#isOfTypeWithName`.
This makes is easier for external actors to implement custom `MethodMatcher`
implementations without copying and pasting logic out of `MethodMatcher`.
You can see that, currently, the entire contents of `MethodMatcher#matchesTargetType` is currently copy-pasted here:
https://github.com/openrewrite/rewrite-analysis/blob/5956c0868de11bff8d892b4203ea02b3d2c08905/src/main/java/org/openrewrite/analysis/BasicJavaTypeMethodMatcher.java#L43-L74
- Is the name of the method `isOfTypeWithName` fine?
- Should `isOfTypeWithName` be a static method on `TypeUtils` or on `MethodMatcher`?
- Is the `@Incubating` annotation on the new method `isOfTypeWithName` specifying the correct version?
Continuing to operate with copy-pasted …
> Refactor `MethodMatcher#matchesTargetType`

- rewrite-core/src/main/java/org/openrewrite/Recipe.java
- rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
- rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Make it the responsibility of whatever is going to run the recipe, not RecipeScheduler
> My proposal for ensuring recipe validation happens exactly once per run

- .gitattributes
- rewrite-core/src/main/java/org/openrewrite/Checksum.java
- rewrite-core/src/main/java/org/openrewrite/remote/Remote.java
- rewrite-core/src/main/java/org/openrewrite/remote/RemoteArchive.java
- rewrite-core/src/main/java/org/openrewrite/remote/RemoteFile.java
- rewrite-maven/build.gradle.kts
- rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenWrapper.java
- rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenWrapper.java
- rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenWrapperTest.java
- rewrite-maven/src/test/resources/mvnw
- rewrite-maven/src/test/resources/mvnw.cmd
Fixes gh-1565 and gh-2996
Adding an `UpdateMavenWrapper` to help manage Maven Wrapper upgrades much like the `UpdateGradleWrapper` equivalent.
One aspect of the implementation that I'm less than happy with is that Apache doesn't provide pre-generated SHA-256 checksums in their Maven Central repository. This thus required streaming the wrapper jar and full maven distribution down to gain access to that SHA-256 checksum. 
With Maven 3.9.3, they do publish a CycloneDX SBOM which also contains the required SHA-256 checksum, but that is the only release version available with such a mechanism. Thus, I opted to calculate the checksum on the fly for now. If the ASF at some point in the future reliably provides a SHA-256 in a consumable fashion, then it would be apt for us to adopt that directly …
> Add `UpdateMavenWrapper` recipe including checksum verification

- rewrite-json/src/main/java/org/openrewrite/json/JsonPathMatcher.java
- rewrite-json/src/test/java/org/openrewrite/json/JsonPathMatcherTest.java
- rewrite-json/src/test/java/org/openrewrite/json/search/FindKeyTest.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/JsonPathMatcherTest.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/search/FindKeyTest.java
JsonPathMatcher will only return the items in a list that fully patch a sequence of binary expressions.
Issue reported by design partner.
fixes #3401
> Only return the fully matched items from a sequence of binary expressions in JsonPathMatcher.

- rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
Small change; including a blank `String` in the `imports` when building a `JavaTemplate` now throws an exception, instead of silently ignoring the blank entry.
I think failing fast here is more helpful and matches the spirit of a non-null API
> JavaTemplate.Builder.imports - throw on blank import

- rewrite-core/src/main/java/org/openrewrite/FindParseFailures.java
- rewrite-core/src/test/java/org/openrewrite/FindParseFailuresTest.java
Changes:
- Added optional filters to `FindParseFailures`:
- `parserType` only marks sources with the specified parserType.
- `stackTrace` only marks sources with the specified stackTrace.
The changes will be used with data tables and notebooks to focus on fixing the most common parsing failures first.
> Added optional filters on find parse failures.

- rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
https://github.com/openrewrite/rewrite/issues/3275 pointed out an issue with incorrectly removing an import that was being used as a function parameter. This change updates the class path matching logic to check for either a `.` or a `$` class path separator. 
My motivation is to resolve https://github.com/openrewrite/rewrite/issues/3275 and make the RemoveUnusedImports recipe more reliable for wider adoption. 
I co-opted the predicate used in https://github.com/openrewrite/rewrite/pull/3363 to more generally match against class paths that have a `$` as a separator. 
Any maintainer 😄 
n/a
n/a
> Issue 3275/fix remove used param

- rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
Make it explicit the possibility to use `latest.release` and `latest.patch` as newVersion to upgrade to the latest available version or the latest patch version of the current version (only if already a valid semantic version).
Right now it's not clear for users how to get this behavior since it's not properly documented anywhere.
Maybe trying to find a better text to explain the functionality.
@mike-solomon
> Improved newVersion description

- rewrite-java/src/main/java/org/openrewrite/java/search/UsesMethod.java
If `UsesMethod` does not find any reference to the desired method in `TypesInUse` then it should return rather than traversing the entire LST in an attempt to find a match.
This change is being made for performance reasons, because this visitor is used very frequently as a precondition by recipes.
> `UsesMethod` should rely on `TypesInUse`

- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
Changes:
- Detect a null anchor to prevent an NPE in Yaml$Alias.
- Throws an exception to surface the parsing error as a ParserErrorResult.
> Prevent NPE and surface the cause as a ParserErrorResult in YamlParser.

- rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddGradleEnterpriseGradlePlugin.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddGradleEnterpriseGradlePluginTest.java
- rewrite-maven/src/main/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtension.java
Main change is renaming `AddGradleEnterprise` to `AddGradleEnterpriseGradlePlugin`. Others are just fixing param descriptions.
Have consistent labeling between the Gradle Enterprise related recipes.
I assume the documentation will be re-generated from those changes ?
> Polish Gradle Enterprise recipes names and descriptions

- rewrite-core/src/main/java/org/openrewrite/internal/RecipeIntrospectionUtils.java
When creating a Recipe instance String constructor arguments will be null
Recipes with required parameters with type String and that don't override validate method will be considered valid since those parameters would be initialized with an empty string. As a result, default implementation won't catch it.
I'd like to know whether there is a negative implication of this change.
@sambsnyd @jkschneider 
This change is part of the scope of the issue that allows run recipe without required parameters been passed on
> String fields are null by default.

- rewrite-core/src/main/java/org/openrewrite/marker/SearchResult.java
- rewrite-java-test/src/test/java/org/openrewrite/marker/SearchResultsTest.java
`SearchResult.mergingFound` has been fixed to only add the description if
the description isn't already present on a found `SearchResult`.
Externally having to guard against a `SearchResult` marker before calling
`mergingFound` is annoying, and, given the use of this method, often the behaviour
you would want anyways.
This is particularily true given that, by default, the recipe scheduler runs any recipe
twice. As such, any `mergingFound` call by default will be invoked twice.
In recipe tests, you can fix this by calling `expectedCyclesThatMakeChanges(1)`.
But that's a bit of a hack, and should be avoided.
> Fix SearchResults.mergingFound duplicating description

- rewrite-core/src/test/java/org/openrewrite/config/ChangeTextToSam.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/FormatPreservingReader.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Add a test to verify how a Unicode suffix is parsed in Yaml.
Fixes https://github.com/openrewrite/rewrite/issues/2062
> Account for Unicode characters in Yaml FormatPreservingReader

- rewrite-core/src/main/java/org/openrewrite/remote/RemoteVisitor.java
- rewrite-core/src/test/java/org/openrewrite/remote/RemoteVisitorTest.java
Visit markers on `Remote` file types.
Markers are visited in every other SourceFile type and I believe this should be standard. If not accepted, this could lead to a problem where a recipe author believes that `visitMarkers` should be called and isn't within a recipe.
N/A
@sambsnyd 
N/A
N/A
> Visit markers on RemoteVisitor

- rewrite-core/src/test/java/org/openrewrite/RecipeSchedulerTest.java
- rewrite-core/src/test/java/org/openrewrite/table/RecipeRunStatsTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/ExtractInterfaceTest.java
- rewrite-maven/src/test/java/org/openrewrite/maven/AssertionsTest.java
- rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Added checking if a recipe can be instantiated via RecipeIntrospectionUtils, because we are using it to get RecipeDescriptor, and if they fail because of null parameters it will make the recipe execution to fail in SaaS, CLI and build plugins.
Recent changes in #3404
> Checking RecipeIntrospectionUtils in rewrite-test

- rewrite-yaml/src/main/java/org/openrewrite/yaml/FormatPreservingReader.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Turn YAML files with unicode into ParseErrors
#3421 is proving difficult to resolve on short notice, and we'd rather have most of the project parsed rather than none of the project.
> Turn YAML files with unicode into ParseErrors

- rewrite-core/src/main/java/org/openrewrite/remote/LocalRemoteArtifactCache.java
- rewrite-core/src/test/java/org/openrewrite/remote/BlackHoleOutputStream.java
- rewrite-core/src/test/java/org/openrewrite/remote/RemoteArchiveTest.java
- rewrite-core/src/test/java/org/openrewrite/remote/RemoteFileTest.java
- rewrite-core/src/test/resources/gradle-wrapper.properties
Each remote download will get a unique UUID so there are no collisions with the downloads.  Added tests for RemoteArchive and RemoteFile
Currently when multiple threads are trying to download through the RemoteArchve or RemoteFile a `java.util.concurrent.ExecutionException` is thrown 
e.g. 
```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unable to load path [gradle-[^\/]+\/(?:.*\/)+gradle-(plugins|wrapper)-(?!shared).*\.jar, gradle-wrapper.jar] in zip file https://services.gradle.org/distributions/gradle-7.6.2-bin.zip
java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
Caused by java.lang.IllegalArgumentException: Unable to load path …
```
> fix: RemoteFile/RemoteArchive can now handle multiple threads trying to download the same file without error.

- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Restore constructors as they were before https://github.com/openrewrite/rewrite/commit/df5478b8592d90bba65923878b08ae0a412fdbc9 to aid migration of modules and allow gradual adoption.
Reported errors with deployed snapshots.
Can't imagine this would trip up serialization, but pointing it out just in case.
@sambsnyd 
Fix it everywhere, but since it's on the weekend and I'm about to head out this was easier.
https://github.com/openrewrite/rewrite/commit/df5478b8592d90bba65923878b08ae0a412fdbc9\
> Restore now deprecated constructors pending module migrations

- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
Prevent NPE on Space.getComments
Seen in CLI tests; not clear where the error originates, so perhaps easiest to not blow up here over it.
```
Running recipe in github.com/Netflix/conductor@main
org.openrewrite.internal.RecipeRunException: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.Space.getComments()" because "space" is null
at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:329)
at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:184)
at org.openrewrite.RecipeScheduler$RecipeRunCycle.lambda$editSources$3(RecipeScheduler.java:231)
at io.micrometer.core.instrument.AbstractTimer.recordCallable(AbstractTimer.java:147)
at org.openrewrite.table.RecipeRunStats.recordEdit(RecipeRunStats.java:56)
at org.openrewrite.RecipeScheduler$RecipeRunCycle.lambda$editSource …
```
> Prevent NPE on null Space of unknown origin

- rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependency.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyTest.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/ChangePluginTest.java
Added a new test to validate the behavior of ChangeDependency on unpinned dependencies.
Although we cannot check managed versions of Gradle right now, if the previous dependency is managed, we are going to assume that the new one will be managed too, and do not add a version tag. That was the previous behavior of the recipe before recent changes.
However, with the the new parameter `overrideManagedVersion` it will always add the tag version to the new dependency. 
This way we can force to add the newVersion, but we keep the default previous behavior. 
This recipe is also used in rewrite-java-dependencies and rewrite-spring, and it was not clear the behavior of the individual recipe.
> Added unpinned version test

- rewrite-core/src/main/java/org/openrewrite/marker/BuildTool.java
The build tool enumeration to support the Moderne CLI option, which is required for non Java repositories.
Being able to report the same markers from the Moderne CLI than from build tools
@joanvr 
@timtebeek
> Adding the Moderne CLI as a valid build tool

- rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
When running Maven on Linux from a system maintainer-installed package and adding a dependency to a recipe that is also a dependency of Maven itself (e.g. `slf4j-api`), then the system-installed version is used (e.g. `file:/usr/share/java/slf4j-api.jar`). Unfortunately, this path is not matched be the regular expression, since no version is added to the file name. This results in an incomprehensible error "Unable to find runtime dependencies beginning with: slf4j-api" that gives no clue what's wrong. Therefore, its better to also output the current class path being scanned.
In the situation described above, the following template cannot be built, because the dependency `slf4j-api` cannot be resolved because the artifact cannot be found on the class path:
```
private static JavaTemplate …
```
> Ensure that system-installed artifacts can be resolved while constructing JavaParser classpath

- rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddBuildPluginTest.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddGradleEnterpriseGradlePluginTest.java
When adding a new gradle plugin, we need to take into consideration the license header if we are creating a new plugins block as the first statement. For empty files with no statements and just the license header, the license header is in a comment at EOF.
AddGradleEnterpriseGradlePlugin recipe was producing unexpected results with license header duplicated or after the plugins block.
That's why I've added a test in this recipe too.
> Take license header into account when adding gradle plugin

- rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddGradleEnterpriseGradlePlugin.java
- rewrite-maven/src/main/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtension.java
Example and valid values for PublishCriteria on recipe AddGradleEnterpriseMavenExtension were wrong, thus causing the SaaS to display them all in lowercase and then failing to assign the proper value on recipe execution. Also improved this in the description and on the other related recipe AddGradleEnterpriseGradlePlugin.java
On the SaaS, the enum values of PublishCriteria were wrongly displayed, and the recipe execution failed when a value was choosen.
We could also improve the ObjectMapper on the SaaS to accept case insensitive enums, but anyway, I think that this fix here is also good to have.
> fixed valid values and docs for Gradle Enterprise recipes

- rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
- rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
AddImport does not respect new line styling when adding new imports. It is related to `ImportLayoutStyle::addImport` works, because it can override whatever prefix we add to the new import.
Maybe we should fix addImport and instead of always adding \n to consider CRLF based on a parameter? 
Also changed some ListUtils.map to ListUtils.mapFirst equivalent when only changing the first element, and withPrefix(getPrefix().withComments) for withComments directly in import. Probably those "helpers" weren't available at the time of building this recipe.
I thought about adding an extra parameter to addImport (or to ImportLayoutStyle builder?) so it adds \n or \r\n according to the provided preference. But this may require adding a "default" value with the same signature to not affect the public …
> Fix CRLF newlines in AddImport

- rewrite-core/src/main/java/org/openrewrite/ExecutionContext.java
- rewrite-core/src/main/java/org/openrewrite/Parser.java
- rewrite-core/src/main/java/org/openrewrite/SourceFile.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/search/DependencyInsight.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
- rewrite-hcl/src/main/java/org/openrewrite/hcl/HclParser.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
- rewrite-json/src/main/java/org/openrewrite/json/JsonParser.java
- rewrite-maven/src/main/java/org/openrewrite/maven/table/DependencyGraph.java
- rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java
- rewrite-protobuf/src/main/java/org/openrewrite/protobuf/ProtoParser.java
- rewrite-xml/src/main/java/org/openrewrite/xml/XmlParser.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/AppendToSequenceTest.java
Parsers should prove that their printed representation matches the original source code to prevent patch apply failures on commit. The lack of parse-to-print idempotence can otherwise go unnoticed until a commit.
> Require parse-to-print idempotence

- rewrite-java-test/src/test/java/org/openrewrite/java/ShortenFullyQualifiedTypeReferencesTest.java
- rewrite-java/src/main/java/org/openrewrite/java/ExtractInterface.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/recipes/MigrateRecipeToRewrite8.java
- rewrite-java/src/main/java/org/openrewrite/java/service/ImportService.java
- rewrite-java/src/main/java/org/openrewrite/java/service/package-info.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaSourceFile.java
Let `JavaSourceFile` act as a service registry, so that other JVM languages (like Kotlin or Groovy) can override some central "services" which require a different implementation than the standard Java implementation.
An example is imports: Kotlin doesn't really have static imports, it has more implicitly imported types, and also the concept of aliases. With the indirection via an `ImportService` (which Kotlin can extend), the existing Java recipes can continue using `JavaVisitor#maybeAddImport()` and will end up using the Kotlin-specific implementation when visiting Kotlin sources.
The `ImportService` can also be extended to provide a visitor to remove imports (`RemoveImport`) and other import-related operations, if required.
> Add `JavaSourceFile#service(Class)` and `ImportService`

- rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
- rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/service/ImportService.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
This canonical form accepts separate strings for the package name, type name (qualified in case of nested classes), and member. This way there is no confusion about what constitutes the package name or an owning class.
> Add `maybeAddImport(String, String, String, boolean)`

- rewrite-xml/src/main/java/org/openrewrite/xml/ChangeNamespaceValue.java
- rewrite-xml/src/test/java/org/openrewrite/xml/ChangeNamespaceValueTest.java
This pull request fixes the version matching issue in ChangeNamespaceValue
This changes was necessary to resolve failures in rewrite-liberty repo.
> Fix version matching issue in ChangeNamespaceValue and added test

- rewrite-yaml/src/main/java/org/openrewrite/yaml/FormatPreservingReader.java
Remove specific exception thrown when unicode is detected in Yaml in favor of generic catch when printed file is unequal.
Similar handling & reporting across parsers.
- https://github.com/openrewrite/rewrite/issues/2062
- https://github.com/openrewrite/rewrite/pull/3419
- https://github.com/openrewrite/rewrite/pull/3421
> Rely on parser to catch print inequality

- rewrite-java-test/src/test/java/org/openrewrite/java/search/FindMethodsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindMethods.java
- rewrite-java/src/main/java/org/openrewrite/java/table/MethodCalls.java
Add two columns to the data table produced by FindMethods
Particularly helps cases with wildcards, as `*..*Utils *(..)` does not always produce a data table row that can be traced back without context. Having the type and method name available, and split out from additional context, makes it easier to sort & filter on values as opposed to the usage line only.
Called out below.
Helps prioritize replacements applied at scale, as it's now somewhat annoying to pull from the usage columns only, which contains a mix of qualified and unqualified method calls, using different or even no select.
> Add columns for type and method to `MethodCalls` datatable produced by `FindMethods`

- rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
- rewrite-java/src/test/java/org/openrewrite/java/tree/SpaceTest.java
We found a maybe long-existing bug in the method `Space#format` that the suffix of the last comment could be wrong.
For example:
```java
class A
// comment
```
The last comment here should have an empty suffix, however, it has a `\n` suffix.
> Fix a bug of last comment suffix

- rewrite-java-test/src/test/java/org/openrewrite/java/ReorderMethodArgumentsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/ReorderMethodArguments.java
This recipe was not changing the method type, so even when changing the order of the arguments, it was matching again the next cycle and "reordering" the arguments again. If we update the methodType of the methodInvocation it's not needed to "hack" the tests forcing one cycle only, and thus we can check the idempotency of the recipe.
I was using this recipe in another recipe, and not getting the expected results, because the recipe was applied two times (one in each cycle).
@knutwannheden @timtebeek
> Changing method type in ReorderMethodArguments

- rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitor.java
Add `shouldSimplifyEqualsOn` to `SimplifyBooleanExpressionVisitor`, which a subclass in rewrite-static-analysis can override to accommodate Kotlin.
Such that we don't have to maintain two separate copies while we wait for rewrite-kotlin to merge into OpenRewrite/rewrite.
Do we need additional such calls for comparison to `null` in `maybeReplaceCompareWithNull`?
Method modeled after what we already have in
https://github.com/openrewrite/rewrite-static-analysis/blob/772c82062d277e3cab1a1006904817a84b484c8c/src/main/java/org/openrewrite/staticanalysis/SimplifyBooleanExpression.java#L200-L213
> Allow rewrite-static-analysis to reuse `SimplifyBooleanExpressionVisitor`

- rewrite-core/src/main/java/org/openrewrite/text/CreateTextFile.java
- rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
- rewrite-test/src/test/java/org/openrewrite/text/CreateTextFileTest.java
When `SourceSpec.noTrim = true` do not trim the actual output either, as this tripped up tests in #3491 .
- #3491 
- https://github.com/openrewrite/rewrite-jenkins/compare/main...bugfix/generate-codeowners-with-newline
> Do not trim actual either with no trim

- rewrite-maven/src/main/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtension.java
- rewrite-maven/src/test/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtensionTest.java
Changes to `AddGradleEnterpriseMavenExtension` recipe:
- fetch the latest Gradle Enterprise Maven extension version when the version attribute is not set.
- recipe display name is also changed to align with the `AddGradleEnterpriseGradlePlugin` recipe.
The `AddGradleEnterpriseMavenExtension` version attribute is optional but when not set it results in a extensions.xml with no version for the Gradle Enterprise extension, causing a subsequent build failure.
> Fix AddGradleEnterpriseMavenExtension optional version to get the latest

- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java
- rewrite-maven/src/test/java/org/openrewrite/maven/UpgradePluginVersionTest.java
Instead of using the parameter groupId and artifactId for the ChangePluginVersionVisitor, use the actual ones found in the tag. Otherwise, when using globs with wildcard characters, it just replaces all versions for every match everytime.
When trying the recipe with globs (that are supported by the underlying MavenVisitor), if we found multiple matches, all the matches get the same version (the last one applied).
A valid use case would be to update all plugins to it's latest versions. To accomplish that one could use this recipe with `groupId=*`, `artifactId=*`, `newVersion=latest.release`, but then it replaces all the versions of all plugins to the latest version of the last plugin found. 
@timtebeek 
In the test, to avoid breaking the change when a new version is released of any of the …
> Use tag groupId and artifactId to change version

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
- rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
First attempt at upgrading plugin dependency versions.
Maven plugins can have dependencies themselves, as the rewrite-maven-plugin does.
We want to support upgrading those dependencies too.
> Upgrade Maven plugin dependencies

- rewrite-hcl/src/main/java/org/openrewrite/hcl/tree/Space.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
- rewrite-json/src/main/java/org/openrewrite/json/tree/Space.java
- rewrite-protobuf/src/main/java/org/openrewrite/protobuf/tree/Space.java
- tools/language-parser-builder/src/main/java/org/openrewrite/toml/tree/Space.java
Using a `HashMap` (or `WeakHashMap`) concurrently can cause infinite loops.
At the same time also move the string allocation to the value provider for the `computeIfAbsent()` call to save some object allocations.
> Make `Space#flyweights` synchronized once again

- rewrite-java-test/src/test/java/org/openrewrite/java/ShortenFullyQualifiedTypeReferencesTest.java
- rewrite-java/src/main/java/org/openrewrite/java/ShortenFullyQualifiedTypeReferences.java
This method can be called to construct a visitor which is designed to be registered using `doAfterVisit()` and will modify the given subtree only.
> Add `ShortenFullyQualifiedTypeReferences#modifyOnly(J)`

- rewrite-java/src/main/java/org/openrewrite/java/internal/template/AbstractRefasterJavaVisitor.java
This is a base class used by Refaster-based recipes as generated by the `rewrite-templating` annotation processor. It contains some simple utility methods to simplify the generation of the recipes.
> Add `AbstractRefasterJavaVisitor`

- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
- rewrite-java-11/src/main/java/org/openrewrite/java/Java11Parser.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java
- rewrite-java-17/src/main/java/org/openrewrite/java/Java17Parser.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java
- rewrite-java-8/src/main/java/org/openrewrite/java/Java8Parser.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Instead of directly resolving artifact names to classpath entries inside `JavaParser.Builder#classpath(String...)` this is now delayed until `build()` is called for the first time. This has the advantage that constructing a builder is cheap even when the `classpath(String...)` method gets invoked. As a result a recipe can initialize a `JavaTemplate` (with a customized `JavaBuilder`) in a field initializer of its visitor without incurring a rather big overhead.
Also, as was done for `JavaParser.Builder` in https://github.com/openrewrite/rewrite/commit/5413da97869c6fd75742d2b53211a831ae99eef4 the initial value for `GroovyParser.Builder#classpath` should also be the empty list, rather than the runtime classpath.
> Delay the resolution of classpath in `JavaParser.Builder`

- rewrite-yaml/src/main/java/org/openrewrite/yaml/FormatPreservingReader.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/FormatPreservingReaderTest.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Update the YAML parser to support multiple bytes (> 2) unicode characters.
Root cause: Snake-yaml parser is based on the characters index and the reader (prefix parsing is based on the reader index) is based on the source index.
If there are any >2 bytes of Unicode characters in the source code, it will make the index mismatch and cause problem.
fixes https://github.com/openrewrite/rewrite/issues/2062
> yaml parser support unicode

- rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeLineBreaks.java
Right now we have a recipe with the display name of `Normalize the line breaks` and a recipe with the display name of `Normalize line breaks` (one for Java and one for XML). Let's make them both say the same thing since they do the same thing in their respective language.
> Standardize line break recipe name

- rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
- rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
- rewrite-core/src/main/java/org/openrewrite/config/Environment.java
- rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java
- rewrite-core/src/main/java/org/openrewrite/internal/lang/NullUtils.java
- rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java
- rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java
- rewrite-core/src/test/resources/META-INF/rewrite/test-sample-a.yml
- rewrite-core/src/test/resources/META-INF/rewrite/test-sample-b.yml
- rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddSettingsPluginRepository.java
- rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java
- YamlResourceLoader now uses jackson to try to instantiate imperative recipes with zero args if basic reflection fails. And, reverted change to RecipeSpec which made it scanRuntimeClasspath unnecessarily for yaml recipes. Fixes #3414
- adding RewriteTest/RecipeSpec recipeFromResources option to scan all rewrite yamls on classpath (ignoring classes. Fixes #3096
- In `ClasspathScanningLoader`, the constructor overloads were starting to get diverse in functionality, so I opted for a factory method for this new scenario. Open to changing it
- In `ClasspathScanningLoader`, there's this comment, which I'm not sure is accurate today; I think the new case `RecipeLifecycleTest::declarativeRecipeChainFromResourcesIncludesImperativeRecipesInDescriptors` disproves it …
> RewriteTest / YamlResourceLoader Enhancements

- rewrite-core/src/main/java/org/openrewrite/Recipe.java
- rewrite-core/src/main/java/org/openrewrite/internal/RecipeIntrospectionUtils.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
- rewrite-properties/src/main/java/org/openrewrite/properties/AddProperty.java
Fixes #3508, preserves intent of #3404
This makes the default validation slightly more strict, and may break some existing recipes for which a blank String is a valid argument for some field. I've fixed a few such recipes in this same PR.
> Recipe validation / RecipeIntrospectionUtils changes for String fields

- rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/OrderImports.java
- rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
This is a follow on to https://github.com/openrewrite/rewrite/pull/3397 which attempted to address https://github.com/openrewrite/rewrite/issues/3275. 
This change attempts to bridge the gap between static fully qualified paths and non-static imports. In addition it addresses one concern about unfolding wildcard imports by introducing an a boolean option to "Unfold wildcard imports".
My motivation is to resolve https://github.com/openrewrite/rewrite/issues/3275 and make the RemoveUnusedImports recipe more reliable for wider adoption.
Could you double check that I added the boolean option to this recipe correctly? I attempted to copy the pattern from other recipes. Does any documentation need to be updated or is that done as part of the build? 
Any maintainer 😄
n/a
n/a
> Issue 3275/fix remove used param v2

- rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
- rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeParentVersion.java
- rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
Add support for update/adding `relativePath` on `UpdateParentPom` receipe
Fixes https://github.com/openrewrite/rewrite/issues/3536
Refactoring multi-module Maven projects
None found
Tested with
I've added 3 unit tests to cover 3 new use case
- Update relative path
- Add new relative path if not set (empty value)
- Add new relative path if not set (non-empty value)
```
./gradlew :rewrite-maven:test --info --tests '*ChangeParentPomTest' --continue
```
Let me know if ok. I can also update the documentation if needed
> Add support for `relativePath` change on `ChangeParentPom`

- rewrite-core/src/main/java/org/openrewrite/style/NamedStyles.java
Merely to start a discussion; I'd rather have it fixed at the source than with this workaround.
Seen when running `Add missing @Override to overriding and implementing methods` against OpenRewrite org.
https://app.moderne.io/results/t0GqaF80q
```java
public TreeVisitor<?, ExecutionContext> getVisitor() {
return new RemoveToStringFromArraysVisitor();
}
```
```
Cannot invoke "java.util.Collection.iterator()" because "namedStyle.styles" is null
```
```
java.lang.NullPointerException: Cannot invoke "java.util.Collection.iterator()" because "namedStyle.styles" is null
org.openrewrite.style.NamedStyles.merge(NamedStyles.java:59)
org.openrewrite.SourceFile.getStyle(SourceFile.java:75)
org.openrewrite.java.format.AutoFormatVisitor.visit(AutoFormatVisitor.java:60) …
```
> Prevent NPE on `namedStyle.styles.iterator()`

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepositoryMirror.java
- rewrite-maven/src/test/java/org/openrewrite/maven/tree/MavenRepositoryMirrorTest.java
As [documented](https://maven.apache.org/guides/mini/guide-mirror-settings.html) (and verified by manual testing) it is always the first matching Maven mirror that should get selected, when finding a mirror for a particular repository. I.e. the mirrors should not be applied recursively.
Additionally, this commit will use the precomputed mirrors (from the `ExecutionContext`) whenever possible, as computing the mirrors is somewhat expensive.
> No recursive application of Maven mirrors

- rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java
- rewrite-maven/src/main/java/org/openrewrite/maven/MavenTagInsertionComparator.java
- rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
Found issue when testing https://github.com/openrewrite/rewrite/pull/3537 in real use case.
I ended-up with duplicate `relativePath` tag on maven pom.
I'm not sure why, I was not able to reproduce with unit test. I think the model need to be refreshed earlier.
In any case I've added a tentative fix and increase the test coverage for multi module
- Changing parent module only
- Changing child module to point to a different external pom
I've also ensured the relativePath is added after the version on the parent pom-
> Fix issue with duplicate `relativePath` on `ChangeParentPom`

- rewrite-maven/src/main/java/org/openrewrite/maven/AddPlugin.java
- rewrite-maven/src/test/java/org/openrewrite/maven/AddPluginTest.java
- `version` is now optional, this is useful for example when inheriting it from a parent.
- Added `filePattern` , this is useful in many cases but for me when working with a multi module maven project.
See section above.
Authors of addPlugin.
@jkschneider 
@sambsnyd
@BoykoAlex
> AddPlugin changes; make `version` optional and add `filePattern`

- rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
- rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java
- rewrite-java/src/main/java/org/openrewrite/java/format/BlankLinesVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeLineBreaksVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeTabsOrSpacesVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/RemoveTrailingWhitespaceVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
When looping over the contents of a `String` it is typically better to work with `String#charAt()`.
> Remove uses of `String#toCharArray()`

- rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
The root cause is the addImport service doesn't support Kotlin alias at the moment, so this approach is a workaround fix.
I have 2 test cases below verified in `rewrite-kotlin` repo, it's not able to add to this repo since no dependency.
```java
@Test
void changeTypeTest2() {
rewriteRun(
spec -> spec.recipe(new ChangeType("java.util.ArrayList", "java.util.LinkedList", true)),
kotlin(
"""
import java.util.ArrayList as MyList
fun main() {
val list = ArrayList<String>()
val list2 = MyList<String>()
}
""",
"""
import java.util.LinkedList as MyList
fun main() {
val list = LinkedList<String>()
val list2 = MyList<String>()
}
"""
)
);
}
@Test
void changeTypeTest3() {
rewriteRun(
spec -> spec.recipe(new ChangeType("java.util.ArrayList", "java.util.LinkedList", true)),
kotlin(
"""
import …
```
> Update ChangeType recipe to support kotlin alias import

- rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java
- rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/service/ImportService.java
To fix the issue of the `ChangeType` recipe missing the Kotlin alias import.
I have a workaround [solution](https://github.com/openrewrite/rewrite/pull/3558) before but it doesn't solve the problem thoroughly. 
The problem is it's impossible to add two imports (one with an alias, the other one without an alias)
I found the only way to solve this is to update AddImport to support alias.
> Update AddImport with alias to support Kotlin alias import

- rewrite-maven/src/main/java/org/openrewrite/maven/cache/LocalMavenArtifactCache.java
- rewrite-maven/src/test/java/org/openrewrite/maven/cache/LocalMavenArtifactCacheTest.java
LocalMavenArtifactCache created an empty file when the input stream is null and then does not write anything to it. This means that a retry will fail on loading this empty file.
During recipe loading a timeout can occur. A retry is put in place to fix this, but these always fail due to the above problem.
Was this a bug or a feature?
no
> avoid creating an empty file if nothing will be written to it.

- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
- rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
And use the escaped groovy method name rewriting to update dependencies with the gradle default scope (although why this scope is being chosen by the java update recipe is unclear).
Added handling for escaped method names in GroovyParserVisitor, then check for configurations that require escaping in the AddDependencyVisitor
This is an enhancement that is also a workaround for https://github.com/openrewrite/rewrite/issues/3559.
A more complete fix would involve determining why the AddJaxbRuntime recipe is selecting certain configurations like default and rewrite to add dependencies to. 
@shanman190 @timtebeek
> Rewrite escaped groovy method names

- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
- rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
Do not look for array dimensions when we encounter varargs in method references in Javadoc.
We failed to parse the file at all
- https://github.com/openrewrite/rewrite/issues/3575
Fixes https://github.com/openrewrite/rewrite/issues/3575
> Handle varargs in `ReloadableJava17JavadocVisitor`

- rewrite-maven/src/main/resources/META-INF/rewrite/maven.yml
- rewrite-maven/src/test/java/org/openrewrite/maven/maven4/PrefixlessExpressionsTest.java
Add Apache Maven best practices (to be expanded upon still) and a recipe to drop prefixless expressions from pom.xml files ahead of Maven 4.
Fixes #1621
- https://github.com/apache/maven/pull/696
- https://issues.apache.org/jira/browse/MNG-7404
> Drop prefixless expressions in POM

- rewrite-maven/src/main/java/org/openrewrite/maven/search/ParentPomInsight.java
- rewrite-maven/src/main/java/org/openrewrite/maven/table/ParentPomsInUse.java
- rewrite-maven/src/test/java/org/openrewrite/maven/search/ParentPomInsightTest.java
Add ParentPomInsight recipe, test & data table to see what parents and versions of parents are used.
Find & bump parent POMs in Apache Maven and beyond.
There's no explicit limit to just the root project; is that correct or should we add that?
- https://maven.apache.org/pom/maven/
- org.apache.maven.shared:maven-shared-components
- org.apache.maven:maven-parent
> Maven parent POM insight through data table

- rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
Fixes #3585.
Same null check as done for the other node in line 874.
> Avoid NPE in SemanticallyEqual

- rewrite-java-test/src/test/java/org/openrewrite/java/format/SingleLineCommentsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/format/SingleLineComments.java
Fixes #3588.
No more trailing blanks being added by SingleLineComment
> Avoid trailing blanks in SingleLineComment

- rewrite-json/src/main/java/org/openrewrite/json/internal/JsonParserVisitor.java
- rewrite-json/src/test/java/org/openrewrite/json/JsonParserTest.java
fixes https://github.com/openrewrite/rewrite/issues/3582
Currently, the JSON parser doesn't support multiple bytes Unicode characters (> 2 bytes).
The root cause is the index from Antlr is mismatched with the source index.
For example:
```java
{
"🤖": "robot",
}
```
Tokens from Antlr
```
Got token: [@0,0:0='{',<1>,1:0]
Got token: [@1,4:6='"🤖"',<10>,2:2]
Got token: [@2,7:7=':',<4>,2:5]
Got token: [@3,9:15='"robot"',<10>,2:7]
Got token: [@4,16:16=',',<2>,2:14]
Got token: [@5,18:18='}',<3>,3:0]
Got token: [@6,19:18='<EOF>',<-1>,3:1]
```
we can see `4:6='"🤖"'`. However, the 🤖 has 4 bytes, so the start/end offset in the source code is not [4,6] but [4,7].
I think all Antlr-based parsers will have the same problem ( doesn’t support multiple bytes of Unicode). and this PR is a common pattern to …
> Update json parser to support multiple-bytes-unicodes

- rewrite-json/src/main/java/org/openrewrite/json/internal/JsonParserVisitor.java
- rewrite-json/src/test/java/org/openrewrite/json/JsonParserTest.java
The `JsonParserVisitor#indexes` array requires an additional 4 bytes of memory per code point in the source code (only in case the source has at least one surrogate). Rather than doing that, the parser can have two cursors which are kept in sync when advancing through the source code: One code point cursor and one code unit cursor. The former is to align with the indexes of the ANTLR tokens and the latter is to be able to read from the underlying source string.
> Remove `JsonParserVisitor#indexes`

- rewrite-json/src/test/java/org/openrewrite/json/JsonParserTest.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/FormatPreservingReader.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/internal/YamlPrinter.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/tree/MappingTest.java
A YAML scalar value can contain unicode escape sequences like `\u0051`. Currently, this throws off the parser.
> Fix parsing of unicode escape sequences in YAML

- rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Fixes #3599 
Since it is an utility method that is invoked from different scenarios check if this change can affect any other behaviors.
@timtebeek
- It seems affected method is being invoked from another unit tests already so specific test was not added.
- Should add a specific unit test for `MissingOverrideAnnotation` recipe to verify this bugfix.
- no new files were added
> [TypeUtils.findOverridenMethod] Skip found methods with default access and not same package

- rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePlugin.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePluginTest.java
- rewrite-maven/src/main/java/org/openrewrite/maven/AddDevelocityMavenExtension.java
- rewrite-maven/src/test/java/org/openrewrite/maven/AddDevelocityMavenExtensionTest.java
Rename `AddGradleEnterpriseGradlePlugin`, `AddGradleEnterpriseMavenExtension` and their metadatas.
Gradle Enterprise was recently renamed to Develocity.
> Rename Gradle Enterprise recipes

- rewrite-java-test/src/test/java/org/openrewrite/java/format/TabsAndIndentsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
Make sure the formatting in the following code remains as is.
```java
class Foo {
String test() {
return "foobar"
.substring(
1
).substring(
2
).substring(
3
);
}
}
```
> Fix the indentation of parameterized chained method calls

- rewrite-maven/src/main/java/org/openrewrite/maven/search/FindProperties.java
- rewrite-maven/src/test/java/org/openrewrite/maven/search/FindPropertiesTest.java
Previously, all property usages were printed the actual value of the property, not only the ones matching the propertyPattern. Now we also apply the propertyPattern to find usages.
Another recipe is using this recipe to find java.version property, and it was always returning results if there were any property being used in the pom.
@timtebeek @knutwannheden @pstreef 
I've seen that there is a find method at the bottom, that only returns property definitions, but not property usages, that has duplicated code. To avoid propagating a change in behavior down, I've left the method as it is, but I found kinda inconsistent to have this code partially duplicated and with different behavior than in the actual recipe.
> Fixed property usage pattern matching search results

- rewrite-yaml/src/main/java/org/openrewrite/yaml/internal/YamlPrinter.java
Changes:
- A null anchor in an alias will not cause an NPE.
> Check for null anchor in yaml printer.

- rewrite-java-test/src/test/java/org/openrewrite/java/RemoveAnnotationTest.java
- rewrite-java/src/main/java/org/openrewrite/java/RemoveAnnotationVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/Expression.java
This change the `RemoveAnnotation` recipe/visitor to remove unused annotation parameter imports
> Remove unused annotation parameter imports

- rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
When changing a inner class, even with the ignoreDefinition, it still changes it if it's used in the same class where it's defined. I narrow it the issue to the visitIdentifier method, and checking that the identifier it's not in a class definition fix the issue. 
However, it still adds the import even if it's not needed. I've tried to check the logic of when to add the import, but owningClass of Test.InnerB is null, don't know why... maybe because the way we created the type?
Fixes #3598
Fix the add import logic 
@knutwannheden
> fixed inner class

- rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Fix the assignability test for generic type variable types.
> Match `JavaType.GenericTypeVariable` in `TypeUtils#isAssignableTo()`

- rewrite-xml/src/main/java/org/openrewrite/xml/RemoveXmlTag.java
- rewrite-xml/src/test/java/org/openrewrite/xml/RemoveXmlTagTest.java
the noop treevisitor was replaced with a hassource visitor which always matches
the following line
(https://github.com/openrewrite/rewrite/blob/d5ed2c5a1cc64b412afcee87c32ba6ab1b344758/rewrite-core/src/main/java/org/openrewrite/Preconditions.java#L41)
would always result to false on an xml file
`!(tree instanceof SourceFile)` would be false in case of an xml.document which inherits from source file
`check.visit(tree, ctx) != tree` is false since check is the noop treevisitor which returns the tree
since both are false the whole check is false
also added a test for it
> Fixed error when no file matcher was present

- rewrite-java-test/src/test/java/org/openrewrite/java/DeleteMethodArgumentTest.java
- rewrite-java/src/main/java/org/openrewrite/java/DeleteMethodArgument.java
Updating method type list of arguments to avoid next calls to the recipe to keep method matching
Right now this recipe is not idempotent, thus we need to specify in the tests that we only want one cycle. This is not very convenient when using this recipe from other recipes, and also leaves the method in an inconsistent state.
@timtebeek 
I had to change a test, that was relying specifically on the fact that the method type is not updated and that subsequent calls to the recipe will still match and delete the parameter. I do not know if this is also used in recipes that are using this one.
> update method type on DeleteMethodArgument

- rewrite-core/src/main/java/org/openrewrite/ParseExceptionResult.java
- rewrite-core/src/main/java/org/openrewrite/Parser.java
- rewrite-core/src/main/java/org/openrewrite/Result.java
- rewrite-core/src/main/java/org/openrewrite/tree/ParseError.java
- rewrite-core/src/test/java/org/openrewrite/FindParseFailuresTest.java
- rewrite-core/src/test/java/org/openrewrite/ParserTest.java
This PR will help us more efficiently when working on parsing to print idempotent issues on new languages.
> For parsing errors caused by print-idempotent check, add diff to the message of `ParseExceptionResult` marker

- rewrite-gradle/src/main/java/org/openrewrite/gradle/GradleParser.java
Fixed default classpath for settings parser.
When trying to parse a `settings.gradle` file it was failing with Class not found exceptions due to not properly setting the classpath on the parser.
@knutwannheden @jkschneider
> fix defaultClasspath for GradleParser

- rewrite-protobuf/src/main/java/org/openrewrite/protobuf/ProtoParser.java
- rewrite-protobuf/src/test/java/org/openrewrite/protobuf/ProtoParserTest.java
Proto3 files are now returned as plain text files, rather than skipped, pending a proper Proto3 parser.
Warning about out of date LSTs, since files where accepted by the parser but skipped, as discussed on Slack.
We could have gone for `ParseError` instead, but that limits the options for folks to target these in search or text replace.
> Do not skip proto3 files, as it warns about out of date LSTs

- rewrite-core/src/main/java/org/openrewrite/text/CreateTextFile.java
- rewrite-test/build.gradle.kts
- rewrite-test/src/test/java/org/openrewrite/text/CreateTextFileTest.java
Allow `CreateTextFile` to overwrite files in a different format than `PlainText`.
We recently started parsing `Jenkinsfile` as Groovy, which unfortunately broke the `CreateTextFile` used in `ModernizeJenkinsfile`
https://github.com/openrewrite/rewrite-jenkins/blob/8914ccd62655d65f2c54e2e40ed6289f13f69542/src/main/resources/META-INF/rewrite/rewrite.yml#L53-L70
Fixes https://github.com/openrewrite/rewrite-jenkins/issues/52
Called out below.
Not really; looked towards `FindAndReplace` as that also allows text replace regardless of file type.
- https://github.com/openrewrite/rewrite-jenkins/issues/52
> CreateTextFile should override files of different type

- rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
- rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Do not replace the repo with the user-agnostic ~/.m2/repository if it is not the local default one
If a custom local maven repo is configured, we cannot assume that we can replace it with ~/.m2/repository, because it will point to a different location.
@timtebeek @pstreef
> do not overwrite the repo if it's not the default local one

- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
- rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
- rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Add a list of `J.Modifier` to `J.TypeParameter` for Kotlin.
to support variance cases like this :
```kotlin
@Target(AnnotationTarget.TYPE_PARAMETER)
annotation class Anno
class Foo  <   @Anno     out     T :  Any    >  () {}
```
`out` will be a modifier of `T :  Any` which is a  `J.TypeParameter` here.
as same as to `in` and `reified` keywords.
> Add modifiers to TypeParameter for kotlin

- rewrite-core/src/main/java/org/openrewrite/marker/ci/BitbucketBuildEnvironment.java
- rewrite-core/src/main/java/org/openrewrite/marker/ci/BuildEnvironment.java
Add Bitbucket BuildEnvironment
Recognize bitbucket CI, such that the CLI progress bar adjusts output.
Any reason we didn't have this before?
Anything we should be mindful of in terms of detection order?
We could detect `CI` only as a catch all CI env; but then we lack input for `GitProvenance`.
As per https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/
> Add BitbucketBuildEnvironment for better progress indicators

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
- rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Wrote the unit test for the case #3699 and proposed fix
Fixes https://github.com/openrewrite/rewrite/issues/3699
No
No
I don't think there are any, but I'm glad to hear about them.
After this fix, there is no ClassCastException. But the test asserts fails anyway because the POM is changed here - see the results of the tests. And now I don't know what to do with this. Should we suppress it or ignore it in the code itself? So that test would expect such changes or ignore them? Or is here some other way? Correct the parser, so these changes wouldn't appear and there would be no difference?
> Do not log `ClassCastException` in MavenParser in case of malformed POM

- rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
- rewrite-maven/src/test/java/org/openrewrite/maven/tree/ResolvedPomTest.java
When resolving a dependency then a transitive dependency could be a managed dependency with a placeholder classifier. This placeholder must then be resolved before the version can be resolved, as it otherwise won't be found and results in a `MavenDownloadingException`.
> Resolve dependency version after type and classifier

- rewrite-java-test/src/test/java/org/openrewrite/java/UseStaticImportTest.java
- rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java
Fixes #3705.
Avoids the recipe in case of type parameters, as suggested by @knutwannheden
> Ignore methods with type parameters in UseStaticImport

- rewrite-maven/src/main/java/org/openrewrite/maven/ChangePackaging.java
- rewrite-maven/src/test/java/org/openrewrite/maven/ChangePackagingTest.java
- rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java
Omit `jar` packaging on maven pom.xml files (it is the default)
Omit the `<packaging>jar</packaging>` tag on pom.xml files when using the `ChangePackaging` recipe.
> Remove default `jar` packaging when using `ChangePackaging`

- rewrite-java-test/src/test/java/org/openrewrite/java/ReorderMethodArgumentsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/ReorderMethodArguments.java
Added support for constructors too
Needed in https://github.com/openrewrite/rewrite-migrate-java/pull/338 
@timtebeek 
Alternative to https://github.com/openrewrite/rewrite/pull/3710
> Reorder constructor arguments too

- rewrite-maven/src/main/java/org/openrewrite/maven/search/ParentPomInsight.java
- rewrite-maven/src/test/java/org/openrewrite/maven/search/ParentPomInsightTest.java
Add a version selector to ParentPomInsight, based in what I'd seen in DependencyInsight. 
Limit results to particular parent pom version, such as non-snapshot versions.
> Support optional version selector in ParentPomInsight

- rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
YamlResourceLoader initializes the lazy loaded recipes with all it's available recipes, so the recipe list gets properly populated with the actual recipes. However, with Environment.scanJar, first we are initializing the recipes from the dependencies `ClasspathScanningLoader`, which will not have the full list of recipes, thus causing validating errors if the recipe is nested in multiple levels of DeclarativeRecipes from a different jar artifact.
The initialize method right now, clears the uninitialized list of recipes, thus not allowing us to re-initialize again later on (which happens when we are using the same recipe from the "main" `YamlResourceLoader`, so if the first initialize fails to find some recipes (because from the dependency `ClasspathScanningLoader` we do not see all the …
> allow initialize the recipe multiple times

- rewrite-java/src/main/java/org/openrewrite/java/SimplifyMethodChain.java
Checking if the parameter is != null before accessing it. If we do not properly populate the field, it will throw an NPE aside from the validation error.
Fixes #3580
@timtebeek @knutwannheden @Bananeweizen
> fixed possible NPE when required methodPatternChain not provided

- rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java
- rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
Changes `XPathMatcher` to allow `//` syntax.
https://github.com/openrewrite/rewrite-migrate-java/issues/353
This is just enough to fix the before mentioned issue, definitely needs more testing and a better implementation.
> Tentative fix for missing "//" operator on `XPathMatcher`

- rewrite-java-test/src/test/java/org/openrewrite/java/format/TabsAndIndentsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java
Test case showing bug with continuation indents improperly being auto formatted.
I've seen another case related to continuation indents for method arguments as well as method chains, but haven't been able to reproduce that case yet.
> AutoFormat bug with method parameter alignment when using tabs

- rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
Possibly due to mirrors applied with property placeholders. This is part exploratory until I know exactly what's lead to the problem in the first place, but the changes here ought to help regardless.
> Prevent NPE as reported due to null normalized repository

- rewrite-java-test/src/test/java/org/openrewrite/java/UseStaticImportTest.java
- rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java
If a class declares a method with the same name as a candidate for a static import, then that will always lead to compile errors if the static import is applied. Therefore the recipe must check for not having any similarly named method locally.
Additional precondition for static import, namely `not(DeclaresMethod("* sameNameAsMethodPattern(..)"`.
Quite some compile errors on larger code bases with UseStaticImport recipe. The included unit test demonstrates this and leads to uncompilable code without the change.
The method pattern is created via String manipulation. Not sure if there are better ways using MethodPattern, MethodPatternParser etc. but that was hard to explore.
> Don't use static import on collision with local method

- rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
Partially revert 0902de56473f03f11bf1b2262a0039bec16f40f8 so that the recipe scheduler only runs a single cycle if a _changing recipe_ explicitly requested another cycle. In this context a recipe which adds a message to the `ExecutionContext` is also considered a changing recipe.
Also, use a `Set` (specifically a `Set` based on `IdentityHashMap`) to track the recipes that made changes in a cycle. This improves performance a bit, because the recipe instances are typically the same and then there is no need to query the same recipe repeatedly for `causesAnotherCycle()`.
> Only run recipe a single cycle when possible

- rewrite-java-test/src/test/java/org/openrewrite/java/UseStaticImportTest.java
- rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java
Fixes [org.openrewrite.java.testing.junit5.AssertToAssertionsTest#staticallyImportAssertions](https://github.com/openrewrite/rewrite-testing-frameworks/blob/39dc67cab9a2d32ed000e5ad1348d31cae3979cd/src/test/java/org/openrewrite/java/testing/junit5/AssertToAssertionsTest.java#L318) after
- https://github.com/openrewrite/rewrite/pull/3729
> Stop over eager exclude of UseStaticImport

- rewrite-java-test/src/test/java/org/openrewrite/java/recipes/SourceSpecTextBlockIndentationTest.java
- rewrite-java/src/main/java/org/openrewrite/java/recipes/SourceSpecTextBlockIndentation.java
Add a newline & autoformat when SourceSpec text block has no whitespace or comment prefix.
Commonly pointed out in review; by automating the code change & review we reduce review burden, and get more consistent code.
> Ensure SourceSpec text blcks start on a new line

- rewrite-java/src/main/java/org/openrewrite/java/marker/Quoted.java
This marker will represent quoted identifiers in languages like JavaScript and Kotlin.
The change will allow the identifier text to be correctly represented while preserving the escapes.
Example: ChangeType from Map to List should update the identifiers correctly from:
```
`Map`
```
to
```
`List`
```
> Added quoted marker to represent escaped identifiers.

- rewrite-java-test/src/test/java/org/openrewrite/java/UseStaticImportTest.java
- rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java
* add tests for good and bad cases
* fix issue by checking method to be static
* verified that the bad case fails without the fix and passes with the fix
> Restrict UseStaticImport to static methods (#3661)

- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeTree.java
Updated TypeTree.build to support the detection of escaped identifiers and add `Quote` markers.
Notes:
- These changes are related to https://github.com/openrewrite/rewrite-kotlin/issues/493 to allow ChangeType to work on imports with escaped names and for the ImportService in rewrite-kotlin to create imports with escaped names.
> Added support for escaped identifiers to TypeTree.build.

- settings.gradle.kts
This was breaking my attempt to run the CodeQL scanner for OpenRewrite from my fork.
https://github.com/JLLeitschuh/rewrite-1/actions/runs/7094115471/job/19308794549#step:4:98
> Don't push to GE Build Cache without Creds

- rewrite-core/src/main/java/org/openrewrite/marker/AlreadyReplaced.java
- rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java
- rewrite-core/src/test/java/org/openrewrite/text/FindAndReplaceTest.java
Make `FindAndReplace.replacement` nullable, such that it becomes optional in the UI, and can remove matches.
Sometimes you just need to remove a line, as seen in
- https://github.com/openrewrite/rewrite/pull/3765
> Allow FindAndReplace to remove matches

- rewrite-properties/src/main/java/org/openrewrite/properties/CreatePropertiesFile.java
- rewrite-xml/src/main/java/org/openrewrite/xml/CreateXmlFile.java
- rewrite-yaml/src/main/java/org/openrewrite/yaml/CreateYamlFile.java
Replace StringUtils used by the recipes that create files
Running the recipes with the Maven plugin was showing a `A required class was missing` exception
> Replace `org.junit.platform.commons.util.StringUtils` with `org.openrewrite.internal.StringUtils`

- rewrite-core/src/main/java/org/openrewrite/internal/lang/NullUtils.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddProperty.java
- rewrite-properties/src/main/java/org/openrewrite/properties/AddProperty.java
- rewrite-properties/src/test/java/org/openrewrite/properties/AddPropertyTest.java
`AddSpringProperty` from `rewrite-spring` accepts comments, but only applies it's a YAML file. This PR changes `AddProperty` to accept comments.
Add properties to Spring applications.
> `AddPropery` now accepts a comment

- rewrite-java-test/src/test/java/org/openrewrite/java/RenameVariableTest.java
- rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
Changes:
- RenameVariable will not update names of `@param` in JavaDocs.
fixes https://github.com/openrewrite/rewrite/issues/3772
> Updated RenameVariable to not update JavaDoc param names.

- rewrite-groovy/src/test/java/org/openrewrite/groovy/JavaTemplateMatchTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateContextFreeTest.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaTemplateSemanticallyEqual.java
When a `JavaTemplate` is applied to a non-Java LST it may end up returning the input itself. In this case `JavaTemplate#match()` should return `false`.
> Consider templates returning input as no match

- rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java
- rewrite-properties/src/main/java/org/openrewrite/properties/internal/PropertiesPrinter.java
- rewrite-properties/src/main/java/org/openrewrite/properties/tree/Properties.java
- rewrite-properties/src/test/java/org/openrewrite/properties/AddPropertyTest.java
- rewrite-properties/src/test/java/org/openrewrite/properties/PropertiesParserTest.java
- rewrite-properties/src/test/java/org/openrewrite/properties/search/FindPropertiesTest.java
Changes:
- Continuations are preserved in `Entry#key` and `Value#text`
- Add methods `Entry#getKeySource` and `Value#getSourceText` to retrieve the source text.
- Updated `get` methods to trim continuations from the text.
fixes #2473 
fixes #3741
> Added support for continuations in properties.

- rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java
Provides necessary hints for clients understand the capabilities.
> fix: update `helpText` for `FindAndReplace` recipe to denote support for multiline strings

- rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
- rewrite-java-test/src/test/java/org/openrewrite/java/search/HasJavaVersionTest.java
When a precondition visitor extends an `XyzIsoVisitor` class (like `JavaIsoVisitor`) and there overrides the `visit()` method, then this will result in a `ClassCastException` when the visitor is given a source file which is not of that type.
> `PreconditionBellwether` must call `isAcceptable()`

- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest3Test.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest5Test.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodName.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodTargetToStatic.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodTargetToVariable.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
- rewrite-java/src/main/java/org/openrewrite/java/ImplementInterface.java
- rewrite-java/src/main/java/org/openrewrite/java/SimplifyMethodChain.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java
Changes:
- FindMissingTypes will validate the `name` field `MethodInvocation` and `MethodDeclaration` when the method type is not null and the type on the identifier is not null.
- FindMissingTypes will validate the `clazz` field on `J.ParameterizedType` and `J.NewClass` when the clazz is a `J.Identifier` and the type is not null.
- ChangeMethodName, ChangeMethodTargetToStatic, ChangeMethodTargetToVariable, ChangePackage, ChangeType, SimplifyMethodChain, and ImplementInterface will update the old type with the new type on applicable identifiers.
These types occur from the Java compiler and are expected on the LST. The changes help to identify unexpected changes through recipes and misaligned type mappings in other implementations of `J`.
fixes #3739
> Added a few type validation checks to FindMissingTypes.

- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest4Test.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest7Test.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java
Changes:
- JavaTemplate will update names of J.MethodDeclaration and J.MethodInvocation.
fixes #3787
> Replaced old method type on names of J.MethodInvocation and J.MethodDeclaration in JavaTemplateJavaExtension.

- rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseMapNotation.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeStaticFieldToMethod.java
- rewrite-java/src/main/java/org/openrewrite/java/DeleteMethodArgument.java
- rewrite-java/src/main/java/org/openrewrite/java/RemoveImplements.java
- rewrite-java/src/main/java/org/openrewrite/java/ReorderMethodArguments.java
Changes:
The following recipes will update the original method type on the method names to the new method type.
- DeleteMethodArgument.
- ReorderMethodArguments.
- ChangeStaticFieldToMethod.
- DependencyUseMapNotation
- RemoveImplements.
> Change original method types on method invocation names along with methodType field.

- rewrite-maven/src/main/java/org/openrewrite/maven/AddPlugin.java
- rewrite-maven/src/test/java/org/openrewrite/maven/AddPluginTest.java
`AddPlugin` throws exception if the plugin being added is already present on pom.xml and it's version is managed by a parent pom.
No
No one.
> Fix for AddPlugin when plugin version is managed

- rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java
- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java
- rewrite-java/src/main/java/org/openrewrite/java/UnwrapParentheses.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/format/MethodParamPad.java
- rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
This is to get rid of breaking change like https://github.com/openrewrite/rewrite/issues/3783
slack discussion : https://moderneinc.slack.com/archives/C067J83AFHB/p1701957313256969
> Disable Java `SpacesVisitor` for non-Java sources

- rewrite-core/src/main/java/org/openrewrite/ExecutionContext.java
- rewrite-core/src/main/java/org/openrewrite/Recipe.java
- rewrite-core/src/main/java/org/openrewrite/WorkingDirectoryExecutionContextView.java
- rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
This directory can be written to by the recipes being executed. Depending on whether the `createNew()` or `useExisting()` factory method is used, the directory will get automatically deleted again once the `WorkingDirectoryExecutionContextView`.
The idea is that recipes should only have to either directly call `ctx.getMessage(WORKING_DIRECTORY)` or use the static `getWorkingDirectory(ctx)` method to access the current working directory.
> Add a new `WORKING_DIRECTORY` message to `ExecutionContext`

- rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
Skip performing extra work when the current Gradle version was updated earlier in the cycle.
Overall reduce what would be considered duplicate work due to ordering within the recipe stack. For most cases, the stack will include Gradle updates that incrementally go higher. However, users may pull in recipes in varying orders, so we should ensure that we do the minimum amount of work necessary.
Any of: @jkschneider @sambsnyd @timtebeek 
Only one really is to try to strictly order recipes in the recipe stack as a user, so that things always go up and never down. Though this can be harder than it sounds.
> Skip updating Gradle when already updated

- rewrite-java-test/src/test/java/org/openrewrite/java/search/HasJavaVersionTest.java
- rewrite-java/src/main/java/org/openrewrite/java/search/HasJavaVersion.java
Let `HasJavaVersion` return a `TreeVisitor` instead of a `JavaIsoVisitor`
Set a property for use of virtual threads if on Java 21, with a non-scanning recipe.
- https://github.com/openrewrite/rewrite-spring/pull/446
Necessary for proper functioning of this recipe & tests:
- https://github.com/openrewrite/rewrite-spring/pull/460
We add the Java version marker to all source files in
https://github.com/openrewrite/rewrite-maven-plugin/blob/1d205eac8f43a17395ed317b8e8984aa25990a59/src/main/java/org/openrewrite/maven/MavenMojoProjectParser.java#L296
> Find JavaVersion markers on any source file

- rewrite-java-test/src/test/java/org/openrewrite/java/recipes/SelectRecipeExamplesTest.java
- rewrite-java/src/main/java/org/openrewrite/java/recipes/SelectRecipeExamples.java
Skip `@Nested` classes for `@DocumentExample`.
Since there's often more than one, and all got a `@DocumentExample`
> Skip nested classes for document examples

- rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
- rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
When building gridgain/gridgain@main there is a `StackOverflowError` because the root project references `parent/pom.xml` as its parent and the latter contains `<relativePath/>`. But that actually means that Maven should *not* look for the parent in the current project.
It seems difficult to get this 100% correct right now, as we with our current model we deserialize using Jackson into `RawPom.Parent` can't tell the difference between an absent `<relativePath>` element and a present but empty `<relativePath>` element, even though that is significant in Maven.
As a shortcut we can check if the parent (in the file system) has a matching GA or not.
> Fix `StackOverflowError` in `MavenPomDownloader`

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
- Catch the UncheckedIOException thrown in RawPom parser
https://github.com/openrewrite/rewrite/blob/e1d09d09f1467531f1d72388658ca7306ccc7ea6/rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java#L105-L115  
Ensure we're able to troubleshoot and/or continue in the face of parse failures, to get away from stack traces like:
```java
Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character 's' (code 115) expected '='
at [row,col {unknown-source}]: [9,27]
at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar (StreamScanner.java:666)
at com.ctc.wstx.sr.BasicStreamReader.handleNonNsAttrs (BasicStreamReader.java:3213)
at com.ctc.wstx.sr.BasicStreamReader.handleStartElem (BasicStreamReader.java:3055)
at com.ctc.wstx.sr.BasicStreamReader.nextFromTree …
```
> Improve diagnostics on RawPom parse failures

- rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
- rewrite-xml/build.gradle.kts
- rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java
Added test that replicates issue with escaped value in tag, which results in a List of Xml.CharData.
When encountered, tag the text from each CharData, unescape that for use in download URLs, and concatenate.
This broke whenever we wanted to use an escaped value; we'd end up with no value at all.
Fixes #3811
Ok to use Streams and commons-text `StringEscapeUtils` in the uncommon case of more than one child value?
Not escaping still lead to download errors when composing depedency URLs.
- #3811
> Handle XML escapes in tag values

- rewrite-java/src/main/java/org/openrewrite/java/JavaParserExecutionContextView.java
Switched mkdirs and exists when creating a directory in home directory
This can potentially be a race condition where the directory does not exists and we fail to create it because some other thread has created in between.
Fixes: https://github.com/moderneinc/customer-requests/issues/191
@timtebeek @knutwannheden 
We could use `Files::createDirectories` since it does not fail if the directories already exists.
Similar fix done here: https://github.com/moderneinc/moderne-cli/pull/1002
> switch around mkdirs exists to avoid race condition

- rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java
Changes:
- Clarified the message where differences in method types are identified in FindMissingTypes.
> Clarified messaging of methodType checks in FindMissingTypes.

- rewrite-core/src/main/java/org/openrewrite/Recipe.java
When creating a Validated.required include the Recipe class simple name.
Fixes #3587
@Bananeweizen 
This seemed the have the least impact by not changing the Recipe class signature.
I figured `Class.getSimpleName` would be enough to pin down the cause in most cases.
-  #3587
> Include Recipe class simple name in validation errors

- rewrite-maven/src/main/java/org/openrewrite/maven/cache/InMemoryMavenPomCache.java
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepository.java
- rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepositoryMirror.java
- rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
This PR introduces two small optimizations to `MavenPomDownloader`:
1. Add a trailing '/' to Maven repository URL checks to avoid HTTP 302 redirects on slow Artifactory instances. Also tag the repository URL as known, if able to connect to it.
2. When deriving metadata for artifacts present on the local maven repository, consider only successfully downloaded artifacts.
This PR also fixes the counting of `deriveMetadata` successful calls.
Increased latency when working on network restricted environments with slow Artifactory proxies.
No.
No workarounds for environment issues
> Maven POM downloader optimizations

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/search/SemanticallyEqualTest.java
- rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
When comparing `J.FieldAccess` instances, the targets also needs to be compared.
> `SemanticallyEqual`: Fix bug in `visitFieldAccess()`

- rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/format/IndentsTest.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/tree/ScalarTest.java
Changes:
- The new line at the end of folded scalars is appropriately set on the prefix of the next key.
fixes #3531
> Fixed prefix on key after folder scalars.

- rewrite-java/src/main/java/org/openrewrite/java/ClassDefinitionLength.java
- rewrite-java/src/main/java/org/openrewrite/java/MethodDefinitionLength.java
- rewrite-java/src/main/java/org/openrewrite/java/table/TokenCount.java
- rewrite-java/src/test/java/org/openrewrite/java/ClassDefinitionLengthTest.java
- rewrite-java/src/test/java/org/openrewrite/java/MethodDefinitionLengthTest.java
Adding two recipes which estimates the number of token for class definitions and method definitions, and inputs those estimates into datatables. 
This is to estimate latency for the ai agent recommender.
> Feat:token length estimator

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
- rewrite-maven/src/test/java/org/openrewrite/maven/UpgradePluginVersionTest.java
The default groupId for Maven plugins is not the one from the current pom but `org.apache.maven.plugins`.
The default groupId for Maven plugins was the one from the currently resolved POM, while it should be `org.apache.maven.plugins`.
Correctness :).
See https://stackoverflow.com/questions/65527291/is-groupid-required-for-plugins-in-maven-pom-xml for the details.
@timtebeek hey, found this while working on the update recipes for Quarkus 3.7. I can work around it for now but I think it's worth a fix upstream. Thanks!
> Fix the plugin default groupId

- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
This reverts commit 006a99bf321e7f652c7acd52a4d54d37c0bc7036.
As discussed this caused downstream failures.
> Revert "The `managedReference` fields are no longer required"

- rewrite-java-tck/src/main/java/org/openrewrite/java/tree/AnnotationTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/service/AnnotationServiceTest.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/RemoveImplements.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindDeprecatedClasses.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindDeprecatedFields.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindDeprecatedMethods.java
- rewrite-java/src/main/java/org/openrewrite/java/service/AnnotationService.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/JavaSourceFile.java
Instead of calling the `getAllAnnotations()` and `getAnnotations()` methods directly, recipes and visitors should be using the `AnnotationService`. This will allow `rewrite-kotlin` to properly support multi annotations and annotations with use-site targets.
> New `AnnotationService`

- rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeTreeTest.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/TypeTree.java
Changes:
- TypeTree#build will preserve whitespace in escaped names.
fixes #3845
> Preserve whitespace in escaped names.

- rewrite-maven/build.gradle.kts
- rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
- rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenArtifactDownloader.java
- rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
`resilience4j-retry` replaced with `dev.failsafe`
`resilience4j-retry` has a lot of transitive dependencies and the latest version depends on java 17. Having to pin this to 1.7.0 can cause issues with consumers.
[FailSafe](https://github.com/failsafe-lib/failsafe) is a "lightweight, zero-dependency library for handling failures in Java 8+" which can handle the retries in stead
I need to look into metrics. If the old retries had them and if we want them on the new.
Implement an internal retrier.
> Replace resilience4j with failsafe

- rewrite-java/src/main/java/org/openrewrite/java/internal/TypesInUse.java
This refactoring will also make it better suitable for languages which extend `J`.
> Simplify `TypesInUse` utility

- rewrite-core/src/main/java/org/openrewrite/marker/OperatingSystemProvenance.java
Making EOL property public 
Need access to EOL property for https://github.com/moderneinc/customer-requests/issues/46
> fix: make EOL public on OperatingSystemProvenance

- rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
- rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodDeclarationTest.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
- rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java
- rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
- rewrite-java-tck/src/main/java/org/openrewrite/java/tree/AnnotationTest.java
- rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ArrayTypeTest.java
- rewrite-java-tck/src/main/java/org/openrewrite/java/tree/MethodInvocationTest.java
- rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/search/FindTypesTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/service/AnnotationServiceTest.java
- rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
- rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java
- rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java
- rewrite-java/src/main/java/org/openrewrite/java/format/NoWhitespaceAfter.java
- rewrite-java/src/main/java/org/openrewrite/java/search/FindTypes.java
- rewrite-java/src/main/java/org/openrewrite/java/service/AnnotationService.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Changes:
- Updated J.ArrayType to preserve annotations on dimensions.
- Removed `J.ArrayType#dimensions` field and added a constructor to transform old LSTs into the new model.
- Deprecated `J.VariableDeclarations#dimensionsBeforeName`
- `...` is preserved in the `J.VariableDeclarations#varargs` field instead of the prefix of the variable name.
- Updated `GroovyParserVisitor` with the new `J.ArrayType`.
- Applied optimizations from Java 17 and 21 parsers to Java 11 and 8 parsers.
fixes #2911
fixes #3440
fixes #3453
> Added ArrayTypeTree and support for annotated dimensions of array types.

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java
- rewrite-maven/src/test/java/org/openrewrite/maven/RemoveDuplicateDependenciesTest.java
Also take `classifier` into account when resolving managed dependencies.
Fixes https://github.com/openrewrite/rewrite/issues/3832
> Correctly deduplicate managed dependencies using classifier

- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Changes:
- ArrayType#create will generate the correct `JavaType`(s) from old Groovy LSTs.
> Minor revision to ArrayType#create to account for types on J.ArrayType from old Groovy LSTs.

- rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java
For Groovy support the `J.Ternary` was extended to also implement the `Statement` interface. As a consequence its coordinate is now a `CoordinateBuilder.Statement` coordinate. Allow `JavaTemplate` to replace it in its `visitExpression()` method in `JavaTemplateJavaExtension`.
Issue: openrewrite/rewrite-static-analysis#203
> Allow `JavaTemplate` to deal with expressions that are also statements

- rewrite-core/src/main/java/org/openrewrite/internal/NameCaseConvention.java
Add a break statement in for loop. 
We don't have to check all characters in a string to see whether the string is `allUpperCase`. We can break the for loop when any character is lowercase. 
N/A 
N/A 
N/A 
N/A
> Add break statement to toCamelCase

- rewrite-java-test/src/test/java/org/openrewrite/java/ShortenFullyQualifiedTypeReferencesTest.java
- rewrite-java/src/main/java/org/openrewrite/java/ShortenFullyQualifiedTypeReferences.java
Changes:
- Annotated fully qualified type references will be formatted correctly by ShortenFullyQualifiedTypeReferences.
fixes #3870
> Fixed formatting of annotated fully qualified type references in ShorenFullyQualifiedTypeReferences.

- rewrite-java-test/src/test/java/org/openrewrite/java/format/NoWhitespaceAfterTest.java
- rewrite-java/src/main/java/org/openrewrite/java/format/NoWhitespaceAfter.java
Changes:
- Annotated arrays will be appropriately formatted by NoWhiteSpaceAfter.
fixes #3869
fixes #2911
> Fixed formatting of annotated arrays in NoWhitespaceAfter.

- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
- rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
- rewrite-java-tck/src/main/java/org/openrewrite/java/tree/VariableDeclarationsTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/FinalizeLocalVariablesTest.java
When `var` is used with unknown type, rewrite consider `var` as `Space`. We need to add additional logic to identifyt `var` keyword. 
[Issue link](https://github.com/openrewrite/rewrite/issues/3744)
Below test code doesn't work. It rewrites `var a = b` into `finalvar a = b` (should have space between final and var) 
```java
@Test
@Issue("https://github.com/openrewrite/rewrite/issues/3744")
void missingTypePlusVarNotMissingSpace() {
rewriteRun(
s -> s.typeValidationOptions(TypeValidation.none()),
//language=java
java(
"""
import foo.Unknown;
class Bar {
void test(Unknown b) {
var a = b;
}
}
""",
"""
import foo.Unknown;
class Bar {
void test(Unknown b) {
final var a = b;
} 
}
"""
)
);
}
```
- Whether it's ok to put the checking logic into
- `ReloadableJava11ParserVisitor`
- …
> Check "var" keyword when varType is null or JCErroneous

- rewrite-maven/src/main/java/org/openrewrite/maven/AddDependencyVisitor.java
- rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
AddDependencyVisitor should add \<type\> tag during XML generation
I've noticed that the AddDependencyVisitor does not generate \<type\>, which prevents us from adding dependencies of the pom type. I believe this is not intentional, as the AddManagedDependencyVisitor is capable of generating \<type\>.
> Missing type tag in AddDependencyVisitor

- rewrite-java/src/main/java/org/openrewrite/java/ChangeAnnotationAttributeName.java
- rewrite-java/src/test/java/org/openrewrite/java/ChangeAnnotationAttributeNameTest.java
The `ChangeAnnotationAttributeName` recipe supports renaming annotation attributes (like `@Foo(x = "y")`). If the attribute name is `value` it's possible to not write an assignment and just write the value (like `Bar("z")`), and this case was not handled previously.
This change adds the following (validated by new tests):
- support for renaming implicit value attributes (`Bar("z")` to `Bar(foo = "z")`)
- support for expanding implicit value attributes (`Bar("z")` to `Bar(value = "z")`)
- ensures the tree is unchanged for an identical rename (`@Foo(x = "y")` to `@Foo(x = "y")`)
Noticed this comment: https://github.com/openrewrite/rewrite-openapi/issues/1#issuecomment-1877633407
How I created the `J.Assignment`, I hacked it to get what I wanted, but there might be a better way. Should there …
> Supporting changing name of implicit `value` attributes in ChangeAnnotationAttributeName

- rewrite-java/src/main/java/org/openrewrite/java/RemoveAnnotationAttribute.java
- rewrite-java/src/test/java/org/openrewrite/java/RemoveAnnotationAttributeTest.java
New recipe for removing annotation attributes by name
This is needed for https://github.com/openrewrite/rewrite-openapi/issues/1
How to format attributes to avoid unwanted whitespace.
@timtebeek 
Opted for not changing `ChangeAnnotationAttributeName` since a dedicated recipe is more discoverable.
> Add `RemoveAnnotationAttribute` recipe

- rewrite-java-test/src/test/java/org/openrewrite/java/RemoveImportTest.java
- rewrite-java/src/main/java/org/openrewrite/java/RemoveImport.java
If the removed import was a static import and was followed by a separating blank line, that blank line would be collapsed. Also if the removed import was followed by a comment, that comment would be lost.
This commit addresses these two issues by:
- not overwriting the prefix spacing if it'd remove whitespace
- only copy whitespace from removed import, don't overwrite comments
> Preserve space and comments after import in RemoveImport

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java
- rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitor.java
As discovered on 
- https://github.com/openrewrite/rewrite-static-analysis/pull/231
```diff
SimplifyTernaryTest > test() FAILED
org.opentest4j.AssertionFailedError: [Unexpected result in "Test.java":
diff --git a/Test.java b/Test.java
index acd7493..f59a06e 100644
--- a/Test.java
+++ b/Test.java
@@ -16,8 +16,8 @@
boolean unchanged1 = booleanExpression() ? booleanExpression() : !booleanExpression();
boolean unchanged2 = booleanExpression() ? true : !booleanExpression();
boolean unchanged3 = booleanExpression() ? booleanExpression() : false;
-    boolean unchanged4 = booleanExpression() && booleanExpression() ? true : false;
-    boolean unchanged5 = booleanExpression() && booleanExpression() ? false : true;
+    boolean unchanged4 = booleanExpression();
+    boolean unchanged5 = …
```
> Do not simplify two identical method calls

- rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesTest.java
- rewrite-java/src/main/java/org/openrewrite/java/UnwrapParentheses.java
As spotted in failure on `main` of rewrite-migrate-java in
- https://github.com/openrewrite/rewrite-migrate-java/pull/387
> Do not unwrap parentheses around negated ternary

- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeMapping.java
- rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeSignatureBuilder.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java
- rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeSignatureBuilder.java
- rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
- rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeMapping.java
- rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeSignatureBuilder.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java
- rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeSignatureBuilder.java
- rewrite-java-tck/src/main/java/org/openrewrite/java/tree/NewClassTest.java
- rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
When the target type of a constructor call declares generic type variables, the `J.NewClass` type attribution should also include these details. So for example the type attribution for `new ArrayList<String>()` should be a `JavaType.Method` which as the declaring type has `java.util.ArrayList<String>` rather than just `java.util.ArrayList`.
> Constructor call type attribution should include generics

- rewrite-core/src/main/java/org/openrewrite/internal/NameCaseConvention.java
- rewrite-core/src/test/java/org/openrewrite/internal/NameCaseConventionTest.java
`LOWER_CAMEL` and `UPPER_CAMEL` can now handle uppercase abbreviation better 
AS-IS 
```
-      PdfDocumentViewModel PDFviewModel = new PdfDocumentViewModel(mockPDF);
+      PdfDocumentViewModel pDFviewModel = new PdfDocumentViewModel(mockPDF);
```
TO-BE(`LOWER_CAMEL`)  
```
-      PdfDocumentViewModel PDFviewModel = new PdfDocumentViewModel(mockPDF);
+      PdfDocumentViewModel pdfViewModel = new PdfDocumentViewModel(mockPdf);
```
https://github.com/openrewrite/rewrite/issues/3333
@koppor
[Issue](https://github.com/openrewrite/rewrite/issues/3333#issuecomment-1888128281)
> Fix LOWER_CAMEL, UPPER_CAMEL to handle uppercase abbreviation better

- rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
- rewrite-maven/src/main/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactId.java
- rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
- rewrite-maven/src/test/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactIdTest.java
ChangeDependencyGroupIdAndArtifactId and ChangeManagedDependencyGroupIdAndArtifactId are intended to be set up to *change* maven coordinates. If the pre- and post-coordinates are the same, it's likely that the UpgradeDependencyVersion recipe was intended. This change adds validation of the newGroupId/newArtifactId options.
See https://github.com/openrewrite/rewrite-java-dependencies/issues/55
That the use of `Validated` is correct.
@timtebeek
> Validate that Change(Managed)DependencyGroupIdAndArtifactId updates GAV

- rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
- rewrite-java/src/main/java/org/openrewrite/java/internal/TypesInUse.java
Introduced in 9d264b4f4991b62854572c5e576e2ab0514361d5
Fixes: #3909
> Fix `TypesInUse` regression

- rewrite-java-test/src/test/java/org/openrewrite/java/recipes/MissingOptionExampleTest.java
- rewrite-java/src/main/java/org/openrewrite/java/recipes/MissingOptionExample.java
As came up in Slack: https://github.com/openrewrite/gh-automation/issues/45#issuecomment-1891827588
> Find `@Option` annotations without `example` values

- rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
When downloading Maven metadata the `AddDependencyVisitor` should not configure any default repos and must therefore use the `MavenPomDownloader(ExecutionContext)` constructor.
> Gradle `AddDependencyVisitor` should not use default Maven repos

- rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java
- rewrite-xml/src/main/java/org/openrewrite/xml/ChangeTagAttribute.java
- rewrite-xml/src/test/java/org/openrewrite/xml/ChangeTagAttributeTest.java
Allow the usage of regular expressions on `ChangeTagAttribute`
Replace namespaces/namespaces URIs on `schemaLocation`.
No
No
No
No
> Allow regular expressions on `ChangeTagAttribute`

- rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependency.java
- rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java
Added same validation for Gradle `ChangeDependency` as was done for the Maven equivalent via https://github.com/openrewrite/rewrite/pull/3889.
I did go ahead and clean up the descriptions a little bit more, so now I think they overall are a bit clearer in terms of intent.
N/A
- https://github.com/openrewrite/rewrite/pull/3889
- https://github.com/openrewrite/rewrite/commit/82d57a4c24c5998a7db2e8e564ca038d7e214317
> Perform same newGroupId and newArtifactId validations for Gradle ChangeDependency recipe

- rewrite-maven/src/main/java/org/openrewrite/maven/tree/Plugin.java
- rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Mark `JsonNode configuration` as `@Nullable`, and make cascading null safety changes.
MavenParser leaves the field as null when not provided.
> Plugin configuration can be null

- rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
Tests for the `XPathMatcher` enhancement mentioned on #3919.
Provide test scenarios for 
- #3919
Just providing disabled test cases
No
No
No
> Tests for XPathMatcher #3919

- rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
- rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
This could be useful when loading a Maven pom.xml only to iterate over its properties, plugins, etc.
> `MavenParser` allows skipping dependency resolution

- rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
Since a `ResolvedGroupArtifactVersion` is expected to have non-`null` values for `groupId` and `version`, the `RawPom#toPom()` method now also enforces this and throws an exception when `null` values are present. This in turn makes the parser as a whole more robust as it will immediately convert this to a `ParseError` rather than failing hard later on.
> Make `MavenParser` stricter

- rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateAnnotationTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateContextFreeTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/JavaVisitorTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/format/MinimumViableSpacingTest.java
- rewrite-java-test/src/test/java/org/openrewrite/java/recipes/SourceSpecTextBlockIndentationTest.java
- rewrite-java/src/test/java/org/openrewrite/java/CreateEmptyJavaClassTest.java
- rewrite-maven/src/main/java/org/openrewrite/maven/AddProfile.java
- rewrite-maven/src/test/java/org/openrewrite/maven/AddProfileTest.java
- rewrite-properties/src/test/java/org/openrewrite/properties/CreatePropertiesFileTest.java
- rewrite-test/src/main/java/org/openrewrite/test/LargeSourceSetCheckingExpectedCycles.java
- rewrite-xml/src/test/java/org/openrewrite/xml/ChangeNamespaceValueTest.java
- rewrite-xml/src/test/java/org/openrewrite/xml/ChangeTagAttributeTest.java
- rewrite-xml/src/test/java/org/openrewrite/xml/CreateXmlFileTest.java
- rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
There appear to be quite a few more recipes which make additional invisible changes in the second cycle. As a quick fix this commit adds `expectedCyclesThatMakeChanges(2)` to these tests so they pass.
> Fix another bug in `LargeSourceSetCheckingExpectedCycles`

- rewrite-gradle/src/main/java/org/openrewrite/gradle/IsBuildGradle.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/IsSettingsGradle.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
- rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/UpgradePluginVersionTest.java
Changing the `UpgradePluginVersion` recipe from a Recipe to a ScanningRecipe so that we can match plugin version variables with anything declared in a `gradle.properties` file
@timtebeek @shanman190 who are aware of the context behind this and the similar improvements that were made to `UpgradeDependencyVersion`
> Adding support for plugin versions in gradle.properties file

- rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java
- rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/UpgradePluginVersionTest.java
Change the gradle plugin property resolver to ignore unresolved versions instead of setting them - this mirrors what the groovy resolver does. This solves a problem whereby glob versions like "5.40.X" were getting set incorrectly.
@timtebeek @shanman190
> Upgrade plugin versions in gradle.properties
