openrewrite/rewrite

rewrite-java/src/main/java/org/openrewrite/java/ReorderMethodArguments.java, rewrite-test/src/main/kotlin/org/openrewrite/java/AddImportTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeFieldNameTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeFieldTypeTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeLiteralTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeMethodNameTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeMethodTargetToStaticTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeMethodTargetToVariableTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeTypeTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/DeleteMethodArgumentTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/DeleteStatementTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/GenerateConstructorUsingFieldsTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/ImplementInterfaceTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/InsertMethodArgumentTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/OrderImportTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveImportTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/RenameVariableTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/ReorderMethodArgumentsTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/UnwrapParenthesesTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/UseStaticImportTest.kt
Update tests for visitors to take advantage of RefactorVisitorTest
Closes #26
=> Update tests for visitors to take advantage of RefactorVisitorTestResolved conflicts

rewrite-maven/src/main/java/org/openrewrite/maven/MavenModuleLoader.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/AddDependencyTest.kt, rewrite-maven/src/test/kotlin/org/openrewrite/maven/ChangeDependencyScopeTest.kt, rewrite-maven/src/test/kotlin/org/openrewrite/maven/ChangeDependencyVersionTest.kt, rewrite-maven/src/test/kotlin/org/openrewrite/maven/ChangeParentVersionTest.kt, rewrite-maven/src/test/kotlin/org/openrewrite/maven/ChangePropertyValueTest.kt, rewrite-xml/src/test/kotlin/org/openrewrite/xml/AddToTagTest.kt, rewrite-xml/src/test/kotlin/org/openrewrite/xml/ChangeTagValueTest.kt, rewrite-xml/src/test/kotlin/org/openrewrite/xml/XPathMatcherTest.kt, rewrite-xml/src/test/kotlin/org/openrewrite/xml/XmlParserTest.kt, rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangePropertyKeyTest.kt, rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/CoalescePropertiesTest.kt
Updated the tests in the maven, xml, yaml, properties modules to fit the RefactorVisitorTest pattern
Closes #30
=> Refactored Maven, XML and YAML test files to RefactorVisitorTest pattern

rewrite-maven/build.gradle.kts, rewrite-maven/src/main/java/org/openrewrite/maven/MavenModuleLoader.java, rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/ParentModelResolver.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/MavenParserTest.kt
This should get basics of repositories defined in settings.xml working, at least for the sample settings.xml we have. 
I haven't tried it on an authenticated repository yet.
=> Load Maven repositories defined in settings.xml

rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
=> Fix null check

rewrite-java/src/main/java/org/openrewrite/java/AddAnnotation.java, rewrite-java/src/main/java/org/openrewrite/java/AutoFormat.java, rewrite-test/src/main/kotlin/org/openrewrite/java/AddAnnotationTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/tree/AutoFormatTest.kt
Fixed multiple irregular formatting issues as described in issue #64. 
Closed #64
=> Debugging auto format

rewrite-java/src/main/java/org/openrewrite/java/JavaSourceVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/tree/MethodTypeBuilder.java, rewrite-java/src/main/java/org/openrewrite/java/tree/TreeBuilder.java, rewrite-test/src/main/kotlin/org/openrewrite/java/tree/TreeBuilderTest.kt
Adding some cleanup and tests to buildSnippet
=> Build snippet usability

rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
=> Fixing TypeUtils.isString()

rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/ShiftFormatLeftProcessor.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlProcessor.java
part of: https://github.com/openrewrite/rewrite/issues/142
Cleanup todo's leftover from previous PRs
=> Tidy 7x rewrite-yaml comments

rewrite-maven/build.gradle.kts, rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenDownloader.java
Curious for someone with resilience4j experience to review. This passes our existing tests, but obviously none of our existing tests required retries to pass.
=> Add retries to MavenDownloader

rewrite-core/src/main/java/org/openrewrite/Recipe.java, rewrite-core/src/main/java/org/openrewrite/marker/Markers.java, rewrite-core/src/main/java/org/openrewrite/marker/SearchResult.java, rewrite-core/src/main/java/org/openrewrite/style/NamedStyles.java, rewrite-core/src/test/java/org/openrewrite/marker/MarkersTest.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Modules.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java
=> prevent adding duplicate markers, using object equality

rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/internal/JavaPrinter.java, rewrite-java/src/main/java/org/openrewrite/java/tree/Coordinates.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JContainer.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JRightPadded.java, rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
coordinates scoped to those relevant to known use cases
=> Coordinates, 2nd half

rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/SimplifyBooleanReturnTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/UnnecessaryParenthesesTest.kt
polish on https://github.com/openrewrite/rewrite/pull/217 and https://github.com/openrewrite/rewrite/pull/204
=> Polish on test body indentation

rewrite-java/src/main/java/org/openrewrite/java/cleanup/CovariantEqualsVisitor.java
continuation from https://github.com/openrewrite/rewrite/pull/244
see also https://github.com/openrewrite/rewrite/issues/251
=> Prepend new Statements to Method Body using before() coordinates

rewrite-java/src/main/java/org/openrewrite/java/cleanup/CovariantEqualsVisitor.java
small detail but wanted to put it in use
see also: https://github.com/openrewrite/rewrite/commit/535eadfa092b1e7b5fd043489334807969e6e620
see also: https://github.com/openrewrite/rewrite/issues/258
originally part of https://github.com/openrewrite/rewrite/pull/244
=> CovariantEquals to use addAnnotation coordinates

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/HideUtilityClassConstructor.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/HideUtilityClassConstructorVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/HideUtilityClassConstructorTest.kt
part of #197
see also: https://github.com/openrewrite/rewrite-checkstyle/blob/master/src/main/java/org/openrewrite/checkstyle/HideUtilityClassConstructor.java
=> HideUtilityClassConstructor

rewrite-core/src/main/java/org/openrewrite/HiddenRecipe.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyVersion.java, rewrite-maven/src/main/java/org/openrewrite/maven/RemoveProperty.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/ChangeDependencyVersionAddsVersionTag.kt, rewrite-maven/src/test/kotlin/org/openrewrite/maven/RemoveProperty.kt
New RemoveProperty for removing maven properties
Update ChangeDependency to add version tag when the transitive dependency has been removed
Add license to HiddenRecipe
=> Add Maven Remove Property and update ChangeDepency

rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt
=> Fixing navigation of annotations on ClassDeclation kind

rewrite-test/src/main/kotlin/org/openrewrite/java/MethodMatcherTest.kt
Per the [`MethodMatcher` documentation](https://github.com/openrewrite/rewrite/blob/a1b50b8a3cb79efc77bd8c298b64abbb52e1e43a/rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java#L53), the following syntax should match any `foo` method on any class: `* foo(..)`.
If the class is not in a package, it correctly matches:
```
class A {
void foo() {}
}
```
If the class is in a package (any package), it fails to match:
```
package a;
class A {
void foo() {}
}
```
Related to #383
=> Added unit tests for a bug in MethodMatcher

rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
A parser is now seeded with the runtime classpath as a default.
=> Default parser uses runtime class path

rewrite-java/src/main/java/org/openrewrite/java/format/WrappingAndBracesVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/format/WrappingAndBracesTest.kt
fixes #375 
Adds a condition to check for comments prior to adding a new line.
=> Refactor WrappingAndBraces to retain trailing comments.

rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveUnusedImportsTest.kt
Demonstrates the issue in #429
=> Add failing and disabled unit test for RemoveUnusedImports

rewrite-java-11/src/main/java/org/openrewrite/java/Java11ParserVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java, rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java, rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveUnusedImportsTest.kt
Add Annotations to J.Package and update RemoveUnusedImports accordingly.  Fixes #429
=> Add Annotations to J.Package and update RemoveUnusedImports

rewrite-maven/src/main/java/org/openrewrite/maven/cache/RocksdbMavenPomCache.java
RocksdbMavenPomCache - Delete cached values when exceptions are thrown during deserialization
=> RocksdbMavenPomCache - Delete non-deserializable cache values

.idea/compiler.xml, rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11TreeDebugTests.kt, rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java/src/main/java/org/openrewrite/java/search/HasTypes.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTreeCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt
Some tests were not running as part of our integration build add the missing test and some comments to remind devs to put their tests in both the compatibility kits and the debug testing classes.
=> Fixing tests

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11TreeDebugTests.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/PrimitiveWrapperClassConstructorToValueOf.java, rewrite-java/src/main/resources/META-INF/rewrite/cleanup.yml, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/PrimitiveWrapperClassConstructorToValueOfTest.kt
Cleanup recipe for Converting Primitive Wrapper Class Constructors to valueOf. Fixes #473
=> Cleanup recipe for Converting Primitive Wrapper Class Constructors to valueOf

rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java, rewrite-test/src/main/kotlin/org/openrewrite/java/RenameVariableTest.kt
=> Added a condition to RenameVariable to prevent renaming constant values.

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/DefaultComesLast.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/DefaultComesLastStyle.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/DefaultComesLastVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/DefaultComesLastTest.kt
https://github.com/openrewrite/rewrite/issues/197
Cleanup recipe for having the last `case` in a `switch` be `default`.
=> DefaultComesLast

rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenArtifactHelper.java
**Before the fix**: Multiple repos could be passed to `MavenArtifactHelper.downloadArtifactAndDependencies`, but only the first one would ever be used. This could lead to a null pointer when getting the first (null) element off of the artifact classpath.
**After the fix**: The repos are queried, in order, until an artifact is found. If no artifact is found, an `UncheckedIOException` is thrown.
=> fix: Search repos in order in MavenArtifactHelper

rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizeLocalVariablesVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/FinalizeLocalVariablesTest.kt
https://github.com/openrewrite/rewrite/issues/549
=> Do not add final modifier to catch blocks

rewrite-java-11/src/main/java/org/openrewrite/java/Java11ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java, rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavaTypeSerializerTest.kt
This PR adds JavaType.WildCard to rewrite's type system
=> Adding wildcard types

rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java, rewrite-test/src/main/kotlin/org/openrewrite/java/MethodMatcherTest.kt
=> fixes #383 add full wildcard support to method matcher.

rewrite-maven/src/test/kotlin/org/openrewrite/maven/UpgradeDependencyVersionTest.kt
test for https://github.com/openrewrite/rewrite/issues/565
=> Test for resolving groupId and artifactId from properties [#565]

rewrite-maven/src/main/java/org/openrewrite/maven/RemovePlugin.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/RemovePluginTest.kt
fixes https://github.com/openrewrite/rewrite/issues/584
for downstream consumption of https://github.com/openrewrite/rewrite-quarkus/issues/16
=> `RemovePlugin` -- ability to remove maven plugins from maven pom

rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/UpgradeDependencyVersionTest.kt
Added a check for property values if the groupId or artifactId fail to find a match.
=> Added property resolution to maven visitor.

rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java, rewrite-core/src/main/java/org/openrewrite/config/Environment.java
Allow more fine-grained control over class-loading in Environment.scan
by allowing the user to provide a custom ClassLoader
=> feat: Allow passing in ClassLoader into Environment

rewrite-core/src/main/java/org/openrewrite/config/CategoryDescriptor.java, rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java, rewrite-core/src/main/java/org/openrewrite/config/Environment.java, rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java, rewrite-java/src/main/resources/META-INF/rewrite/java-categories.yml
=> Category descriptors

rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeFieldNameTest.kt
test demonstrating https://github.com/openrewrite/rewrite/issues/632 + slight changes to the test setup necessary to demonstrate the issue
=> Test demonstrating ChangeFieldName not changing statically imported names

rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
PR for https://github.com/openrewrite/rewrite/issues/636
(what a title)
=> ContinuationIndents applied to method selects when used as method invocation arguments

rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
tests for https://github.com/openrewrite/rewrite/issues/660
=> Test to demonstrate continuation indent when method block has closing bracket on its own line

rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
=> Applies formatting to single line comments in TabsAndIndentVisitor

rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenArtifactHelper.java
Previously you could only download an artifact and its dependencies.
With this change, you can now download the artifact itself without any
of its dependencies. This is useful for determining if there is a new
snapshotted version of a library.
=> feat: Add ability to download a specific artifact

rewrite-java/src/main/java/org/openrewrite/java/format/TabsAndIndentsVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/format/TabsAndIndentsTest.kt
Added formatting of whitespace in block comments that is based on the style. fixes #677
=> Added conditions to normalize whitespace in block comments. fixes #677

rewrite-properties/src/main/java/org/openrewrite/properties/ChangePropertyKey.java, rewrite-properties/src/main/java/org/openrewrite/properties/ChangePropertyValue.java, rewrite-properties/src/test/kotlin/org/openrewrite/properties/ChangePropertyKeyTest.kt, rewrite-properties/src/test/kotlin/org/openrewrite/properties/ChangePropertyValueTest.kt
=> Optional fileMatcher option for properties recipe

rewrite-maven/src/integTest/kotlin/org/openrewrite/maven/ParentModelResolver.java
Co-authored-by: Moderne <team@moderne.io>
😉
=> refactor: parameterize slf4j logging statements

rewrite-maven/src/test/kotlin/org/openrewrite/maven/UpgradeDependencyVersionTest.kt
test for https://github.com/openrewrite/rewrite/issues/739
=> test upgradeVersionWithGroupIdAndArtifactIdDefinedAsProperty

rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
Adjusted minimumFoldedImports to use maximum count detected instead of minimum. fixes #746.
=> Slight adjustment to importLayoutStatistics heuristics

rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java, rewrite-test/src/main/kotlin/org/openrewrite/java/AddImportTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/RemoveUnusedImportsTest.kt
fixes #776
- Removed disabled from a test in RemovedUnusedImports that works now
- Refactored the for loop control that sets starFoldFrom.
=> Adjusted for loop control in ImportLayoutStyle#addImport.

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/IndexOfShouldNotCompareGreaterThanZero.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/IndexOfShouldNotCompareGreaterThanZeroTest.kt
PR closes https://github.com/openrewrite/rewrite/issues/799
=> indexOf should not compare greater than zero [#799]

rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java, rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt
This PR tries to fix the issue https://github.com/openrewrite/rewrite/issues/847. The Checkstyle modules are group by their name and instead of using a single module per name, now it's accepted more than one.
=> Fixing duplicated Checkstyle modules.

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnusedAssignments.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedAssignmentsTest.kt
see: https://github.com/openrewrite/rewrite/issues/821
=> Remove unused assignments

rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnusedLocalVariables.java, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedLocalVariablesTest.kt
see: #828
- Generally cleaner approach to lhs vs. rhs. There's room for improvement even still, but, will iterate.
- Considers assignments within control contexts, e.g. `while()`, to be significant when evaluating reads.
=> UnusedLocalVariable improvements on evaluating left-hand vs right-hand read operations

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/NeedBraces.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/NeedBracesStyle.java, rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java, rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java, rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/NeedBracesTest.kt
See https://github.com/openrewrite/rewrite/issues/797
=> [#797] need braces

rewrite-java/src/main/java/org/openrewrite/java/OrderImports.java, rewrite-java/src/main/java/org/openrewrite/java/marker/JavaProvenance.java, rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java, rewrite-test/src/main/kotlin/org/openrewrite/java/OrderImportsTest.kt
- Get classpath info from JavaProvenance in OrderImports.
- Prevent import folding if it will cause a namespace conflict.
fixes #860.
=> Prevent import folding if it creates a namespace conflict.

rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawMavenResolver.java
```xml
<project>
<properties>
<packaging>jar</packaging>
</properties>
<packaging>${packaging}</packaging>
</project>
```
=> Update RawMavenResolver to handle case where `packaging` value is a property value

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/OperatorWrap.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/OperatorWrapStyle.java, rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java, rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java, rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/OperatorWrapTest.kt
See: https://github.com/openrewrite/rewrite/issues/797
=> [#797] OperatorWrap

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoWhitespaceAfter.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoWhitespaceAfterStyle.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoWhitespaceBefore.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoWhitespaceBeforeStyle.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/OperatorWrap.java, rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java, rewrite-java/src/main/java/org/openrewrite/java/style/CheckstyleConfigLoader.java, rewrite-java/src/test/kotlin/org/openrewrite/java/style/CheckstyleConfigLoaderTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/NoWhitespaceAfterTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/NoWhitespaceBeforeTest.kt
See: #797
- NoWhitespaceBefore
- NoWhitespaceAfter
=> [#797] NoWhitespaceAfter, NoWhitespaceBefore

rewrite-maven/src/main/java/org/openrewrite/maven/AddPlugin.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/AddPluginTest.kt
Fixes #915 
(Perhaps `@Builder` would be a better choice here, if yes, I can rework it with `@Builder`)
=> Support Executions in AddPlugin

rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeTypeTest.kt
Refactored `ChangeType` to take advantage of new capabilities of the framework.
=> Fixing `ChangeType` edge cases

rewrite-hcl/src/main/java/org/openrewrite/hcl/tree/Space.java, rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java, rewrite-json/src/main/java/org/openrewrite/json/tree/Space.java
Fixing a subtle issue that causes extra `Space` instances to be created.
=> Unnecessary space instance creation

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/marker/JavaVersion.java, rewrite-java/src/main/java/org/openrewrite/java/search/UsesJavaVersion.java, rewrite-java/src/test/kotlin/org/openrewrite/java/marker/JavaVersionTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/search/UsesJavaVersionTest.kt
Added UsesJavaVersion visitor.
Added MajorVersion enum to JavaVersion.
fixes #983
=> Added UsesJavaVersion to filter applicability by java version.

rewrite-java/src/main/resources/META-INF/rewrite/static-analysis-cleanup.yml
Often the uncovered through tools like Sonar analysis, for example.
=> feat(java): declarative recipe of common static analysis issues

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/ExplicitLambdaArgumentTypes.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/ExplicitLambdaArgumentTypesTest.kt
Fixes https://github.com/openrewrite/rewrite/issues/982
=> Explicitly declare types on lambda arguments

rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/NeedBraces.java, rewrite-java/src/main/java/org/openrewrite/java/format/EmptyNewlineAtEndOfFile.java, rewrite-maven/src/main/java/org/openrewrite/maven/OrderPomElements.java
Correct estimate for add braces from 15m -> 2m
=> feat(recipes): update and add missing effort estimates per occurance

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/MissingOverrideAnnotation.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/MissingOverrideAnnotationTest.kt
see: https://github.com/openrewrite/rewrite/issues/561
=> Add missing override annotations

rewrite-java/src/main/java/org/openrewrite/java/format/BlankLinesVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/MissingOverrideAnnotationTest.kt
Fixes #1033
Fixup formatting on cases where annotations are added
=> Fixup BlankLinesVisitor equality checking for the first statement of the block

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/ForLoopControlVariablePostfixOperators.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/ForLoopControlVariablePostfixOperatorsTest.kt
Recipe inspired by this article https://inside.java/2021/09/20/javac-tree-api/
=> Use postfix counters on for loop induction variables

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseCollectionInterfaces.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/UseCollectionInterfacesTest.kt
=> Added UseJavaInterface recipe to fix code flagged by RSPEC-1319.

rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.kt
Part of https://github.com/openrewrite/rewrite/issues/1073
ChangeDependencyGroupIdAndArtifactId
=> Change dependency groupId and artifactId

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/marker/InStyleForEachLoop.java, rewrite-groovy/src/test/kotlin/org/openrewrite/groovy/tree/ForLoopTest.kt
Still need to do something about parameter annotations. Open to suggestions
=> GroovyParser for each loop support.

rewrite-java/src/main/java/org/openrewrite/java/format/BlankLinesVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/format/BlankLinesTest.kt
Fixes https://github.com/openrewrite/rewrite/issues/1171
=> BlankLines formatting on nested classes and enums

rewrite-properties/src/main/java/org/openrewrite/properties/internal/PropertiesPrinter.java, rewrite-properties/src/main/java/org/openrewrite/properties/search/FindProperties.java, rewrite-properties/src/test/kotlin/org/openrewrite/properties/search/FindPropertiesTest.kt
Followup to https://github.com/openrewrite/rewrite/pull/1195
=> FindProperties should have marker on the value, same as yaml and other search results

rewrite-java/src/main/java/org/openrewrite/java/cleanup/NoValueOfOnStringType.java, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/NoValueOfOnStringTypeTest.kt
Fixes https://github.com/openrewrite/rewrite/issues/1200
=> NoValueOfOnStringType check for immediate parent being a binary

rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodAccessLevel.java, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeMethodAccessLevelTest.kt
=> ChangeMethodAccessLevel should pass on matchOverrides

rewrite-java-11/src/main/java/org/openrewrite/java/TypeMapping.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableTypeMapping.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTypeTest.kt
=> Resolve type parameters in TypeMapping#signature.

rewrite-java-11/src/main/java/org/openrewrite/java/Java11TypeMapping.java, rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11TypeMappingTest.kt, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java
=> Added a condition to cover when a method selectType is a Type.Unknown.

rewrite-java-11/src/main/java/org/openrewrite/java/Java11TypeMapping.java, rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11TypeMappingTest.kt, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java
=> Use the symbolType#superfield_type in Java 8 and Java 11 TypeMapping

rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnusedLocalVariables.java, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedLocalVariablesTest.kt
Closes https://github.com/openrewrite/rewrite/issues/1332
=> [#1332] Configurable array of ignorable variable names in UnusedLocal Variables

build.gradle.kts, rewrite-java-8/build.gradle.kts, rewrite-maven/build.gradle.kts, rewrite-test/build.gradle.kts
addresses https://github.com/openrewrite/rewrite/runs/4896100027?check_suite_focus=true
=> logback 1.0.x -> 1.2.10

rewrite-java-11/src/main/java/org/openrewrite/java/Java11JavadocVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java, rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
=> Added visitParameterizedType in JavaDocVisitors and JavaDocPrinter.

rewrite-core/src/main/java/org/openrewrite/marker/Range.java, rewrite-java/src/main/java/org/openrewrite/java/UpdateSourcePositions.java, rewrite-test/src/main/kotlin/org/openrewrite/java/UpdateSourcePositionsTest.kt
@jkschneider I figured that i do need the line and column for start and end of a node. Here is my attempt at supporting lines and columns. Didn't try it against Boot LS as I'm still far from making everything compile with JDT replaced with OR.
Feel free to modify this as you like :-)
=> Support Range for AST node with pos including line, column

rewrite-core/src/main/java/org/openrewrite/semver/LatestRelease.java, rewrite-core/src/test/kotlin/org/openrewrite/semver/LatestReleaseTest.kt, rewrite-maven/src/test/kotlin/org/openrewrite/maven/UpgradeDependencyVersionTest.kt
=> #1334 Match versionPattern when explicitly set blank

rewrite-java-11/src/main/java/org/openrewrite/java/Java11JavadocVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
=> Increment cursor position in `JavadocVisitors#whitespaceBefore()`.

rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
- Grouped and sorted the java doc tests.
- Added comments to groupings.
=> Organize and group the java doc tests

rewrite-json/src/main/java/org/openrewrite/json/JsonPathMatcher.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java, rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/JsonPathMatcherTest.kt
=> Prevent infinite recursion in JsonPathMatcher.

rewrite-maven/build.gradle.kts
=> added `-parameters` to rewrite-maven `build.gradle.kts`.

rewrite-maven/src/main/java/org/openrewrite/maven/search/DependencyInsight.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/search/DependencyInsightTest.kt
=> Added condition to filter by the provided scope in DependencyInsight.

rewrite-maven/src/main/java/org/openrewrite/maven/AddManagedDependency.java
See issue [#1448](https://github.com/openrewrite/rewrite/issues/1448)
=> AddManagedDependency: Allow wildcard only match on artifact

rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
=> Support ChangePackage recursive subpackages visit

rewrite-maven/src/main/java/org/openrewrite/maven/RemoveExclusion.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/RemoveExclusionTest.kt
Hi there,
Experimenting with OpenRewrite in Quarkus and this is something we would need.
Thanks for taking it into consideration.
=> Also consider dependencyManagement when removing exclusions

rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java, rewrite-maven/src/main/java/org/openrewrite/maven/ExcludeDependency.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedDependency.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.kt
Ensure the maven model is updated when either adding exclusions or changing the groupId/artifactId
=> Update model when modifying dependencies fixes #1500

rewrite-core/build.gradle.kts, rewrite-core/src/main/java/org/openrewrite/ipc/http/HttpSender.java, rewrite-core/src/main/java/org/openrewrite/ipc/http/HttpStatusClass.java, rewrite-core/src/main/java/org/openrewrite/ipc/http/HttpUrlConnectionSender.java, rewrite-core/src/main/java/org/openrewrite/ipc/http/OkHttpSender.java, rewrite-maven/build.gradle.kts, rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java, rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenArtifactDownloader.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/MavenParserTest.kt
=> Add HttpSender interface to decouple rewrite-maven from OkHttp

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/kotlin/org/openrewrite/groovy/tree/AssignmentTest.kt, rewrite-groovy/src/test/kotlin/org/openrewrite/groovy/tree/UnaryTest.kt
Changes:
- unary plus (`def a = +5`) operators will be included in the AST.
fixes #1522
=> Fixed unary plus operator in GroovyParserVisitor.

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/G.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/GLeftPadded.java, rewrite-groovy/src/test/kotlin/org/openrewrite/groovy/tree/BinaryTest.kt, rewrite-java/src/main/java/org/openrewrite/java/tree/JLeftPadded.java
Changes:
- Added support for Groovy's find and match operators.
- Added `G.Binary.Type` which may be expanded to support other Groovy-specific operations.
fixes #1531
=> Added Groovy's find and match operators.

rewrite-core/src/main/java/org/openrewrite/Parser.java, rewrite-core/src/main/java/org/openrewrite/Result.java, rewrite-core/src/test/kotlin/org/openrewrite/ResultTest.kt, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java, rewrite-groovy/src/test/kotlin/org/openrewrite/groovy/GroovyTypeSignatureBuilderTest.java, rewrite-java-11/src/test/java/org/openrewrite/java/Java11TypeSignatureBuilderTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java, rewrite-maven/src/integTest/kotlin/org/openrewrite/maven/ParentModelResolver.java, rewrite-test/src/main/java/org/openrewrite/MetricsDestinations.java, rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java, rewrite-test/src/main/kotlin/org/openrewrite/java/NoWhitespaceBeforeTest.kt
=> Consistent use of UTF-8

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
=> Added type cache to gradle parser builder.

rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveUnusedLocalVariables.java, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RemoveUnusedLocalVariablesTest.kt
=> Fix RemoveUnusedLocalVariables when Initalizer Side Effects

rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyArtifactId.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyGroupId.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyVersion.java
Refactors some code to use the common `ChangeStringLiteral.withStringValue` method.
=> Unify logic to ChangeStringLiteral

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/RenameExceptionInEmptyCatch.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/RenameExceptionInEmptyCatchTest.kt
Changes:
- Added `RenameExceptionInEmptyCatch` recipe.
fixes #1601
=> Added `RenameExceptionInEmptyCatch` recipe.

rewrite-java/src/main/java/org/openrewrite/java/marker/JavaSourceSet.java, rewrite-test/build.gradle.kts, rewrite-test/src/main/kotlin/org/openrewrite/java/marker/JavaSourceSetTest.kt
Changes:
- Updated `JavaSourceSet` to detect and type attribute shaded jars.
fixes #1677
=> Fix IOB in JavaSourceSet from shaded jars.

rewrite-core/src/main/java/org/openrewrite/internal/EncodingDetectingInputStream.java, rewrite-core/src/test/java/org/openrewrite/internal/EncodingDetectingInputStreamTest.java, rewrite-test/src/test/java/EncodingTest.java
Changes:
- Updated the encoding detection to be more accurate.
=> Updated encoding detection.

rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java, rewrite-maven/src/main/java/org/openrewrite/maven/MavenSettings.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenXmlMapper.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawRepository.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Plugin.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Profile.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenArtifactDownloader.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/MavenSettingsTest.kt, rewrite-maven/src/test/kotlin/org/openrewrite/maven/internal/RawMavenTest.kt, rewrite-maven/src/test/kotlin/org/openrewrite/maven/internal/RawPomTest.kt
The supports the reading of the plugin information from XML into the RawPom and Pom model.
=> Add plugin model to RawPom and Pom

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReference.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReferenceTest.kt
Changes:
- Added new recipe `ReplaceLambdaWithMethodReference`.
fixes #1546
=> Added recipe `ReplaceLambdaWithMethodReference`.

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/internal/YamlPrinter.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/tree/Yaml.java, rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/tree/MappingTest.kt
Changes:
- Added support for flow style mappings
fixes #423
=> Added support for flow style mappings to Yaml.

rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceDuplicateStringLiterals.java, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/ReplaceDuplicateStringLiteralsTest.kt
Changes:
- `ReplaceDuplicateStringLiterals` will apply to `main` sources by default.
- Added option to run `ReplaceDuplicateStringLiterals` on `test`.
fixes #1740
=> Defaulted changes from ReplaceDuplicateStringLiterals to main source set.

rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodNameCasing.java, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/MethodNameCasingTest.kt
Changes:
- `MethodNameCasing` will apply to `main` sources by default.
- Added option to run `MethodNameCasing` on `test`.
fixes #1741
=> Defaulted changes from MethodNameCasing to main source set.

rewrite-java-11/src/test/kotlin/org/openrewrite/java/Java11VisitorDebugTests.kt, rewrite-java-8/src/test/kotlin/org/openrewrite/java/Java8VisitorDebugTest.kt, rewrite-java/src/main/java/org/openrewrite/java/dataflow/analysis/ForwardFlow.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/dataflow/FindLocalFlowPathsNumericTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/dataflow/FindLocalFlowPathsStringTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/search/UriCreatedWithHttpSchemeTest.kt
Most of these new tests currently fail, but should pass.
=> Add a variety of dataflow analysis tests

rewrite-maven/src/main/java/org/openrewrite/maven/AddCommentToMavenDependency.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/AddCommentToMavenDependencyTest.kt
=> Added AddCommentToTagTest recipe.

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyTypeMapping.java, rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeMapping.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java, rewrite-java/src/main/java/org/openrewrite/java/JavaTypeVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/UnsafeJavaTypeVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/internal/JavaReflectionTypeMapping.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java, rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java, rewrite-java/src/test/kotlin/org/openrewrite/java/internal/JavaReflectionTypeMappingTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaParserTypeMappingTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTypeMappingTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/tree/TypeUtilsTest.kt
Changes:
- Added type parameters to `JavaType.Class`.
fixes #1782
=> Detect method overrides of parameterized types with generic bounds.

rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyClassifier.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/ChangeDependencyClassifierTest.kt
Recipe for modifying dependency classifier node.
=> Change dependency classifier recipe

rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java, rewrite-test/src/main/kotlin/org/openrewrite/java/search/SemanticallyEqualTest.kt
Changes:
- Added `areSemanticallyEqual` to `SemanticallyEqual`. `areSemanticallyEqual` includes additional support for method invocations and new class constructors to compare the `methodType` instead of the type of each parameter. I.E. void foo(Object obj) {} invoked with `java.lang.String` or `java.lang.Integer` will return true.
fixes #1899
=> Added support to check for semantic equivalence of method invocations in `SemanticallyEqual`

rewrite-java/src/main/java/org/openrewrite/java/RenameClass.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/RenameClassTest.kt
=> Added `RenameClass` recipe.

rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangePackageTest.kt
=> Update applicable prefixes when necessary in ChangePackage.

rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyConstantIfBranchExecution.java, rewrite-test/src/main/kotlin/org/openrewrite/java/cleanup/SimplifyConstantIfBranchExecutionTest.kt
Fixes https://github.com/openrewrite/rewrite-java-security/issues/34
=> Fix simplify if branch execution when jumps are present

rewrite-java/src/main/java/org/openrewrite/java/search/FindVariableNamesInScope.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaVisitorCompatibilityKit.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/search/FindVariableNamesInScopeTest.kt
Changes:
- Added utility to find names in the scope of a cursor.
fixes #1928
=> Added visitor to find all names in a given cursor scope.

rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeTypeTest.kt
Changes:
- `ChangeType` will change the source path when the class definition is changed.
fixes #1904
=> Added change class definition visitor to `ChangeType.`

rewrite-java/src/main/java/org/openrewrite/java/search/FindMethods.java, rewrite-test/src/main/kotlin/org/openrewrite/java/search/FindMethodsTest.kt
This makes it easier to debug if data flow or taint flow is somehow broken
on the SaaS independent of a higher level recipie.
=> Add ability to visualize DataFlow and Taint Flow with FindMethdods

rewrite-xml/src/main/java/org/openrewrite/xml/ChangeTagName.java, rewrite-xml/src/test/kotlin/org/openrewrite/xml/ChangeTagNameTest.kt
=> Adding XML ChangeTagName recipe

rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java, rewrite-java/src/main/java/org/openrewrite/java/tree/CoordinateBuilder.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java, rewrite-test/src/main/kotlin/org/openrewrite/java/JavaTemplateSubstitutionsTest.kt
Changes:
- Added support to replace ArrayAccess.
- Added support to replace literal.
- Added support to replace binary.
=> Expand java template support

rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java, rewrite-maven/src/test/kotlin/org/openrewrite/maven/RemoveRedundantDependencyVersionsTest.kt
=> Fixed regression on default behavior of RemoveRedundantDependencyVersions

rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java, rewrite-test/src/main/kotlin/org/openrewrite/java/ChangeTypeTest.kt
Changes:
- Added missing JavaTypes to ChangeTypeVisitor#updateType.
- Added visitType to minimize original types in typesInUse.
=> Enhanced JavaType updates in ChangeType

rewrite-yaml/src/test/kotlin/org/openrewrite/yaml/ChangeKeyTest.kt
Added test for relocate property with common infix
=> Added test to relocate the property update with common infix

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/tree/JavadocTest.kt
=> Cast J to NameTree in visitParameterizedType of JavadocVisitors.

rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
Exceptions thrown during applicability tests and `recipe.visit()` were not passed into the error handler defined in the execution context.  This led to different behavior depending on where an exception was thrown.
New Behavior: 
- An exception thrown from an applicability test (that operates over all source files) is passed to the error handler and the recipe will return the original sources.
- An exception thrown from the `recipe.visit()` method is passed to the error handler and the recipe will return the original sources.
=> Better error handling in RecipeScheduler

rewrite-core/src/test/kotlin/org/openrewrite/RecipeSchedulerTest.kt, rewrite-groovy/src/test/kotlin/org/openrewrite/groovy/tree/MethodInvocationTest.kt
- Fix RecipeSchedulerTest
- Fix failing MethodInvocationTest#nullSafeDereference
=> Fix failing tests on `main`

rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java, rewrite-core/src/test/kotlin/org/openrewrite/marker/GitProvenanceTest.kt
The local branch may not be set when using a CI tool. The logic to derive the branch name in the GitProvenance from the remote was incorrect.
This error manifests as a null pointer exception when the following set of commands are run:
```
git init .
git fetch --tags --force --progress -- 'git@github.com:tkvangorder/jmdns.git' '+refs/heads/*:refs/remotes/origin/*' # timeout=10
git config remote.origin.url git@github.com:tkvangorder/jmdns.git
git rev-parse origin/incoming^{commit}
git config core.sparsecheckout
git checkout -f 64f48ab717e0c8022f60d7dcb7f148f47c7f1227
git rev-list --no-walk 64f48ab717e0c8022f60d7dcb7f148f47c7f1227 # timeout=10
mvndebug -B -DpomCacheDirectory=. -Drat.skip=true -Dmaven.findbugs.enable=false -Dspotbugs.skip=true -Dpmd.skip=true -Dcpd.skip=true …
```
=> GitProvenance is not correctly deriving the branch name when a local branch does not exist

rewrite-core/src/main/java/org/openrewrite/marker/DotResult.java, rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlow.java, rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowIllegalStateException.java, rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowJavaPrinter.java, rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowNode.java, rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowVisualizationVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/controlflow/Guard.java
- Fix access modifiers on a few classes
- Make several ControlFlow classes `final`
- Cleanup `ControlFlowJavaPrinter`
=> Minor cleanups to ControlFlow

rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowSummaryDotVisualizer.java, rewrite-test/src/main/kotlin/org/openrewrite/java/controlflow/ControlFlowDotFileViewerTest.kt
- place Start and End nodes of a method at the topmost and bottommost levels of the graph respectively
- use a monospace font for code
- left-align the last line of each statement in a basic block
=> Just some small aesthetic changes to graphviz dot marker

rewrite-test/src/main/kotlin/org/openrewrite/java/controlflow/ControlFlowTest.kt
Related https://github.com/openrewrite/rewrite/issues/2128
=> Add test demonstrating ternary in for each loop issue

rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowDotFileGenerator.java, rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowSummaryDotVisualizer.java, rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowVisualization.java, rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlowVisualizationVisitor.java, rewrite-test/src/main/kotlin/org/openrewrite/java/controlflow/ControlFlowDotFileViewerTest.kt, rewrite-test/src/main/kotlin/org/openrewrite/java/controlflow/ControlFlowTest.kt
- Added a dark mode
- Fixed ControlFlowDotFileViewerTest
=> Control flow dot visualizer dark mode

rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
=> Fix NPE in `JavaType$Method#equals`

rewrite-java-tck/src/main/kotlin/org/openrewrite/java/ImplementInterfaceTest.kt, rewrite-java/src/main/java/org/openrewrite/java/ImplementInterface.java
Hi,
this PR extends the `ImplementInterface` visitor with optional type parameters. We use this extended visitor in a custom recipe to add interfaces to class declarations and I thought it would be a nice addition for the project.
Kind regards
Thomas
=> feat: support type parameters in ImplementInterface visitor

rewrite-core/src/main/java/org/openrewrite/RecipeRunException.java, rewrite-core/src/main/java/org/openrewrite/Tree.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
=> Failure to download metadata during UpgradeDependencyVersion should embed the exception and continue processing the pom file.

rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveGradleDependency.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveGradleDependencyTest.java
This is a follow up for the changes made in #2252
=> Added recipe to remove an existing Gradle dependency

rewrite-java-tck/src/main/kotlin/org/openrewrite/java/cleanup/MethodNameCasingTest.kt, rewrite-java/src/main/java/org/openrewrite/java/cleanup/MethodNameCasing.java
=> Snake case should contain at least one underscore

rewrite-maven/src/main/java/org/openrewrite/maven/AddRepository.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddRepositoryTest.java
The goal is for Boot 3 migration add maven repo to grab Spring Boot 3 snapshots until Boot 3 is released.
=> Add Maven Repository recipe

rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/ChangePropertyKeyTest.java
=> Fix for edge case PatternSyntaxException in Yaml/ChangePropertyKey

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
=> Fixed regression with maven anonymous download

rewrite-java/src/main/java/org/openrewrite/java/ReplaceConstant.java
Java literals can take many forms (e.g. `1_000`, `0b1111`, `0xff`) and the `ReplaceConstant` should support all of them.
=> Make `ReplaceConstant` support full Java literal syntax

rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
=> Fixed issues parsing Maven projects using CI Friendly versions

rewrite-java-tck/src/main/kotlin/org/openrewrite/java/cleanup/NeedBracesTest.kt, rewrite-java-tck/src/main/kotlin/org/openrewrite/java/format/WrappingAndBracesTest.kt, rewrite-java-tck/src/main/kotlin/org/openrewrite/java/style/AutodetectTest.kt, rewrite-java/src/main/java/org/openrewrite/java/format/AutoFormatVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/format/WrappingAndBracesVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java, rewrite-java/src/main/java/org/openrewrite/java/style/IntelliJ.java, rewrite-java/src/main/java/org/openrewrite/java/style/WrappingAndBracesStyle.java
Added auto-detection for WrappingAndBracesStyle#ifStatement.elseOnNewLine. Added auto-formatting support for else on new lines. Updated NeedBracesTest(s) with auto-formatting.
fixes #2440
=> Added IfStatement to WrappingAndBracesStyle.

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
To debug repository normalization, add a nullReasonConsumer and make normalizeRepository public.
=> Make normalizeRepository public

rewrite-maven/src/main/java/org/openrewrite/maven/AddRepository.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddRepositoryTest.java
Adjustments for AddRepository maven recipe.
=> AddRepo recipes adjustments

rewrite-java-tck/src/main/kotlin/org/openrewrite/java/ChangePackageTest.kt, rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Changes:
- Added JavaType#buildType(String, Kind)
- Updated ChangePackageTest to use RewriteTest.
- Updated ChangePackage to use current classes Kind.Class.
fixes #2477
=> Change types with the correct Kind.

rewrite-java-tck/src/main/kotlin/org/openrewrite/java/ChangePackageTest.kt, rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
Fixes https://github.com/openrewrite/rewrite/issues/2439
Redo PR as asked by Tracey on slack
=> ChangePackage: static import enum of same package

rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java, rewrite-properties/src/test/kotlin/org/openrewrite/properties/PropertiesParserTest.kt
=> Added support for `!` to delineate comments.

rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java, rewrite-properties/src/test/kotlin/org/openrewrite/properties/PropertiesParserTest.kt
=> Property comments with multiple delimiters

rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java, rewrite-properties/src/test/kotlin/org/openrewrite/properties/PropertiesParserTest.kt
=> Added support for Property entry delimiters '\s' and ':' to PropertiesParser.

rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ClassDeclarationTest.java
https://docs.oracle.com/en/java/javase/17/language/sealed-classes-and-interfaces.html
=> unit test for sealed interfaces

rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddBuildPlugin.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddSettingsPlugin.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddBuildPluginTest.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddSettingsPluginTest.java
=> Fix a couple of test failures and rename a few parameters found in the

rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddGradleEnterprise.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddSettingsPluginTest.java
=> Add plugin block after pluginManagement.

rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java
=> Allow empty property tags in UpdateMavenModel

rewrite-java/src/main/java/org/openrewrite/java/internal/JavaTypeCache.java
The Snappy compression used in `JavaTypeCache` is typically not able to compress signatures which are shorter than about 50 characters. The compressed representation is often even one or two bytes larger.
Thus this commit aims at slightly optimizing the cache by using the signature String object itself as the cache key in these cases. As a result the cache keys are then around 6 bytes longer (when accounting for String's 24 byte object size vs. BytesKey's 16 bytes), but the whole parsing phase is about 5% faster.
Different thresholds for when to start compressing could make sense in different situations, so maybe this ought to be configurable.
=> Slightly optimizes the `JavaTypeCache`

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceRedundantFormatWithPrintfTest.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceRedundantFormatWithPrintf.java
Still uncertain about whether there's a more reliable way to modify the insides of string literals, but this seems good otherwise.
=> replace redundant println(format()) with printf()

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/RemoveCallsToObjectFinalizeTest.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/RemoveCallsToObjectFinalize.java
=> Add RemoveCallsToObjectFinalize

rewrite-core/src/main/java/org/openrewrite/marker/OperatingSystem.java
https://github.com/moderneinc/moderne-scm/issues/412
=> #412 Added Operating System Marker to Rewrite

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java
=> Use GroovyClassLoader in SourceUnit and CompilationUnit of GroovyParser.

rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRepository.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveRepositoryTest.java
=> Extend remove repository to remove plugin repositories

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/FinalizePrivateFieldsTest.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/FinalizePrivateFields.java
=> Fix issue that private fields that might have been not initialized can not be final

rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReference.java
Removed sys out statement mentioned in #2804
=> No sys out print statements (Cont.)

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UseThreadNotifyAllTest.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseObjectNotifyAll.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseThreadNotifyAll.java
=> Use `Object.notifyAll()` instead of `Object.notify()`

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateSubstitutionsTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/controlflow/ControlFlowTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/controlflow/ControlFlow.java
=> Fix Control Flow Graph Generation for iterable for each

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UseSystemLineSeparatorTest.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/UseSystemLineSeparator.java
=> Replace `System.getProperty("line.separator")` with `System.lineSeparator()`

rewrite-maven/src/test/java/org/openrewrite/maven/AssertionsTest.java, rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
I believe this fixes https://github.com/openrewrite/rewrite/issues/2847
=> Group sourceSpecs by parser class

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReferenceTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
Fixes #2897
See details and root cause at #2897.
=> fix: Fix an error of mismatch statement number generated from JavaTemplate

rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceStringLiteralWithConstantTest.java, rewrite-java/src/main/java/org/openrewrite/java/ReplaceStringLiteralWithConstant.java
=> Added ReplaceStringLiteralWithConstant recipe

rewrite-maven/src/main/java/org/openrewrite/maven/search/DependencyInsight.java, rewrite-maven/src/main/java/org/openrewrite/maven/search/DoesNotIncludeDependency.java, rewrite-maven/src/main/java/org/openrewrite/maven/search/FindDependency.java, rewrite-maven/src/test/java/org/openrewrite/maven/search/DependencyInsightTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/search/DoesNotIncludeDependencyTest.java
=> Added Maven/DoesNotIncludeDependency generic applicability test

rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java, rewrite-core/src/main/java/org/openrewrite/table/SourcesFileResults.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/ReplaceStringBuilderWithString.java
Add estimated time saving to the sourcesFileResult data table.
=> Add estimated time saving to the sourcesFileResult data table

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/java/cleanup/ChangePackageTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
Changes:
- Implemented withPackage in GroovyVisitor.
- Updated ChangePackage to work on J island grammars.
fixes #2986
=> Revise ChangePackage to work on J island grammars.

rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYamlVisitor.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/ChangePropertyKeyTest.java
=> fix: merge new entry into existing mapping (#2881)

.github/workflows/ci-early-access.yml
For potential inclusion in https://wiki.openjdk.org/display/quality/Quality+Outreach
=> Try out 20-ea for now, 21-ea soon

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/ReplaceLambdaWithMethodReferenceTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
This PR is to fix this error from SAAS
=> Fix a template error with Try in a For loop

rewrite-core/src/main/java/org/openrewrite/FindBuildToolFailures.java, rewrite-core/src/test/java/org/openrewrite/FailureLogAnalyzerTest.java
As identified on the archived spring-projects/spring-integration-kafka
=> Possibly downgrade Java when necessary

rewrite-maven/build.gradle.kts, rewrite-maven/src/main/java/org/openrewrite/maven/internal/VersionRequirement.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/VersionRequirementTest.java
=> Handling of missing lower and upper boundaries in version ranges

rewrite-maven/src/test/java/org/openrewrite/maven/MavenSettingsTest.java
=> Use hasSize() for list/collections instead of size().isEqualTo() (#3032)

rewrite-java-test/src/test/java/org/openrewrite/java/UnwrapParenthesesTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/EqualsAvoidsNullTest.java, rewrite-java/src/main/java/org/openrewrite/java/UnwrapParentheses.java
=> #2950 Preserve parentheses around binary operations

rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceConstantWithAnotherConstantTest.java, rewrite-java/src/main/java/org/openrewrite/java/ReplaceConstantWithAnotherConstant.java
=> Added replace constant with another constant recipe.

rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactId.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactIdTest.java
=> Introduce `org.openrewrite.maven.ChangePluginGroupIdAndArtifactId`

README.md
=> Animate the README with a custom OpenRewrite GIF!

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
As per https://github.com/openrewrite/rewrite/issues/1859#issuecomment-1440558482
=> Improve error reporting: do not swallow an error of the first download attempt.

rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/search/DoesNotIncludeDependencyTest.java
Candidate fix for #3088 
Requires thorough review!
=> No scope BOM dependency support

rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/AppendToSequence.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/AppendToSequenceVisitor.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/AppendToSequenceTest.java
this recipe appends a new value to a YAML sequence
=> new YAML recipe: AppendToSequence

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesTest.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesVisitor.java
Needed for https://github.com/openrewrite/rewrite-migrate-java/blob/713e52ae29069ee187ff8abf7d292de17448b31b/src/main/java/org/openrewrite/java/migrate/apache/commons/lang/IsNotEmptyToJdk.java#L78
=> Unwrap when if condition is a single parenthesized expression

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
=> MavenPomDownloader support download snapshot timestamp version

rewrite-java-test/src/test/java/org/openrewrite/java/NoStaticImportTest.java, rewrite-java/src/main/java/org/openrewrite/java/NoStaticImport.java
=> NoStaticImport recipe updates inner calls #3161

CONTRIBUTING.md
While onboarding, I tripped over the "gradle need jdk8" problem and feel like, this something for the contributing guide.
=> CONTRIBUTING.md need JDK8 and gradle remark

rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java, rewrite-core/src/test/java/org/openrewrite/marker/GitProvenanceTest.java
Fixes https://github.com/moderneinc/moderne-cli/issues/319
=> Support git origin URLs that start with org-

rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java
=> ChangePackage skipped on FQCN annotation arguments

rewrite-java-test/src/test/java/org/openrewrite/java/AddLicenseHeaderTest.java
For https://github.com/openrewrite/rewrite/issues/3198
=>  #3198 Javadoc link to array not preserved

rewrite-yaml/build.gradle.kts, rewrite-yaml/src/test/java/org/openrewrite/yaml/AppendToSequenceTest.java
=> AppendToSequence twice skips one

rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java, rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
For https://github.com/openrewrite/rewrite/issues/1753
=> Add sporadically failing multi-module ChangeParentPom tests

rewrite-core/src/main/java/org/openrewrite/FindBuildToolFailures.java, rewrite-core/src/main/java/org/openrewrite/FindParseFailures.java, rewrite-hcl/src/main/java/org/openrewrite/hcl/format/NormalizeFormat.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodTargetToStatic.java, rewrite-java/src/main/java/org/openrewrite/java/UpdateSourcePositions.java, rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeFormat.java, rewrite-maven/src/main/java/org/openrewrite/maven/search/EffectiveMavenRepositories.java, rewrite-xml/src/main/java/org/openrewrite/xml/format/NormalizeFormat.java
For some recipes based on this request:
https://moderneinc.slack.com/archives/C01VADFPJQZ/p1683572711182819
=> Change AST -> LST

rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
For [#3208](https://github.com/openrewrite/rewrite/issues/3208)
=> Gradle Recipe AddDependency without version

rewrite-core/src/main/java/org/openrewrite/internal/ExceptionUtils.java, rewrite-core/src/main/java/org/openrewrite/marker/Markup.java, rewrite-java-test/src/test/java/org/openrewrite/java/RecipeMarkupDemonstrationTest.java
Context: https://github.com/openrewrite/rewrite/pull/3199
=> Fixes serialization issues with Exception#cause

rewrite-core/src/main/java/org/openrewrite/marker/SearchResult.java
=> Add `SearchResults.mergingFound`

rewrite-test/build.gradle.kts
Fixes https://github.com/openrewrite/rewrite/issues/3243
=> Fix NoClassDefFoundError in RewriteTest on jgit diff()

rewrite-xml/src/main/java/org/openrewrite/xml/SemanticallyEqual.java, rewrite-xml/src/test/java/org/openrewrite/xml/SemanticallyEqualTest.java
=> Compare XML tag names for equality

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeFieldNameTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeFieldName.java
Added a failing test in ChangeFieldNameTest
Closes #3257
Not sure if the name of my unit test is okay
Still get myself familiar with AST, probably will have new discovery later
Checklist
=> added a failing test in ChangeFieldNameTest

rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java, rewrite-core/src/test/java/org/openrewrite/table/SourceFileResultsTest.java
This data table wasn't being produced at all. 
I recorded it to match the existing test case, but I'm not sure if this is quite right
=> Fix SourceFileResults data table

rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java, rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java, rewrite-xml/src/main/java/org/openrewrite/xml/format/AutoFormatVisitor.java, rewrite-xml/src/main/java/org/openrewrite/xml/style/Autodetect.java, rewrite-xml/src/test/java/org/openrewrite/xml/format/AutodetectTest.java
Rearrange style autodetection so that it can come before LST serialization
=> Tweak style autodetect

rewrite-java-test/src/test/java/org/openrewrite/java/format/MinimumViableSpacingTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/recipes/MigrateRecipeToRewrite8Test.java, rewrite-java/src/main/java/org/openrewrite/java/format/MinimumViableSpacingVisitor.java
Fixes https://github.com/openrewrite/rewrite/issues/3346
=> Fix AutoFormat issue of extraneous spaces added for annotated return type

rewrite-core/src/main/java/org/openrewrite/Recipe.java, rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
=> Remove Recipe.NOOP

rewrite-java/src/main/java/org/openrewrite/java/OrderImports.java
When I originally looked at this recipe, I was a bit confused on what it does as the description was very generic. I think that providing more information would help people who view this recipe in our docs or in the saas who won't necessarily take the time to dig into the code.
Would appreciate a second pair of eyes to make sure I've summarized this recipe correctly. I largely borrowed from the information [here](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/OrderImports.java#L39-L41).
=> Improve OrderImports description

rewrite-java/src/main/java/org/openrewrite/java/ReplaceStringLiteralWithConstant.java
Prevent from NullPointerException if both literalValue and fullyQualifiedConstantName are null
Fix issue with recipe loading on SaaS
@sambsnyd @kmccarp @jkschneider
=> Fixed nullpointer exception.

rewrite-core/src/main/java/org/openrewrite/config/ClasspathScanningLoader.java
Add a timer to configuring a Recipe when loading it from a recipe jar.
I want to be able to gather information around when scanning a recipe jar is missing recipes.
Nothing specific.
@sambsnyd
This could be a counter if timing causes too much overhead.
N/A
- ~[ ] I've added unit tests to cover both positive and negative cases~
- ~[x] I've added the license header to any new files through `./gradlew licenseFormat`~
- ~[ ] I've used the IntelliJ auto-formatter on affected files~
- No, because it would have modified other parts of the file.
- ~[ ] I've updated the documentation (if applicable)~
=> chore(metrics): Add timer to configuring a recipe

rewrite-json/src/main/java/org/openrewrite/json/ChangeKey.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/AppendToSequence.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangeKey.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyValue.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangeValue.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/CoalesceProperties.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/CommentOutProperty.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/CopyValue.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteKey.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteProperty.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/cleanup/RemoveUnused.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/search/FindKey.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/search/FindProperty.java
I'm working through the recipes trying to make sure that the descriptions and params make sense grammatically and things are spelled correctly. This PR is mostly dedicated to YAML recipes with 1 minor JSON recipe included.
=> Improve recipe descriptions

rewrite-java-test/src/test/java/org/openrewrite/java/recipes/UpdateMovedPackageClassNameTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/recipes/UpdateStaticAnalysisPackageTest.java, rewrite-java/src/main/resources/META-INF/rewrite/migrate-rewrite.yml
Following https://github.com/openrewrite/rewrite/commit/387a405814ae0868d8ff8c9d21510e7f3d88b22a & https://github.com/openrewrite/rewrite-static-analysis/commit/38823f3a21c5c5ec681fc0c7555baeb140fd11dc
=> Migrate moved recipes

rewrite-xml/src/main/java/org/openrewrite/xml/XmlParser.java
Treat .xjb resource files as XML
Migrate JAXB2 to Jakarta JAXB2
No workaround; XJB files are currently parsed as Quarks
=> Add support for JAXB XJB xml files

rewrite-maven/build.gradle.kts, rewrite-maven/src/main/java/org/openrewrite/maven/internal/InsertDependencyComparator.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
Prevent NPE by checking whether the other tag we compare against is null.
Fixes #3458
Pointed out in review comments.
=> Add Maven dependency before only comments in <dependencies>

rewrite-xml/src/main/java/org/openrewrite/xml/ChangeNamespaceValue.java, rewrite-xml/src/test/java/org/openrewrite/xml/ChangeNamespaceValueTest.java
Add ChangeNamespaceValue recipe to recipe-xml.
This recipe was moved from the `rewrite-liberty` recipe on Tim request.
=> Added ChangeNamespaceValue recipe and tests

rewrite-core/src/main/java/org/openrewrite/style/NamedStyles.java, rewrite-java-tck/build.gradle.kts, rewrite-java-test/src/test/java/org/openrewrite/java/EnvironmentTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java, rewrite-java/src/main/java/org/openrewrite/java/OrderImports.java, rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
Use correct product name "IntelliJ IDEA"
Small improvements
Please check if all changes are relevant
@timtebeek 
Ran the build and it passes.
=> Use the correct product name "IntelliJ IDEA"

rewrite-core/src/main/java/org/openrewrite/LargeSourceSet.java, rewrite-core/src/main/java/org/openrewrite/internal/InMemoryLargeSourceSet.java
=> Add utility to get original source file from LSS

rewrite-maven/src/main/java/org/openrewrite/maven/AddGradleEnterpriseMavenExtension.java
AddGradleEnterpriseMavenExtension version attribute is optional
Forgot to add this in previous PR https://github.com/openrewrite/rewrite/pull/3487
=> Set AddGradleEnterpriseMavenExtension version attribute as optional

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeClassInheritanceTest.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
=> #3289 padding on implements

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/VariableNameUtilsTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java, rewrite-java/src/main/java/org/openrewrite/java/JavadocVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java
=> Fix the Javadoc Cursor path not being restored

rewrite-maven/src/main/java/org/openrewrite/maven/ChangeProjectVersion.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangeProjectVersionTest.java
Added a new recipe to allow changing the project version of a maven project.
Customer request
@timtebeek
=> Added new recipe to change project version of a maven project.

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
This should add these responses as empty results in the maven cache
=> Add 409 and other non retryable status codes to isClientSideException()

rewrite-core/src/main/java/org/openrewrite/table/RewriteRecipeSource.java, rewrite-java-test/src/test/java/org/openrewrite/java/recipes/FindRecipesTest.java, rewrite-java/src/main/java/org/openrewrite/java/recipes/FindRecipes.java
Changes:
- FindRecipes will include the recipe options as JSON.
Format:
```json
[
{
"name": "optionName",
"displayName": "...",
"description": "...",
"example": "...",
"required": false,
"valid": ["private", "protected", "package", "public"]
}
]
```
=> Added recipe options as JSON to FindRecipes.

rewrite-benchmarks/build.gradle.kts, rewrite-gradle/build.gradle.kts, rewrite-groovy/build.gradle.kts, rewrite-java-11/build.gradle.kts, rewrite-java-21/build.gradle.kts, rewrite-java-21/src/main/java/org/openrewrite/java/Java21Parser.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ModifierResults.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21Parser.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserInputFileObject.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeMapping.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeSignatureBuilder.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/package-info.java, rewrite-java-8/build.gradle.kts, rewrite-java-tck/README.md, rewrite-java-tck/build.gradle.kts, rewrite-java-test/build.gradle.kts, rewrite-java/build.gradle.kts, rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java, rewrite-maven/build.gradle.kts, settings.gradle.kts, tools/language-parser-builder/build.gradle.kts
Initial setup for Java 21
To prepare for new recipes
Ideally the upgrade to Gradle 8.4 is done first
=> feat: initial setup for java 21

rewrite-maven/build.gradle.kts
Updated the comment to reflect the current situation given the maintainer has said there'll be no newer Java 8 version fixing the issue 
Actualize comments
=> chore: update comment about resilience4j

rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
This pull request fixes typo `occurence -> occurrence` in comment of `importLayoutStyle.java`
=> fix typo in ImportLayoutStyle.java comment

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/tree/MappingTest.java
=> Minor fix: added multiline scalar condition back into YamlParser with test.

rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedDependency.java
- https://github.com/openrewrite/rewrite/issues/3626
=> Exclude `ResolvedDependency#dependencies` in `hashCode()`

rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/CircleCiBuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/CustomBuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/DroneBuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/GithubActionsBuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/GitlabBuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/search/FindCommitters.java, rewrite-core/src/main/java/org/openrewrite/table/CommitsByDay.java, rewrite-core/src/main/java/org/openrewrite/table/Committers.java, rewrite-core/src/main/java/org/openrewrite/table/DistinctCommitters.java, rewrite-core/src/test/java/org/openrewrite/FindGitProvenanceTest.java, rewrite-core/src/test/java/org/openrewrite/marker/GitProvenanceTest.java, rewrite-core/src/test/java/org/openrewrite/search/FindCommittersTest.java
Adding committer activity to `GitProvenance`
=> Info on committer activity

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeSignatureBuilder.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeSignatureBuilder.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeSignatureBuilder.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeSignatureBuilder.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/MethodInvocationTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/DefaultJavaTypeSignatureBuilder.java
=> Handle `JavaType.Intersection` in `DefaultJavaTypeSignatureBuilder`

rewrite-java/src/main/java/org/openrewrite/java/search/FindMethods.java
Changed one word in description "Find method usages by pattern." to "Find method calls by pattern."
Name remains the same.
Help the search ai find the recipe by using call instead of usages. Related to https://github.com/moderneinc/moderne-recipe-search/issues/6
=> Changing word in find methods recipe's description for better search

rewrite-core/src/main/java/org/openrewrite/marker/ci/BitbucketBuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/BuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/CircleCiBuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/DroneBuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/GithubActionsBuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/GitlabBuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/IncompleteGitConfigException.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/JenkinsBuildEnvironment.java, rewrite-core/src/main/java/org/openrewrite/marker/ci/TeamcityBuildEnvironment.java
- Add `TeamcityBuildEnvironment` & detection from `BuildEnvironment`.
- Applied formatter to all other build environment markers.
Fixes #3751
- #3751
=> Detect teamcity build environment

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/AnnotationTest.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Changes:
- Annotated types with annotations in fully qualified names will parse correctly.
fixes #3683
=> Added support for annotations in fully qualified type names.

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitor.java
Simplify additional cases as discovered on
- https://github.com/openrewrite/rewrite-static-analysis/pull/231
=> Simplify `!(false)` and `!((false))`

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesTest.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesVisitor.java
Fixes #3883 
https://github.com/openrewrite/rewrite-static-analysis/pull/231
No
No
No
=> Remove unnnecessary parenthesis from unary expressions

rewrite-core/src/main/java/org/openrewrite/ipc/http/HttpSender.java
Adding file upload functionality to HttpSender
Migrating Moderne CLI to use HttpSender.
@timtebeek 
The alternative is to implement this on the consumer side.
=> Add simple single file multipart file upload to HttpSender

rewrite-java-test/src/test/java/org/openrewrite/java/RemoveObjectsIsNullTest.java, rewrite-java/src/main/java/org/openrewrite/java/RemoveObjectsIsNull.java
Fixes https://github.com/openrewrite/rewrite/issues/3915
Fixes https://github.com/openrewrite/rewrite/issues/3916
=> Change primitive handling in RemoveObjectsIsNull

rewrite-java-test/build.gradle.kts, rewrite-java-test/src/test/java/org/openrewrite/java/format/NoWhitespaceBeforeTest.java, rewrite-java/src/main/java/org/openrewrite/java/format/NoWhitespaceAfter.java, rewrite-java/src/main/java/org/openrewrite/java/format/NoWhitespaceBefore.java
Fixes https://github.com/openrewrite/rewrite-static-analysis/issues/233
=> Skip NoWhitespaceBefore and NoWhitespaceBefore for Groovy

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateJavaCompatibility.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateJavaCompatibilityTest.java
Fixes https://github.com/openrewrite/rewrite/issues/3938
=> Do not downgrade SourceCompatibility by default

rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java
Follow up from:
- https://github.com/openrewrite/rewrite/commit/def2c570146ea91fe1488d7e7bdee1b22a8d316a
- https://github.com/openrewrite/rewrite/pull/3933
=> Prevent exceptions on missing GradleProject markers

rewrite-java/src/main/java/org/openrewrite/java/marker/JavaSourceSet.java
Avoid calling `ClassGraph` twice and avoid some unnecessary memory allocations.
=> Faster scanning in `JavaSourceSet`

rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactIdTest.java
=> fix: profile specific plugins were not matched

rewrite-core/src/main/java/org/openrewrite/LargeSourceSet.java, rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java
This method allows the implementation to know whether the new cycle is definitely the last cycle or not.
=> Add `LargeSourceSet#beforeCycle(boolean)`

rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveDependencyTest.java
Transformed reproducer from gh-4033 to a `RewriteTest` implementation
=> Add test case for removal in subprojects

rewrite-groovy/src/test/java/org/openrewrite/groovy/cleanup/SimplifyBooleanExpressionVisitorTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitor.java
Fixes https://github.com/openrewrite/rewrite-static-analysis/pull/266
https://rewriteoss.slack.com/archives/C01A843MWG5/p1709465857842709
=> Simplify more boolean expressions

rewrite-maven/src/main/java/org/openrewrite/maven/AddProperty.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangePropertyValue.java
Follow-up of #3992 and #4032 
Add maven dependencies with version declared as properties
No
No
No
No
=> Update maven model when adding/changing properties to pom

rewrite-gradle/src/main/groovy/RewriteGradleProject.groovy
Added `deploy` and `earlib` as gradle dependency handlers
Support version bumps in ear projects
=> Added gradle dependency scopes for ear plugin

rewrite-core/src/main/java/org/openrewrite/text/AppendToTextFile.java
See https://github.com/openrewrite/rewrite/issues/4092
@mike-solomon
=> Warn about plain text specifics in AppendToTextFile.java

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlIsoVisitor.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlVisitor.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/internal/YamlPrinter.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/tree/Yaml.java
This is for `Yaml.Document.End` LST elements.
=> Add missing `YamlVisitor#visitDocumentEnd()`

rewrite-core/src/main/java/org/openrewrite/search/FindCommitters.java
Extract and use method to find committers
Reusing of functionality
No semantic changes
=> Extract find committers method

rewrite-maven/src/main/java/org/openrewrite/maven/tree/Plugin.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/tree/ResolvedPomTest.java
fixes #4145
Change `ResolvedPom` to add support to merge executions.
Found the bug and reported at #4145 and thought about trying a fix.
None, do your worst and comment it out
=> Adds support for merging plugins executions

rewrite-gradle/src/main/groovy/RewriteGradleProject.groovy, rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyTest.java
Added the providedCompile to the DependencyHandlerSpec and created a test for it
If you run the gradle ChangeDependency recipe against a war project, it will not update the dependencies for the providedCompile configuration.
=> Add providedCompile to the DependencyHandlerSpec for ChangeDependency gradle 

rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Fixes https://github.com/openrewrite/rewrite-micronaut/pull/107
Following 159f27c215be4efe82d5b6ddf7c6ccf27d0d3e6e
=> Restore adding missing prefix in MergeYaml

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeMethodNameTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodName.java, rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
For
- https://github.com/openrewrite/rewrite-migrate-java/issues/435
- https://github.com/openrewrite/rewrite-migrate-java/pull/473
=> Support NewClass in MethodMatcher and ChangeMethodName

rewrite-maven/src/main/java/org/openrewrite/maven/AddProperty.java, rewrite-maven/src/main/java/org/openrewrite/maven/AddPropertyVisitor.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddPropertyTest.java
@sambsnyd as per slack conversation: https://rewriteoss.slack.com/archives/G01J94KRH70/p1715357115031169. Hope this what you had in mind as well.
=> Allow for simple re-usable `AddPropertyVisitor`

gradle/wrapper/gradle-wrapper.properties, gradlew, rewrite-gradle/src/main/resources/gradlew
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.gradle.UpdateGradleWrapper?organizationId=T3BlblJld3JpdGU%3D
=> refactor: Update Gradle wrapper

rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceStringLiteralWithConstantTest.java, rewrite-java/src/main/java/org/openrewrite/java/ReplaceStringLiteralWithConstant.java
Fixes https://github.com/openrewrite/rewrite-spring/issues/536
- https://github.com/openrewrite/rewrite-spring/issues/536
=> Do not throw if `ReplaceStringLiteralWithConstant` value not found

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveEnableFeaturePreviewTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceStringLiteralWithConstantTest.java, rewrite-java/src/main/java/org/openrewrite/java/ReplaceAnnotation.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddPropertyTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/ModernizeObsoletePomsTest.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/DeletePropertyKeyTest.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.recipes.OpenRewriteBestPractices?organizationId=T3BlblJld3JpdGU%3D
=> refactor: OpenRewrite best practices

rewrite-core/src/main/java/org/openrewrite/config/RecipeDescriptor.java
Wasn't sure if this was a conscious omission or not; figured easiest to ask in a PR for one click Merge/Close.
- https://github.com/openrewrite/rewrite/pull/4253
=> Add NlsRewrite hints to Refaster RecipeDescriptor fields

rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyClassifier.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyClassifierTest.java
This is to align with Maven counter part
=> Gradle `ChangeDependencyClassifier` supports add and remove classifier

rewrite-core/src/main/java/org/openrewrite/semver/LatestRelease.java, rewrite-core/src/test/java/org/openrewrite/semver/LatestReleaseTest.java
made this comparator a bit more robust for edge cases (see commit messages)
I would've just pushed this directly, but, having some auth challenges right now and pushing to my fork was expedient
=> LatestRelease enhancements

rewrite-java/src/main/java/org/openrewrite/java/trait/Literal.java
=> Reword literal trait description

rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
Adding tests in an attempt to reproduce an issue.
Testing if an issue can be reproduced
Any other edge-cases that might produce the issue
@timtebeek 
Not adding these tests
=> feat: Add tests for `AddDependency` already in test scope

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeStaticFieldToMethodTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/marker/JavaSourceSetTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeStaticFieldToMethod.java
and nested code.
- Fixes #4382
Hmm.. I have not done this.  Can this be done via a gradle command?  Apologies if that's clear in doc or gradle config (don't use gradle much).
=> Fix issue in ChangeStaticFieldToMethod when used in (implied) array

build.gradle.kts, suppressions.xml
add initial set that were previously reported / false positives
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/709
=> chore: add suppressions for owasp dependency check

rewrite-java-test/src/test/java/org/openrewrite/RepeatTest.java, rewrite-java/src/main/java/org/openrewrite/java/search/HasMinimumJavaVersion.java, rewrite-java/src/test/java/org/openrewrite/java/trait/VariableAccessTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemovePropertyTest.java, rewrite-test/src/test/java/org/openrewrite/RenameFileTest.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.LambdaBlockToExpression?organizationId=T3BlblJld3JpdGU%3D
=> refactor: Simplify lambda blocks to expressions

rewrite-core/src/main/java/org/openrewrite/PathUtils.java, rewrite-core/src/main/java/org/openrewrite/internal/lang/NonNullApi.java, rewrite-core/src/main/java/org/openrewrite/internal/lang/NullUtils.java, rewrite-core/src/main/java/org/openrewrite/internal/lang/Nullable.java, rewrite-core/src/test/java/org/openrewrite/PathUtilsTest.java, rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java, rewrite-core/src/test/java/org/openrewrite/table/SourceFileResultsTest.java, rewrite-java-test/src/test/java/org/openrewrite/RepeatTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaTypeTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/search/HasMinimumJavaVersionTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/search/IsOrIsNotLikelyTestTest.java, rewrite-java/src/main/java/org/openrewrite/java/format/EmptyNewlineAtEndOfFile.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginConfiguration.java, rewrite-maven/src/main/java/org/openrewrite/maven/RemoveManagedDependency.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java, rewrite-xml/src/test/java/org/openrewrite/xml/trait/NamespacedTest.java
- Following https://github.com/openrewrite/rewrite/pull/4406
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.RemoveUnusedImports?organizationId=T3BlblJld3JpdGU%3D
=> refactor: Remove unused imports

rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
Previously we did not pass along the details message for a singular `MavenDownloadingException`, but did for `MavenDownloadingExceptions`.
We want to show the message details downstream in the Maven plugin when we fail to build a project, as we've seen project fail partially and subtly leading to unseen changes and missing types. A hard failure with more details is then preferred.
=> Also show details for singular MavenDownloadingException

suppressions.xml
related to https://github.com/moderneinc/dependency-vulnerability-reports/issues/738
=> chore: update suppression dates

rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java
As suggested on
- https://github.com/openrewrite/rewrite/pull/4530#issuecomment-2382971751
To fix the downstream issues on rewrite-jackson
- https://github.com/openrewrite/rewrite/pull/4530#issuecomment-2382685644
=> Drop AllArgsConstructor from RawPom$Build

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AnnotationTest.java
See: https://github.com/openrewrite/rewrite/issues/4055#issuecomment-2392913541
=> Allow parsing nested Groovy annotations

rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
- Fixes https://github.com/openrewrite/rewrite/issues/4540
@Col-E
- https://github.com/openrewrite/rewrite/pull/4516
- https://github.com/openrewrite/rewrite-maven-plugin/pull/872
- https://github.com/openrewrite/rewrite-gradle-plugin/pull/335
=> Use reflection to invoke getCommentTree to support Java 21 & 23

suppressions.xml
No new versions are available.
=> Suppressing vulnerabilities

suppressions.xml
related to:
- https://github.com/moderneinc/dependency-vulnerability-reports/issues/776
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.xml.security.UpdateOwaspSuppressionDate?organizationId=T3BlblJld3JpdGU%3D#defaults=W3sidmFsdWUiOlsiQ1ZFLTIwMTctMTI2MjYiLCJDVkUtMjAxOS0xNTA1MiIsIkNWRS0yMDIzLTM1OTQ3ICIsIkNWRS0yMDIxLTI5NDI4IiwiQ1ZFLTIwMjAtMTE5NzkiLCJDVkUtMjAyMS0zMjc1MSIsIkNWRS0yMDIzLTQ1MTYxIiwiQ1ZFLTIwMjMtNDUxNjMiLCJDVkUtMjAyMy01OTY0ICIsIkNWRS0yMDE5LTExNDAyIiwiQ1ZFLTIwMTktMTE0MDMiLCJDVkUtMjAyMS00MTU4OSIsIkNWRS0yMDIzLTQ5MjM4IiwiQ1ZFLTIwMjItMjUzNjQiLCJDVkUtMjAyMi0xNDcxIiwiQ1ZFLTIwMTgtMTI1OCJdLCJuYW1lIjoiY3ZlTGlzdCJ9XQ==
=> refactor: update OWASP suppression date bounds

rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
=> Allow to add Maven test scoped dependency

rewrite-toml/src/main/java/org/openrewrite/toml/TomlVisitor.java, rewrite-toml/src/main/java/org/openrewrite/toml/tree/Toml.java, rewrite-toml/src/test/java/.editorconfig, rewrite-toml/src/test/java/org/openrewrite/toml/TomlParserTest.java, rewrite-toml/src/test/java/org/openrewrite/toml/TomlVisitorTest.java
- Fix https://github.com/openrewrite/rewrite/issues/4890
=> Add TomlVisitorTest after seeing ClassCastException in arrays

rewrite-toml/src/main/java/org/openrewrite/toml/TomlIsoVisitor.java, rewrite-toml/src/main/java/org/openrewrite/toml/internal/TomlPrinter.java, rewrite-toml/src/main/java/org/openrewrite/toml/tree/Toml.java
Added a few missing `@Nullable` annotations and added accessors for `Toml.Table#name`.
=> TOML model cleanups

rewrite-core/src/main/java/org/openrewrite/format/LineBreaks.java, rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeLineBreaksVisitor.java, rewrite-xml/src/main/java/org/openrewrite/xml/format/NormalizeLineBreaksVisitor.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/format/NormalizeLineBreaksVisitor.java
Pure refactoring. DRYing and extracting `normalizeNewLines` utility method to rewrite-core.
It's copied to three places and I was about to copy it the fourth time.
=> Refactoring, extract normalizeNewLines()

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
According to the maven documentation we should use the repository specified in the setting.xml then the pom.xml
https://maven.apache.org/guides/mini/guide-multiple-repositories.html
=> Maven repository ordering should give precedence to Maven settings over local repositories

rewrite-java-tck/src/main/java/org/openrewrite/java/tree/SwitchTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
A PR was merged with this test that applies more broadly in a sub optimal place
@jevanlingen
=> Move switch test case to regression project

suppressions.xml
re: https://github.com/moderneinc/dependency-vulnerability-reports/issues/799
=> chore: update suppressions for 2025-01-22 report

rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveRedundantDependencyVersions.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Applying openrewrite code suggestions.
Addressing the comments in unrelated PRs:
```
Some suggestions could not be made:
rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveRedundantDependencyVersions.java
lines 240-241
rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
lines 1278-1278
```
=> Applying code suggestions

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
Fix npe
Improve 
- https://github.com/openrewrite/rewrite/pull/5003
=> Fix NullPointerException in Java parser for Enums with missing type information

rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyClassifier.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyExtension.java
Minor change.
Fixing descriptions of two recipes in `rewrite-gradle`.
I noticed it by accident when browsing related code.
=> Fixing descriptions of two recipes in rewrite-gradle

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
=> Fix POM download

rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
Added testcase to prove maven config properties work and are read only
@jevanlingen 
Adjusted testcase proposed in #5070 that was removed
=> Prove once more maven config properties are resolved

rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPluginRepositories.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Profile.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpgradePluginVersionTest.java
Extends Pom model to support Plugin Repositories 
fix #5065
=> Adds support for Plugin Repositories in Maven Pom

rewrite-core/src/main/java/org/openrewrite/Validated.java, rewrite-core/src/main/java/org/openrewrite/rpc/RewriteRpc.java, rewrite.yml
Tweak and reapply best practices to avoid comments on PRs unrelated to the findings.
=> Apply & update OpenRewrite best practices

rewrite-gradle/src/test/java/org/openrewrite/gradle/search/FindDependencyTest.java, rewrite-maven/src/main/java/org/openrewrite/maven/Assertions.java, rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenResolutionResult.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenModelTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java
- https://github.com/openrewrite/rewrite-maven-plugin/pull/955
=> Store MavenSession.userProperties in MavenResolutionResult

rewrite-kotlin/build.gradle.kts, rewrite-kotlin/src/main/java/org/openrewrite/kotlin/KotlinParser.java, rewrite-kotlin/src/test/java/org/openrewrite/kotlin/style/AutodetectTest.java
Fixed the build
Failing build
@knutwannheden
=> Fix rewrite-kotlin tests

rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java
Minor follow-up to #5149.
Addressing the review comment: https://github.com/openrewrite/rewrite/pull/5149#discussion_r1986913887
=> Add validation for 'key' in MergeYaml

rewrite-core/src/main/java/org/openrewrite/table/RecipeRunStats.java
`RecipeRunStats` will now add a row for recipes that have a `scan` timer registered but no `edit` timer.
In case a recipe has not hit its edit phase when it times out or is forcibly killed, we still want to know how much time was taken in the scanning phase.
N/A
@sambsnyd 
N/A
N/A
- ~[] I've added unit tests to cover both positive and negative cases~
=> Include scan-only changes when a recipe times out

rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersion.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersionTest.java
Be more defensive when parsing potential java version properties
Recipe failures after 
- https://github.com/openrewrite/rewrite/pull/5168
=> Fix java version update

rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
When trying to resolve a pom without a version simply skip it as that will not succeed.
=> When no version is present, skip resolving

rewrite-core/src/main/java/org/openrewrite/internal/RecipeIntrospectionUtils.java
The constructor lookup was incorrect for the case when constructor arguments were provided.
=> Fix bug in `RecipeIntrospectionUtils#constructRecipe()`

rewrite-gradle/src/test/java/org/openrewrite/gradle/tree/ExtTest.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/G.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java
1. Added support for spaceship operator in groovy parser.
2. closes #5180
=> Added support for groovy spaceship operator.

rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactId.java
Updated various descriptions in this recipe to reflect it's actual logic
- https://github.com/openrewrite/rewrite/pull/5252
=> Update `ChangePluginGroupIdAndArtifactId` descriptions

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RealWorldGroovyTest.java
1. Fixed groovy parser tp handle multiple backslahses in string.
2. Fixed possible infinite loop issue.
3. close #5232
=> Fixed groovy parser issue when dealing with multiple backslashes in string.

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesTest.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/UnnecessaryParenthesesVisitor.java
=> Unwrap parentheses around method invocation arguments

rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/tech.picnic.errorprone.refasterrules.TimeRulesRecipes?organizationId=T3BlblJld3JpdGU%3D
=> refactor: `TimeRules` Refaster recipes

rewrite-groovy/src/main/resources/META-INF/rewrite/examples.yml, rewrite-hcl/src/main/resources/META-INF/rewrite/examples.yml, rewrite-java-test/src/main/resources/META-INF/rewrite/examples.yml, rewrite-java/src/main/resources/META-INF/rewrite/examples.yml, rewrite-json/src/main/resources/META-INF/rewrite/examples.yml, rewrite-kotlin/src/main/resources/META-INF/rewrite/examples.yml, rewrite-maven/src/main/resources/META-INF/rewrite/examples.yml, rewrite-properties/src/main/resources/META-INF/rewrite/examples.yml, rewrite-xml/src/main/resources/META-INF/rewrite/examples.yml, rewrite-yaml/src/main/resources/META-INF/rewrite/examples.yml
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.recipes.ExamplesExtractor?organizationId=ODQ2MGExMTUtNDg0My00N2EwLTgzMGMtNGE1NGExMTBmZDkw
=> refactor: Extract documentation examples from tests

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/G.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/GLeftPadded.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/GSpace.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyVisitorTest.java
Adding support for Groovy spread operator
- Closes #5297
=> Add support for Groovy spread operator.

rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java, rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Fix handling recursive types.
- fixes https://github.com/openrewrite/rewrite/issues/5289
Not related, but should we handle the `$` symbol `BugTest$Rec<?>`?
=> Fix recursive types

rewrite-gradle/src/main/java/org/openrewrite/gradle/gradle8/JacocoReportDeprecations.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/gradle8/package-info.java, rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-8.yml, rewrite-gradle/src/test/java/org/openrewrite/gradle/gradle8/JacocoReportDeprecationsTest.java
- For more context: https://github.com/openrewrite/rewrite-migrate-java/pull/708
=> Rename deprecated JaCoCo properties as part of Gradle 8 migration

rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/main/java/org/openrewrite/maven/plugin/DependencyPluginGoalResolveSources.java, rewrite-maven/src/main/resources/META-INF/rewrite/maven.yml, rewrite-maven/src/test/java/org/openrewrite/maven/plugin/DependencyPluginGoalResolveSourcesTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/plugin/DependencyPluginSourcesToResolveSourcesTest.java
- Fixes https://github.com/openrewrite/rewrite-apache/issues/20
- Replaces https://github.com/openrewrite/rewrite-apache/pull/65
=> Add `DependencyPluginGoalResolveSources` recipe for Maven

rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java
- Fixes #4072
Added a test
Post the merge of some other groovy related fixes, I wanted to verify if this issue is still active. It seems to be resolved without any new code changes. 
@greg-at-moderne @timtebeek
=> Add test for open issue after some other fixes

rewrite-core/src/main/java/org/openrewrite/rpc/RewriteRpc.java, rewrite-core/src/main/java/org/openrewrite/rpc/request/Parse.java, rewrite-core/src/main/java/org/openrewrite/rpc/request/ParseResponse.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JContainer.java, rewrite-javascript/rewrite/src/javascript/parser.ts, rewrite-javascript/rewrite/src/javascript/print.ts, rewrite-javascript/rewrite/src/javascript/visitor.ts, rewrite-javascript/rewrite/src/parser.ts, rewrite-javascript/rewrite/src/rpc/request/parse.ts, rewrite-javascript/rewrite/src/rpc/rewrite-rpc.ts, rewrite-javascript/rewrite/src/rpc/server.ts, rewrite-javascript/rewrite/test/rpc/rewrite-rpc.test.ts, rewrite-javascript/src/integTest/java/org/openrewrite/javascript/JavaScriptParserTest.java, rewrite-javascript/src/integTest/java/org/openrewrite/javascript/rpc/JavaScriptRewriteRpcTest.java, rewrite-javascript/src/integTest/java/org/openrewrite/javascript/rpc/JavaToJavaScriptRpcTest.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/Assertions.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/JavaScriptParser.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/JavaScriptVisitor.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/rpc/JavaScriptReceiver.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/rpc/JavaScriptRewriteRpc.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/tree/JS.java
=> RPC-based JavaScript parser

rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveRedundantDependencyVersions.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveRedundantDependencyVersionsTest.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactId.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
Nothing, just small refactoring.
I wil make adjustments to this recipe in the future, it's better not to include this small refactoring in that recipe.
=> Cleanup RemoveRedundantDependencyVersions recipe

rewrite-javascript/src/main/java/org/openrewrite/javascript/tree/JS.java
Fixing code suggestions in a single Javascript file.
Address warnings like:
https://github.com/openrewrite/rewrite/pull/5414#pullrequestreview-2835394990
=> Fixing code suggestions

rewrite-gradle/src/test/java/org/openrewrite/gradle/AddPropertyTest.java
additional test case in gradle AddPropertyTest
=> Add additional test case to gradle AddPropertyTest

rewrite-core/src/test/java/org/openrewrite/PathUtilsTest.java
more assertions in PathUtilsTest
=> Add assertions in PathUtilsTest

rewrite-javascript/rewrite/src/java/visitor.ts, rewrite-javascript/rewrite/src/javascript/visitor.ts, rewrite-javascript/rewrite/test/java/visitor.test.ts
Continuation of #5430, but for Expressions.
As before.
=> Javascript - calling visitExpression for subclasses

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/src/javascript/style.ts, rewrite-javascript/rewrite/src/test/rewrite-test.ts, rewrite-javascript/rewrite/test/javascript/format/blank-lines-visitor.test.ts
Adding BlankLinesVisitor to Javascript Autoformatter.
One more step (not the final one) towards complete auto formatting solution for JS/TS.
=> Javascript - Adding BlankLinesVisitor

rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/AppendToSequenceTest.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/JsonPathMatcherTest.java
We had this issue pop up during a connect. 
We still won;t support full usecases of jsonpath -> opened another ticket to track a more uniform solving of these issues.
=> Added support for index visitation and all matching elements when filtering

rewrite-java/src/main/java/org/openrewrite/java/FullyQualifyMemberReference.java
=> Remove double annotation

rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
- Fixes https://github.com/openrewrite/rewrite-maven-plugin/issues/983
- https://github.com/openrewrite/rewrite/pull/5375
- https://github.com/openrewrite/rewrite/issues/4983
- https://github.com/openrewrite/rewrite/issues/4183
- https://github.com/openrewrite/rewrite-spring/issues/316
- https://github.com/openrewrite/rewrite-maven-plugin/issues/981
=> "No version provided" for managed Maven dependencies with type

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsAssertions.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateGenericsTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavaTemplateSemanticallyEqual.java, rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java, rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Restore support for infer mode
The scenarios that were causing regressions.
Handling special cases: Method Variable and Annotation.
=> Support infer mode

rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java
The `classesDirByArtifact` map in `TypeTable.java` was susceptible to
concurrent modification exceptions when accessed by multiple threads
simultaneously, particularly during parallel test execution.
This commit introduces the following changes to ensure thread safety:
1.  The `classesDirByArtifact` map is now wrapped using
`Collections.synchronizedMap(new LinkedHashMap<>())`. This retains
the insertion order characteristics of `LinkedHashMap` while
providing synchronized access to its methods.
2.  Explicit `synchronized(classesDirByArtifact)` blocks have been added
around iterations of `classesDirByArtifact.keySet()` in the
`artifactsNotYetWritten` method and `classesDirByArtifact.entrySet()`
in the `load` method. This prevents `ConcurrentModificationException`
during these iteration …
=> Fix `ConcurrentModificationException` in `TypeTable`

rewrite-javascript/rewrite/test/javascript/format/spaces-visitor.test.ts
Minor change to the `spaces-visitor.test.ts`.
Not calling the whole `AutoformatVisitor`, but `SpacesVisitor` directly.
To narrow down the tested logic more precisely.
=> Calling SpacesVisitor directly in spaces-visitor.test.ts

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/src/javascript/style.ts, rewrite-javascript/rewrite/src/tree.ts, rewrite-javascript/rewrite/test/javascript/format/format.test.ts, rewrite-javascript/rewrite/test/javascript/format/tabs-and-indents-visitor.test.ts
Amending the AutoformatVisitor in Javascript continued.
Adding `TabsAndIndentsVisitor`.
One more step towards JS autoformatting feature.
=> Adding TabsAndIndentsVisitor

rewrite-javascript/rewrite/src/javascript/format.ts
Changing the generics type parameter of `AutoformatVisitor` and subvisitors to take `P` as type parameter.
Will be needed for calling the visitors in various situations. We are using it (yet) anyway.
=> Generics P instead of hard-coding ExecutionContext in AutoformatVisitor

rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveRepository.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveRepositoryTest.java
Added kotlin support to RemoveRepository recipe
=> Support Kotlin for the RemoveRepository recipe

rewrite-core/src/main/java/org/openrewrite/rpc/RpcReceiveQueue.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveRepository.java, rewrite-hcl/src/main/java/org/openrewrite/hcl/JsonPathMatcher.java, rewrite-java/src/main/java/org/openrewrite/java/internal/ClassIdResolver.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java, rewrite-json/src/main/java/org/openrewrite/json/JsonPathMatcher.java, rewrite-kotlin/src/main/java/org/openrewrite/kotlin/cleanup/RemoveTrailingSemicolon.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenXmlMapper.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/JsonPathMatcher.java
- Following https://github.com/openrewrite/rewrite-static-analysis/pull/569
=> Annotate nullable methods that return from ternary

rewrite-core/src/main/java/org/openrewrite/DataTable.java, rewrite-core/src/main/java/org/openrewrite/marker/SearchResult.java, rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java, rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.AnnotateNullableParameters?organizationId=ODQ2MGExMTUtNDg0My00N2EwLTgzMGMtNGE1NGExMTBmZDkw
=> refactor: Annotate null-checked method parameters with `@Nullable`

rewrite-java/src/main/java/org/openrewrite/java/internal/rpc/JavaReceiver.java, rewrite-java/src/main/java/org/openrewrite/java/internal/rpc/JavaSender.java, rewrite-javascript/rewrite/src/java/rpc.ts, rewrite-javascript/rewrite/src/javascript/rpc.ts, rewrite-javascript/rewrite/src/javascript/tree.ts, rewrite-javascript/rewrite/src/rpc/codec.ts, rewrite-javascript/rewrite/src/rpc/queue.ts, rewrite-javascript/src/main/java/org/openrewrite/javascript/JavaScriptVisitor.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/rpc/JavaScriptReceiver.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/rpc/JavaScriptSender.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/tree/JS.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/tree/JSX.java
Fixes a few bugs and adds workarounds for some problems, which will be addressed in a cleaner way in the future.
=> Various fixes to JS model and RPC logic

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest5Test.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest6Test.java, rewrite-java-test/src/test/java/org/openrewrite/java/format/WrappingAndBracesTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java, rewrite-java/src/main/java/org/openrewrite/java/format/WrappingAndBracesVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java, rewrite-java/src/main/java/org/openrewrite/java/style/IntelliJ.java, rewrite-java/src/main/java/org/openrewrite/java/style/WrappingAndBracesStyle.java
Implemented annotation wrapping style detection, IntelliJ default and applying of the detected style
- https://github.com/openrewrite/rewrite/issues/5392
Situations where comments might get lost (I'll add more testcases regarding this)
Test coverage in general
- https://github.com/openrewrite/rewrite-static-analysis/issues/543
=> Implement annotation wrapping style detection, IntelliJ default and applying

.claude/settings.local.json, rewrite-core/src/main/java/org/openrewrite/rpc/RewriteRpc.java, rewrite-core/src/main/java/org/openrewrite/rpc/RpcReceiveQueue.java, rewrite-core/src/main/java/org/openrewrite/rpc/RpcSendQueue.java, rewrite-core/src/main/java/org/openrewrite/rpc/request/GetObject.java, rewrite-core/src/main/java/org/openrewrite/rpc/request/GetRef.java, rewrite-core/src/main/java/org/openrewrite/rpc/request/GetRefResponse.java, rewrite-core/src/main/java/org/openrewrite/text/PlainText.java, rewrite-core/src/test/java/org/openrewrite/rpc/GetRefRequestTest.java, rewrite-core/src/test/java/org/openrewrite/rpc/IndependentCacheManagementTest.java, rewrite-core/src/test/java/org/openrewrite/rpc/RpcReceiveQueueTest.java, rewrite-javascript/rewrite/src/rpc/queue.ts, rewrite-javascript/rewrite/src/rpc/reference.ts, rewrite-javascript/rewrite/src/rpc/request/get-object.ts, rewrite-javascript/rewrite/src/rpc/request/get-ref.ts, rewrite-javascript/rewrite/src/rpc/request/index.ts, rewrite-javascript/rewrite/src/rpc/rewrite-rpc.ts, rewrite-javascript/rewrite/src/text/rpc.ts, rewrite-javascript/rewrite/test/rpc/independent-cache-management.test.ts, rewrite-javascript/src/integTest/java/org/openrewrite/javascript/rpc/JavaScriptRewriteRpcTest.java
- **Add new `GetRef` and remove `ClearObjectMaps`**
- **Add some tests**
- **Simplify**
- **Simplify**
- **Simplify**
- **Simplify**
=> no clearobjectmaps

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
Just a description change
- Fix: https://github.com/openrewrite/rewrite/issues/4816
=> Fixed UpdateGradleWrapper description to represent behaviour

rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java, rewrite-core/src/test/java/org/openrewrite/internal/EncodingDetectingInputStreamTest.java, rewrite-core/src/test/java/org/openrewrite/internal/ListUtilsTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/FindCommentsTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/ImplementInterfaceTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/SimplifyMethodChainTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/format/WrappingAndBracesTest.java, rewrite-java/src/test/java/org/openrewrite/java/FullyQualifyMemberReferenceTest.java, rewrite-kotlin/src/test/java/org/openrewrite/kotlin/format/WrappingAndBracesTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java, rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java, rewrite-test/src/test/java/org/openrewrite/test/RecipePrinterTest.java, rewrite-test/src/test/java/org/openrewrite/test/internal/RewriteTestTest.java
Use this link to re-run the recipe: https://app.moderne.io/builder/j1pfpwnjZ?organizationId=ODQ2MGExMTUtNDg0My00N2EwLTgzMGMtNGE1NGExMTBmZDkw
=> refactor: Replace `Arrays.asList` with `List.of` in tests

rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java
Improvement to recipe description.
It's not clear what the limitations of the UpgradePluginVersion recipe are: https://github.com/openrewrite/rewrite/issues/5745.
=> Clarify the use of the recipe

rewrite-xml/src/main/java/org/openrewrite/xml/ChangeTagAttribute.java, rewrite-xml/src/test/java/org/openrewrite/xml/ChangeTagAttributeTest.java
=> ChangeTagAttribute should be idempotent

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
Revert https://github.com/openrewrite/rewrite/pull/5756.
Downstream failures.
=> Revert "Support for external properties for UpgradeTransitiveDependencyVersion recipe (#5756)"

rewrite-gradle/src/main/java/org/openrewrite/gradle/gradle8/JacocoReportDeprecations.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.PreferIncrementOperator?organizationId=QUxML09wZW4gU291cmNlL09wZW5SZXdyaXRl
=> refactor: Prefer increment and decrement operators

rewrite-core/src/main/java/org/openrewrite/MoveFile.java, rewrite-core/src/main/java/org/openrewrite/internal/PropertyPlaceholderHelper.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/gradle8/JacocoReportDeprecations.java, rewrite-java/src/main/java/org/openrewrite/java/CreateEmptyJavaClass.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/VersionRequirement.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.PreferIncrementOperator?organizationId=QUxML09wZW4gU291cmNlL09wZW5SZXdyaXRl
=> refactor: Prefer increment/decrement and compound assignment operators

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java
- Fixes https://github.com/openrewrite/rewrite/issues/5855
=> Support Javadoc generic wildcards

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/HelmTemplateParsingTest.java
- Fixes https://github.com/openrewrite/rewrite/issues/5987
=> Helm template placeholders in comments

.github/workflows/receive-pr.yml, rewrite-core/src/main/java/org/openrewrite/rpc/RpcReceiveQueue.java, rewrite-core/src/main/java/org/openrewrite/rpc/RpcSendQueue.java, rewrite-core/src/test/java/org/openrewrite/marker/OperatingSystemProvenanceTest.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/AnnotationTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/rpc/JavaReceiver.java, rewrite-javascript/src/integTest/java/org/openrewrite/javascript/rpc/JavaScriptRewriteRpcTest.java, rewrite-kotlin/build.gradle.kts
=> Restore pull request receive workflow to apply best practices

rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ConstructorTest.java
Added testcases to cover flexible constructor bodies
https://openjdk.org/jeps/513
=> Add tests for flexible constructor bodies

rewrite-java-test/src/test/java/org/openrewrite/java/search/FindDistinctMethodsTest.java, rewrite-java/src/main/java/org/openrewrite/java/search/FindDistinctMethods.java
Added a recipe to list distinct methods matching a method matcher.
Helpful to understand the set of unique APIs in use, potentially matching on a subset of APIs with a wildcarded method matcher.
=> Find distinct methods

rewrite-java/src/main/java/org/openrewrite/java/search/UsesType.java
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.StringLatin1.charAt (StringLatin1.java:48)
at java.lang.String.charAt (String.java:1517)
at org.openrewrite.java.search.UsesType.<init> (UsesType.java:58)
at org.openrewrite.gradle.AddDependency$1.usesType (AddDependency.java:165)
at org.openrewrite.gradle.AddDependency$1.lambda$visit$0 (AddDependency.java:177)
at java.util.HashMap.compute (HashMap.java:1316)
at org.openrewrite.gradle.AddDependency$1.lambda$visit$3 (AddDependency.java:177)
at java.util.Optional.ifPresent (Optional.java:178)
at org.openrewrite.gradle.AddDependency$1.visit (AddDependency.java:176)
at org.openrewrite.gradle.AddDependency$1.visit (AddDependency.java:155)
at org.openrewrite.java.dependencies.AddDependency$1.visit …
```
=> fix: AddDependency with onlyIfUsing: "*" cause: StringIndexOutOfBoundsException

rewrite-core/src/main/java/org/openrewrite/semver/XRange.java, rewrite-core/src/test/java/org/openrewrite/semver/XRangeTest.java
The semantics are already very similar, might as well interpret it this way.
=> Treat Gradle's + dynamic verison selector as an XRange
