openrewrite/rewrite

rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java
When a repository is freshly cloned and no other actions have been taken (like pull) ORIG_HEAD is not available. Using HEAD as a fallback works to find the committers.
=> Find Committers on freshly cloned repositories

rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java
Add null check for objectId
A non null ref can have a null objectId (if there are no commits):
SymbolicRef[HEAD -> refs/heads/main=0000000000000000000000000000000000000000(-1)]
=> Add null check. A non null ref can point to a null objectId:

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Fixing a bug in the Properties visitor for the rewrite-gradle plugin which failed to check whether the property currently being visited is referenced by the GroupArtifact that the recipe refers to
@timtebeek and @shanman190  have the context for this
=> fix: prevent all referenced properties from updating to latest regardless of recipe

rewrite-core/src/main/java/org/openrewrite/search/FindCommitters.java, rewrite-core/src/test/java/org/openrewrite/search/FindCommittersTest.java
An option added to the FindCommitters recipe to only list committers since a specific date
I want to filter on committers from the last N days
no
no
Yes, doing this on the consumer side, but this is more useful for everyone.
no
=> feat: add from date option to FindCommitters recipe

rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseStringNotation.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/DependencyUseStringNotationTest.java
Added support in the `DependencyUseStringNotation.coerceToStringNotation` method for GString to String
closes #3959 
@timtebeek 
As currently the variable is just not in output, it think, although perhaps not completely mapping all kinds of GString's, this is still better as it supports something more. 
- [] I've used the IntelliJ IDEA auto-formatter on affected files
=> Make DependencyUseStringNotation compatible with G.GString

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
This improves the resolution event listener to not report repository access failures on repositories that are accessible but have disabled directory listing.
=> Normalization of maven repositories that don't permit directory listing

rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java, rewrite-maven/src/main/java/org/openrewrite/maven/utilities/RetainVersions.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
Also update Maven managed dependencies by default in ChangeDependencyGroupIdAndArtifactId 
By customer request to be less surprising by default: a change in the GAV should propagate to managed dependencies too by default, not require the same parameters passed into `ChangeManagedDependencyGroupIdAndArtifactId` a second time.
There was a surprising bit of depth to this into how the various arguments work together, and what might be desired from a user's perspective; I hope the named variables in the decision logic help follow along and troubleshoot if there are any issues.
I've chosen to only update the managed dependency GAV is a version argument is already provided, as it's quite unlikely that a GAV change uses the same version, and we don't want to have failures to resolve the managed …
=> Also update Maven managed dependency by default in `ChangeDependencyGroupIdAndArtifactId`

rewrite-maven/src/main/java/org/openrewrite/maven/ChangePackaging.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangePackagingTest.java
Added option to `ChangePackaging` to match the pom's packaging before changes
Change only packaging of a specific type
No
No
No
No
=> Changes packaging only if it matches provided packaging

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
When deciding if a HttpSender response has reached a server, ignore  lower than 100 response codes
Currently a -1 response code can be returned when the server was not reachable.
=> Less than 100 response status implies bad connection

rewrite-core/src/main/java/org/openrewrite/PathUtils.java, rewrite-core/src/test/java/org/openrewrite/PathUtilsTest.java
matchesGlob in PathUtils now supports negation with !()
I was writing a custom recipe where I wanted to apply the changes to source files whose filename ends with `*IT.java`, while excluding a few exceptions e.g. `CucumberLauncherIT.java`. However, when I used FindSourceFiles, I realized negation was not supported in the glob patterns.
@shanman190 @timtebeek 
#3847
=> Support negation in globmatcher in pathutils

rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java, rewrite-test/src/test/java/org/openrewrite/test/internal/RewriteTestTest.java
In the cases where the description ends with a list of resources
the recipe should allow that the list not end with a period.
Modifies `RecipeTest#validateRecipeNameAndDescription` to support descriptions
that are not terminated in a `.` under certain conditions.
I want to write a recipe that has a description that ends with a list of links.
The formatting is very weird if this list is required to end in a `.`
Are there other conditions that I should be testing for here?
Recipe authors could manually override `validateRecipeNameAndDescription` to change the behaviour of the validation, but this seems like a better general solution.
=> Allow non-period terminated Recipe descriptions

rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenWrapper.java, rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenWrapper.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenWrapperTest.java
- Make sure the files are updated in place when updated
- Do not escape colons in the URLs injected in the .properties file. When using `mvn wrapper:wrapper` you don't get colons and they are actually causing issues at least for the `maven-wrapper.jar` as this property is not loaded from Java
- Avoid adding the `maven-wrapper.jar` checksum by default as it's causing issues on Windows due to https://issues.apache.org/jira/browse/MWRAPPER-103 -> this is probably something we need to discussed
- https://github.com/openrewrite/rewrite/issues/3982
- Discussions in https://github.com/quarkusio/quarkus/issues/38569
I didn't have the time to add tests for the first commit yet. I'll have a look at it in the next days as time permits if nobody beats me to it.
@timtebeek @shanman190 
^ Is there a …
=> Assorted UpdateMavenWrapper fixes

rewrite-java/src/main/java/org/openrewrite/java/recipes/RewriteTestClassesShouldNotBePublic.java, rewrite-java/src/test/java/org/openrewrite/java/recipes/RewriteTestClassesShouldNotBePublicTest.java
One less thing to keep an eye on in reviews; mostly lifted from the existing `TestsShouldNotBePublicTest` that does not match when there's overridden methods, and we can't safely change `TestsShouldNotBePublicTest` for other cases.
=> Add RewriteTestClassesShouldNotBePublic recipe for reviews

rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java, rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java
When a declarative recipe contains both preconditions and scanning recipes in its list, the scanning recipe's scanner is never executed because the bellwether precondition doesn't get initialized until the execute phase. Similarly, the generate phase won't be executed either, because `BellwetherDecoratedScanningRecipe` doesn't cater for this.
This PR changes this by always running the scanning and generate phase of any contained scanning recipes. This at least allows scanning recipes to function properly.
More fine grained control of how preconditions should apply to the scanning phase are the subject of #4005.
=> Allow declarative preconditions for scanning recipes

rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java, rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
This PR fixes the Regex Pattern in XPathMatcher to support the 'dot' character in xPaths. 
I was trying to use the xPathMatcher to find a match for a groupId in a pom file (e.g. `dependency[groupId='com.fasterxml.jackson']`). However, I noticed that the Regex pattern defined [here](https://github.com/kislam01/rewrite/blob/main/rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java#L43) does not support the 'dot' character, which is why it wasn't able to find a match for the groupId. This PR aims to resolve this issue.
=> Fixed regex in XPathMatcher to support dots

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/format/AutoFormat.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/format/AutoFormatVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/format/MinimumViableSpacingVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/service/GroovyAutoFormatService.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/G.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/format/AutoFormatVisitorTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/format/NormalizeLineBreaksTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/format/NormalizeTabsOrSpacesTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ConstructorTest.java
Bringing back some auto formatting rules to the `G` type. This focuses on tabs VS spaces, normalizing EOL characters, blank lines, and removing trailing whitespace.
Historically, Groovy auto formatting was a bear and would pretty often result in files becoming invalid. As a result, it was disabled fully in the `org.openrewrite.java.format.AutoFormatVisitor`, so that the Java auto formatting rules would never be applied to any non-`J` type.
While re-introducing auto format support, I found two bugs. One of which is found fixed within this PR, but the other has been noted with a pair of disabled tests.
* If a visitor used with `withClasses` or `withImports` on an instance of `G`, this would result in the `G.CompilationUnit` being recreated due to a bug in the logic. Specifically, getting …
=> Enhance autoformat logic for Groovy files

rewrite-core/src/main/java/org/openrewrite/Cursor.java, rewrite-core/src/main/java/org/openrewrite/Repeat.java, rewrite-java-test/src/test/java/org/openrewrite/RepeatTest.java
The `Cursor` wasn't being set in `Repeat` causing issues when
used for non `SourceFile` trees.
Adds a call to `setCursor` in the loop for `Repeat`.
Also adds internal validation that `Repeat` is being called with the correct
`Cursor` set.
When using `Recipe` visitors on sub-trees, and those visitors called `autoFormat` they were failing
when the `JavaSourceFile` couldn't be located in the `Cursor` hierarchy.
=> Correctly set `Cursor` in `Repeat`

rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java
I often find myself shooting myself in the foot passing the wrong `Cursor` to `visitNonNull`.
This is a very easy mistake to make and often leads to quite a bit of confusion.
This fixes that by validating that a parent cursor is being passed, not the current cursor.
Adds a bit of sanity validation to `visitNonNull(Tree tree, P p, Cursor parent)`
AFAIK this method is really only called when composing one visitor of another visitor, and
isn't called in the hot-path for normal LST tree traversal.
Reduce how often I and other's new to OpenRewrite make the mistake of passing the `Cursor` for the tree, instead of passing the parent cursor.
=> Fix 🦶🔫: Validate `visitNonNull` arguments

rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java
As spotted while going over
- https://github.com/openrewrite/rewrite/pull/4006
=> Only process markers when using type in AddDependency

rewrite-core/src/main/java/org/eclipse/jgit/util/FS.java, rewrite-java/src/main/java/org/openrewrite/java/recipes/FindRecipes.java
I'm really curious and want to try the new Error Prone Support integration! 
Use this link to re-run the recipe: https://app.moderne.io/recipes/tech.picnic.errorprone.refasterrules.StringRulesRecipes?organizationId=T3BlblJld3JpdGU%3D
=> refactor: Refaster rules related to expressions dealing with `String`s

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavaTemplateSemanticallyEqual.java
When a `JavaTemplate` contains the same parameter repeated multiple times, the result returned by `find()` should only register it once.
=> Fix `JavaTemplate` matching of repeated parameters

rewrite-java-test/src/test/java/org/openrewrite/java/search/HasJavaVersionTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/search/UsesMethodTest.java, rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java, rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java, rewrite-java/src/main/java/org/openrewrite/java/search/FindMethods.java, rewrite-java/src/main/java/org/openrewrite/java/search/UsesMethod.java
When `FindMethods` is used on a source file that already has a `SearchResult` marker on the root node (as e.g. added by `HasJavaVersion`) then the recipe will not find anything, because its `UsesMethod` precondition evaluates to `false` (because the root node already has a `SearchResult` marker).
To avoid this aliasing issue and also avoid issues if `UsesMethod` is applied before another recipe / visitor that adds a `SearchResult` marker, the `UsesMethod` visitor now uses its own marker type. The marker will only be added if the source file doesn't already have a marker which was created for the same method pattern.
=> Let `UsesMethod` add its own marker

rewrite-maven/src/main/java/org/openrewrite/maven/AddPlugin.java
Fix documentation example for maven.AddPlugin
The <executions> element has to be included by the user, as is made clear in AddPluginTest: https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/test/java/org/openrewrite/maven/AddPluginTest.java#L125-L139
One could possibly argue that the documentation is correct, but the implementation is wrong; but the implementation follows the same convention used by the other parameters (`configuration` and `dependencies`).
=> Fix documentation example for maven.AddPlugin

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
Following questions like https://github.com/openrewrite/rewrite-maven-plugin/issues/742
Now that we surface `repositoryAccessFailed` in download logs and the Maven plugin, we don't want to raise any false alarms. We seem to also have sufficiently troubleshot the issues that prompted the eager propagation of exceptions, such that a reduced case could now make sense again.
=> Only report unrecovered repositoryAccessFailed

rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
This a follow-up on #4040, `JavaParser` should try to use public class names, when available.  
Identified while testing #4030 
No
No
You can provide the correct source path when calling the Java Parser directly, but not when the parser is being called by a `JavaTemplate`.
No
=> `JavaParser` should favor public classes when naming source inputs

rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
The String representation of a path is related to the OS (or more correctly the underlying file system implementation). Compare the path without converting to String to be OS agnostic.
The unit test failed on Windows, because of slash-versus-backslash issues. With this change applied, all tests pass on my Windows system.
=> Make unit test work correctly on Windows

rewrite-java-test/src/test/java/org/openrewrite/java/AddNullMethodArgumentTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddNullMethodArgument.java
Add recipe `AddNullMethodArgument`
When changing a method we often add a nullable argument. Sometimes overriding it as to not break existing consumers. With this recipe we can migrate more quickly by adding a null value as the argument.
line 104 of the recipe, creating the actual `null` literal.
~Also `addArgumentsConsecutively` is not working as expected. Any suggestions? If not I'll give it another try soon.~
@timtebeek
=> Add `AddNullMethodArgument` recipe

rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java
Before the change the build has this warning
```
C:\dev\openrewrite\git\rewrite\rewrite-maven\src\main\java\org\openrewrite\maven\UpgradePluginVersion.java:169: warning: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
@Value
^
```
=> Fix build warning about generated equals/hash

rewrite-test/src/main/java/org/openrewrite/Issue.java
Allow multiple issue annotations for a test.
I once used that accidentally because I have it in other projects, and had to fix the PR after I noticed the compile error.
It uses a nested interface for the container class to avoid it being shown in typical code completion of the IDE.
=> Make @Issue repeatable

rewrite-java-test/src/test/java/org/openrewrite/java/AddLiteralMethodArgumentTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddLiteralMethodArgument.java
This recipe finds a method and adds a literal argument at the specified index.
Recipe was added
In stead of only adding a null argument we can now also specify a literal. This means when adding an argument and fixing the calls with a recipe we no longer need to require the field to be boxed and nullable for primitives.
-
@timtebeek 
No
It's very similar to the `AddNullMethodArgument` recipe added last week.
=> Add recipe `AddLiteralMethodArgument`

rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependency.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyVersionSelector.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddBuildPlugin.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePlugin.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddSettingsPlugin.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/ChangePlugin.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/UpgradePluginVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/ChangePluginTest.java
* Adapted to use new `DependencyVersionSelector`
* Previsit `J.MethodInvocation` instances such that we can properly migrate a plugin declaration only when it matches the previous plugin id.
Previously, plugins would be downgraded as long as they matched the new plugin id.
N/A
=> Previsit method invocations for `gradle.ChangePlugin`

rewrite-properties/src/main/java/org/openrewrite/properties/PropertiesParser.java, rewrite-properties/src/test/java/org/openrewrite/properties/PropertiesParserTest.java
In the state machine of the properties parser do not accept further delimiters after the first non escaped delimiter was found.
Fixes #4026.
The actual bug fix is in the first commit, so you may want to review it separately. The second commit removes all arithmetic from the state variable and gives readable names to the states to make debugging more simple for the next one looking into this.
=> Parse property values starting with the delimiter character

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyTypeMapping.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AttributeTest.java
Improved the groovy parser to support:
- reference to FQNC like in the `ProcessBuilder.Redirect.to(..)` call
- groovy xml node attribute manipulation like `n.@conf = 'runtime->default;docs->docs;sources->sources'`
I tried to use the ChangeDependency recipe on an old gradle build with lots of custom code
- in `GroovyTypeMapping#classType`, in production i've encountered some `ClassCastException` where `JavaType.Unknown` cannot be casted to `JavaType.Class` but i was not able to reproduce in unit tests. I found that downcasting to `JavaType.FullyQualified` avoids the CCE and does not seem to break something else
=> Fix gradle build files parsing issues

rewrite-java-test/src/test/java/org/openrewrite/java/VariableNameUtilsTest.java, rewrite-java/src/main/java/org/openrewrite/java/VariableNameUtils.java
Used in `InstanceOfPatternMatch` to detect variables that exist in the surrounding context, which now fails to pick up pattern matching for instance of variables, and as such introduces two identically named variables.
- https://github.com/openrewrite/rewrite-static-analysis/pull/265
- https://github.com/openrewrite/rewrite-static-analysis/pull/175
=> Detect instanceof pattern variables in scope

rewrite-java-test/src/test/java/org/openrewrite/java/RenameVariableTest.java, rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
TypeCasts and nested FiedAccess are now supported when renaming variables
Fix issue #4059
@timtebeek
=> Fix RenameVariable for variables referenced through type casts

rewrite-maven/src/main/java/org/openrewrite/maven/search/FindProperties.java, rewrite-maven/src/main/java/org/openrewrite/maven/table/MavenProperties.java, rewrite-maven/src/test/java/org/openrewrite/maven/search/FindPropertiesTest.java
The valuePattern allows use as DevCenter measurement, while the table enables custom visualizations.
Target use is the `<jenkins.version>` used in Jenkins plugins.
=> Add table and version matcher to Maven FindProperties

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Closes #4080.
Might take a couple iterations in Actions; I wrote/tested this in a weird network environment. Fingers crossed.
=> ensuring connection timeouts get wrapped by MavenDownloadingException

rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
`AddDependency` now works with empty maven projects
Refactor Spring Boot Starters
No
No
N/A
N/A
=> Add dependency now works with empty maven projects

rewrite-core/src/main/java/org/openrewrite/RecipeRun.java, rewrite-core/src/test/java/org/openrewrite/RecipeRunTest.java
Added logic in the RewriteRun Class in Rewrite-Core to output Datatable values as a CSV
Datatable information is currently only accessible in memory in OSS, rendering it extremely difficult to use/access.  This change (coupled with the Maven Plugin PR below) would allow easy access to any datatable information created by recipes. This is especially useful for OSS users wanting to use recipes designed to only output datatable information. 
See related [Maven Plugin PR](https://github.com/openrewrite/rewrite-maven-plugin/pull/751)
=> Printable Recipe Datatables 

rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenArtifactDownloader.java
When the repository url ends with a `/` we add another causing an incorrect URL, this results in a 404 returned from the maven repo which we translate to a `MavenDownloadingException` causing the 500 responses.
=> Fix for artifacts not found (surfacing in 500 internal server errors).

rewrite-maven/src/main/java/org/openrewrite/maven/AddProperty.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeParentVersion.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddRepositoryTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenDependencyFailuresTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeParentVersionTest.java
When the new parent pom doesn't define all the same properties or managed dependencies as the old parent pom, they will now all be brought down to the child pom.
=> Enhance ChangeParentPom to keep more projects compiling post-upgrade.

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
[See this Slack thread](https://rewriteoss.slack.com/archives/C01A843MWG5/p1711408293433509?thread_ts=1710442165.133859&cid=C01A843MWG5)
We should have support for earlib which does not extend anything yet is a default gradle thing.
Are we sure this null wasn't necessary earlier for some other reasons? Should we not add earlib as a separate if block or is any configuration okay? A manually created configuration would also be supported like this, I guess.
@sambsnyd
=> Fix for gradle configurations that do not extend another configuration to allow transitive dependency version upgrade

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
[See this Slack thread](https://rewriteoss.slack.com/archives/C01A843MWG5/p1711408293433509?thread_ts=1710442165.133859&cid=C01A843MWG5)
We should have support for earlib which does not extend anything yet is a default gradle thing.
@sambsnyd
=> Fix UpgradeTransitiveDependencyVersion

rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
In stead of enabling disabling maven central and local together, make them configurable separately.
For recipe installing we would like to use maven local in most cases but not maven central in all cases.
I replaced [existing functionality added a few hours ago](https://github.com/openrewrite/rewrite/commit/152606fe7ab2a9d7f9f55e9bbadb2e7961da993b), but it was very new so might not be depended on yet 🙏 
@sambsnyd 
We could keep both settings, but that would only be for backwards compatibility.
Sometimes Maven central is blocked on a firewall and causes long waits for a timeout before the repo will not be considered.
=> feat: Granular enable/disable adding default/fallback repositories

rewrite-java-test/src/test/java/org/openrewrite/java/format/MinimumViableSpacingTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/format/SpacesTest.java, rewrite-java/src/main/java/org/openrewrite/java/format/MinimumViableSpacingVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java
Adds a space between annotations for all cases where an `addAnnotation()` coordinate exists, which can be used together with `JavaTemplate` to add an annotation.
Fixes: #4115
=> `SpacesVisitor`: Add space between annotations

rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java, rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
[Issue#4119](https://github.com/openrewrite/rewrite/issues/4119)
the xPathmatcher supports relative Paths and conditions
[[XPathMatcher does not support paths containing "//" and conditions](https://github.com/openrewrite/rewrite/issues/4119#top)](https://github.com/openrewrite/rewrite/issues/4119)
------
-----
------
-----
=> XPathMatcher does not support paths containing "//" and conditions #4119

rewrite-xml/src/main/java/org/openrewrite/xml/CountLinesVisitor.java, rewrite-xml/src/main/java/org/openrewrite/xml/XmlIsoVisitor.java, rewrite-xml/src/main/java/org/openrewrite/xml/XmlVisitor.java, rewrite-xml/src/main/java/org/openrewrite/xml/internal/XmlPrinter.java, rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java
* `visitTagClosing()` for `Xml.Tag.Closing`
* `visitAttributeValue()` for `Xml.Attribute.Value`
* `visitDocTypeDeclExternalSubsets` for `Xml.DocTypeDecl.ExternalSubsets`
=> Add missing `visit()` methods to `XmlVisitor`

rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Fix invalid pattern in https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java#L123
The `file.getName()` and pattern `Pattern.compile("[/\\\\]" + artifactName + "-?.*\\.jar$")` is mismatch so that the pattern.matcher will always be `false`. The `file.getName()` returns a simple filename without any `/` but the pattern needs a `/`.
See more details in https://github.com/openrewrite/rewrite/issues/4123
Fix https://github.com/openrewrite/rewrite/issues/4123
No
No
No
No
=> fix invalid jarPattern in JavaParser

rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java, rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
tbd
[#4120 ](https://github.com/openrewrite/rewrite/issues/4132)
I am not 100% sure if my new condition is 100% correct but i cannot think of other testcases. Maybe the review can think of more
The xPathMatcher did not check if the condition was forthe previous element in the xPath and accepted every tag a condition was met.
eg. //dependency[artifact-id='bla']/version and accepted //dependency[artifact-id='bla']/version and //dependency[artifact-id='bla']/artifact-id
- [x ] I've added unit tests to cover both positive and negative cases
- [x ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [x ] I've used the IntelliJ IDEA auto-formatter on affected files (for some reason my …
=> Test case for XPath Matcher matches too many tags when using relative Paths and conditions

rewrite-core/src/main/java/org/openrewrite/internal/EncodingDetectingInputStream.java, rewrite-core/src/test/java/org/openrewrite/internal/EncodingDetectingInputStreamTest.java
The sequence `C3 AF C2` is not actually the UTF-8 BOM sequence. The BOM sequence is the `\uFEFF` character, which in UTF-8 is encoded as `EF BB BF`. But if these three bytes were to get encoded as individual characters using UTF-8, then the sequence `C3 AF C2` is the first half of `C3 AF C2 BB C2 BF`. But note that this is not a proper UTF-8 BOM, but a BOM that erroneously got encoded again.
=> Correct UTF-8 BOM detection in `EncodingDetectingInputStream`

rewrite-core/src/main/java/org/openrewrite/Preconditions.java, rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java, rewrite-maven/src/test/java/org/openrewrite/maven/search/FindPluginTest.java
Precondition Bellwether uses a supplier to fetch a new visitor each time
This causes a bug when a certain condition is met
@sambsnyd 
to use recipes instead of suppliers but the suppliers feel more correct
see attachement below
- [ x] I've added unit tests to cover both positive and negative cases
- [x ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
=> preconditions are no longer cached

rewrite-json/src/main/java/org/openrewrite/json/JsonVisitor.java, rewrite-json/src/main/java/org/openrewrite/json/tree/JsonRightPadded.java
Changes `<T>` to `<T extends Json>` as that is the only way it is currently being used.
Note: In the `J` model the padding constructs are also used to wrap non-`Tree` elements, but not in `Json`.
=> Add generic type variable bound to `JsonRightPadded<T>`

rewrite-java-test/src/test/java/org/openrewrite/java/format/BlankLinesTest.java, rewrite-java/src/main/java/org/openrewrite/java/format/BlankLinesVisitor.java
Make the `aroundMethod` in [java/style/BlankLinesStyle.java](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/style/BlankLinesStyle.java#L53) also take effect in methods of anonymous inner class.
Fix https://github.com/openrewrite/rewrite/issues/4154.
No.
No.
No.
No.
=> fix: use aroundMethod for anonymous inner class in blankLines

rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddBuildPlugin.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePlugin.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddSettingsPlugin.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddBuildPluginTest.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddSettingsPluginTest.java
Enable non-eager application of plugins.
As a Gradle user sometimes it is necessary to not eagerly apply a plugin, so that you can then later apply it in the project using alternative methods.
Nothing in particular.
Anybody.
Have my own version of the recipe.
None.
=> Allow non-eager application of Gradle plugins

rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java, rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/RemoveObjectsIsNull.java, rewrite-java/src/main/java/org/openrewrite/java/format/OperatorWrap.java, rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
The name should be in line with `J.InstanceOf#getExpression()` and the `J.InstanceOf#expression` field, therefore renaming. Keeping the old method as deprecated for backward compatibility.
For the same reason also renaming `J.LambdaParameters.Padding#getParams()` to align with `J.LambdaParameters#getParameters()`.
=> Rename `J.InstanceOf.Padding#getExpr()` and `J.LambdaParameters.Padding#getParams()`

rewrite-core/src/main/java/org/openrewrite/config/Environment.java, rewrite-test/src/test/java/org/openrewrite/config/EnvironmentTest.java
When active recipe(s) not found, provide a helpful `Did you mean: ...` of closest match.
Misconfigurations are common and hard to spot, as seen in supporting OSS and even colleagues.
In particular when generated Refaster recipes are used, folks might fail to add the `Recipe` or `Recipes` suffix.
By providing the nearest match as a suggestion folks have an easier way to troubleshoot this themselves.
1. I'd expect calls to `Environment#activateRecipes(Iterable<String> activeRecipes)` to be rare enough to be ok with the streams use there. Outside perhaps tests I'd expect that to be called once per recipe run. Calling that out for review.
2. We already have a dependency on commons-lang3, which has the `getLevenshteinDistance` we use here. Didn't want to add a new dependency just for that, but …
=> Suggest alternatives when active recipes are not found

rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
I found [this issue](https://github.com/openrewrite/rewrite/issues/3200) describing problems with migrating annotations in `package-info.java`. We seem to still have this problem.
In this MR, I have added a (failing) test showing our issue.
Our actual issue is regarding applying jakarta migration for this class:
```
@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.com/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example;
```
We have made it work using `org.openrewrite.java.ChangeType` for our migration, but would prefer if `org.openrewrite.java.ChangePackage` worked for this.
Please note that this does not fix the issue, only adds a test case to it :-)
=> ChangePackage fails to migrate annotation argument enum in package-info

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
YAML supports lists of lists. They are not common but sometimes required, for example, in some AWS CloudFormation templates. Currently, the YamlParser doesn't correctly parse these lists. It adds additional hyphens.
```
Original     ->     After parsing
root:               root:
- - a               - - - a
- b                 - b
```
This happens for every line that contains multiple hyphens (like for the 'a' line in the example above).
That's because the parser interprets these hyphens twice. Once as a SequenceEntry and once as prefix for the last block of that line (in this example, the scalar 'a').
The bug is in SequenceBuilder.push. This method builds the prefix of a given block by using the substring between the FIRST hyphen and the block itself. So if there is more than one hyphen …
=> YAML: Support lists of lists

rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependency.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/AddDependencyVisitor.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java
Due to the Groovy compiler misinterpreting receiver classes for the `dependencies` block, this can result in the `gradle.AddDependency` recipe placing new dependencies improperly.
* Fixing gh-4094
Just the pattern of using a `Predicate` from the recipe standpoint as the mechanism with which to invert the control flow and allow more specific insertion points from a dependency standpoint.
Anybody who wants to double check the work.
None
None
=> Only allow Gradle `AddDependency` to add dependencies to the top-level `dependencies` block

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
The commit 264e8e86 introduced support for list of lists of scalars. But this didn't fix lists of lists of other blocks (like mappings). This commit will also fix these cases.
The underlying problem was that some tokens were interpreted twice. This was caused by YamlParser.parseFromInput. This method calculates the prefix of a token by using the substring yamlSource[lastEnd:tokenIdx]. Normally, the characters that were newly interpreted should be marked as used by incrementing the index `lastEnd`. But for sequences this index wasn't updated in every case. It was only updated if there was an anchor or an openingBracketIndex. Because of this, the prefix was used for multiple consecutive sequences in other cases.
To fix this, update `lastEnd` in every case for sequences.
The yaml-parser has …
=> YAML: Support other cases of lists of lists

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java, rewrite-test/src/main/java/org/openrewrite/test/SourceSpec.java
`ChangeClassDefinition` in `ChangeType` previously changed package declaration of sibling types, this PR restricts these to only the classes that should actually be changed
Closes https://github.com/openrewrite/rewrite/issues/4182
~~I'm not exactly sure as to whether this is the proper way to do it (tracking required modification in JavaSourceFile visits), but at the very least this should show what the root cause is. And I suppose this breaks the immutability rule~~ should be addressed now
=> Don't modify package declaration of siblings in ChangeType

rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java, rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/RemoveAnnotationVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/format/NormalizeFormatVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/format/WrappingAndBracesVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Instead, the already existing `Padding` wrapper can be used to access the raw `kind` property value.
=> Remove `J.ClassDeclaration.Annotations` wrapper

rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangePackage.java
The mistake was in `isTargetRecursivePackageName(String packageName)` not in package name match in `preVisit(..)`
When I tried to fix matching condition I found that `typeInNestedPackageInheritingFromTypeInBasePackage` test fails and then I found this
Fixes #4188
- #4188
=> org.openrewrite.java.ChangePackage precise package match

rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java, rewrite-java/src/test/java/org/openrewrite/java/style/ImportLayoutStyleTest.java
Problem:
- The presence check does not take the member of static imports into consideration
- The comparison by size cannot handle the case where the original imports contain duplicated imports making its the size be equal to that of the ideally ordered, distinct imports even after adding a new import
Fix: check the presence using the fully qualified names of imports.
Fix https://github.com/openrewrite/rewrite/issues/4196
=> Fix bug adding import to a list of imports containing duplicate imports.

rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveEnableFeaturePreview.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveEnableFeaturePreviewTest.java
Added a gradle recipe to remove the `enableFeaturePreview` method from `settings.gradle`.
Provide the feature to remove via a property.
A `rewrite.yml` file would include the recipe like this:
```
- og.openrewrite.gradle.RemoveEnableFeaturePreview:
previewFeatureName: ONE_LOCKFILE_PER_PROJECT
```
It would remove the following line from `settings.gradle`
```
enableFeaturePreview('ONE_LOCKFILE_PER_PROJECT')
```
I wrote this recipe for use at my company and was encouraged to contribute it here by @shanman190 and @timtebeek. Slack thread: https://rewriteoss.slack.com/archives/C01A843MWG5/p1715414946440599?thread_ts=1715381394.713129&cid=C01A843MWG5
=> Added gradle recipe to remove enableFeaturePreview method

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeMethodTargetToStaticTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodTargetToStatic.java
For https://github.com/openrewrite/rewrite-migrate-java/pull/477
Previously any cases where a static method was called on an instance (improper use) then ChangeMethodTargetToStatic would not make any changes. With this change we now also flush those out.
=> ChangeMethodTargetToStatic should also change instance usage

rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java, rewrite-core/src/test/java/org/openrewrite/config/YamlResourceLoaderTest.java
Added logic to catch NoClassDefFoundError errors when loading YAML recipes with missing recipe dependencies
NoClassDefFoundError errors were previously not handled compromising troubleshooting.
Potential for regressed behaviour.
@timtebeek 
No
No
=> bug: Handle NoClassDefFoundError when loading YAML recipes with missing recipe dependencies

rewrite-gradle/src/main/java/org/openrewrite/gradle/AddProperty.java
Change overwrite example to 'true'
I just found in the `AddProperty` gradle recipe that the docs had a string example where it should have been boolean.
Here's the current docs: https://docs.openrewrite.org/recipes/gradle/addproperty
Overwrite example should be `true` or `false`, not `Enable the gradle build cache`
=> Fix documentation discrepancy

rewrite-java/src/main/java/org/openrewrite/java/search/HasBuildToolVersion.java, rewrite-java/src/test/java/org/openrewrite/java/search/HasBuildToolVersionTest.java
Add HasBuildToolVersion
Act as a filter such that we don't unnecessarily add build plugins, as seen on
- https://github.com/openrewrite/rewrite-testing-frameworks/compare/v2.9.0...v2.10.0
Enums are fine as options right?
Place this in rewrite-testing-frameworks only.
[Maven parent v32](https://github.com/apache/maven-parent/blob/maven-parent-32/pom.xml) was the first to use [Apache parent v20](https://repo1.maven.org/maven2/org/apache/apache/20/apache-20.pom).
Maven 3.5.4 [still used](https://github.com/apache/maven/blob/maven-3.6.0/pom.xml) maven-parent 31
Maven 3.6.0 [uses](https://github.com/apache/maven/blob/maven-3.6.0/pom.xml) maven-parent 33
=> Add HasBuildToolVersion

rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteProperty.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/DeletePropertyKeyTest.java
fixes #4204
Additional check added to `DeleteProperty` yaml recipe to not add `ToBeRemoved` marker if sequence was empty before the recipe has removed its entries.
=> bug: yaml: DeleteProperty: do not remove unrelated empty sequences

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Prevent `IndexOutOfBoundsException` with new workaround for issues in the underlying `YamlParser` events.
Received reports about failures with a particular Yaml snippet; with this exact snippet you hit the new conditional.
Even if you change strings in the Yaml snippet, you will not hit the new conditional; Fun times to be had tracing that down.
Ideally we report this upstream and see it resolved there.
The earlier workaround was introduced in these two commits to work around bugs with the underlying Yaml parser we use.
- https://github.com/openrewrite/rewrite/pull/4178
- https://github.com/openrewrite/rewrite/pull/4187
=> Parse troublesome Yaml with new workaround in workaround for underying parser bug

rewrite-java/src/main/java/org/openrewrite/java/ReplaceAnnotation.java, rewrite-java/src/test/java/org/openrewrite/java/ReplaceAnnotationTest.java
Add a Recipe which replaces an Annotation with a JavaTemplate.
While writing a cross Framework Migration from TestNG to JUnit Jupiter I implemented the replacement of annotations repeatedly.
This could become handy for other cross Framework Migrations as well.
=> Add recipe to replace Annotation

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java, rewrite-maven/src/test/java/org/openrewrite/maven/tree/PomTest.java
When ascertaining if a recipe dependency was downloaded in `MavenPomDownloader` only POM packaging types of "jar" where verified to have a non-empty jar file downloaded. The POM packaging type "bundle" is also a single jar and the current code was skipping validation for such dependencies resulting in failures to install recipes. These changes include the "bundle" packaging type when verifying a recipe dependency was downloaded.
Fixes a customer issue when attempting to install a recipe with a dependency having a bundle packaging type. Eg https://mvnrepository.com/artifact/net.minidev/json-smart/2.5.1
No
@sambsnyd 
No
No
=> fix: Recognize bundle POM packaging type as jars when verifying recipe dependency downloads

rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyUseStringNotation.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/DependencyUseStringNotationTest.java
The existing recipe does not take classifiers into consideration and simply removes them. 
We should either support it, or not change the dependencies with classifiers. 
Decided we want to support it.
Classifiers are supported by both notations.
I only add the classifier if a version is specified. Otherwise, if no version is specified, it would be added to the string like it is a version.
Not migrating to string notation if classifier is mentioned could also be done, but less optimal
=> Added classifier support to DependencyUseStringNotation recipe

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTypeTest.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
This will help us detect that, for example, `java.util.Collection#add` is overridden by `java.util.List#add`.
=> Strengthen override method determination for generic parameters

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
Added a simple method name check to avoid a bug int he current recipe.
Current created constraints are invalid. This PR closes #4228
We could stop the recursive self calls at a sooner point but I tried and could not find the correct point to do this.
We could check for other calls, but did not find any other J.MethodInvocations in our codebase/my experience.
=> Do not add constraints inside version J.MethodInvocations part of the constraint itself.

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
In this version, the recipe will by default consider all transitive configurations to be adding constraints. 
One can limit this behaviour by specifying constraints that need to be considered. 
Eg. in the light of vulnerability patching, a recipe runner might only be interested in running against `runtime` jars. 
That would be feasible by specifying both default runtime available configurations(implementation, runtimeOnly) + any manually added **transitive** ones.
This change will only have impact if a configurations list was specified. We reintroduce/combine earlier behaviour by checking for the extendsFrom + must be transitive. 
Added some test cases to further explain expectations/behaviour.
See #4230 for a blacklist approach
Our preference goes towards a whitelist approach as that …
=> Only consider specified configurations for UpgradeTransitiveDependencies created constraints

rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveRedundantDependencyVersionsTest.java
Added property version resolution for dependencies/plugins using the maven property syntax to define versions and removed the early exit logic for this case.
Redundant Dependencies and Plugin versions defined through maven properties should still be removed by this recipe instead of being ignored.
=> Add Property Resolution to RemoveRedundantDependencyVersions

rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java, rewrite-java/src/test/java/org/openrewrite/java/style/ImportLayoutStyleTest.java
Closes: #4241
We will close the bug explained in the mentioned issue.
We do not want to have imports on a single line.
If we need to go for another solution, at least the test case is already pushed.
See Issue for other possibilities. Or expect from EU that always imports are sorted.
=> Import get inserted at correct index with newline space

rewrite-core/src/main/java/org/openrewrite/DataTable.java, rewrite-core/src/main/java/org/openrewrite/MyRecipe.java, rewrite-core/src/main/java/org/openrewrite/NlsRewrite.java, rewrite-core/src/main/java/org/openrewrite/Option.java, rewrite-core/src/main/java/org/openrewrite/Recipe.java, rewrite-core/src/main/java/org/openrewrite/config/CategoryDescriptor.java, rewrite-core/src/main/java/org/openrewrite/config/ColumnDescriptor.java, rewrite-core/src/main/java/org/openrewrite/config/OptionDescriptor.java, rewrite-core/src/main/java/org/openrewrite/style/NamedStyles.java
When implementing recipes, the `@Nls` annotation will help guide folks to case the display name and description correctly.
=> Use `@Nls` annotations to hint at sentence-case requirements

rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java, rewrite-java/src/test/java/org/openrewrite/java/internal/template/TypeParameterTest.java
This PR ensures that withFullyQualifiedName never hides the original `Parametrized` type, which includes info about generic params
I noticed that bug, so I decided to fix it right away by PR
=> Fix `Parameterized` is hidden by `withFullyQualifiedName`

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateSubstitutionsTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
Update `BlockStatementTemplateGenerator` to separately handle `J.MethodInvocation`, and not produce an assignment when the methodInvocation has a void return type. This prevents a compiler error for such templates. Additionally wrap any generated template for J.MethodInvocation in a block (`class Template {{ ... }}`, as opposed to `class Template { ... }`) to allow for throwing exceptions.
Broke the recipes generated for this one, which contained `final JavaTemplate after = JavaTemplate.builder("throw new AssertionError();").build();`.
https://github.com/PicnicSupermarket/error-prone-support/blob/d81fe19836db9f0001fb9c01370a3b808c46b440/error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TestNGToAssertJRules.java#L156-L167
Could have nested the generated template in the …
=> Allow JavaTemplate to throw new Exception

rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java
`visitStatement()` now also calls `visitMarkers()` for the markers on the `JRightPadded` object.
=> Add dedicated `JavaPrinter#printStatementTerminator()`

rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java, rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java
I've updated the way that DeclarativeRecipe.validate() works. Before, it was always required to call `DeclarativeRecipe.initialize()` in order to validate that all recipes were initialized before using the recipe.
There are use cases where a DeclarativeRecipe can be constructed with already-instantiated recipe objects. In this case, we don't want to require initialization. 
N/A
@sambsnyd 
Yes, the most important part here was to fix a null pointer. Before this change, the validation code was as follows:
```
return Validated.<Object>test("initialization",
"initialize(..) must be called on DeclarativeRecipe prior to use.",
this, r -> initValidation != null)
.and(validation)
.and(initValidation);
```
If `initialize` was not called, then `initValidation` would be null. the …
=> feat: If DeclarativeRecipe only has already-initialized recipes, don't require initialization

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Fixes: #4275
A check before casting. If it is not a string, it is most likely not a dependency notation. 
In line with: "Do not change anything if we are not sure", I propose to just give back this argument as is without touching. 
This is actually not meant to be coded like this in gradle, yet it is working unfortunately and has been copy/pasted througout some of our repo's.
=> Ignore method invocation arguments that are not string J.Literals

rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
Declarative recipes with preconditions no longer ignore "causesAnotherCycle" of bundled recipes.
I don't know how to test this as I couldn't reproduce it in unit tests (seems to always run extra cycles when testing?). I'm fairly new to OpenRewrite so any guidance would be welcome.
A declarative recipe I'm working on was not completing as expected.
It looked like additional cycles caused by one of the recipes in the list were not being processed.
Since I couldn't reproduce it in my unit tests, I debugged the use case and noticed that causesAnotherCycle was not properly delegated to my recipe causing the run to end prematurely.
I run OpenRewrite via the IntelliJ plugin.
=> fix: fix bellwether decorated recipe ignoring causesAnotherCycle

rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java, rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java, rewrite-core/src/test/java/org/openrewrite/RecipeRunTest.java, rewrite-core/src/test/java/org/openrewrite/text/FindAndReplaceTest.java, rewrite-java-test/src/test/java/org/openrewrite/text/FindAndReplaceJavaTest.java
Added a Plaintext Only option to the find and replace recipe, which when enabled, limits the recipe to only act on plaintext files. This option defaults to false.
FindAndReplace by default replaces text in for most sourcefile types, which may not be desirable in certain cases since this recipe coverts any sourcefile to a plaintext file, thereby causing information loss for the rest of the recipe run. Enabling this flag limits the recipe scope to plaintext files for cases where a user only wants to replace something thats already parsed as a plaintext file. 
For example, this flag could prove useful in [this](https://github.com/openrewrite/rewrite-spring/pull/538) PR where we only want to touch manifest and dockerfiles.
=> Add PlaintextOnly Option to FindAndReplace Recipe

rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveDuplicateDependenciesTest.java
Find managedDependency() did not take type into account
It is a valid case to specify different dependencyManagement dependencies for the same artifact but with different types (used for example if you create a test-jar of a dependency and manage its version). Without this fix, the RemoveDuplicateDependencies recipe removed duplicate dependencyManagement dependencies with same artifact but different types
=> Preserve multiple dependencyManagement with different types

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
When we change the type of identifiers, also recreate any static imports, same as we do for method invocations.
These static imports are also removed when the RemoveImport visitor removes non-static imports, so we really need to recreate these as opposed to changing the type of an existing import.
- Fixes https://github.com/openrewrite/rewrite-jackson/pull/6
=> Recreate static imports for identifiers in ChangeType

rewrite-core/src/main/java/org/openrewrite/Recipe.java, rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java, rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java
Fixes a problem where RecipeDescriptor does not have the options on it when a recipe has preconditions.
When a recipe is actually a delegate it can return that delegate to be used in option extraction.
Currently a recipe with preconditions will have no options on the descriptors of children
Adding a specific check for the Bellwether wrapper, but I think this is cleaner.
=> fix: Add DelegatingRecipe to find underlying recipe for loading options

rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
Check if import dependency was already resolved before
Add a check if import dependency was already resolved before
To avoid StackOverflowError in case of circular import deps 
- https://github.com/openrewrite/rewrite/issues/4093
Fixes https://github.com/openrewrite/rewrite/issues/4093
=> Fix StackOverflowError in case of circular import deps

rewrite-maven/src/main/java/org/openrewrite/maven/RenamePropertyKey.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemovePropertyTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/RenamePropertyKeyTest.java
`UpdateMavenModel` visitor only adds or modifies properties but never removes them.
Consequently, `RemoveProperty` recipe would only remove property from XML but leave it in the model unless parent or dependencies have changed. Tests are modified to demonstrate the issue and test for it.
=> Remove property in maven model

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
After 
- https://github.com/openrewrite/rewrite/pull/4291
We continued to see issues in
- https://github.com/openrewrite/rewrite-jackson/pull/6
I've updated the test to better replicate the issue there. With this change the test fails with left imports.
```diff
Unexpected result in "A.java":
diff --git a/A.java b/A.java
index 98d3bcb..da17811 100644
--- a/A.java
+++ b/A.java
@@ -1,6 +1,8 @@ 
import com.fasterxml.jackson.databind.ObjectMapper;
+import com.fasterxml.jackson.databind.SerializationFeature;
import static com.fasterxml.jackson.databind.SerializationFeature.WRAP_ROOT_VALUE;
+import static org.codehaus.jackson.map.SerializationConfig.SerializationFeature.WRAP_ROOT_VALUE;
class A {
void test() {
```
=> ChangeType leads to botched imports for nested fields

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenMetadata.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenMetadataTest.java
Prevent an NPE by adding a null check, and changing the API response to be nullable to handle it downstream.
A community member [reported seeing an exception](https://rewriteoss.slack.com/archives/C01A843MWG5/p1719241761219139?thread_ts=1719084080.404999&cid=C01A843MWG5) that I can't explain otherwise.
```
[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:5.34.1:run (default-cli) on project xxx-v1: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:5.34.1:run failed: Error while visiting pom.xml: java.lang.NullPointerException: Cannot invoke "org.openrewrite.maven.tree.MavenMetadata.getVersioning()" because "metadata" is null
[ERROR]   org.openrewrite.maven.tree.MavenMetadata.parse(MavenMetadata.java:85)
[ERROR] …
```
=> Handle MavenMetadata parser result NPE as reported by community member

rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java, rewrite-xml/src/main/java/org/openrewrite/xml/tree/Namespaced.java, rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java, rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java, rewrite-xml/src/test/java/org/openrewrite/xml/search/HasNamespaceUriTest.java
Add support for `namespace-uri()` conditions in XPathMatcher, along with tests
Add attribute match support in XPathMatcher (`/@attributeName`)
Update XPath splitter to handle URLs
Be able to use namespace filters in XPathMatcher
@sambsnyd @timtebeek 
FYI: @ammachado 
Unsure about the addition of the new Interface `Namespaced` (or its naming). Just wanted to be able to run one of my methods on both `Xml.Tag` and `Xml.Attribute` objects.
=> Add XPath support for namespace-uri() condition and attribute elements

rewrite-java-test/src/test/java/org/openrewrite/java/RemoveObjectsIsNullTest.java, rewrite-java/src/main/java/org/openrewrite/java/RemoveObjectsIsNull.java
This version includes parentheses around the JavaTemplate expressions to ensure correct negation handling, and uses SimplifyBooleanExpressionVisitor to simplify expressions as needed.
- Fixes #4244
=> RemoveObjectsIsNull fails on negated expressions fixed

rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java, rewrite-maven/src/main/java/org/openrewrite/maven/MavenSettings.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenModel.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepository.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepositoryMirror.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenSettingsTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/tree/MavenRepositoryMirrorTest.java
Replace the `connectTimeout` and `readTimeout` on `MavenSettings` and `MavenRepositoryMirror` with a singular `timeout`.
Based on what's available by default according to the docs, as opposed to our accidental custom format previously. https://maven.apache.org/guides/mini/guide-http-settings.html#connection-timeouts
There's a change to a tree class in here that's likely the only one serialized
`rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepositoryMirror.java`
In practice these won't have had a non-null value, as we diverged from the standard.
That's why I think it ought to be safe(r) to change this serialized class, as opposed to when there would have been values present to migrate over.
There's also the more challenging per-http-method-connect/read-timeout. That's …
=> Switch to a single timeout for MavenSettings and MavenRepositoryMirror

rewrite-java-test/src/test/java/org/openrewrite/java/UseStaticImportTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/search/MaybeUsesImportTest.java, rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java
Ensure that an import static is not created if a method with the same name already exists, either locally (this fixes this to take into account package name) or already imported statically.
- Fixes https://github.com/openrewrite/rewrite/issues/4304
=> Fix method name collisions with UseStaticImport

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java
Not able to (unit) test due to no known circular dependencies in OSS packages.
Fixes #4299
=> Resolved stackoverflow exception for circular dependencies.

rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java, rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
Add XPath support for:
- chained conditions   eg. `//*[condition1][condition2']`
- `and`/`or` operators   eg. `//*[condition1 or condition2]` and `//*[condition1 and condition2]`
=> XPath condition enhancements - multiple conditions and and/or operators

rewrite-core/src/main/java/org/openrewrite/trait/TraitMatcher.java, rewrite-java/src/main/java/org/openrewrite/java/trait/Annotated.java, rewrite-java/src/main/java/org/openrewrite/java/trait/Literal.java, rewrite-java/src/main/java/org/openrewrite/java/trait/Traits.java, rewrite-java/src/test/java/org/openrewrite/java/trait/AnnotatedTest.java, rewrite-java/src/test/java/org/openrewrite/java/trait/LiteralTest.java, rewrite-java/src/test/java/org/openrewrite/java/trait/VariableAccessTest.java
_Much_ easier to get at annotation attribute values and literal values.
=> `Annotated` and `Literal` traits

rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePlugin.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePluginTest.java, rewrite-maven/src/main/java/org/openrewrite/maven/AddDevelocityMavenExtension.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddDevelocityMavenExtensionTest.java
Gradle Enterprise was renamed to Develocity and as such the Gradle plugin has been equally renamed including with a Maven POM relocation. Additionally changes to the configuration names have been introduced as part of the product rename and must be taken by end users.
https://docs.gradle.com/enterprise/gradle-plugin/legacy/#develocity_migration
https://docs.gradle.com/enterprise/maven-extension/legacy/#develocity_migration
Not in particular.
Do the migration manually
* #4134 
* #4135
=> Migrate add Develocity recipes to handle the new develocity configurations

rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/MigrateGradleEnterpriseToDevelocity.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/MigrateGradleEnterpriseToDevelocityTest.java
Add migration recipe for Gradle projects to take existing Gradle Enterprise configurations and migrate those to their Develocity counterpart.
Fixes #4135.
Nothing in particular.
Anyone
Do the migration manually
https://docs.gradle.com/enterprise/gradle-plugin/legacy/#develocity_migration
=> Add Gradle Enterprise to Develocity 3.17+ migration recipe for Gradle

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
We returned a TreeVisitor from `getVisitor(Accumulator)`, which then implicitly returns true, meaning we incorrectly skipped the Maven visitor for `pom.xml` files, calling the Gradle visitor instead. https://github.com/openrewrite/rewrite-java-dependencies/blob/2e3f39c4863b943cdaacb39d0e788c9c73e3f949/src/main/java/org/openrewrite/java/dependencies/UpgradeTransitiveDependencyVersion.java#L128-L133
With this change we only return true for Groovy and Properties files, as we should.
- Fixes https://github.com/openrewrite/rewrite-java-dependencies/pull/106
=> Gradle UpgradeDependencyVersion visitor should override isAcceptable

rewrite-core/src/main/java/org/openrewrite/shell/exec/ShellExecutor.java
Adding a default executor for running npm commands in code mod recipes.
Standardize execution of npm commands in codemod recipes and allow for customization of the environment the commands are running in. The moderne platform needs to be able to customize the environment when running codemods recipes on the moderne platform to allow custom registries.
Duplicate shell running code in these code mod repos. 
https://github.com/moderneinc/rewrite-codemods/blob/main/src/main/java/org/openrewrite/codemods/NodeBasedRecipe.java#L111 
https://github.com/moderneinc/rewrite-codemods-ng/blob/main/src/main/java/org/openrewrite/codemods/migrate/angular/NodeBasedRecipe.java#L150
=> feat: add shell executor interface for running shell commands during recipe execution

rewrite-core/src/main/java/org/openrewrite/Recipe.java, rewrite-core/src/main/java/org/openrewrite/RecipeList.java, rewrite-core/src/test/java/org/openrewrite/RecipeListTest.java
Adding a mechanism to define multiple migration recipes in one recipe class... in code rather than YAML. AI code assistants are only able to offer completion suggestions in one file at a time, so adding this makes the framework more amenable to AI based code assistance.
=> `Recipe#buildRecipeList` to aid AI code assistants to write recipes

rewrite-maven/src/main/java/org/openrewrite/maven/MavenParser.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
A property resolver has also been added to the project version, not only to the parent version.
As mentioned in the issue #4319 both poms do not change if there is a property inside the version. So I took the initiative and started looking for the error. It took me a while to figure it out, but now I get it.
- Fixes #4319
=> Fixed maven multi module property version problem

rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Sometimes, inexplicably we would get this StackOverflow. Using `preVisit` will avoid this.
=> Avoid potential for StackOverflow on J#getWeight

.github/workflows/receive-pr.yml, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/MigrateGradleEnterpriseToDevelocityTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/UseStaticImportTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/format/EmptyNewlineAtEndOfFileTest.java, rewrite-java/src/main/java/org/openrewrite/java/format/EmptyNewlineAtEndOfFile.java
As the Groovy parser has a known issue that would be more effort to resolve.
This change here stops incorrect suggestions on automated code reviews, while still enforcing empty new lines at the end of files.
=> `EmptyNewlineAtEndOfFile` should retain non-whitespace characters

rewrite-core/src/main/java/org/openrewrite/config/Environment.java, rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java, rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java, rewrite-core/src/test/java/org/openrewrite/table/SourceFileResultsTest.java, rewrite-core/src/test/resources/META-INF/rewrite/test-sample-a.yml, rewrite-core/src/test/resources/META-INF/rewrite/test-sample-b.yml, rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceStringLiteralWithConstantTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/search/HasJavaVersionTest.java, rewrite-java-test/src/test/java/org/openrewrite/text/FindAndReplaceJavaTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/RenamePropertyKeyTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/search/FindPluginTest.java, rewrite-test/src/test/java/org/openrewrite/config/EnvironmentTest.java, rewrite-test/src/test/resources/META-INF/rewrite/rewrite.yml
Remove `activateAll()` and do not wrap single active recipe into a new `CompositeRecipe`.
- Removes need for edge case handling unwrap in https://github.com/openrewrite/rewrite-maven-plugin/pull/816
- Closer to what folks would expect in the simplest case: the directly instantiated Recipe, not an indirection wrapper.
The CompositeRecipe overrides a number of methods like the estimated time and data table descriptors. I think it's fine to skip this indirection, but an extra pair of eyes can't hurt.
https://github.com/openrewrite/rewrite/blob/03c458404073082275a752063887c188d213afbe/rewrite-core/src/main/java/org/openrewrite/config/CompositeRecipe.java#L25-L71
We can leave this indirection in for consistent handling no matter the number of active recipes.
- As discovered on …
=> Do not wrap single active recipe & remove `activateAll()`

rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
Fixes AddOrUpdateAnnotationAttribute to work with values of type Class
Fix a bug.
No. 
No. 
No. 
No.
=> Fix AddOrUpdateAnnotationAttribute for values of type Class

rewrite-core/src/main/java/org/openrewrite/internal/InMemoryLargeSourceSet.java, rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeRunCycle.java, rewrite-core/src/main/java/org/openrewrite/text/CreateTextFile.java, rewrite-test/src/test/java/org/openrewrite/text/CreateTextFileTest.java
generate no longer creates files at the same path multiple times
Currently the same file can be created multiple times, causing instabilities in recipe execution. For instance
running `CreateTextFile` twice in the same run causes multiple cycles changing back and forth from 1 text to the other, even if `overwriteExisting` is false
This is a change in the core recipe running and might have unwanted side-effects
@sambsnyd @timtebeek 
Fixing it on the recipe level alone, but this would require "rescanning" during the edit phase.
=> fix: Dont generate the same file multiple times & fix CreateTextFile

rewrite-yaml/src/main/java/org/openrewrite/yaml/CreateYamlFile.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/CreateYamlFileTest.java
When a precondition is present and matched, an empty file is generated but the content is not added.
```
expected: "content: yes"
but was: ""
```
`CreateYamlFile` will add content in the generate phase to work "correctly" with preconditions.
Just like CreateTextFile, CreateYaml should always add content if a file is created.
-->
=> fix: `CreateYaml` does not work the same as `CreateTextFile` with precondition

rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Added test case to test inline comment retention for mergeyaml recipe
We have same issue as described here
- https://github.com/openrewrite/rewrite/issues/2218
Nothing as of now.
@timtebeek @pstreef to review this test case
There is no work around for this issue. Developers want to retain the comments in their yaml file.
=> Merge yaml test for inline comments retention

rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java
Temporary directory created by `JavaTemplate`, subdirectories within, and files copied there were registered for deletion upon JVM shutdown.
- Fixes #4369 
- Tested only inside this project, ie. during the build. (Luckily tests for current `main` leave such directories already).
Specifically - didn't test it with maven plugin, rewrite-migrate-java, etc.
Don't know how this class is used across components.
#4369 was observed after maven ran many recipes on multi-module project.
- wait for systemd-tmpfiles to reclaim temporary but no longer used space
- manually remove files left after rewrite executions
=> Remove temporary JavaTemplate files

rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java, rewrite-core/src/main/java/org/openrewrite/scm/AzureDevOpsCloneUrl.java, rewrite-core/src/main/java/org/openrewrite/scm/AzureDevOpsScm.java, rewrite-core/src/test/java/org/openrewrite/marker/GitProvenanceTest.java, rewrite-core/src/test/java/org/openrewrite/scm/AzureDevOpsScmTest.java
- built org name from organization and project a la gitlab
- use `Pattern`s to parse Azure DevOps urls
- additional tests
- additional changes to run with `moderne-cli`
=> refactor: Azure devops refactoring

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
Modify `UpdateGradleWrapper` to only generate a wrapper when it has deduced that there also exists a Gradle project within the source set.
When running the recipe with either the default or an explicit `true` value for the `addIfMissing` parameter will result in a new Gradle wrapper being generated at the root of the project, even if one doesn't make sense for the repository at hand.
Are there use cases where a Gradle wrapper may be desired and a Gradle project doesn't exist? 🤔
Anyone
* Use a precondition to gate the generation within upstream recipes
* Be more selective when using the default or explicit `true` value for the `addIfMissing` parameter
N/A
=> Only add a Gradle wrapper if there is a Gradle project

rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java, rewrite-core/src/test/java/org/openrewrite/RecipeLifecycleTest.java, rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java
I have changed the `new Properties()` used in test `RecipeSpec` to be a class field. This allows customization of logic deeper in rewrite-core. In this case I have changed the `JsonMapper` in `YamlResourceLoader` to allow `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` to be customized. The default is that `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` is disabled as that was the existing behavior.
Users can now make their tests fail if there are unknown properties present in the recipe using
`spec.failOnUnknownProperties(true)`
I also had to update the `RECIPE_CACHE` key as the properties set can change the recipe outcome - although typically the new part of the key will be `{}` as no existing code could be configuring any properties.
This allows bugs for incorrectly specified …
=> Added test property for FAIL_ON_UNKNOWN_PROPERTIES configuration

rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Pending proper support in https://github.com/openrewrite/rewrite/issues/4054#issuecomment-2267605739 this is the easiest way not to trip over these files, such that folks don't need other workarounds to get their projects to build and run recipes.
=> Ignore module-info.java files for now

rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveRedundantDependencyVersionsTest.java
- Fixes https://github.com/openrewrite/rewrite/discussions/4386
I had doubts about including scope or classifier here as well; any thoughts there?
@crankydillo
=> Retain dependencyManagement entries with exclusions

rewrite-yaml/src/main/java/org/openrewrite/yaml/CommentOutProperty.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/CommentOutPropertyTest.java
Just demonstrate it doesn't works as expected (or I didn't understood the recipe).
Instead of commenting out the property it's removed.
=> fix: CommentOutProperty to work with single keys

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Update `GitRemote` to include port in origin.
Host port is required to avoid ambiguity between origins.
No
@pstreef 
No
No
=> fix: Include port in GitRemote origin

rewrite-gradle/src/main/java/org/openrewrite/gradle/trait/GradleDependency.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/trait/GradleTraitMatcher.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/trait/package-info.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/trait/GradleDependencyTest.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/trait/Traits.java
Added an implementation of the `Trait` api for Gradle dependencies
Having the same `Trait` api available for Gradle as was introduced for Maven.
Nothing in particular
Anyone
None
* https://github.com/openrewrite/rewrite/commit/c24e9920b509a79a9189402095b905f6ccbd1cd4
=> Add GradleDependency trait

rewrite-core/src/main/java/org/openrewrite/Tree.java, rewrite-java-test/src/test/java/org/openrewrite/java/search/FindTypesTest.java, rewrite-java/src/main/java/org/openrewrite/java/search/FindTypes.java, rewrite-java/src/main/java/org/openrewrite/java/table/TypeUses.java
`FindTypes` produces a new data table used for impact analysis.
Categorizing uses of JUnit `@Rule` in a set of repositories.
=> `FindTypes` produces data table `TypeUses`

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
When a default port is explicitly added to a url it is not considered as part of the origin. Only if the port deviates from the protocols default port do we add it.
This would avoid having 2 different origins for the same protocol and port.
no
@timtebeek  for review
@bryceatmoderne @shanman190 for reference
=> feat: Do not add explicit default ports to origin

rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java, rewrite-core/src/test/java/org/openrewrite/marker/GitProvenanceTest.java
Fixes a deserialization issue caused by the new constructor on `GitProvenance`
Is there another way to achieve this on a value class with 2 constructors without the `.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)` ?
no
Changing this to an `@Data`. But losing immutability would be bad.
=> fix: Allow deserialization of GitProvenance

rewrite-java-test/build.gradle.kts, rewrite-java-test/src/test/java/org/openrewrite/java/marker/JavaSourceSetTest.java, rewrite-java/src/main/java/org/openrewrite/java/marker/JavaSourceSet.java
They are using `fj.data.$`, which then leads to an empty String.
First noticed on recipe runs against [rewrite-migrate-java](https://github.com/openrewrite/rewrite-migrate-java), where the previous lead to:
```
Caused by: java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at …
```
=> Tolerate weird class names, as seen in functionaljava

rewrite-java/src/main/java/org/openrewrite/java/Assertions.java, rewrite-java/src/main/java/org/openrewrite/java/marker/JavaSourceSet.java
=> fix: Remove JavaSourceSet.typeToGav field to ensure Jackson serialization

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java, rewrite-java/src/main/java/org/openrewrite/java/TreeVisitingPrinter.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
Replicate generic type issue affecting a downstream PR.
```diff
diff --git a/Foo.java b/Foo.java
index c811849..2466f30 100644
--- a/Foo.java
+++ b/Foo.java
@@ -1,7 +1,8 @@ 
import batch.StepBuilder;
class Foo {
void test() {
-        new StepBuilder()
+        new StepBuilder()/*__TEMPLATE_STOP__*/
+                ./*__TEMPLATE_STOP__*/<String>method()
.<String>method();
}
}
```
This is holding up
- https://github.com/openrewrite/rewrite-spring/pull/284
Not yet explored the fix; figured log the issue first to document the problem in isolation. Any help welcome.
@knutwannheden or @sambsnyd
=> Isolate JavaTemplate issue with generic type parameters

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java
=> Better ignore blank wrapperUri when determining whether to use existing Gradle wrapper URI

rewrite-xml/src/main/java/org/openrewrite/xml/XmlParser.java
https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
https://learn.microsoft.com/en-us/nuget/reference/packages-config
Alternatively we could have picked these up from PlainText and parsed them as XML there, but that just seems needless extra steps.
There's a small risk of any non-XML `packages.config` files being picked up. I'd say that's unlikely and tolerable.
=> Parse packages.config as XML for C#

rewrite-core/build.gradle.kts, rewrite-core/src/main/java/org/openrewrite/internal/lang/NonNull.java, rewrite-core/src/main/java/org/openrewrite/internal/lang/NonNullApi.java, rewrite-core/src/main/java/org/openrewrite/internal/lang/NonNullFields.java, rewrite-core/src/main/java/org/openrewrite/internal/lang/NullFields.java, rewrite-core/src/main/java/org/openrewrite/internal/lang/Nullable.java
This sets the groundwork to mass migrate OpenRewrite to JSpecify.
Since JSpecify went GA there is now no longer any need for OpenRewrite to maintain its own meta-annotations.
=> Migrate to JSpecify

rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactId.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactIdTest.java
It was mistakenly changed here:
https://github.com/openrewrite/rewrite/pull/3843/files#diff-a3496299541c5119d2fd48e331f97b62173789f41a9ec4f5f25f9e8454ab7518R59
I made sure we don't break people who are using `newArtifact`.
- Fixes #4420
=> Restore newArtifactId property in ChangePluginGroupIdAndArtifactId

rewrite-java/src/main/java/org/openrewrite/java/service/AnnotationService.java
The `AnnotationService` will now also return any type use annotation that is on the type of a variable is in `J.@Nullable Identifier label`.
At some point the `AnnotationService` should probably offer more precise methods, which allow checking for annotations with a given target (e.g. type use), so that the expected annotations are returned / matched.
=> Check for annotations on qualified type

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
For GString substrings restore the length calculations we saw before https://github.com/openrewrite/rewrite/commit/b1cb4708f9d4acb1ad89c47d8b6d6e8d112b2f52, as this negatively affected projects using Groovy 2.5, or by extension Gradle 5 or 6.
Restore successful parsing for Gradle 5 and 6 projects that use GStrings.
This was a bit tricky to test, since we use the latest Groovy in rewrite-groovy. I was able to unit test this by adding a quick sample project:
```kts
plugins {
id("org.openrewrite.build.language-library")
}
dependencies {
implementation(project(":rewrite-groovy"))
implementation(project(":rewrite-test"))
implementation('org.codehaus.groovy:groovy:2.5.23')
}
```
And adding some unit tests there:
```java
package org.openrewrite.groovy.test;
import org.junit.jupiter.api.Test; …
```
=> Use correct length for GString substrings

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java, rewrite-core/src/test/java/org/openrewrite/marker/GitProvenanceTest.java
In stead of manipulating URIs and matching on a simple origin, we now register multiple URIs for a remote git server. This way we can indicate the multiple protocols/ports indeed point to the same server.
We can currently get multiple origins for the same server which means we could fail to match.
the `normalizeUri` method
@bryceatmoderne
=> Support multiple protocols and ports for a single `GitRemote` server and build URIs

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/LiteralTest.java
Resolve Groovy parser issues affecting Gradle projects ;
some of the tests here fare worse on Groovy 2.5.
- Follows https://github.com/openrewrite/rewrite/pull/4430
=> Groovy issues with Strings in parentheses

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeMapping.java, rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeSignatureBuilder.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeSignatureBuilder.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeMapping.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeSignatureBuilder.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeSignatureBuilder.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java, rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Try to fix #4423 by correcting the type attribution for some generics and the corresponding type assignability check.
- Fixes: #4423
=> Fixes for type attribution and `TypeUtils#isAssignableTo()`

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
the `.replaceFirst(".git$", "")` is supposed to strip off `.git` at the end of a clone url, but in the following clone url `https://github.com/openrewrite/jgit` it also matches the regex because `.` is not escaped
=> fix: do not replace jgit in clone url (regex issue)

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Strip the protocol when adding a git remote with a single origin string
We dont want protocols in origins
@bryceatmoderne
=> fix: No protocol in origin

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Add a method to find out if a remote server is registered by (possibly not normalized) origin
Knowledge is power
Am I using `@Nullable` like the cool kids do?
@timtebeek @bryceatmoderne 
guessing if a server is registered by random dice roll
no
=> Add method to find a `GitRemote.RemoteServer` registered to the `GitRemote.Parser`

rewrite-java/src/main/java/org/openrewrite/java/internal/template/AnnotationTemplateGenerator.java, rewrite-java/src/test/java/org/openrewrite/java/ReplaceAnnotationTest.java
Before we extracted all annotations; now only annotations with the template comment, avoiding confusion as to what annotation gets replaced.
- Fixes https://github.com/openrewrite/rewrite/issues/4441
=> Only extract annotations with template comment

rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java
The use of `JavaTypeVisitor` in `JavaTemplateJavaExtension` is what caused the `StackOverflowError`, as the `JavaType` graphs can contain cycles and don't provide any mechanism to guard against that.
While I understand the reason for using a `JavaTypeVisitor` to also correct the references to that type in the graph, it won't fix all references in any case, so it seems a bit futile. Until OpenRewrite provides a mechanism to "globally" update a type attribution, I feel like the best option here is to do what other recipes typically do: Just update the reference at hand.
The other alternative here would be to use the internal method `unsafeSet()`.
- Fixes: #4161
=> Prevent `StackOverflowError` in `JavaTemplateJavaExtension`

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Forcing lowercase on all URLs (and origins) registered to GitRemote
This improves the matching by being case insensitive
Should we force the locale?
@bryceatmoderne
=> Force lowercase urls and origins in `GitRemote`

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Theoretically the `newType` can already be used and therefore we should exclude it from checking ambiguity
https://ge.openrewrite.org/s/fyq3wpbm56qgk/tests/task/:test/details/org.openrewrite.apache.httpclient4.CookieConstantsTest/cookieConstantsMapping()?top-execution=1
@timtebeek
=> Fix `ChangeType` issue introduced in #4458

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
This reverts commit 758bbd8201c37fda503632fcac2f6547e7169e41.
We've concluded we are solving this in the wrong place, but rather should do the work in the Moderne SaaS code to make repository matching case insensitive. Force lowercasing it this early will result in URLs that look unnatural especially to Bitbucket users who are used to seeing project paths be all uppercased.
=> Revert "Force lowercase urls and origins in `GitRemote` (#4456)"

rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
https://ge.openrewrite.org/s/7acywy46uorxi/tests/task/:test/details/org.openrewrite.java.migrate.javax.UseJoinColumnForMappingTest/useJoinColumnForManyToOneNoAttr()?top-execution=1
@timtebeek
=> Retain default `ChangeType` behavior when dependency conflict cannot be determined

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
update `GitRemote` origin matching to be case insensitive
When a clone url has an incorrect or different case we still want to be able to match it against a registered origin.
We're comparing everything case-insensitive except for the protocol. Since the URI parsers do not like that.
We went with lowercasing everything before, but that has more implications and impacts UX
Lowercasing was released and reverted before.
=> Case insensitive origin matching

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Add a static constructor for `GitRemote.Service`
There are a few different places where different cases have been used in configurations like BITBUCKET_CLOUD or BitbucketCloud and it would be nice to have a single helper method to initiate a service.
Doing this on the consuming side
=> Add static constructor for `GitRemote.Service` from any previously used name formats

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
Ignore case on `GitRemote` string fields
A git clone URL should be compared case insensivive. All fields (except service) are derivatives
no
=> Ignore case on GitRemote equals

rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java, rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Some improvements to handling nested inner class imports
- Fixes https://github.com/openrewrite/rewrite/issues/3283
@timtebeek
=> `RemoveUnusedImports` should not remove imports for used nested classes

rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java
=> `RemoveUnusedImports` should retain explicit import when there are conflicting classes in the same package

rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java
To allow folks to override `<localRepository>` through their `settings.xml`, as opposed to jumping to `~/.m2/repository` by default.
=> Fallback to settings.xml for MavenExecutionContextView.getLocalRepository

rewrite-java-test/src/test/java/org/openrewrite/java/search/SemanticallyEqualTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/service/AnnotationServiceTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavaTemplateSemanticallyEqual.java, rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
While comparing two lambdas for semantical equality, the lambda parameter names should be ignored. This actually also applies to other variables (e.g. variables declared in a block such as a lambda body), but that is out of scope for this PR.
This will allow Refaster recipes to match a lambda against other lambdas using different parameter names.
=> `SemanticallyEqual` should allow for different lambda parameter names

rewrite-java-test/src/test/java/org/openrewrite/java/OrderImportsTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/RemoveUnusedImportsTest.java, rewrite-java/src/main/java/org/openrewrite/java/RemoveUnusedImports.java, rewrite-java/src/main/java/org/openrewrite/java/style/ImportLayoutStyle.java
Improved handling of inner classes
https://rewriteoss.slack.com/archives/C01A843MWG5/p1725947336140549
@timtebeek
=> Improve handling of inner classes

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
Use `HEAD` in stead of `GET` request to determine if a maven server exists
If a maven server does not block directory listing the listing itself might be very slow causing read timeouts.
The removed check looks redundant to me
@timtebeek 
Do nothing
no
~- [ ] I've added unit tests to cover both positive and negative cases~ (already exist)
=> Use a `HEAD` request to check if a maven server is reachable

rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveRedundantDependencyVersionsTest.java
I noticed several issues with `RemoveRedundantDependencyVersions` and plugins
- version shouldn't be removed from plugin in `pluginManagement` when no parent already defines it – probably a regression from #4156, the current logic finds the plugin in `pluginManagement` and removes the version since it is managed!
- version should be removed from `pluginManagement` when it matches the parent’s `pluginManagement`
- plugin should be removed from `pluginManagement` when nothing else is left (like for `dependencyManagement`) – need to keep it if there is configuration, executions or anything other than `groupId`, `artifactId` and `version`.
For now these are just failing unit tests to show the problems.
I would like proper management of plugins by `RemoveRedundantDependencyVersions` :)
In …
=> RemoveRedundantDependencyVersions handles pluginManagement incorrectly

rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-5.yml, rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-6.yml, rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-7.yml, rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-8.yml
When upgrading Java versions folks also need to upgrade older Gradle versions. While upgrading the wrapper is one part of that upgrade, at times there's required changes as well, in particular going from 4.x to 5.0. Some of these changes we can already automate, others might still follow now that the framework for these migrations is there.
- For the `RemoveEnableFeaturePreview` record I went by when those keys were dropped from the enum, going by latest.patch; seemed ok, but could be double checked as documentation was hard to find.
- Intentionally left out `compile` -> `api/implementation`, although that'll be a bigger pain point. Anything we can do for reasonable coverage here? Perhaps look if `java-library` plugin is defined and base our behavior on that? Or at worst merely post a …
=> Add declarative Gradle upgrade recipes

rewrite-java-test/src/test/java/org/openrewrite/java/search/FindTypesTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavadocPrinter.java
When running the "FindTypes" recipe we are getting duplicate search markers being added to the result. 
Having 2 search parameters printed in the search results is confusing
=> Fixing duplicate search markers in javaDocs

rewrite-maven/src/main/java/org/openrewrite/maven/RemoveDuplicateDependencies.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveDuplicateDependenciesTest.java
Added support for `<scope>import</scope>` in `RemoveDuplicateDependencies`
It seems we have duplicate imports in our poms 😏
I don’t really see any.
=> Handle bom import in RemoveDuplicateDependencies

rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/RawPom.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Plugin.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveRedundantDependencyVersionsTest.java
Handle the default value of plugin `groupId` as per https://maven.apache.org/xsd/maven-4.0.0.xsd
- Found after #4493 was merged and released 🙄
See also [is groupId required for plugins in Maven pom.xml?](https://stackoverflow.com/questions/65527291/is-groupid-required-for-plugins-in-maven-pom-xml) on Stack Overflow.
Someone declared a plugin without groupId…
It would be possible to fix just `RemoveRedundantDependencyVersions`, but since this default value is defined in the xsd, I thought it would be better to fix the parsing/resolution.
It was causing an invisible NPE in `RemoveRedundantDependencyVersions` for the `pluginManagement` case. I’m not sure how such exceptions should be handled.
Theoretically the `artifactId` is optional as well, but I don’t see why anyone wouldn’t provide it. …
=> Handle plugins without groupId

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
Use `maven-metadata-local.xml` when accessing `file://` URIs, as documented on
- https://maven.apache.org/ref/3.9.9/maven-repository-metadata/
Improve odds of picking up an existing local file, as opposed to downloading metadata remotely.
Presumably the local metadata might be outdated; should we guard against that somehow?
@DidierLoiseau
Locally I also see `maven-metadata-central.xml` as well as a few other repo-ids; Should we account for those?
- https://github.com/openrewrite/rewrite/issues/4508
=> Use `maven-metadata-local.xml` for `file://` paths

rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
`com.sun.tools.javac.tree.DocCommentTable#getCommentTree` used to return `com.sun.tools.javac.tree.DCTree.DCDocComment` in Java 21.
As of Java 23 it returns `com.sun.source.doctree.DocCommentTree`, an interface that was already present and implemented by `DCDocComment`.
https://github.com/openrewrite/rewrite/blob/a98d83d698dda9971c93a0767b7f85d5866f306d/rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java#L1666
This PR changes the usage downstream in `formatWithCommentTree` to use the interface instead.
- Fixes https://github.com/openrewrite/rewrite/issues/4513
A separate Java 23 parser; decided against for now as we still have work to do on our Java 21 parser, and will likely only target LST releases going forward. That said if support is easy to …
=> Accommodate Java 23 in ReloadableJava21ParserVisitor

rewrite-maven/src/main/java/org/openrewrite/maven/UpgradePluginVersion.java
As pointed out via Slack: https://rewriteoss.slack.com/archives/C01A843MWG5/p1726844234112149?thread_ts=1725959799.580249&cid=C01A843MWG5
> it seems that the issue is due to the tag being visited again after updating the property. I added some logs in the if-elseif check that you mentioned earlier and got the output after running the test with profiles.
> ```java
> if (version.trim().startsWith("${") && !newVersion.equals(getResolutionResult().getPom().getValue(version.trim()))) {
>     System.out.println("IF: Updating property: " + version);
>     doAfterVisit(new ChangePropertyValue(version, newVersion, false, false).getVisitor());
> } else if (!newVersion.equals(version)) {
>     System.out.printf("ELSEIF: version: %s, new-version: %s, resolved: %s\n", version, newVersion, …
```
=> Only bump Maven plugin version property when needed

rewrite-xml/src/main/java/org/openrewrite/xml/XmlParser.java, rewrite-xml/src/test/java/org/openrewrite/xml/XmlParserTest.java
`.vbproj` and `.fsproj` are .NET project XML files and need to be parsed as such.
Prior to these changes these file types were being parsed as `PlainText`.
No.
@timtebeek 
No.
No.
=> Parse .NET .vbproj and .fsproj files as XML

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenRepository.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
To test if a repository is reachable we currently do a HEAD request. Unfortunately a HEAD request is just as slow as a GET on artifactory. `OPTIONS` is much faster, but it does not take authentication into account and is not always supported (thinking about reverse-proxies)
With this PR we now try an OPTIONS request first, if that returns 200 we accept that the server is reachable. If an error is returned we first try a HEAD request to see if that returns a 200 (in case of maven central OPTIONS gives an error, while HEAD returns 200)
If that is OK we set `knownToExist` to true.
We still first try https before (maybe) trying the original url.
Some artifactory repositories are VERY slow at directory listing. 
`knownToExist` is now true in most cases, even if the authentication would fail. …
=> Use `OPTIONS` request before falling back to `HEAD` request when trying to connect to repositories during normalization.

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
- Fixes #4490
By allowing only distributionUri OR version/distribution, we also no longer use gradle services to determine the version which could not be available on the distributionUrl
Follow up from
- https://github.com/openrewrite/rewrite/pull/4445
=> Adding gradle wrapper through distribution is now possible

rewrite-maven/src/main/java/org/openrewrite/maven/RemoveManagedDependency.java
This one is not exactly rocket science but I noticed it while reading the doc so I might as well fix it.
See https://docs.openrewrite.org/recipes/maven/removemanageddependency .
=> Fix a very minor typo in RemoveManagedDependency doc

rewrite-core/src/main/java/org/openrewrite/TreeVisitor.java, rewrite-xml/src/main/java/org/openrewrite/xml/AddOrUpdateChild.java, rewrite-xml/src/main/java/org/openrewrite/xml/AddToTagVisitor.java, rewrite-xml/src/main/java/org/openrewrite/xml/FilterTagChildrenVisitor.java, rewrite-xml/src/main/java/org/openrewrite/xml/MapTagChildrenVisitor.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/style/Autodetect.java
Adjust some of the `@Nullable` and `@NonNull` annotations in `TreeVisitor` to reduce the number of warnings in code using the API as well as in `TreeVisitor` itself.
=> Nullability cleanups in `TreeVisitor`

rewrite-core/src/main/java/org/openrewrite/Tree.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
As the property will be phased out, mark it as write-only for serialization purposes. Also clean up some of the Jackson annotations.
=> Add `@JsonProperty` to `JavaType#getManagedReference()`

rewrite-xml/src/main/java/org/openrewrite/xml/AddOrUpdateChildTag.java, rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java, rewrite-xml/src/test/java/org/openrewrite/xml/AddOrUpdateChildTagTest.java, rewrite-xml/src/test/java/org/openrewrite/xml/XPathMatcherTest.java
Simple XML recipe that can add or update a child below the element(s) selected by XPath.
Provide more flexible ways of updating XML/pom files. In our specific case we need to configure `openapi-generator-maven-plugin` with `<useJakartaEe>true</useJakartaEe>` when it matches `<generatorName>spring</generatorName>`, following `JavaxMigrationToJakarta` (once this PR is merged, maybe it could be included there).
I had considered offering the option to add the child even when it already exists, but that wouldn’t be idempotent. I implemented an option to not replace the child in such a case, disabled by default.
I based this branch on top of #4532 so the former should be merged first and it’s not needed to review the changes on XPath implementation. I just wanted to use the XPath fixes in the …
=> Expose AddOrUpdateChild as a recipe using XPath + child XML

rewrite-maven/src/main/java/org/openrewrite/maven/RemoveRedundantDependencyVersions.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Plugin.java
`org.openrewrite.maven.tree.Plugin.getGroupId()` is now non-null, defaulting to `org.openrewrite.maven.tree.Plugin.PLUGIN_DEFAULT_GROUPID`. 
closes #4526 
This ensures no more NullPointerExceptions can occur. Plugins can have a `null` `groupId` but not all places of the code take that situation into account. By automatically defaulting to `org.apache.maven.plugins` in the getter itself, there is no more need in the code to duplicate the nullability _branching_, and potentially forgetting it. 
**I was not able to provide a test** for this case because the project being tested needs to use a parent pom that uses plugin management with plugins not explicitly setting `<groupId>org.apache.maven.plugins</groupId>`. I could not find a public pom file that I could use as a parent in the tests. …
=> Make Plugin.getGroupId() NonNull

rewrite-maven/src/main/java/org/openrewrite/maven/AddProfile.java, rewrite-maven/src/main/java/org/openrewrite/maven/AddRepository.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyClassifier.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyScope.java, rewrite-maven/src/main/java/org/openrewrite/maven/ManageDependencies.java, rewrite-maven/src/main/java/org/openrewrite/maven/RemoveDependency.java, rewrite-maven/src/main/java/org/openrewrite/maven/RemoveManagedDependency.java, rewrite-maven/src/main/java/org/openrewrite/maven/RemovePlugin.java, rewrite-maven/src/main/java/org/openrewrite/maven/RemoveProperty.java, rewrite-maven/src/main/java/org/openrewrite/maven/cleanup/DependencyManagementDependencyRequiresVersion.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddProfileTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemovePropertyTest.java, rewrite-xml/src/main/java/org/openrewrite/xml/RemoveContentVisitor.java, rewrite-xml/src/main/java/org/openrewrite/xml/RemoveEmptyXmlTags.java, rewrite-xml/src/main/java/org/openrewrite/xml/RemoveXmlTag.java, rewrite-xml/src/test/java/org/openrewrite/xml/RemoveContentTest.java
I saw in many project maven properties with an attached comment.
When running some recipes to remove properties the comment is left behind
I don't know how to fix it but I've implemented a test that demonstrates the issue
Example when cleanup property override (that are defined on a parent pom)
I would expect the TODO comment is also gone
Some help to implement it
Not really
=> Remove maven properties should remove comment

rewrite-core/src/main/java/org/openrewrite/RecipeSerializer.java, rewrite-core/src/test/java/org/openrewrite/RecipeSerializerTest.java
Jackson's `JavaTimeModule` from `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` has been added to the `RecipeSerialiser`
At a division within Port of Rotterdam's IT department we're looking into consolidating our landscape of microservices into a more concise and _better_ updated set. We've been starting to use openrewrite, including writing some own custom recipes. When testing the custom declarative recipes we found that our unit tests failed when the `estimatedEffortPerOccurrence` field was used.
A short discussion with @timtebeek on slack led to this RP: https://rewriteoss.slack.com/archives/C01A843MWG5/p1727732492972659
The tests could use some improvement probably. They work and somewhat proof the point, but are very limited.
Nope
Nope, based on the discussion on slack this …
=> Allow RecipeSerializer to (de)serialize java.time.Duration for estimatedEffortPerOccurrence field

rewrite-java/src/main/java/org/openrewrite/java/recipes/NoMutableStaticFieldsInRecipes.java, rewrite-java/src/test/java/org/openrewrite/java/recipes/NoMutableStaticFieldsInRecipesTest.java
- https://github.com/openrewrite/rewrite-hibernate/pull/40#discussion_r1789224281
=> Add recipe to remove mutable static fields from Recipes

rewrite-core/src/main/java/org/openrewrite/remote/LocalRemoteArtifactCache.java
Move cleanup of temporary artifact in the put method of `LocalRemoteArtifactCache.java` to the finally block. 
Having disk fill up in the Moderne SaaS on a large run that is updating gradle wrappers.
Related to: https://github.com/moderneinc/customer-requests/issues/620
@sambsnyd
=> cleanup temp remote artifact

rewrite-java/src/main/java/org/openrewrite/java/JavaIsoVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/JavaPrinter.java, rewrite-java/src/main/java/org/openrewrite/java/JavaVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/UpdateSourcePositions.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Allows `Modifier` LST to be visited
Consistency and resolve issues with remoting to other langugages
=> Add withModifier to base java visitors

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ImportTest.java
Add `import` to `statementDelim(Tree)` in Java ParserVisitors.
- Fixes https://github.com/openrewrite/rewrite/issues/4569
@traceyyoshima
=> Detect whitespace before import semicolon

rewrite-maven/src/main/java/org/openrewrite/maven/AddPlugin.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenResolutionResult.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddPluginTest.java
Generally to avoid conflicts in a multimodule project you want to manage plugins from a parent/root pom.
However the current behavior of the `AddPlugin` is to add it to every single pom.
@timtebeek
=> Add `addToRootPom` option to `AddPlugin` recipe

rewrite-java-8/build.gradle.kts, rewrite-java/build.gradle.kts, rewrite-test/build.gradle.kts
Use the JUnit BOM to specify the version of all JUnit dependencies.
Since `rewrite-test` uses JUnit as an `api()` dependency, this is done through `api(platform(…))` instead of `testImplementation(platform(…))`.
I tried to build OpenRewrite on my Linux Desktop machine, and I kept getting the following error:
```
> Task :rewrite-java-17:compatibilityTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':rewrite-java-17:compatibilityTest'.
> Could not resolve all files for configuration ':rewrite-java-17:compatibilityTestRuntimeClasspath'.
> Could not find org.junit.platform:junit-platform-launcher:.
Required by:
project :rewrite-java-17
```
(also with the other `rewrite-java-*` modules)
I don’t really understand why it works in other …
=> Fix missing junit-platform-launcher version

rewrite-maven/build.gradle.kts, rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeParentVersionTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
I enabled TLS support in OkHttp MockWebServer for some tests, in order to be able to reply with an actual HTTPS response.
On my machine, `MavenPomDownloaderTest` goes down from 1m15 to 18s, and `MavenParserTest` goes from **7min** to 1min! (more on this minute below)
This can also serve as POC to be used in other tests.
Some time ago, I got curious about what was making those tests so slow, so investigated them. I had kept this on the side while working on other things but I thought it was still worth integrating.
Without TLS support, the `MavenPomDownloader` first tries HTTPS before HTTP. As MockWebServer does not expect this, it tries to parse the TLS handshake as an HTTP request line, and since it does not receive a `\n`, it just waits for it until the client times out, and then it …
=> Actually use TLS in (some) Maven tests and shove a few minutes from their execution

rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyValue.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/ChangePropertyValueTest.java
- Fixes #4593
Support Yaml.Sequence for ChangePropertyValue
In our yamls we want to update an entry of a list in the yaml with a certain text value by another text value. If we would fo this with a simple text Find/Replace, the other occurences outside the propertyKey binding would also be updated.
Thinking about backwards compatibilty, I did not add a boolean flag that enables this behaviour. 
@timtebeek anyone you think of in particular?
Custom recipe for arrays?
=> ChangePropertyValue in list yaml entries

rewrite-java-test/src/test/java/org/openrewrite/java/VariableNameUtilsTest.java, rewrite-java/src/main/java/org/openrewrite/java/VariableNameUtils.java
Currently, Enums aren't being added to the list of used variable names which can result in collisions when naming new variable.
=> Add used enums into the list of used variable names

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
Fix an infinite loop in MavenPomDownloader
Since this MR https://github.com/openrewrite/rewrite/pull/4472 , there is an infinite loop in `MavenPomDownloader.download()` when root pom have a parent.
- https://github.com/openrewrite/rewrite/pull/4472
=> Fix infinite loop in MavenPomDownloader

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
For large source files this results in a large object allocation for every array-typed variable in the source file, as it copies the entire source code following that variable.
=> Remove problematic `String#substring()` call

rewrite-hcl/build.gradle.kts, rewrite-hcl/src/main/java/org/openrewrite/hcl/Assertions.java, rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/HclParserVisitor.java, rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclCommentTest.java, rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclStringTest.java
Handle single line comments starting with `//` separately in the HclParserVisitor.
Credits for discovering this omission and fix go to @rahul3509 ! 🙏🏻 
- Fixes #4544
- https://github.com/openrewrite/rewrite/issues/4611
- https://github.com/openrewrite/rewrite/issues/4612
- https://github.com/openrewrite/rewrite/issues/4613
=> Fix parsing of HCL comments using //

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java, rewrite-java/src/main/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitor.java
Expand `SimplifyBooleanExpressionVisitor` to also clear out ternary expressions with a hardcoded true/false 
- For https://github.com/openrewrite/rewrite-static-analysis/pull/258
- https://github.com/openrewrite/rewrite-feature-flags/pull/36
Didn't want to duplicate or recurse too much for parentheses, instead assuming this is often combined with remove unnecessary parentheses already.
=> Simplify constant ternary expressions too

rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java
Backport the changes from the Java 23 support in our Java 21 parser to our Java 17 parser:
- https://github.com/openrewrite/rewrite/pull/4516
As requested via links below, and helpful for folks that only have rewrite-java-17 on their classpath still.
@stephan202
- https://github.com/PicnicSupermarket/error-prone-support/pull/1329#issuecomment-2350934389
- https://github.com/openrewrite/rewrite/pull/4516#issuecomment-2440037849
=> Backport DocCommentTree reflection to ReloadableJava17ParserVisitor

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
I'm really sorry for solving the problem so late. @philippe-granet 
- https://github.com/openrewrite/rewrite/pull/4598
tried to fix the infinity loop with an if statement. That's also probably why one of the tests mentioned by @nmck257 failed.
I fixed the problem by implementing a method called resolveGav(). This uses the already available mergeProperties method to see if the property for the version is located in one of the modules.
Since it was my own fault 
- https://github.com/openrewrite/rewrite/pull/4472
and the attempt to fix this problem led to a failing test 
- https://github.com/openrewrite/rewrite/pull/4598.
My sincere apologies for producing such a catastrophe.
=> Fix failing test and infinity loop in MavenPomDownloader

rewrite-core/src/main/java/org/openrewrite/ExcludeFileFromGitignore.java, rewrite-core/src/test/java/org/openrewrite/ExcludeFileFromGitignoreTest.java
Added a recipe
First iteration of this seems to work well.
@timtebeek as discussed
FindAndReplaceText is very restrictive on this. This really uses gitignore rules/logic to determine if a change to the gitignore is necessary.
I've added a workaround for https://github.com/openrewrite/jgit/issues/3
In a next iteration, I want to remove this workaround again once jgit is fixed but guessing we will have some longer checks there. 
Planning on 2 later iterations: 
- removeEmptyGitignoreFile boolean option that removes a file if the last gitignore entry was removed or it only contains comments/empty lines after changes.
- support wildcard filepaths or directories with wildcard as input: This should match all files matching and for each of these files calculate same negations. Instead of …
=> Add Recipe that allows for the removal/negation of gitignore rules.

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
Identified a setup of comments that doesn't get parsed properly and added that as reproducer testcase
- Fixes https://github.com/openrewrite/rewrite/issues/4344
@nielsdebruin @timtebeek
=> Comments cannot be parsed properly

rewrite-core/build.gradle.kts, rewrite-core/src/main/java/org/openrewrite/remote/RemoteArchive.java, rewrite-core/src/main/java/org/openrewrite/remote/RemoteFile.java, rewrite-core/src/test/java/org/openrewrite/remote/RemoteArchiveTest.java, rewrite-core/src/test/java/org/openrewrite/remote/RemoteFileTest.java, rewrite-test/src/main/java/org/openrewrite/test/MockHttpSender.java
When we are downloading files we should check that the http call was successful instead of assuming that because no exception was thrown that the http status was successful. In the case were we get a 408, we don't throw an exception. This results in a InputStream of null to be returned. When reading from a InputStream of null, it infinitely returns a list of null bytes. In our use case we end up writing null to a temporary file until we run out of disk space
We can also make this change in the `HttpSender` and throw when we get a none successful http code
=> Check that we have downloaded the file successfully

rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenResolutionResult.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Pom.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
- #4590 failed to take into account older serialized LSTs
=> Prevent NPE on older LSTs not yet containing ResolvedPom.subprojects

rewrite-core/src/main/java/org/openrewrite/ExcludeFileFromGitignore.java, rewrite-core/src/test/java/org/openrewrite/ExcludeFileFromGitignoreTest.java
As Leanne has mentioned in our slack, we need to handle negations slightly different leading to more negation rules.
This results in dirtier rules result 😞 
But openrewrite is not to blame for git's behaviour 😄 
This one should fix the nested traversal rules
=> Fixed negation of nested files and directories if excluded by another rule

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
When substituting a generic type variable we should only add the name of the generic type variable, not its bounds, as that syntax is for declaration site only.
- Issue: openrewrite/rewrite-migrate-java#550
=> Fix `Substitutions` for generic type variables

rewrite-core/src/main/java/org/openrewrite/ExcludeFileFromGitignore.java, rewrite-core/src/test/java/org/openrewrite/ExcludeFileFromGitignoreTest.java
Hi @lkerford 
As discussed I wrote a fix for the reverse negation addition. 
This fix will add the negations at the **last** found ignoring rules as git takes the last lines in the gitignore file first. 
If a negation is already mentioned before an ignore, the ignore will be negated again and possibly the old negation (if exactly matched) will be cleaned up.
=> Fixed reverse order of gitignore file

rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyVersionSelector.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
See the slack exception logs -> https://rewriteoss.slack.com/archives/C01A843MWG5/p1730974519581749
=> Catch non-semver compatible exception in case of version update

rewrite-core/src/main/java/org/openrewrite/ExcludeFileFromGitignore.java, rewrite-core/src/test/java/org/openrewrite/ExcludeFileFromGitignoreTest.java
As I originally used a Set, the empty lines and comments with same text where being filtered to a single occurence (the last one).
By changing the implementation to a LinkedList into which we add conditionally entries, we can save a new List instantiation + keep comments and whitelines non-distinct, maintaining dinstinction of the gitgnore lines (same line later in file makes sure we only keep that one)
See the changed test for the bug I was facing while first time running on a gitignore file with multiple empty lines.
=> Keep multiple whitelines and same comments from the gitignore file

rewrite-yaml/src/main/java/org/openrewrite/yaml/search/FindProperty.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/search/FindPropertyTest.java
I have changed the org.openrewrite.yaml.search.FindProperty search recipe to allow searching for yaml properties which have a specific scalar value. The new reciped parameter propertyValue is OPTIONAL which ensures downwards-compatibility.
I need this search functionality for a specific use case I am working on.
I want to alter a yamle file if the specified yaml key does have a certain value. The search recipe can act as a Precondition here.
I thried to create a dedicated org.openrewrite.yaml.search.FindPropertyWithValue recipe inheriting from org.openrewrite.yaml.search.FindProperty, but recipes are final and do not allow for inheritance. This is why I added an optional parameter to the existing recipe instead.
Also I did not find out how to test a negative search case. I marked hence …
=> Feature - YAML search - find properties with a specific scalar value

rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclStringTest.java
Fixing the recently added (#4616) test case called `quoteEscaping` in HCL handling.
As is, the test runs rewrite against an invalid HCL fail and fails (as noted by `@ExpectedToFail`). Thus, fixing the tested HCL syntax, observing the test pass (with no code changes) and removing the `@ExpectedToFail` annotation.
Closes #4612.
Fix the bug in tests.
@timtebeek was the one to look at it before
=> Fixing the quoteEscaping test case for proper quote character escaping

rewrite-maven/src/main/java/org/openrewrite/maven/RemoveUnusedProperties.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveUnusedPropertiesTest.java
- https://github.com/openrewrite/rewrite/pull/4636#issuecomment-2471768419
=> Account for a second common resource filtering pattern

rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
Fixed bug that caused incorrect code when `AddOrUpdateAnnotationAttribute` on annotation with empty bracket e.g., `@Foo()`.
The recipe `AddOrUpdateAnnotationAttribute` can be used to modify the attribute values on annotation. When no attribute values have been specified, the recipe will work fine if the syntax `@Foo` is used. However, if `@Foo()` is used, which is also valid java. Then, the recipe breaks.
**Example**
```java
public @interface Foo {
String[] array() default {};
}
```
If we run `AddOrUpdateAnnotationAttribute` on `A` annotated with `@Foo`, configured to set the value of `Foo.array` to "newTest1,newTest2" we **correctly** get:
```java
@Foo
public class A {}
@Foo(array = {"newTest1", "newTest2"})
public class A {
}
```
Yet applying it to `@Foo()`, **incorrectly** yields …
=> Fix bug using `AddOrUpdateAnnotationAttribute` on annotation with empty brackets

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
A test case was added to demonstrate an issue with using the `ChangeType` recipe on a `J.ClassDeclaration` object.
`ChangeType` fails to change the class name for a `J.ClassDeclaration` object. This may be related to 
- #4648
since we noticed this new regression in a local recipe today.
@timtebeek
=> ChangeType does not work on J.ClassDeclaration

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java
@timtebeek 
Tests initially introduced in this PR
- https://github.com/openrewrite/rewrite/pull/4670
=> Refactor `ChangeType` tests to adhere to testing framework

rewrite-maven/src/main/java/org/openrewrite/maven/AddProfile.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangePackaging.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangeProjectVersion.java, rewrite-maven/src/main/java/org/openrewrite/maven/IncrementProjectVersion.java, rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java
Moved project matcher to `MavenVisitor`
Clean up references
No
N/A
N/A
N/A
=> Move project matcher to MavenVisitor

rewrite-gradle/src/test/java/org/openrewrite/gradle/search/FindPluginsTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/DeleteMethodArgumentTest.java, rewrite-java/src/main/java/org/openrewrite/java/DeleteMethodArgument.java
- Fix https://github.com/openrewrite/rewrite/issues/4676
Below case will failed because it will change to `"public class A {{ B.foo( 1, 2); }}"` which contains a redundant space before the first argument.
```java
@Test
void deleteFirstArgument() {
rewriteRun(
spec -> spec.recipe(new DeleteMethodArgument("B foo(int, int, int)", 0)),
java(b),
java(
"public class A {{ B.foo(0, 1, 2); }}",
"public class A {{ B.foo(1, 2); }}"
)
);
}
```
correct answer: `"public class A {{ B.foo(1, 2); }}"`, no space before the first `1` element.
actual answer:    `"public class A {{ B.foo( 1, 2); }}"` has a redundant space before the first `1` element.
This PR aims to fix the issue.
Fix https://github.com/openrewrite/rewrite/issues/4676
=> Remove redundant space for DeleteMethodArgument when argumentIndex=0

rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java, rewrite-java/src/main/java/org/openrewrite/java/recipes/MissingOptionExample.java
This PR enhances the functionality of the `AddOrUpdateAnnotationAttribute` recipe, allowing not only to override but also to append to array values. A new option, `arrayAppend`, has been introduced, enabling users to append to attributes with an `array` type. When used in conjunction with the `addOnly` option, users can control whether a value will be appended only if it is not already present, thereby avoiding duplication.
- See #4157 
@timtebeek @Laurens-W
=> Append items to annotation attribute array

rewrite-xml/src/test/java/org/openrewrite/xml/XmlParserTest.java
Add `isTrue()` to an `assertThat(...)` in a test of the XmlParserTest.
If no condition is added, the assertion has no impact.
@Laurens-W
=> Call `isTrue` on `Reference` asserts in `XmlParserTest`

rewrite-xml/src/main/java/org/openrewrite/xml/trait/SpringReference.java
Failure reported on platform
@knutwannheden 
```
```
```
Cannot invoke "org.openrewrite.xml.tree.Xml$Tag.getAttributes()" because the return value of "org.openrewrite.xml.tree.Xml$Document.getRoot()" is null
```
```
java.lang.NullPointerException: Cannot invoke "org.openrewrite.xml.tree.Xml$Tag.getAttributes()" because the return value of "org.openrewrite.xml.tree.Xml$Document.getRoot()" is null
org.openrewrite.xml.trait.SpringReference$Provider.isAcceptable(SpringReference.java:118)
org.openrewrite.SourceFileWithReferences$References.lambda$build$0(SourceFileWithReferences.java:59)
java.base/java.lang.Iterable.forEach(Iterable.java:75)
org.openrewrite.SourceFileWithReferences$References.build(SourceFileWithReferences.java:58)
org.openrewrite.xml.tree.Xml$Document.getReferences(Xml.java:17 …
```
=> Fix NPE in `SpringReference`

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java, rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java, rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Validate argument count with respect to parameter count.
=> Make `FindMissingTypes` stricter for method invocations

rewrite-core/src/main/java/org/openrewrite/table/RewriteRecipeSource.java, rewrite-java-test/src/test/java/org/openrewrite/java/recipes/FindRecipesTest.java, rewrite-java/src/main/java/org/openrewrite/java/recipes/FindRecipes.java
Find Refaster style recipes as well; through proxy of `@RecipeDescriptor`.
Be able to analyze the recipes we have, and potentially train on those found.
Added a new `RecipeType.Refaster`; figured that be easier than an `@Option`.
* Separate recipe: more work to maintain.
* An option: needs repeated recipe runs.
* Match `@AfterTemplate`; would then also match those [from Picnic](https://github.com/PicnicSupermarket/error-prone-support/tree/master/error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules), but those lack a guaranteed name & description, making them harder to train on.
- https://bsky.app/profile/agoncal.bsky.social/post/3lbfd2lpny22v
=> Find Refaster style recipes as well

rewrite-java-test/src/test/java/org/openrewrite/java/recipes/FindRecipesTest.java, rewrite-java/src/main/java/org/openrewrite/java/recipes/FindRecipes.java
- https://github.com/openrewrite/rewrite/pull/4693
=> Find Yaml recipes as well

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/TypeUtilsTest.java, rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
`TypeUtils#isAssignable()` is used by many different recipes. One complexity that up until now hadn't been considered is that the assignability check when also considering the call-site variance. For example, checking if `java.util.List<String>` can be assigned to `<T extends java.util.Collection<String>>` depends a lot on where that `<T>` is declared (e.g. as the parameter or return type of a method or the type of a local variable). The API new allows the caller to provide an additional `TypePosition` parameter to indicate this.
=> `TypeUtils#isAssignable()` improvements

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/CompilationUnitTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ConstructorTest.java
=> Support Groovy declared constructors

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
- Fixes https://github.com/openrewrite/rewrite-logging-frameworks/pull/186
- Fixes https://github.com/openrewrite/rewrite-logging-frameworks/issues/185
=> Add missing semicolon to JavaTemplate stub when replacing method arguments

rewrite-core/src/main/java/org/openrewrite/ScanningRecipe.java, rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java
Make `getRecipeList` and `buildRecipeList` `final` in `ScanningRecipe`.
Frequent source of confusion among users as the scanning conditions are not applied to these methods. Figured by making it explicit that this pattern is not expected or supported we'd see fewer questions like
- https://github.com/openrewrite/rewrite/issues/4711
Any valid cases I'd missed that should support this still?
=> Restrict usage of `RecipeList` methods from `ScanningRecipe`

rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java, rewrite-hcl/src/main/java/org/openrewrite/hcl/HclTemplate.java
The reason for this change is that the mapping functions should all expect a non-`null` input but are allowed to return `null` to signal that the corresponding result is to be removed from the list.
Additionally, the return type of the methods has been annotated with `@Nullable` where appropriate (typically when the input `List` is `null`). So that this doesn't result in new warnings getting reported, the methods have now additionally also been annotated with `@Contract`, using which we capture the details of when the method returns `null`. With powerful static analysis tools like IDEA, this should typically not result in any new unwanted warnings.
For example when a `with`-method is called by mapping the result of the corresponding `get`-method this is not an issue, as both the …
=> Replace `UnaryOperator` with `Function` in `ListUtils` methods

rewrite-maven/src/main/java/org/openrewrite/maven/ExcludeDependency.java, rewrite-maven/src/test/java/org/openrewrite/maven/ExcludeDependencyTest.java
Run a second cycle of ExcludeDependency when the document has changed, to also exclude previously omitted dependencies.
- Fixes https://github.com/openrewrite/rewrite/pull/4563
Second cycle might require changes in the future, but at that point we're more free to change the model as well, as seen in:
- https://github.com/openrewrite/rewrite/pull/4563
@siborea @ckcd 
Credits for the test here go to @ckcd 🙏🏻 
We can change the model as seen in this work
- https://github.com/openrewrite/rewrite/pull/4563
But that would then need careful consideration to account for serialization, and we'd be doing so for a single use case here.
=> Exclude omitted dependencies as well through a second cycle

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
- Fixes https://github.com/openrewrite/rewrite/issues/4726
@tylervangorder-8451
=> Allow orgs with leading numbers in name in GitRemote

rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java
We're understandably getting reports that older recipe jars now can not run, following
- #4720
This restores those methods for now, but also locks us into new compilations again using the implied old methods. 🤔
=> Restore ListUtils map methods that accept UnaryOperator

rewrite-core/src/main/java/org/openrewrite/internal/PropertyPlaceholderHelper.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
~~This just demonstrate an issue we are facing with jenkins modernization.~~
The `ChangeParentPom` recipe wrongly add a dependency into dependency management when it should not
Such dependency is still managed by the bom.
```
+            <dependency>
+                <groupId>org.jenkins-ci.plugins</groupId>
+                <artifactId>scm-api</artifactId>
+                <version>698.v8e3b_c788f0a_6</version>
+            </dependency>
```
I think it cause issue because the `${jenkins.baseline}` on the artifact id.
But I don't know how and the best way to fix it
Any help would be appreciated
=> Resove dependencies bom with properties on `ChangeParentPom`

rewrite-core/src/main/java/org/openrewrite/internal/NamingService.java, rewrite-java/src/main/java/org/openrewrite/java/service/JavaNamingService.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JavaSourceFile.java, rewrite-java/src/test/java/org/openrewrite/java/service/JavaNamingServiceTest.java
Added a `NamingService` interface including a Java implementation
Working on 
- https://github.com/openrewrite/rewrite-static-analysis/pull/397
@knutwannheden @OlegDokuka @timtebeek
=> Add `NamingService` with Java implementation

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Use different way of retrieving metadata map
@sambsnyd @timtebeek @knutwannheden 
Exception that was being swallowed:
`java.lang.NoSuchMethodError: org.codehaus.groovy.ast.expr.ConstructorCallExpression.getMetaDataMap()Ljava/util/Map;`
=> Fix Gradle/Groovy parser issue related to Java class references

rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
`J.Case` is now handled as a block of code that needs method invocations to be ended with a semicolon
- https://github.com/openrewrite/rewrite-logging-frameworks/issues/192
@timtebeek 
Relevant test case
- https://github.com/openrewrite/rewrite-logging-frameworks/issues/192
=> Take `J.Case` into account in JavaTemplate

rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
`J.Case` is now handled as a block of code that needs method invocations to be ended with a semicolon
- https://github.com/openrewrite/rewrite/pull/4744
feedback here after initial change
@timtebeek
=> Always add closing semicolon for `J.Case` in JavaTemplate

rewrite-yaml/src/main/java/org/openrewrite/yaml/CommentOutProperty.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/CommentOutPropertyTest.java
=> feat: Added option to comment out property in yaml

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/CastTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RangeTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/TernaryTest.java, rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
Nested parentheses around variable expressions are supported as well for the groovy parser.
Also added the tests for method invocation with nested parentheses (but disabled). 
- https://github.com/openrewrite/rewrite/issues/4703
- https://github.com/openrewrite/rewrite/issues/4615
=> Support variable expressions in parenthesis

rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java
Added support to retrieve the classpath by artifact name for Bazel projects.
In Bazel projects, creating an instance of JavaParser with artifact names as classpath can fail when artifact names include a "-". This issue arises because Bazel replaces "-" with "_" when generating JAR files.
Example usage
```
JavaParser.fromJavaVersion().classpath("aws-java-sdk-s3").build()
```
Above code fails with `IllegalStateException Unable to construct JavaParser`.
To address this, updated JarPattern to include the normalized artifact name, ensuring it can correctly locate the JAR file names generated using bazel convention.
Note: A minor refactor to make code testable for the part which was updated.
=> Update get classpath by artifact name to support bazel

rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java, rewrite-java/src/main/java/org/openrewrite/java/JavaParserExecutionContextView.java
When we use the default download location we create the folder if it is missing. We also need to do this if a custom location is provided
If the custom location is not created, the recipe which requires the associated resources will fail because it cannot find the associated resources
=> Make sure provided download target exist before writing files to it

rewrite-java/src/main/java/org/openrewrite/java/RemoveMethodInvocationsVisitor.java, rewrite-java/src/test/java/org/openrewrite/java/RemoveMethodInvocationsVisitorTest.java
Add test to verify if RemoveMethodInvocationsVisitor can delete static method
After moving recipe `org.openrewrite.java.migrate.RemoveMethodInvocation` defined on project `rewrite-migrate-java` to `org.openrewrite.java.RemoveMethodInvocations` in `rewrite-java' some custom recipe now failed 
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.testing.easymock.EasymockRemoveReplay
displayName: Remove EasyMock `replay()`"
description: Remove EasyMock `replay()` method calls.
recipeList:
- org.openrewrite.java.migrate.RemoveMethodInvocation:
methodPattern: org.easymock..EasyMock replay(..)
```
this exemple work but the recipe has been removed : 
- recipe : https://github.com/dralagen/rewrite-testing-frameworks/blob/java-migrate-removeMethodInvocation/src/main/resource …
=> `RemoveMethodInvocationsVisitor` can remove static method

rewrite-gradle/src/main/java/org/openrewrite/gradle/ChangeDependencyClassifier.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/RemoveRedundantDependencyVersions.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/RemoveRedundantDependencyVersionsTest.java
Add recipe to remove redundant versions.
A similar feature is available in Maven.
Nothing in particular
Anybody
Forcibly removing versions would result in broken builds.
* https://github.com/openrewrite/rewrite/discussions/4485
=> Remove redundant versions for Gradle

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
This can be used to generate a clone url without first needing to build a `GitRemote` object out of it (having to pass nulls where they are not allowed)
=> Allow building uri from origin, path and service type

rewrite-core/src/main/java/org/openrewrite/text/Find.java, rewrite-core/src/test/java/org/openrewrite/text/FindTest.java
The `Find` has been modified to increase its performance. Nearly all these optimizations are related to how Strings are handled. 
- Replace basic String concatenation with a `StringBuilder` where we set the capacity to the exact length of the final String. Apart from setting the capacity exactly, this will mostly only affect OpenRewrite users using old JVM, since most modern JVM will often already generate optimized bytecode using a StringBuilder.
- **Significantly** reduce the number of generated substrings, e.g., while looking up line ending on substrings.
- Avoid recomputing common values, byte precomputing them outside the loop.
Make it faster.
@kmccarp @timtebeek
=> Performance improvements of `Find` recipe

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
This will allow finding a server without first stripping the protocol on the consumers end.
=> Strip origin in findRemoteServer

rewrite-java-test/src/test/java/org/openrewrite/java/ChangeTypeTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
The commit e536ed273fda87ce6857b06f200488130b3ef5f3 introduced a regression here when dealing with classes that share a common prefix (such as `foo.Foo` and `foo.Foobar`).
- Fixes: #4773
- Fixes: #4764
=> Correct `J.FieldAccess#isFullyQualifiedClassReference()`

rewrite-core/src/main/java/org/openrewrite/GitRemote.java, rewrite-core/src/test/java/org/openrewrite/GitRemoteTest.java
This changes the output slightly (no more user in the URL) but that is fine as the user is not required/used in matching anyway.
Also fixed the comment and exception text.
=> Normalize server URLs to avoid missing scheme

rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
Add explicit imports to avoid conflicts with classes added to java.lang, like record
- For https://github.com/openrewrite/rewrite-migrate-java/issues/540
=> Add explicit imports to avoid conflicts with classes added to java.lang, like record

rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
Force Importing No Java Record 
@timtebeek
=> Always add import for `Record` classes not from `java.lang` package, to avoid conflicts on Java 14+

rewrite-gradle/src/main/resources/META-INF/rewrite/gradle-8.yml, rewrite-gradle/src/test/java/org/openrewrite/gradle/AddJUnitPlatformLauncherTest.java, rewrite-test/build.gradle.kts
- Add recipe to add Gradle dependency on `org.junit.platform:junit-platform-launcher`
- Add transitive dependency when using `rewrite-test`
Reduce the warnings seen in build logs when using Gradle 8.x, ahead of a migration to Gradle 9.
https://docs.gradle.org/8.11.1/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
Would the `api` dependency already prevent that we have to add the testRuntimeOnly dependency for `rewrite-*`?
We could delay this until Gradle 9, but the warnings are already annoying right now.
=> Add `testRuntimeOnly` dependency on `junit-platform-launcher` with Gradle 8.+

rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
UpgradeDependencyVersionTest.java
validate the upgrade of a Gradle `testImplementation` library
=> enhance UpgradeDependencyVersionTest

rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java
Adds a unit test for the ChangeDependencyGroupIdAndArtifactId recipe to update plugin dependencies. The fix is not provided.
- fixes openrewrite/rewrite/#4779
=> fix[maven]: update plugin dependencies

rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AttributeTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/CastTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ListTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/LiteralTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MapEntryTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RangeTest.java
Nested parentheses around method invocations are supported as well for the groovy parser.
- https://github.com/openrewrite/rewrite/issues/4703
- https://github.com/openrewrite/rewrite/issues/4615
=> Make Groovy Parser correctly handle nested parenthesis

rewrite-xml/src/main/java/org/openrewrite/xml/trait/SpringXmlReference.java, rewrite-xml/src/main/java/org/openrewrite/xml/trait/XmlReference.java, rewrite-xml/src/main/resources/META-INF/services/org.openrewrite.trait.Reference$Provider, rewrite-xml/src/test/java/org/openrewrite/xml/trait/SpringXmlReferenceTest.java
Distinguish between what is XmlReference and what is Spring specific (Matcher and Provider)
@timtebeek @jevanlingen
=> Refactor SpringReference

rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/RemoveDevelocityConfiguration.java, rewrite-gradle/src/main/resources/META-INF/rewrite/gradle.yml, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/RemoveDevelocityTest.java
We had recipes to add and migrate, but lacked recipes to remove. Some internal repositories for now can not use Gradle Enterprise/Develocity, so I'd like to remove these with a recipe.
=> Add recipe to remove Gradle Enterprise and Develocity

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Added fallback for determining parenthesis level for `BinaryExpression`
@timtebeek @jevanlingen @knutwannheden @sambsnyd 
Lower versions of Gradle do not provide the `_INSIDE_PARENTHESES_LEVEL` flag we expect
=> Add fallback for determining parenthesis level for `BinaryExpression`

rewrite-core/src/main/java/org/openrewrite/internal/ReflectionUtils.java, rewrite-core/src/test/java/org/openrewrite/internal/ReflectionUtilsTest.java
Extra utility method to check if a class is available on the classpath.
- https://github.com/openrewrite/rewrite-static-analysis/pull/411#discussion_r1895916548
=> Add a `isClassAvailable` method to the ReflectionUtils

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyTypeMapping.java, rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeMapping.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeMapping.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java, rewrite-java-test/src/main/java/org/openrewrite/java/JavaTypeMappingTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest6Test.java, rewrite-java/src/main/java/org/openrewrite/java/JavaTypeVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/UnsafeJavaTypeVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/internal/JavaReflectionTypeMapping.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Widened the type of `JavaType.Method#thrownExceptions` to `JavaType` to support the mapping of generic exceptions.
A method that throws a combination of a generic and non-generic exception looks like this:
```java
interface Test {
<T extends FileNotFoundException> void throwsGenericException() throws T, InterruptedException;
}
```
Its [JVMS 4.3.4](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.3.4) signature is:
```
<T:Ljava/io/FileNotFoundException;>()V^TT;^Ljava/lang/InterruptedException;
```
Preparing the way for compile verification as a post-recipe task.
Should be LST deserialization compatible, but this is an ABI change and we should release workers and CLI ASAP. Old serialized LSTs will not have mapped generic exceptions correctly. They instead previously …
=> Support mapping of generic thrown exception types

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11TypeMapping.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17TypeMapping.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeMapping.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8TypeMapping.java, rewrite-java-test/src/main/java/org/openrewrite/java/JavaTypeMappingTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/JavaReflectionTypeMapping.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
A new field has been added to `JavaType.Method` called `declaredFormalTypeNames`. The phrase "formal type name" is a reference to the grammar of `FormalTypeParameters` in [JVMS 4.3.4](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.3.4).
Previously, we were unable to detect whether a generic type variable name that was used in either a parameter, return type, or a thrown exception declaration in a method declaration was defined by that method or was instead referring to a type variable of the same name defined by an enclosing class. We could determine whether the class or method defined the type variable only when there was no possibility that the method was shadowing the class.
Some examples for when there will and will not be names in this new array of data:
The …
=> Keep the names of generic type variables defined by methods.

rewrite-java-test/src/main/java/org/openrewrite/java/JavaTypeGoat.java, rewrite-java-test/src/main/java/org/openrewrite/java/JavaTypeMappingTest.java, rewrite-java-test/src/main/resources/JavaTypeGoat.java, rewrite-java/src/main/java/org/openrewrite/java/internal/JavaReflectionTypeMapping.java
Previously `JavaReflectionTypeMapping` was mapping the raw instead of generic type for `JavaType.Variable`. This corrects that to use the generic type declaration as was done in the other type mapping implementations.
Pursuing compiler verification as a post-recipe task.
=> Fix Java reflection mapping of generic typed fields.

rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AttributeTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/CastTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ListTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/LiteralTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MapEntryTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RangeTest.java
- Revert https://github.com/openrewrite/rewrite/pull/4801
- Revert https://github.com/openrewrite/rewrite/pull/4807
Seeing increases parser failures as compared to before: https://app.moderne.io/results/Ab8rNRMZz
In parallel we'll briefly explore a roll forward as well, but this ensures we have a workable version soon.
=> Revert parenthesis changes

rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AttributeTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/CastTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ForLoopTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ListTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/LiteralTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MapEntryTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodDeclarationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RangeTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RealWorldGroovyTest.java
- **Rereverted**: parenthesis changes 
- **Fix**: closing parentheses in `determineParenthesisLevel` not taking into account (like `new ObjectX().objectY.someClosure {}`
- **Fix**: for-loop could not handle modifiers like `for(def x : ["A", "B"])`
- **Improvement**: Support for varargs
- https://github.com/openrewrite/rewrite/pull/4818
When I added the real-live-examples, I also found out we do not support other things:
- [Pattern](https://groovy-lang.org/operators.html#_pattern_operator) operator
-  [anonymous inner classes](https://groovy-lang.org/objectorientation.html#_anonymous_inner_class )
- Java style [class](https://groovy-lang.org/style-guide.html#_classes_as_first_class_citizens) arguments
As these things are possible not easy fixes, I kept the unit tests, but marked them as …
=> Put parenthesis changes back

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AssignmentTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RealWorldGroovyTest.java
Support JavaStyle `.class` suffix.
Though the suffix is [optional](https://groovy-lang.org/style-guide.html#_classes_as_first_class_citizens) in Groovy, you can still use them, see for example: [SchemaZipPlugin](https://github.com/spring-projects/spring-session-data-geode/blob/1ca81cc330f800311be7bfca0aa16030107de288/buildSrc/src/main/groovy/io/spring/gradle/convention/SchemaZipPlugin.groovy).
=> Groovy parsers should be able to support `.class`

rewrite-maven/src/main/java/org/openrewrite/maven/AddAnnotationProcessor.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddAnnotationProcessorTest.java
When adding a Maven annotation processor, handle a version specified as a property correctly.
=> `AddAnnotationProcessor` should compare and update versions using a property

rewrite-gradle/src/main/groovy/RewriteGradleProject.groovy
Mostly to silence the review bot on other PRs. There's an identical method defined on DependencyHandler since 4.5 ; Not sure why this has only just now been flagged, but perhaps the parser improvements mean we can now parse this class.
=> Add missing override annotation

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RealWorldGroovyTest.java
Inner classes our now totally supported (including anonymous classes).
- https://github.com/openrewrite/rewrite/issues/4063
Most work to support inner classes was already done, the new code just adds some missing pieces.
To support
- https://github.com/openrewrite/rewrite/issues/4704
a `visitConstructor` was added. The code was 95% the same as the `visitMethod`. So I merged the `visitMethod` and `visitConstructor` again (a _ConstructorNode_ extends a _MethodNode_, so _visitMethod_ is enough).
=> Support inner classes for groovy

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AnnotationTest.java
Support for:
- nested annotations with properties, like: `@Foo(bar = @Bar(value = "1.0"))`
- annotations with empty arguments, like `@Foo()`
- fix https://github.com/openrewrite/rewrite/issues/4055
The [solution](https://github.com/openrewrite/rewrite/pull/4549) of using
```java
public void visitConstantExpression(ConstantExpression expression) {
..
else if (expression instanceof AnnotationConstantExpression) {
classVisitor.visitAnnotation((AnnotationNode) value);
return ((Expression) classVisitor.pollQueue()).withPrefix(fmt); // pollQueue returns `J.Annotation`
}
return new J.Literal(randomId(), fmt, Markers.EMPTY, value, text, null, jType);
}
```
did not work properly, because it just fooled the compiler (both J.Annotation and J.Literal extend Expression). But in the end all …
=> Support nested annotations with properties and annotations with empty arguments

rewrite-java/src/main/java/org/openrewrite/java/internal/template/BlockStatementTemplateGenerator.java
As seen on https://github.com/finos/spring-bot/blob/4e9ab2d9724125001046cb9131131c006b79372f/libs/teams/teams-chat-workflow-spring-boot-starter/src/main/java/org/finos/springbot/teams/bot/BotController.java#L85
```
"Authorization"
```
```
class org.openrewrite.java.tree.JavaType$Unknown cannot be cast to class org.openrewrite.java.tree.JavaType$Class (org.openrewrite.java.tree.JavaType$Unknown and org.openrewrite.java.tree.JavaType$Class are in unnamed module of loader 'app')
```
```
java.lang.ClassCastException: class org.openrewrite.java.tree.JavaType$Unknown cannot be cast to class org.openrewrite.java.tree.JavaType$Class (org.openrewrite.java.tree.JavaType$Unknown and org.openrewrite.java.tree.JavaType$Class are in unnamed module of loader 'app') …
```
=> Prevent class cast exception on Unknown annotation type

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
Parentheses discovery for method calls did not always work properly.
- https://github.com/openrewrite/rewrite/issues/4055
Failing parts:
```groovy
Micronaut.build(args)
.packages('com.edalex')
.mainClass(Application)
.start()
```
The discovery of parentheses is quite hard to grasp. This is the concept behind it. We defined two variables called `parent` and `child`. The parent and child are nodes, which could be visualised like: `<<child>  parent>`. Notice in source code, the nodes could span multiple lines.
To support this, we loop through all the lines of code of the parent and child element:
```
for (int i = 0; i < (childLineNumber - parentLineNumber); i++)
// move `untilCursor` past next line break every time
// move `untilCursor` after childColumn of last line
```
=> Improve discovery of parentheses level for MethodCallExpression

rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/BuilderHandler.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/LombokTest.java
Added support for the Lombok annotation `@Builder.Default` on final variables.
- In #4823, the `@Builder.Default` annotation was temporarily removed for processing. However, Lombok's HandleBuilder  [skips](https://github.com/projectlombok/lombok/blob/9f5de53e0651142d1fa7a981f221f51a627f41d0/src/core/lombok/javac/handlers/HandleBuilder.java#L281) processing final variables with non-null initialization values unless they include the `@Builder.Default `annotation. To address this, added logic to temporarily remove the final modifier before invoking the annotation processor and restored it afterward.
=> Add Support for Builder.Default annotation for final vars

rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclBlockTest.java
Minor thing. Adding a new UT test case for map/object literals which use an expression instead of hard-coded name on the left-hand side of the map entry. HCL spec requires these to be wrapped with parentheses.
To make sure it works.
=> HCL - UT for expressionOnLeftHandSideOfAMapLiteral

rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/HclParserVisitor.java, rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclCollectionValueTest.java
A minor fix for handling a special case of empty maps (objects) in HCL.
To fix a print-idempotency issue of:
```
-  known_weird_cases = {
-  }
+  known_weird_cases = {}
```
=> HCL - Fixing handling of multi-line empty maps

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodDeclarationTest.java
- Remove `def` check for visitTypeTree
- Remove unnecessary RedundantDef marker for DeclarationExpression
- Made RedundantDef function more specific for MethodNodes
- Added support for `def` keyword for constructors (see [Def and type](https://groovy-lang.org/style-guide.html#_def_and_type))
- Use `skip` function as much as possible
After the changes @Laurens-W made in
- https://github.com/openrewrite/rewrite/pull/4757
the parser did neither need the RedundantDef markers for DeclarationExpressions nor the `def` check for visitTypeTree. So I removed it and rewrote the RedundantDef stuff for methods (as it was the only usage of the `maybeRedundantDef` function, it could be written more specific targeted to method nodes only). 
When I was busy, I saw we could use the `skip` function a lot …
=> Cleanup groovy parser

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AssignmentTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/LiteralTest.java
- Fix: String with line breaks and spaces, like `"\n|  "` are supported as well.
- Cleanup: String literals and the String literals in the GString parser are written in the same way
=> Fix parsing string literal with line breaks and spaces

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RealWorldGroovyTest.java
The pattern operator `~` is parsed correctly.
Support the operator to support Gradle files better. For example the [Spring Boot](https://github.com/spring-projects/spring-boot) project uses it:  [click](https://github.com/spring-projects/spring-boot/blob/183285258d7b5092224eab1600a2cfa8332682d9/settings.gradle#L78).
I took a shortcut to parse the operator as part of a string, that's exactly the same route as how we parse Regexes:
```groovy
// both are typed as strings
def PATTERN = ~/foo/ // should actually be of type `Pattern`
def REGEX = /\d+/ // should actually be a MethodInvocation of `Pattern.matches(regex, string)`
```
This works, because our groovy parser does not do type checks (like we do for Java). If we ever want to support this, we have to change the groovy parser as well.
=> Support pattern operator for groovy

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AnnotationTest.java
Generated [transform](https://medium.com/@AlexanderObregon/exploring-groovys-powerful-ast-transformations-enhancing-your-code-at-compile-time-32bdcd8924a3) annotations are parsed.
- https://github.com/openrewrite/rewrite/issues/4254
Notice with these fixes the parser just ignores the groovy AST transformations. So you cannot use the 'real' AST as the bytecodes dictate in the groovy recipes. If we want to support that, we would have to do a project like `rewrite-lombok`.
=> Skip parsing groovy generated transform methods

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java
Packages can have a `;` semicolon
- fixes https://github.com/openrewrite/rewrite/issues/4070
=> Support semicolon for groovy packages

rewrite-core/build.gradle.kts
Replacing the dependency on `commons-compress` with just `commons-lang3` in `rewrite-core`.
Here's the `diff` on `./gradlew rewrite-core:dependencies --configuration runtimeClasspath`:
```diff
-+--- org.apache.commons:commons-compress:latest.release -> 1.27.1
-|    +--- commons-codec:commons-codec:1.17.1
-|    +--- commons-io:commons-io:2.16.1
-|    \--- org.apache.commons:commons-lang3:3.16.0
++--- org.apache.commons:commons-lang3:latest.release -> 3.17.0
```
(as you can see we upgrade from 3.16.0 to 3.17.0 as a by-product)
- `commons-compress` doesn't seem needed, we only seem to declare it to bring the subdependency of `commons-lang3`
- removing it hoping to reduce the size of all deliverables depending on `rewrite`
The only explicit mention of `commons-compress` I could find was in …
=> Replacing dependency on commons-compress with commons-lang3

rewrite-hcl/src/main/java/org/openrewrite/hcl/tree/Space.java, rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclCommentTest.java
Fixing the Whitespace/Comment formatting logic of HCL to not act specially on `#` or `//` characters within the multiline comment (`/* something*/`).
- fixes #4862
=> HCL - Fixing handling of # or // within multiline comments

rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/HclParserVisitor.java, rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclCommentTest.java
Fixing the logic in HCL parser's `positionOfNext` to properly handle `/*` strings within single-line comments. They do **not** start a multi-line comment.
- fixes #4865
=> fixing comment nesting in positionOfNext()

rewrite-core/src/main/java/org/openrewrite/config/Environment.java
In `scanJar` method in `rewrite-core/src/main/java/org/openrewrite/config/Environment.java`, we are now creating the list of dependencyResourceLoaders in 2 passes to ensure all recipes are resolved. 
Recipe descriptors were missing due to transitive recipes failing to be resolved.
- Shown in this issue: https://github.com/moderneinc/customer-requests/issues/765
Are there any undesirable side effects from this change?
@timtebeek @sambsnyd @kmccarp
=> fix: create dependencyResourceLoaders in 2 passes

rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/HclParserVisitor.java, rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclCommentTest.java
Fixing the handling of empty comments, i.e. just the start of the comment and a newline:
```
//
```
Before this fix, it led to some weird behavior of some of the code being duplicated in the output with slashes removed
```diff
diff --git a/file.tf b/file.tf
index 4f2b4e5..633e863 100644
--- a/file.tf
+++ b/file.tf
@@ -2,5 +2,8 @@ 
#
}
module "something" {
+  source = "..else"
+////}
+module "something" {
source = "../else/"
}
```
=> HCL - Fixing empty comment handling

rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
- Resolves issue #4765 
where no changes were being made to inner annotations.
=> Add test for inner annotations and fix for 'AddOrUpdateAnnotationAttribute'

rewrite-java/src/main/java/org/openrewrite/java/AnnotationMatcher.java, rewrite-java/src/test/java/org/openrewrite/java/trait/AnnotatedTest.java
The `AnnotationMatcher` can now match annotations based on values inside array initializer.
```java
AnnotationMatcher matcher = new AnnotationMatcher("java.lang.SuppressWarnings(\"deprecation\")", false);
J.Annotation anno = // LST of @SuppressWarnings({"deprecation", "unused"});
matcher.match(anno); // true
```
With Traits building on top of the Matcher construct they become a central component for Recipes.
Without the ability to match in values inside arrrays it is not possible to use Traits when we target an Annotation with array values.
An alternative would be to extend the used syntax to enable logical constructs like `X {and/or} Y` and `not X`.
This would need a deeper analysis of the upcomming AspectJ features and additional refactorings.
=> Enable `AnnotationMatcher` to match values in `J.NewArray`

rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
The cursor is added to `RecipeRunException`, and used to add a marker. In tests those markers are not shown however, but it would be helpful to see the cursor position for any exceptions that occur.
=> Print cursor when tests fail to run a recipe

rewrite-gradle/build.gradle.kts, rewrite-test/build.gradle.kts
To reduce warnings seen about https://www.slf4j.org/codes.html#StaticLoggerBinder
=> Add `slf4j-nop` transitively through rewrite-test

rewrite-core/src/main/java/org/openrewrite/semver/LatestRelease.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Hi
fixed a (look like) typo in version comparator implementation which results in same version being comprated to itself
Faced an issue when tried to compare jdk17 to jdk21-chiseled during recipe implemetation
=> `LatestRelease` should replace `metadataPattern` as regex, as documented

rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/RecordPatternMatchingTest.java, rewrite-java/src/main/java/org/openrewrite/java/Assertions.java, rewrite-test/src/main/java/org/openrewrite/test/TypeValidation.java
Record pattern matching for Java 21 is not print idempotent (but not yet properly mapped to the LST)
@timtebeek @knutwannheden
=> Add Record pattern matching print idempotency Java21

rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java, rewrite-java/src/main/java/org/openrewrite/java/recipes/MissingOptionExample.java
The `AddOrUpdateAnnotationAttribute` now has the optional ability to only update the value if the provided `oldAttributeValue` matches.
In the Spring 3.4 migration some steps are exchanging annotation attribute values if they have a speicific value.
A workaround is a specially crafted recipe for every annotation attribute.
=> Add new parameter `oldAttributeValue` to `AddOrUpdateAnnotationAttribute` recipe

rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactId.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactIdTest.java
Fixes #4902 .
Add an optional parameter to `ChangePluginGroupIdAndArtifactId` that permits the user to specify a `newVersion` Option.  This will update maven plugin version.
- See #4902 .
No.
@timtebeek gave design feedback in #4902 so it may make the most sense to have them review the PR.
=> Optionally update maven plugin version in ChangePluginGroupIdAndArtifactId

rewrite-core/src/main/java/org/openrewrite/internal/StringUtils.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/JenkinsFileTest.java
Just demonstrate a bug that we are facing parsing Jenkinsfile with specific multiline comment on one single line
Raise java.lang.StringIndexOutOfBoundsException: String index out of range: 287
No idea how to fix it but it just highlight the issue
=> Groovy parser fail with single line comment

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Changing the behavior of YAML parser with regards to `@variables@`. The special handling of these is now reduced to only the situations when there's space before `@`.
One of the Moderne customers has reported an edge case of YAML parser corrupting values containing `@` in some cases.
- These `@variables` are **not** part of the YAML standard
- It seems our support for them has been added in 2021 to address some specific Spring Boot issue - see #509
- As part of the spec, the `@` sign is not allowed to start a scalar value
- Thus I think it's a fine middle ground to continue to support these non-standard variables in a reduced scope, but fix the problem of `@` being used within the values.
- An alternative would be to drop the support for `@variables@` as non-complaint. But that would be …
=> YAML Parser not to take @variables@ in the middle of scalar

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyTypeAttributionTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/format/OmitParenthesesForLastArgumentLambdaTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ConstructorTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/EnumTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ForLoopTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodDeclarationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/TryTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/VariableDeclarationsTest.java
Also, using `@ExpectedToFail` I found a bunch of tests which appear to have been fixed. I enabled those and replaced `@Disabled` with `@ExpectedToFail` on others.
=> Support Groovy methods declaring generic type parameters

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
Fixing the handling of an edge-case of a YAML with:
- multiline literals using the `|` syntax
- and quoted identifiers.
In some scenarios the YAML parser tends to swallow the first letter of the literal:
```diff
- "one": |
two
-  "three": "four"
+  "hree": "four"
] 
```
which is clearly a bug.
=> Fixing YAML handling of multiline literals in some cases

rewrite-xml/src/main/java/org/openrewrite/xml/style/Autodetect.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/style/Autodetect.java
Minor thing. Pure refactoring.
Renaming two visitors not to use Java in their names as they pertain to XML and YAML respectively.
Clean up the code, make it more readable.
The rename has been triggered by 
- https://github.com/openrewrite/rewrite/pull/4916#discussion_r1919757939
=> Refactoring, renaming visitors not to use Java in their name

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyTypeMapping.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java
While a class extending `groovy.lang.Script` typically represents the synthetic class representing the Groovy script as a whole, this is not necessarily the reason.
Additionally, also fix parsing of classes extending `Object` as well as correct type attribution for parsed classes with a super class (the `JavType.Class` should not declare any inherited methods).
=> Allow Groovy class to extend `groovy.lang.Script`

rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Switch expressions now map the type information provided by the compiler instead of trying to determine it
- fixes https://github.com/openrewrite/rewrite/issues/4928
@timtebeek @knutwannheden
=> Map compiler type information for `SwitchExpression`

rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
For the two recent changes to `J.Case` and `J.SwitchExpression` which both added new fields, the constructor changed and no constructor was added for API backwards compatibility.
This commit adds the corresponding constructors and annotates them both as `@Deprecated` and as `@ScheduledForRemoval` (from the JetBrains annotations). For the latter we provide a date value for the `inVersion` attribute as in `@ScheduledForRemoval(inVersion = "2025-05-01")`. This will allow us to implement some simple tooling to weed these constructors out again, without this chore getting forgotten.
=> Add backwards compatibility constructors

rewrite-java-test/src/test/java/org/openrewrite/java/ChangePackageTest.java, rewrite-java/src/main/java/org/openrewrite/java/PackageMatcher.java
Found as part of Spring Boot 3.3 migration, when trying to update an `application.yaml` file.
=> Fix bug in `PackageMatcher`

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateAnnotationTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/AnnotationTemplateGenerator.java
This will for example allow the `org.openrewrite.java.testing.junit5.RunnerToExtension` recipe to replace the `@RunWith` with `@ExtendWith` when on a nested class.
=> Support annotations on nested classes in `AnnotationTemplateGenerator`

rewrite-hcl/src/main/java/org/openrewrite/hcl/ReplaceLegacyAttributeIndexSyntax.java, rewrite-hcl/src/test/java/org/openrewrite/hcl/ReplaceLegacyAttributeIndexSyntaxTest.java
Adding a new recipe for HCL called `ReplaceLegacyAttributeIndexSyntax`.
This is to migrate from this syntax which HCL considers legacy (which BTW we have recently added support for in the parser - see #4901):
```
aws_acm_certificate.google_dot_com.0.resource_record_name
```
to the "modern" one doing effectively the same:
```
aws_acm_certificate.google_dot_com[0].resource_record_name
```
To enable HCL users of OpenRewrite to migrate their code to new syntax.
=> Adding ReplaceLegacyAttributeIndexSyntax

rewrite-core/src/main/java/org/openrewrite/style/GeneralFormatStyle.java, rewrite-core/src/main/java/org/openrewrite/style/LineWrapSetting.java, rewrite-json/src/main/java/org/openrewrite/json/format/AutoFormatVisitor.java, rewrite-json/src/main/java/org/openrewrite/json/format/Indents.java, rewrite-json/src/main/java/org/openrewrite/json/format/TabsAndIndentsVisitor.java, rewrite-json/src/main/java/org/openrewrite/json/format/WrappingAndBraces.java, rewrite-json/src/main/java/org/openrewrite/json/format/WrappingAndBracesVisitor.java
Continuation of #4931.
Taking the `GeneralFormat.useCRLF` setting in the `WrappingAndBracesVisitor` - part of JSON style autodetection and formatting.
Addressing [this comment](https://github.com/openrewrite/rewrite/pull/4931#discussion_r1928428190) from PR review.
=> Honoring useCRLF in WrappingAndBracesVisitor

rewrite-gradle/src/main/groovy/RewriteGradleProject.groovy, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassDeclarationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ClassExpressionTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
When a Groovy class with a constructor is declared within a compilation unit with a package declaration, the parsing fails.
=> Fix bug parsing Groovy constructor declarations

rewrite-maven/src/main/java/org/openrewrite/maven/trait/MavenDependency.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenSettingsTest.java
At Maven resolution time, if a `MavenSettings` is provided both as part of the `ExecutionContext` and also as part of the `MavenResolutionResult` (created during LST build time), rather than let one override the other, we want to merge them.
There are cases that require adding additional repositories for performance reasons.
Making sure the merge logic is in the correct direction.
@sambsnyd @jkschneider 
N/A
N/A
=> Merge provided and built MavenSettings

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java
Check the sym attribute for "lombok.Generated" instead of looking at the Lombok.Generated annotation. 
Lombok is at runtime not always on the classpath, which leads to a `NoClassDefFoundError`.
=> Check for "lombok.Generated" attribute instead of checking for the `Generated` lombok annotation

rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
=> Fix bug in handling default case in switch statement

rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java, rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
Minor refactoring in a single test: `AutodetectTest` in `rewrite-java-test`.
Simplify code.
I noticed this when doing #4935 and thought this could be helpful.
=> Refactoring AutodetectTest to simplify getStyle

rewrite-java-test/src/test/java/org/openrewrite/java/style/AutodetectTest.java, rewrite-java/src/main/java/org/openrewrite/java/style/Autodetect.java
Reverts openrewrite/rewrite#4947 as it causes:
```
Caused by: java.lang.NoSuchMethodError: 'void org.openrewrite.java.style.Autodetect$Detector.sample(org.openrewrite.SourceFile)'
```
in some of the CI checks.
I continue to believe the change is sound, but apparently we are facing some CI infra issues with incompatible versions being taken.
=> Revert "Refactoring AutodetectTest to simplify getStyle"

rewrite-core/src/main/java/org/openrewrite/style/LineWrapSetting.java, rewrite-json/src/main/java/org/openrewrite/json/format/AutoFormat.java, rewrite-json/src/main/java/org/openrewrite/json/format/AutoFormatVisitor.java, rewrite-json/src/main/java/org/openrewrite/json/format/TabsAndIndentsVisitor.java, rewrite-json/src/main/java/org/openrewrite/json/format/WrappingAndBraces.java, rewrite-json/src/main/java/org/openrewrite/json/format/WrappingAndBracesVisitor.java, rewrite-json/src/main/java/org/openrewrite/json/style/Autodetect.java, rewrite-json/src/main/java/org/openrewrite/json/style/TabsAndIndentsStyle.java, rewrite-json/src/main/java/org/openrewrite/json/style/WrappingAndBracesStyle.java, rewrite-json/src/test/java/org/openrewrite/json/format/AutoFormatTest.java, rewrite-json/src/test/java/org/openrewrite/json/format/TabsAndIndentsVisitorTest.java, rewrite-json/src/test/java/org/openrewrite/json/format/WrappingAndBracesVisitorTest.java
Continuation of #4931.
Additional step in JSON autoformatting. Taking care of the indents, prefixes and suffixes around object and array members.
To provide more complete support for JSON style autodetection and autoformatting.
As indicated in Github comments.
=> Applying JSON formatting to members of objects and arrays

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/internal/Delimiter.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/LiteralTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
Exclude parentheses handling for comments and string literals.
Improvement to
- https://github.com/openrewrite/rewrite/pull/4951
=> Exclude parenthese determination from comments and string literals

rewrite-yaml/src/main/java/org/openrewrite/yaml/format/MinimumViableSpacingVisitor.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Fixing the unwanted carriage return when merging yaml values that are written in flow style
- Resolves #4958
=> Preserve spacing when merging flow style YAML

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ImportTest.java
- Duplicate static star imports work as well.
- Shorten the parser code for ImportNode (we have now methods like `sourceStartsWith`)
- https://github.com/openrewrite/rewrite/issues/4068
=> Support duplicate static star imports for Groovy

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
The `visitClass` method is written a little shorter
=> Use `sourceStartsWith` to simplify visitClass

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ImportTest.java
Duplicate star imports can also have comments.
- https://github.com/openrewrite/rewrite/pull/4982
=> Support duplicate star imports with comments

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Disable parentheses level discovery for methods for Groovy 2.
Groovy 2 does not contain the information we need, it always return -1 for the method calls object-expression. In older version of the groovy-parser this did not cause any exceptions, but since
- https://github.com/openrewrite/rewrite/pull/4951
it does.
Notice before PR #4951, the parser did also not support parentheses level discovery for methods for Groovy 2, but I did not throw an errors by chance.
Would  be nice to have a real working solution for Groovy 2 as well. But let's focus on that at a later stage.
=> Disable parentheses level discovery for method calls for groovy 2

rewrite-yaml/src/main/java/org/openrewrite/yaml/CopyValue.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYamlVisitor.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Add a `insertBefore` option to MergeYaml recipe.
At the moment, the given yaml is always added at last point.
Original:
```yaml
first: 1
third: 3
```
Given:
```yaml
second: 2
```
Transformed:
```yaml
first: 1
third: 3
second: 2
```
With this new option you can define at what point you'll want to insert given yaml. So in the above example, you can make it happen you'll get:
```yaml
first: 1
second: 2
third: 3
```
I choose to implement it the easy way, without a JsonPath or anything. I figured this was not needed at all, as the user applies the insert depth already with the `key` property. 
The new `insertBefore` property just let's you choice where you want insert it for existing keys "within" the `key` property place.
=> Add `insertBefore` option to MergeYaml

rewrite-core/src/main/java/org/openrewrite/marker/GitProvenance.java
Do not create `GitProvenance` for bare git repositories.
We need a working tree to be able to process projects; a lack thereof should not proceed further.
=> Skip GitProvenance for bare repositories

rewrite-core/src/main/java/org/openrewrite/Result.java, rewrite-core/src/main/java/org/openrewrite/UnknownSourceFileChangeException.java
In order to allow clients of OpenRewrite to decide whether to include (or not) the diff text when a source file changed but no changes were reported, extract the logic to a new `Exception`, `UnknownSourceFileChangeException`, passing in the `SourceFile` and diff.
N/A
N/A
The workaround would be to read the text of the error message, which is error- and change-prone.
N/A
~- [ ] I've added unit tests to cover both positive and negative cases~
=> Don't include diff in exception in `Result`

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/internal/Delimiter.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AnnotationTest.java
Annotations on variables are supported as well.
- https://github.com/openrewrite/rewrite/issues/4853
The `@groovy.transform.Field` annotation is a transformer annotation, it changes the scope of a variable within a script to the class level for the script (see [javadoc](https://docs.groovy-lang.org/latest/html/gapi/groovy/transform/Field.html)). This means that the original DeclarationExpression is gone, but the Groovy Compiler replaced it by a semi empty  ConstantExpression.
I put in some work to make it work again, by recreating a DeclarationExpression. This is done very roughly, so the code is neither beautiful nor does restore all type information. At least we can parse `@Field` annotation now, instead of failing. If you have a better idea how to handle this, my ears are open!
=> Groovy parser does not support annotations on variable declarations

rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java, rewrite-java/src/test/java/org/openrewrite/java/internal/parser/TypeTableTest.java
When `VERIFY_CLASS_WRITING` was set to true, we would _not_ validate, while we should.
Seeing downstream failures in rewrite-hibernate that had failed to replicate here
- https://github.com/openrewrite/rewrite/issues/4993
=> Validate written classes if enabled, and fix reported issues

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21Parser.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/LombokTest.java
Default Lombok is disabled again.
There are still issues with Lombok, which  causes wrong positions in the AST. The parsers will break when the positions are off.
=> Disable Lombok again

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateSubstitutionsTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateParser.java
Fixing JavaTemplateParser not to add a semicolon when doing a method arguments replacement.
To address an issue reported by an openrewrite user. The issue symptoms were:
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
org.openrewrite.internal.RecipeRunException: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:290)
at org.openrewrite.TreeVisitor.visit(TreeVisitor.java:157)
at org.openrewrite.java.JavaTemplate.apply(JavaTemplate.java:115)
at org.openrewrite.staticanalysis.BigDecimalRoundingConstantsToEnums$1.visitMethodInvocation(BigDecimalRoundingConstantsToEnums.java:93)
at org.openrewrite.staticanalysis.BigDecimalRoundingConstantsToEnums$1.visitMethodInvocation(BigDecimalRoundingConst …
```
=> Fixing JavaTemplateParser wrt method arguments replacement - removing extra semicolon

rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
Changing two test cases of `ChangeParentPomTest`. Specifically the `pom.xml` they define.
Adding explicit Maven Central repository as the first one, before the Jenkins one (the Maven Central repository is present by default in Maven anyway, it just defaults to being the last one as per this [StackOverflow post](https://stackoverflow.com/a/51792634)).
I've observed the `ChangeParentPomTest` spends a lot of time sending requests to various artifacts in the `jenkins-ci.org` Maven repo. The requests are:
- slow (~600ms vs. ~40ms to Maven Central) where I live
- and they 404 anyway as the Jenkins repo doesn't provide all versions of these standard Java libraries like Jetty or commons-logging
To speed up the CI of this project.
Non-scientific measurement on my laptop for the single test case of …
=> Declaring Maven Central as first repository for some of the tests

rewrite-benchmarks/build.gradle.kts
Upgrading the JMH Gradle plugin to the latest available version (0.7.3).
- It started with me seeing a `Space-assignment syntax in Groovy DSL has been deprecated.` warning in an unrelated Gradle build
- then I noticed we are using an old version, and the old version is violating the minimal plugin version as per https://github.com/melix/jmh-gradle-plugin/blob/493a4f0ca583d95ee5a61f20ae840d8d83eaa108/README.adoc#L38
- and then I tried running the JMH benchmarks locally and without the change they failed with the following error (which goes away after the upgrade):
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':rewrite-benchmarks:jmhRunBytecodeGenerator'.
> 'void org.gradle.workers.WorkerExecutor.submit(java.lang.Class, org.gradle.api.Action)' …
```
=> JMH Gradle plugin 0.7.3

rewrite-java-test/build.gradle.kts
Removing `rewrite-java-test` dependency on `rewrite-maven`.
To speed up the CI of this project.
I've observed a few Gradle scans which spent excessive time running various flavours of compatibility tests for what seems no actual purpose.
E.g. [the Gradle scan for the PR 5023](https://ge.openrewrite.org/s/junoxzkh6h7fg/timeline) has:
The dependency seems to have been added in https://github.com/openrewrite/rewrite/commit/bba8b92fd85ae27b8bb2d5b2a7bfb8bafc2449ad
After that, the actual class needed got moved, but the dependency remained.
=> Removing `rewrite-java-test` dependency on `:rewrite-maven`

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolutionEventListener.java
When a normalization attempt fails, the repository gets cached as `null` and any subsequent normalization attempts are skipped. When this cache is persisted we lose any such information in subsequent runs. Adding this event can give a hint as to why repositories are not attempted for downloading.
New event added and used
Not knowing why a repository is not attempted to be used for downloading
It would be even nicer of downloadError could list all the repositories NOT attempted (with reasons), but that would be a much bigger change.
=> Add `ResolutionEventListener` event whenever a repository normalization attempt is skipped

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21Parser.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java
Only use this version of Lombok.
=> Hardcode Lombok 1.18.37 version

rewrite-core/src/main/java/org/openrewrite/internal/ReflectionUtils.java, rewrite-java-11/build.gradle.kts, rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java, rewrite-java-17/build.gradle.kts, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java, rewrite-java-21/build.gradle.kts, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21Parser.java, rewrite-java-8/build.gradle.kts, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java, rewrite-java-lombok/build.gradle.kts, rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/Lombok.java, rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/LombokSupport.java
The logic to initialize the Lombok annotation processor is now moved to the `rewrite-java-lombok` project and used by all Java parsers.
=> Centralize Lombok initialization logic

rewrite-java/src/main/java/org/openrewrite/java/JavaParser.java, rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java, rewrite-java/src/test/java/org/openrewrite/java/internal/parser/TypeTableTest.java
Read all TypeTable files on the classpath, not just the first.
rewrite-spring depends on rewrite-migrate-java, and as such there's more than one. If the wrong one is picked up, then classes can not be found. If only the recipe modules' own is picked up, then chaining in recipes from other modules might not work.
- As discovered on https://github.com/openrewrite/rewrite-spring/pull/676#issuecomment-2659270062
=> Read all TypeTable `classpath.tsv.zip` files

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodDeclarationTest.java
- **Bugfix**: Support for modifiers for method declarations parameters.
- **Improvement**: Merge `visitModifiers` and `getModifiers` methods.
Code like
```groovy
def accept(final def Map m) {}
def accept2(def m) {}
```
could not be parsed.
=> Support modifiers for Groovy method declaration parameters

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserVisitorTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ImportTest.java
- Building up on #4982.
Changing the special handling of star static imports. The line numbers were calculated improperly, resulting in strange behavior of the `visit` method wrt `sortedByPosition`.
Basically this assumption turned out not to be true in a specific case:
https://github.com/openrewrite/rewrite/blob/194b33db0c7f48fb8b511282ef7d0b53455d2e47/rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java#L2863
To fix a Groovy parsing error demostrated in `org.openrewrite.groovy.tree.ImportTest#multiLineCommentBeforeStarStaticImport`. It resulted in a strange exception of:
```
Caused by:
java.lang.ClassCastException: class org.openrewrite.java.tree.J$Identifier cannot be cast to class org.openrewrite.java.tree.J$FieldAccess (org.openrewrite.java.tree.J$Identifier …
```
=> Groovy - fix support for import statements following multiline comments

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/CommentTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
Multi line comment is allowed at almost any part of the Java source code
where whitespace is allowed. The reloadable Java parser visitor however
swallows multi line comment at the end of a method declaration, which
happens to be a common pattern in GWT in order to embed JavaScript in a
Java class.
- Note that this effectively is a partial revert of https://github.com/openrewrite/rewrite/pull/4412
(commit https://github.com/openrewrite/rewrite/commit/ac32851e09c9b76aed56c898844e217fa9e61367).
- Fixes https://github.com/openrewrite/rewrite/issues/4995
=> fix: handle comment at the end of a method declaration

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/marker/RedundantDef.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodDeclarationTest.java
- Removed use of `RedundantDef` marker in parser
- Improved use of `getModifiers` method
Improvement to:
- https://github.com/openrewrite/rewrite/pull/5045
=> Groovy Parser - Improve retrieval of modifiers

rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/ChangePropertyKey.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/CopyValue.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYamlVisitor.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
- Support comments for the `insert before` option
- Support `insert before` for sequences
- Add support to `insert after`.
- https://github.com/openrewrite/rewrite/pull/4992
was written a little to fast. Lot's of edge cases were missing.
There are still bugs left:
- Adding comments in the `YAML snippet` option does not really work; all cases where it does work are just by luck.
- Comments in [sequences](https://docs.openrewrite.org/concepts-and-explanations/yaml-lst-examples#sequence) do not work very well either. To fix this with current LST model, the same kind of code written inside the `mergeMapping` function should be written inside the `mergeSequence` too.
=> Improve MergeYaml recipe

rewrite-java-test/src/test/java/org/openrewrite/java/format/RemoveTrailingWhitespaceTest.java
Removing `@Disabled` annotation from one of the test cases.
I just found it by accident.
And just figured out the test passes, so I thought we should re-enable.
=> Re-enable disabled test case

rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeRunCycle.java
- Partial(?) fix for https://github.com/openrewrite/rewrite/issues/4909
Do we want to see additional effort logged for #4909 ? This seemed like an omission, but I'm not sure about further changes.
@bmuschko @sambsnyd 
We could also assign some effort for the scanning phase of a recipe, or when creating a data table row. That seems a bit further removed from how we've traditionally estimated and measured effort though, so not (yet) included here.
=> Record a SourcesFileResults.Row for generated sources

rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
This is an attempt to fix this issue #5031
resolves #5031
In the tests, I didn't have the chance to cover the windows line break `CRLF`, though it is implemented in the code.
@timtebeek 
The prefix of the YML entry is split with respect to the line breaks, this way, the last line breaks are lost, then the next entry is appended directly to the comment above, which is considered its prefix.
=> MergeYaml: prevent keys to be appended to the last commit tests

rewrite-yaml/src/main/java/org/openrewrite/yaml/tree/Yaml.java
Add constructors to Yaml.Scalar, Yaml.Sequence and Yaml.Mapping as they existed before
- https://github.com/openrewrite/rewrite/pull/4934
We're getting reports about folks that are attempting to run older compiled recipes with newer versions of the CLI.
```
java.lang.NoSuchMethodError: 'void org.openrewrite.yaml.tree.Yaml$Scalar.<init>(java.util.UUID, java.lang.String, org.openrewrite.marker.Markers, org.openrewrite.yaml.tree.Yaml$Scalar$Style, org.openrewrite.yaml.tree.Yaml$Anchor, java.lang.String)'
```
By restoring these constructors we allow for a gradual adoption, as opposed to a hard required cut over.
I'd added the JsonCreator to avoid ambiguity with deserialization; anything else we'd need to think of?
Not possible to force everyone to switch over at once.
Not desirable to roll …
=> Restore Yaml.* constructors without Tag for gradual adoption

rewrite-core/src/main/resources/META-INF/rewrite/core-categories.yml
We already had `io` there, but then we also have both `org` and `org.openrewrite`. Would this then similarly help group recipes? as needed for 
- https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/167
- https://github.com/moderneinc/rewrite-ai-search/commit/76df9fb37d57791f0e86e9d5eb1f0b46878045f1
=> Add `io.moderne` as root category, same as `org.openrewrite`

rewrite-core/src/main/java/org/openrewrite/Result.java, rewrite-java-test/src/test/java/org/openrewrite/ResultTest.java
When a recipe makes a modification which violates an LST not-null constraint, this can then trigger the validation during the deserialization to return a `Quark` instead of the original source file.
=> Accept after with `DeserializationError` marker in `Result` constructor

rewrite-java-tck/src/main/java/org/openrewrite/java/tree/CommentTest.java, rewrite-java/src/main/java/org/openrewrite/java/tree/Space.java
Fixing an edge case of Java parsing. Namely when a single-line empty comment is at the end of the file and there's no newline after that.
```
class A {
}
//
```
Feedback from one of the OpenRewrite users.
=> Java parsing fix for empty comment as last line

rewrite-hcl/src/main/java/org/openrewrite/hcl/tree/Space.java, rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclCommentTest.java, rewrite-json/src/main/java/org/openrewrite/json/tree/Space.java, rewrite-json/src/test/java/org/openrewrite/json/JsonParserTest.java, rewrite-toml/src/main/java/org/openrewrite/toml/tree/Space.java, rewrite-toml/src/test/java/org/openrewrite/toml/TomlParserTest.java
A follow-up on #5076. I.e. fixing handling of trailing empty single-line comments in:
- HCL
- JSON
- TOML
Addressing this comment: https://github.com/openrewrite/rewrite/pull/5076#issuecomment-2673756937
=> Fixing handling of trailing empty single-line comment

rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java
As many of us found it difficult to read/parse. I think just adding newlines and bringing back the link to docs will be helpful.
=> Reformat the method pattern description to be more readable

rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java
The `getCommentTree` call in the Java 17 parser is called via reflection again .
- https://github.com/PicnicSupermarket/error-prone-support/pull/1557
=> Put the `getCommentTree` reflection code back in the Java 17 parser

rewrite-core/src/main/java/org/openrewrite/internal/AdaptiveRadixTree.java
Rather than storing the compressed keys in `byte[]` fields in each individual `Node` object, the nodes now only have two `int` fields: `keyOffset` and `keyLength`. These identify a range of a large `byte[]` used for the entire tree.
This implementation uses less memory and is also faster for both read and write operations.
=> More compact `AdaptiveRadixTree`

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/CompilationUnitTest.java, rewrite-hcl/src/main/java/org/openrewrite/hcl/internal/HclParserVisitor.java, rewrite-hcl/src/test/java/org/openrewrite/hcl/tree/HclCommentTest.java, rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/CommentTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java, rewrite-json/src/test/java/org/openrewrite/json/JsonParserTest.java, rewrite-protobuf/src/main/java/org/openrewrite/protobuf/internal/ProtoParserVisitor.java, rewrite-protobuf/src/test/java/org/openrewrite/protobuf/tree/EmptyTest.java
This PR adds a test case to demonstrate an error that occurs when parsing multi-line comments in Java.
Source file to parse:
```
package hello;
public class Test {
public static void test() {
/*addItem("Site A", "http://hello.com/A");
addItem("Site B", "http://hello.com/B");
addItem("Site C", "http://hello.com/C");*/
}
}
```
Resulting error from the parser:
```
[When parsing and printing the source code back to text without modifications, the printed source didn't match the original source code. This means there is a bug in the parser implementation itself. Please open an issue to report this, providing a sample of the code that generated this error for "hello/Test.java":
diff --git a/hello/Test.java b/hello/Test.java
index a16afb8..629000e 100644
--- a/hello/Test.java
+++ …
```
=> Fix parsing of multi-line comments "containing" single-line comments

rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java
Only match row GAV against artifact name patterns when different from previous row's GAV.
Also, don't accumulate classes over artifact boundaries.
=> Performance improvement for `TypeTable.Reader`

rewrite-java-tck/build.gradle.kts
Optimize rewrite build time by fixing caching issues, potentially saving **4m48s** on each `compatibilityTest`, `check` and `build` build.
These were discovered running [develocity-build-validation-scripts](https://github.com/gradle/develocity-build-validation-scripts) against the rewrite project. The scripts run 2 subsequent builds to validate that the 2nd was able to re-use work done by the 1st. 4 tasks in `rewrite` couldn't be re-used:
([Workflow run](https://github.com/jprinet/gradle-enterprise-oss-projects/actions/runs/13389683413/job/37394343957#step:6:1479))
In practice, these 4 tasks always re-run and are never `UP-TO-DATE` or `FROM-CACHE`. In Develocity, we can see that re-running these tasks amounts to **4m48s** wall-clock time.
([Build …
=> Fix caching issues in rewrite build

rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYamlVisitor.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
- The `validate` function can now handle wrong input yaml (it fails gracefully, as it is supposed to be)
- The `incoming` field is parsed once it is needed in the MergeYaml recipe.   
The MergeYaml recipe throws a ClassCastException if invalid Yaml is provided (for instance a [ParseError ](https://github.com/openrewrite/rewrite/blob/main/rewrite-core/src/main/java/org/openrewrite/tree/ParseError.java) LST). Normally the YamlIsoVisitor does only run for yaml sources:
```java
@Override
public boolean isAcceptable(SourceFile sourceFile, P p) {
return sourceFile instanceof Yaml.Documents;
}
```
But the MergeYaml recipe does already do some parsing work for the `incoming` field, which is executed by the JVM before the `isAcceptable` has been called. This PR changes this behaviour to start …
=> MergeYaml recipe: Handle ParseError LSTs

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java
The `visitSequence()` method pruned the subtree in some cases leading to that subtree maybe still containing `SequenceWithPrefix` or `MappingWithPrefix` objects, which should be "unwrapped".
=> Make sure `YamlParser#unwrapPrefixedMappings()` visits entire tree

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
Simple NPE fix for old LSTs that don't have `ResolvedPom#pluginRepositories`.
=> Guard against null repos in `MavenPomDownloader#distinctNormalizedRepositories`

rewrite-core/src/main/java/org/openrewrite/shell/exec/ShellExecutor.java
Update `ShellExecutor#exec` to throw an appropriate exception when a shell command's execution fails to complete within the given timeout.
This change will assist in troubleshooting recipes relying on execution of external shell commands. Prior to these changes the following exception was thrown on the call to `Process#waitForm`: `java.lang.IllegalThreadStateException: process hasn't exited` 
No.
@timtebeek @sambsnyd 
No.
No.
=> Detect shell command timeouts and throw an appropriate exception

rewrite-core/src/main/java/org/openrewrite/DataTable.java
Add a method for deciding to allow writing in the current cycle or not. 
This can be used to divert from the default behaviour, which used to be possible with the `maxCycle` field
no
@MBoegers
=> Allow overriding of the cycles that data-tables are allowed to write in.

rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveDependencyTest.java
- Fix https://github.com/openrewrite/rewrite/issues/5117
The reason for this bug should be we ignore parse pom when `type=zip`.
https://github.com/openrewrite/rewrite/blob/main/rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java#L893
I think currently the check is too restrict and for `type=zip` its ok to do after pom parse. For example for the dependency in my test case:
```xml
<dependency>
<groupId>org.elasticsearch.distribution.integ-test-zip</groupId>
<artifactId>elasticsearch</artifactId>
<version>7.17.15</version>
<type>zip</type>
</dependency>
```
Its `pom.xml` is:
https://repo1.maven.org/maven2/org/elasticsearch/distribution/integ-test-zip/elasticsearch/7.17.15/elasticsearch-7.17.15.pom
Fix https://github.com/openrewrite/rewrite/issues/5117
=> fix: ResolvedPom with type=zip

rewrite-gradle/src/main/java/org/openrewrite/gradle/search/FindDependency.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/search/FindDependencyTest.java
GAVs in gradle are represented as `G.GString` if they utilize String interpolation.
able to match `api "org.openrewrite:rewrite-core:${someVersion}"`
=> find-dependency-with-versions

rewrite-java-test/src/test/java/org/openrewrite/java/MethodMatcherTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/search/FindDeprecatedMethodsTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/search/FindMethodsTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddCommentToMethod.java, rewrite-java/src/main/java/org/openrewrite/java/AddLiteralMethodArgument.java, rewrite-java/src/main/java/org/openrewrite/java/AddNullMethodArgument.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodAccessLevel.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodInvocationReturnType.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodName.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodTargetToStatic.java, rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodTargetToVariable.java, rewrite-java/src/main/java/org/openrewrite/java/DeleteMethodArgument.java, rewrite-java/src/main/java/org/openrewrite/java/MethodMatcher.java, rewrite-java/src/main/java/org/openrewrite/java/NoStaticImport.java, rewrite-java/src/main/java/org/openrewrite/java/RemoveMethodInvocations.java, rewrite-java/src/main/java/org/openrewrite/java/ReorderMethodArguments.java, rewrite-java/src/main/java/org/openrewrite/java/UseStaticImport.java, rewrite-java/src/main/java/org/openrewrite/java/search/FindDeprecatedMethods.java, rewrite-java/src/main/java/org/openrewrite/java/search/FindMethodDeclaration.java, rewrite-java/src/main/java/org/openrewrite/java/search/FindMethods.java, rewrite-java/src/main/java/org/openrewrite/java/search/ResultOfMethodCallIgnored.java
Added validation to recipe options (usually called `methodPattern`) that will be turned into a `MethodMatcher`, as misconfiguring the method pattern is a common source of both human and AI error.
Help teach how to use these method patterns correctly, as misconfiguring will simply lead to no results.
=> Validation for recipe options that `MethodMatcher`s are constructed from.

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/RealWorldGroovyTest.java
Bugfix, the groovy parser did not support unassigned closure with GString as return value.
- https://github.com/openrewrite/rewrite/issues/4116
Actually the groovy parser did support it already, it just broke because a `sourceBefore("{")` was called falsy (the `{` char is also part of a GString, which made the parser go wacky).
=> Groovy Parser supports unassigned closure with GString as return value

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java
Regex for parsing package definition in Groovy now correctly handles the optional semicolon
@knutwannheden @shanman190
=> Fix groovy parser parsing package definition

rewrite-yaml/src/main/java/org/openrewrite/yaml/trait/YamlValue.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/trait/YamlValueTest.java
Add a new `YamlValue` trait that makes it easier to write simple YAML recipes that are ultimately just going to modify a YAML mapping entry key ando/or value.
Simplifies a class of YAML recipes.
=> `YamlValue` trait

rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java
Using GZIP adds a small header and a checksum at the end and is a bit "friendlier" as it allows a developer to use `gzcat` to inspect the file contents.
=> Use GZIP rather than raw zlib

rewrite-java-11/build.gradle.kts, rewrite-java-8/build.gradle.kts, rewrite-java-tck/build.gradle.kts
For `rewrite-java-8`, `rewrite-java-11`, and `rewrite-java-tck` we need to use AssertJ 3.x, as AssertJ 4.x now requires Java 17.
=> Pin AssertJ for `rewrite-java-8` to 3.x

rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Slight change in how invalid input (null source) is handled by `MergeYaml`.
Now returning a proper validation error instead of `NullPointerException`.
- fixes #4955
=> Handling null source in MergeYaml

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/EnumTest.java
Fixing how Java enums with no values are parsed. Now they get the `J.EnumValueSet` element with no values. Previously they were parsed as `J.Empty`.
- addressing #5146
=> Handling enums with no values as J.EnumValueSet

rewrite-yaml/src/main/java/org/openrewrite/yaml/MergeYaml.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/MergeYamlTest.java
Fixing `MergeYaml` wrt not duplicating a comment in the specific case of the comment being the last thing:
```diff
containers: ALEF # comment
-            imagePullPolicy: Always # comment
+            imagePullPolicy: Always
```
I started looking at #5135, but this case showed up as related and even simpler, so I figured I could fix this one too.
#5135 is not fixed yet. Let's keep it open, hopefully another fix will address it.
=> Fixing MergeYaml not to duplicate a comment

rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java
When we write the `.class` files for a `TypeTable`, the file should only contain information about the nested types which also belong to that type.
Before this change all `.class` files would contain information about all nested types, which could result in very large `.class` files.
For the `develocity-gradle-plugin` dependency the `TypeTable.Reader` would end up writing 2.7G worth of class files. With this change this drops down to 32M. At the same time this operation now also takes a lot less time to complete.
=> Class files from type tables should not include all nested types

rewrite-java/src/main/java/org/openrewrite/java/internal/parser/JavaParserCaller.java, rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java, rewrite-java/src/test/java/org/openrewrite/java/internal/parser/TypeTableTest.java
For non-abstract methods the byte code should contain a `return` statement bytecode.
=> `TypeTable`: Add method bodies

rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java
XPath expression like 
`"//build/plugins/plugin[artifactId=\"openapi-generator-maven-plugin\"]/executions/execution/configuration/configOptions"` should work like
`"//build/plugins/plugin[artifactId='openapi-generator-maven-plugin']/executions/execution/configuration/configOptions"`
=> Handle double quotes in addition of simple quote in XPathMatcher 

rewrite-java/src/main/java/org/openrewrite/java/ChangeType.java
Added a missing return statement in `ChangeType.updateOuterClassTypes()`.
The comment in line 419 says "just a performance shortcut when this isn't an inner class", but without a return statement, the line only creates a modified object which is then discarded.
=> Adding a missing return, without which a supposed optimization does nothing

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
Method field type references in superclasses and interfaces are now discovered as well.
Having a setup like [AbstractSinkTest](https://github.com/apache/maven-doxia/blob/ede159d464cebf5fb17131794cac0b48d7f21f5a/doxia-core/src/test/java/org/apache/maven/doxia/sink/impl/AbstractSinkTest.java#L101):
```java    
public interface SomeInterface {
boolean test();
}
interface Test extends SomeInterface {
/**
* @see #test()
*/
void onSectionTitle();
}
```
would not find the `test` method reference.
Conceptually equal to:
- https://github.com/openrewrite/rewrite/pull/5163
=> Find method type references in JavaDoc in interfaces and superclasses

rewrite-core/src/main/java/org/openrewrite/DelegatingExecutionContext.java, rewrite-core/src/main/java/org/openrewrite/ExecutionContext.java, rewrite-core/src/main/java/org/openrewrite/InMemoryExecutionContext.java, rewrite-maven/src/main/java/org/openrewrite/maven/MavenExecutionContextView.java
I got a test failure locally which didn't seem like it should be the result of this change so I wanted to check if it reproduced on CI
=> Fix nullability warnings around ExecutionContext.getMessages()

rewrite-java/src/main/java/org/openrewrite/java/internal/template/AnnotationTemplateGenerator.java
Find an valid `annotationParent` to avoid exception.
I have no idea how to program a UT in `rewrite-java`.
Here's how I reproduce the exception:
Run `MigrateApiImplicitParam` on below code, and it throws exception. After debugging, It seems that `AnnotationTemplateGenerator` didn't generate a proper template due to an invalid `annotationParent`. 
This PR tries to find an valid parent.
Code:
```java
import io.swagger.annotations.*;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import org.apache.hc.core5.http.HttpStatus;
public class Example {
@ApiImplicitParams({
@ApiImplicitParam(name = "version", defaultValue="X", required = true, dataType = …
```
=> Retry searching for proper parent

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Direct links to constructors are now supported.
Code like [Maven Doxia's](https://github.com/apache/maven-doxia/blob/ede159d464cebf5fb17131794cac0b48d7f21f5a/doxia-core/src/main/java/org/apache/maven/doxia/index/IndexingSink.java#L41) IndexingSink class gave missing type reference errors:
```java
public class IndexingSink {
/**
* @deprecated legacy constructor, use {@link #IndexingSink(Sink)}.
*/
@Deprecated
public IndexingSink(IndexEntry rootEntry) {
this(rootEntry, new SinkAdapter());
}
public IndexingSink(Sink delegate) {
this(new IndexEntry("index"), delegate);
}
}
```
The parser could not find the types for the constructor arguments.
=> Support this-constructor-links in JavaDoc

rewrite-maven/src/main/java/org/openrewrite/maven/AddProperty.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersion.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersionTest.java
When the maven compiler plugin is configured with a property in the parent pom which is overridden by child poms the child pom is now correctly updated instead of adding the property to the parent
=> Fix handling of maven compiler plugin configuration for java version upgrade

rewrite-core/src/main/java/org/openrewrite/ExecutionContext.java, rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeRunCycle.java, rewrite-maven/src/main/java/org/openrewrite/maven/AddManagedDependency.java, rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java, rewrite-test/src/main/java/org/openrewrite/test/TypeValidation.java, rewrite-test/src/test/java/org/openrewrite/test/internal/RewriteTestTest.java
By design edits during the scanning phase are ignored. This can be a source of confusion for new recipe authors who don't yet fully understand the difference between the scanning and editing phases of the recipe lifecycle.
=> Add new test validation that ScanningRecipe.getScanner() does not attempt edits.

rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceConstantWithAnotherConstantTest.java, rewrite-java/src/main/java/org/openrewrite/java/ReplaceConstantWithAnotherConstant.java
- Fix https://github.com/openrewrite/rewrite/issues/5174
Remove redundant `isVariableDeclaration`.
Fix https://github.com/openrewrite/rewrite/issues/5174
=> fix: ReplaceConstantWithAnotherConstant not work when use static constant within method

rewrite-java/src/main/java/org/openrewrite/java/format/SpacesVisitor.java, rewrite-kotlin/src/main/java/org/openrewrite/kotlin/format/SpacesVisitor.java
I have a local recipe that still has some false positives, but already was able to find these two cases where the response to an `@With` annotated method call went unchecked.
- Inspired by https://github.com/openrewrite/rewrite/pull/5160
=> Assign response from `withTypeParameters` in `SpacesVisitor`

rewrite-core/src/main/java/org/openrewrite/internal/AdaptiveRadixTree.java
Use a more compact bitmap index based `Node64` implementation rather than the `Node48` with an `index` lookup array (32 bytes vs. 278 bytes).
=> `AdaptiveRadixTree`: Faster reads by using a bitmap index `Node64`

rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/SwitchPatternMatchingTest.java
Adds unit test and fix for parsing of switch expression.
- provide a fix for #5139 
Changing the Java code, splitting the combined case.
=> Fixes parsing of switch expression with combined null and default

rewrite-java/src/main/java/org/openrewrite/java/internal/parser/TypeTable.java
When running tests in parallel two processes might simultaneously try to check if a folder exists, before creating, in which case one might fail. By flipping this around we reduce the chance of failures.
=> Flip mkdirs and Files.exists check for TypeTable parallelism

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaParserTest.java
Fixing parsing of Java enums with no values (and no closing semicolon - as opposed to #5147).
- closes #5186.
=> Fixing parsing of empty enums with no semicolon

rewrite-maven/src/test/java/org/openrewrite/maven/MavenDependencyFailuresTest.java
Speeding up the execution of a single unit test case: `MavenDependencyFailuresTest#unresolvableParent` by adding the Maven central repo explicitly as the first one which effectively changes the order of repositories used:
- Before the change the POM resolution first went to the Jenkins repo and then to Maven Central.
- Now it queries Maven Central first, and only then Jenkins.
Speeding up the whole CI suite for this repo.
Specifically:
- This test case has been observed to be one of the slowest in the whole CI suite.
- Not sure if this is in my location and how it works exactly in Github Actions running CI, but the Jenkins CI Maven repo is fairly slow to me. And most of the artefacts queried don't exist there (and thus they result in 404).
Non-scientific on my laptop; running `./gradlew …
=> Speed-up of `MavenDependencyFailuresTest#unresolvableParent` by declaring central maven repo first

rewrite-core/src/main/java/org/openrewrite/semver/LatestIntegration.java, rewrite-core/src/main/java/org/openrewrite/semver/LatestRelease.java, rewrite-core/src/main/java/org/openrewrite/semver/TildeRange.java, rewrite-core/src/main/java/org/openrewrite/semver/VersionComparator.java, rewrite-core/src/test/java/org/openrewrite/semver/LatestPatchTest.java, rewrite-core/src/test/java/org/openrewrite/semver/TildeRangeTest.java
A pre-release like `2.0.0.Alpha1` should be allowed by the `LatestPatch#isValid()` check. This is only not allowed by `LatestRelease`.
Also, `TildeRange` should accept a version like `1.2.3.v20130506`.
=> `LatestPatch#isValid()` should allow pre-releases

rewrite-java-test/src/test/java/org/openrewrite/java/FindMissingTypesTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateInstanceOfTest.java, rewrite-java/src/main/java/org/openrewrite/java/Assertions.java, rewrite-java/src/main/java/org/openrewrite/java/NoMissingTypes.java, rewrite-java/src/main/java/org/openrewrite/java/search/FindMissingTypes.java
Up until now references in Javadoc have always been checked and reported by this recipe. Now this check is optional.
=> `FindMissingTypes`: New option to check references in Javadoc

rewrite-xml/build.gradle.kts, rewrite-xml/src/test/java/org/openrewrite/xml/AddCommentToXmlTagTest.java
Removing the dependency of `rewrite-xml` on `rewrite-maven`.
To speed up the CI builds in this project.
`rewrite-xml` happened to be one of the modules I saw being built in what seemed an unrelated PR:
It turned out `rewrite-xml` depends on `rewrite-maven` for no strong reason, so I thought we could remove the dependency. And for the context `rewrite-maven` depends on `rewrite-core`, `rewrite-java` and more. Thus it's likely to be built in most of the PRs.
=> rewrite-xml not to depend on rewrite-maven

rewrite-gradle/src/main/java/org/openrewrite/gradle/internal/InsertDependencyComparator.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/AddDependencyTest.java, rewrite-maven/src/main/java/org/openrewrite/maven/internal/InsertDependencyComparator.java
The AddDependency recipe does support gradle files with only non-dependencies in its dependency block.
If you have a gradle file that looks for example like this:
```groovy
dependencies {
if (project.hasProperty('x')) {
implementation "commons-lang:commons-lang:1.0"
}
}
```
The recipe would throw an error:
```bash
Caused by: java.lang.NullPointerException: Cannot read field "value" because "anotherFloat" is null
at java.base/java.lang.Float.compareTo(Float.java:923)
at org.openrewrite.gradle.internal.InsertDependencyComparator.compare(InsertDependencyComparator.java:85)
at org.openrewrite.gradle.AddDependencyVisitor$InsertDependencyInOrder.visitMethodInvocation(AddDependencyVisitor.java:282)
```
For the maven counterpart, this actually has already been addressed in …
=> AddDependency recipe: Support only non-dependencies in Gradle's dependency block

rewrite-groovy/build.gradle.kts, rewrite-groovy/src/groovy2Test/java/org/openrewrite/groovy/GroovyParserTest.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/FindBinaryOperationVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/FindTokenVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Added validation which, if a slash is found when determining parenthesis level, will traverse the node to find whether it is actually a division operator.
- #5072 
Whether this is a valid solution, and if so, is narrowing down the traversal based on source offsets of each expression (like in `FindTokenVisitor.visitBinaryExpression`) necessary.
Also added some Groovy 2 tests to replicate for now, although maybe this would not be preferred as the "JVM Test Suite plugin is an [incubating](https://docs.gradle.org/current/userguide/feature_lifecycle.html#sec:incubating_state) API".
I considered whether we should skip the string parsing altogether and only find delimiters via traversing the node tree somehow, but validating the `SLASHY_STRING` seemed to require less change.
=> Ensure a divison is not interpreted as a `SLASHY_STRING` delimiter

rewrite-core/src/main/java/org/openrewrite/Result.java, rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeRunCycle.java
Making Estimated Time Savings count as 0 for source files which didn't have any change to their text.
To fix the cases of overestimation of the time spent in some cases. E.g. this claims 23 hours saved on a purely mechanical change of 8 files:
I couldn't find a better way to exclude the remote source files than this ugly `instanceof Remote`.
=> Assume timeSavings=0 when no changes are made

rewrite-maven/src/main/java/org/openrewrite/maven/RemoveExclusion.java, rewrite-maven/src/main/java/org/openrewrite/maven/search/FindDependency.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveExclusionTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/search/FindDependencyTest.java
If there are properties in the exclusion block, the recipe can still remove the exclusion block if needed.  
Currently pom files with exclusions with properties were ignored by the recipe.
Also added a properties test for FindDependency recipe to check if the same case applies. The test succeeds without any problems :D.
=> Support properties for RemoveExclusion recipe

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java
There are systems in play that return 408 in case of a connection timeout. While this is probably wrong it's easy enough (and safe) to not assume 408 means the server is reached.
=> Do not accept statuc 408 as server is reached

rewrite-core/src/main/java/org/openrewrite/config/Environment.java, rewrite-core/src/main/java/org/openrewrite/config/ResourceLoader.java, rewrite-core/src/main/java/org/openrewrite/config/YamlResourceLoader.java, rewrite-core/src/main/java/org/openrewrite/internal/RecipeIntrospectionUtils.java, rewrite-core/src/main/java/org/openrewrite/internal/RecipeLoader.java, rewrite-core/src/test/java/org/openrewrite/config/YamlResourceLoaderTest.java
Adds a new `ResourceLoader#loadRecipe(String)` method to allow loading a single recipe. This allows the resource loader to only load a specific recipe. The `YamlResourceLoader` caches the parsed YAML so that any referenced recipes can be demand-loaded more quickly. Additional improvements:
* The `loadRecipe()` method allows specifying which "details" should get loaded (maintainers, contributors, and examples)
* Java recipes referenced from YAML are attempted to be loaded using reflection before reverting to the more powerful Jackson `ObjectMapper`
=> More efficient recipe loading

rewrite-yaml/src/main/java/org/openrewrite/yaml/UnfoldProperties.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/UnfoldPropertiesTest.java
A new recipe which is the inverse of the `CoalesceProperties` recipe.
The `MergeYaml` recipe works with 'normal' yaml files. Spring (and more frameworks) uses a dot notation to mark a hierarchy, though Yaml does not have this in it specification. This recipes unfolds dot notated keys, just like the `CoalesceProperties` recipe folds a hierarchical Yaml file back into keys with dots.
=> Add a new `UnfoldProperties` recipe

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/YamlParserTest.java
1. Added code to adjust the `valueStart` when it contains unicode chracters.
2. closes #5177
=> Fixes the YAML parser issue when unicode characters used.

rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenWrapper.java
Adding a cache for artifacts checksums to `MavenWrapper` code.
The initial trigger for this was to speed up the CI builds of this project. In a non-scientific test locally, `UpdateMavenWrapperTest` (which happens to be one of the slowest tests in the whole suite) goes from ~44s to ~11s with this change.
When taking the whole context, I think it will have positive impact on running `UpdateMavenWrapper` recipe on multiple projects at once (or against a project with multiple `pom.xml` files) too.
=> Introducing artifactChecksumCache in MavenWrapper

rewrite-java/src/main/java/org/openrewrite/java/style/Checkstyle.java, rewrite-java/src/main/java/org/openrewrite/java/style/EmptyBlockStyle.java, rewrite-java/src/main/java/org/openrewrite/java/style/OperatorWrapStyle.java
- Fixes https://github.com/openrewrite/rewrite/pull/4820#pullrequestreview-2525657292
Without this change we were getting
```
java.lang.ExceptionInInitializerError
at org.openrewrite.java.style.CheckstyleConfigLoader.loadCheckstyleConfig(CheckstyleConfigLoader.java:63)
at org.openrewrite.java.style.CheckstyleConfigLoader.loadCheckstyleConfig(CheckstyleConfigLoader.java:54)
at org.openrewrite.java.style.CheckstyleConfigLoaderTest.needBraces(CheckstyleConfigLoaderTest.java:245)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.NullPointerException: wrapOption is marked non-null but is null
at …
```
=> Adopt JSpecify in `EmptyBlockStyle` & `OperatorWrapStyle` without breaking `CheckstyleConfigLoaderTest`

rewrite-groovy/src/groovy2Test/java/org/openrewrite/groovy/GroovyParserTest.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Added logic to determine the parenthesis level for `ConstructorCallExpression`s and `ConstantExpression`s when using Groovy 2.
- #5236 
Not sure if it's the best idea to make use of the `determineParenthesisLevel` method for `ConstantExpression` as I think we just need to count the opening brackets at the start, and we could break early if we find a character that's not an opening bracket.
I've only added this for Groovy 2 since I think `_INSIDE_PARENTHESES_LEVEL` is set on these expressions when using Groovy 3.
I also subtract one from the result of `determineParenthesisLevel` to account for the brackets in `new Class(...)`. Are there any cases this doesn't work?
=> Determine parenthesis level for `ConstructorCallExpression` and `ConstantExpression` when using Groovy 2

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParser.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyTemplate.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/internal/template/GroovyBlockStatementTemplateGenerator.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/internal/template/GroovySubstitutions.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/internal/template/GroovyTemplateParser.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/internal/template/package-info.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyTemplateMatchTest.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyTemplateTest.java, rewrite-kotlin/src/main/java/org/openrewrite/kotlin/KotlinParser.java
Adding a context-free template for Groovy.
Learning, mimicking the KotlinTemplate, possible usage for template support (context-free template cache and parameterization) for `G` types with respect to Gradle more specifically
Nothing in particular
@knutwannheden 
N/A
Started with mimicking the KotlinTemplate in it's current state. I did override the `KotlinTemplate#contextSensitive` method to throw an exception as discussed previously with Knut given Kotlin -- and Groovy via this PR -- only support context-free templates. So requesting a context-sensitive template is an end user error at this time.
=> Add Groovy context-free template

rewrite-gradle/build.gradle.kts
Pinning `com.gradle:develocity-gradle-plugin` to 3.x.
Fix the broken CI as explained in #5270.
=> Pinning com.gradle:develocity-gradle-plugin to 3.

rewrite-java/src/main/java/org/openrewrite/java/ChangeMethodInvocationReturnType.java, rewrite-java/src/main/java/org/openrewrite/java/ReplaceStringLiteralValue.java, rewrite-java/src/test/java/org/openrewrite/java/ChangeMethodInvocationReturnTypeTest.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersion.java, rewrite-maven/src/main/java/org/openrewrite/maven/UseMavenCompilerPluginReleaseConfiguration.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenProjectPropertyJavaVersionTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/UseMavenCompilerPluginReleaseConfigurationTest.java
Consistently apply license headers to files that were moved here in
- https://github.com/openrewrite/rewrite/pull/4918
We use the Apache License in this module, as opposed to the MSAL in some others modules.
The intent of #4918 was to accommodate our Quarkus friends with Apache Licensed recipes.
This change makes the license headers reflect that.
=> Use consistent license headers for files moved here

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest.java, rewrite-java/src/main/java/org/openrewrite/java/ParenthesizeVisitor.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/Substitutions.java
This is for the case when a parameter supplied to a `JavaTemplate` requires parenthesizing when inserted into the LST of the template.
Consider the case when the `J.Binary` representing `1 + 2` gets substituted for the parameter in `#{any(int)} * 3`. Then you want to get `(1 + 2) * 3` instead of `1 + 2 * 3`. When you on the other hand literally want to get `1 + 2 * 3`, then you should probably have `1 + 2` as a string and thus as a plain `#{}` template parameter.
Also guards against an accidentally discovered `StackOverflowError` in `JavaTemplate`, when the insertion point itself is used as a template parameter. E.g. assume you have `1 + 2` in the source code and want to replace it with `#{any(int)} * 3` and use that `1 + 2` as the template parameter.
=> Use `maybeParenthesize()` for parameter substitution

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/G.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java
The Groovy parser currently recognizes the [membership operator](https://docs.groovy-lang.org/latest/html/documentation/core-operators.html#_membership_operator) `in`. Groovy supports a negated form of this operator `!in`, which the parser currently does not recognize. 
When `!in` is used in a `settings.gradle` or `build.gradle` file, OpenRewrite gets an error like this: 
```
Caused by: java.lang.IllegalStateException: Unknown binary expression BinaryExpression
```
This PR adds `!in` to the set of recognized binary operators. 
Allow existing `settings.gradle` and `build.gradle` files to be parsed and processed without modification.
=> Add support for Groovy `!in` operator

rewrite-bom/build.gradle.kts
Remove rewrite-java-tck from rewrite-bom
No need for others to depend on, or procure this module.
=> Exclude TCK module from recipe-bom

rewrite-java-test/src/test/java/org/openrewrite/java/cleanup/SimplifyBooleanExpressionVisitorTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/search/SemanticallyEqualTest.java, rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java, rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
Fix incorrect change of `if(!a.equals(this.a))` to `if (false)`
=> Fix bug where `a` is not equal to `this.a` in a setter

rewrite-java-test/src/test/java/org/openrewrite/java/search/SemanticallyEqualTest.java, rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
Fixing the `SemanticallyEqual` to consider two field accesses unequal if they use different field names (even if it's the same type):
```
BigDecimal a = BigDecimal.ONE;
BigDecimal b = BigDecimal.ZERO;
```
shouldn't be considered semantically equal.
The actual trigger was failures of CI in rewrite-logging-frameworks, e.g. https://github.com/openrewrite/rewrite-logging-frameworks/actions/runs/14432137576/attempts/1
And these failures are believed to have been triggered by #5286.
=> SemanticallyEqual should use field names when comparing FieldAccess instances

rewrite-core/src/main/java/org/openrewrite/semver/Semver.java, rewrite-core/src/test/java/org/openrewrite/semver/SemverTest.java
A safety guard in `Semver`'s logic to compare two versions. Basically if one of them doesn't follow the usual pattern, then the pick the other one. In case of both of them being non-standard, just pick one of them deterministically (then it's hard to decide what is max).
Address issue reported by users seeing exceptions being thrown, e.g.
`Error comparing version number SOMETHING-2003.1.0_1 to 1.0.2 in DependencyVulnerabilityCheck`
Yeah. I tried to be defensive and pragmatic about the scenario of two versions being non-standard. I have a hunch this is closer to user expectations. But at the same time the code looks a bit off with not checking `isVersion` consistently in all branches. Happy to take better suggestions.
=> Semver not to choke on unusual version strings

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/internal/MavenPomDownloaderTest.java
A Maven project can contain repos which are unreachable, as they no longer exist. But if that repo isn't required anymore because the artifacts can be found in other repos, there is no need to check if that repo exists anymore.
=> Lazily normalize repositories in `MavenPomDownloader`

rewrite-core/src/main/java/org/openrewrite/Recipe.java, rewrite-core/src/test/java/org/openrewrite/RecipeRunTest.java
Ensure onComplete method is invoked for DelegatingRecipe.
Previously, the onComplete method was not called when a DeclarativeRecipe had a precondition, as the child recipes were wrapped in a DelegatingRecipe.
@knutwannheden @timtebeek
=> Fix: Ensure onComplete is called for DelegatingRecipe

rewrite-java/src/main/java/org/openrewrite/java/AnnotationMatcher.java
Defensive coding around the possibility that `JavaType` annotations can be null.
We need to root out what is causing an LST to be parsed in this way, so this is just a stopgap measure.
=> Workaround AnnotationMatcher NPE

rewrite-java/src/main/java/org/openrewrite/java/search/FindAnnotations.java
Evaluate the precondition without navigating down the tree.
`JUnitUpgrade` is on the top 3 of worst performers in DevCenter and it uses `FindAnnotations` under the covers:
I don't think so, it looks like the other part of that precondition was just a holdover from an earlier time.
=> Improve performance of FindAnnotations precondition

.github/workflows/ci.yml, rewrite-java-21/build.gradle.kts, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeMapping.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21TypeSignatureBuilder.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/internal/Javac.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/internal/JavacTreeMaker.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/internal/Permit.java
The PR updates the module `rewrite-java-21` to be compatible with JDK 24. The main change is eliminating the use of  `UnknownType`, as it has been removed from JDK 24.
- Fixes https://github.com/openrewrite/rewrite/issues/5211
It seems more straightforward to modify the `rewrite-java-21` module than to create a separate module with the new classes.
=> feat: support JDK24

rewrite-kotlin/build.gradle.kts, rewrite-kotlin/src/main/java/org/openrewrite/kotlin/KotlinTypeGoat.kt, rewrite-kotlin/src/main/kotlin/org/openrewrite/kotlin/KotlinIrTypeMapping.kt, rewrite-kotlin/src/main/kotlin/org/openrewrite/kotlin/KotlinTypeMapping.kt, rewrite-kotlin/src/main/kotlin/org/openrewrite/kotlin/internal/IrTreePrinterVisitor.kt, rewrite-kotlin/src/test/resources/KotlinTypeGoat.kt
- rename ctx to name in IrTreePrinterVisitor
- use Gradle DSL for JVM target configuration
- fix deprecation warnings in KotlinIrTypeMapping.kt
- fix deprecation warnings in KotlinTypeMapping.kt
Prepare for Kotlin 2.x migration
=> Remove warnings from Gradle build logFix

rewrite-core/src/main/resources/META-INF/rewrite/core-categories.yml
New core category.
It's weird to see "Tech" as a category:
=> Add `tech` to root categories so Picnic shows as a top-level category.

rewrite-gradle/src/test/java/org/openrewrite/gradle/AddPropertyTest.java
new test case for Gradle AddProperty recipe
```
@Test
void addPropertyAfterDeleteProperty()
```
improved test coverage :)
=> Add additional test case for Gradle AddProperty recipe

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateJavaCompatibility.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateJavaCompatibilityTest.java
This fixes one of the issues that our customers has been facing with Java version migration. 
according to [Gradle documentation](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:compiling_with_release), this property can also be used to set java compile version. 
What I am not sure about is if we do not want to go more in depth than just adapting all `options.release = ... `
What happens if i have another extension that also uses `options.release`? That one will also be changed with current code. 
I do not see a lot of risk there(and this risk is also there for the other properties `sourceCompatibility` and `targetCompatibility`). For this reason I've only added some assurance check by verifying the `target` is `options` instead of just putting all `release` …
=> Added option.release as a field that can set the java version.

rewrite-java-test/src/test/java/org/openrewrite/java/ReplaceConstantWithAnotherConstantTest.java, rewrite-java/src/main/java/org/openrewrite/java/ReplaceConstantWithAnotherConstant.java
Fix https://github.com/openrewrite/rewrite/issues/5224
Update `ReplaceConstantWithAnotherConstant` recipe to handle more cases with import conflict.
- Fix https://github.com/openrewrite/rewrite/issues/5224
=> fix ReplaceConstantWithAnotherConstant not work when contains import conflict

rewrite-core/src/main/java/org/openrewrite/RecipeScheduler.java, rewrite-core/src/main/java/org/openrewrite/config/DeclarativeRecipe.java, rewrite-core/src/main/java/org/openrewrite/search/RepositoryContainsFile.java, rewrite-core/src/main/java/org/openrewrite/search/RepositoryContainsFiles.java, rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/search/ModuleHasPlugin.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/search/ModuleHasPluginTest.java, rewrite-maven/src/main/java/org/openrewrite/maven/search/ModuleHasPlugin.java
Back in rewrite 7 we had two kinds of preconditions: Repository level and file level. Repository level were uncommon but could be used to express things like "Run this recipe only if a particular type is in use or dependency is present". We lost that in the jump to rewrite 8, supporting only file-level preconditions. Until now.
With these changes a DeclarativeRecipe can use a scanning recipe as a precondition. This allows for not only repository level preconditions, but for any arbitrary granularity between file and repository. So this mechanism allows you to express nuanced preconditions like "only run this recipe on java sources gradle projects which apply a particular plugin".
=> Support Scanning Recipes as preconditions in DeclarativeRecipe.

rewrite-java/src/main/java/org/openrewrite/java/AnnotationMatcher.java
Reverts openrewrite/rewrite#5314. The root cause has meanwhile been identified and fixed.
=> Revert "Workaround AnnotationMatcher NPE"

rewrite-gradle/src/test/java/org/openrewrite/gradle/GradleParserTest.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
- Fixes #5349 
There was already a check in place to bypass this issue. However, the cursor reset was misplaced so it only worked when there was no whitespace in front of the `[`. Now that should be fixed!
Do I break something else? I do not see what would be impacted as we already had similar thing when not prefixed with whitespace.
@jevanlingen as you have added that if-statement, hoping you can quickly spot dangers, if any!
Not really
=> Do not bring named parameters out of their containing MapExpression when in an Map with a prefixed space.

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
We ignore the transitive dependency / configuration if there is a direct dependency for the same configuration. This way we can end up with cleaner build.gradle files AND we are more true to [the original documentation](https://docs.openrewrite.org/recipes/java/dependencies/upgradetransitivedependencyversion) of this recipe. 
> Upgrades the version of a transitive dependency in a Maven pom.xml or Gradle build.gradle. **Leaves direct dependencies unmodified.** Can be paired with the regular Upgrade Dependency Version recipe to upgrade a dependency everywhere, regardless of whether it is direct or transitive.
- Fixes #5355
=> Do not bump transitive dependencies if there is a direct dependency also

rewrite-java-test/src/test/java/org/openrewrite/java/UnwrapParenthesesTest.java, rewrite-java/src/main/java/org/openrewrite/java/UnwrapParentheses.java
Changing `UnwrapParentheses` not to remove parenthesis around switch expressions.
- fixes https://github.com/openrewrite/rewrite-static-analysis/issues/534
=> Java - not unwrapping parens around switch expressions

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/AssignmentTest.java
Adding an additional safety check in Groovy parser wrt assignment statements with variable names starting with type names (e.g. `intsomething`)
- fixes #5335
=> Groovy - safety check for variable names starting with type names (e.g. int)

rewrite-maven/src/main/java/org/openrewrite/maven/AddPluginDependency.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddPluginDependencyTest.java
Previously these would not match; now that we use `isPluginTag(pluginGroupId, pluginArtifactId)` they do. Potentially could affect other recipes to, but not explored as part of this PR. As reported via Slack, and created as an example to serve if new cases are found.
=> Add Maven plugin dependency with implied groupId

rewrite-java/src/main/java/org/openrewrite/java/trait/Annotated.java, rewrite-java/src/test/java/org/openrewrite/java/trait/AnnotatedTest.java
As it's documented as a recommendation for performance improvements:
https://github.com/openrewrite/rewrite/blob/a98d83d698dda9971c93a0767b7f85d5866f306d/rewrite-core/src/main/java/org/openrewrite/trait/SimpleTraitMatcher.java#L62-L73
=> Override `asVisitor(VisitFunction2)` in Annotated Trait

rewrite-java/src/main/java/org/openrewrite/java/ReplaceMethodInvocationWithConstant.java, rewrite-java/src/test/java/org/openrewrite/java/ReplaceMethodInvocationWithConstantTest.java
Added a recipe to replace MethodInvocations with a constant values.
See `System.getSecurtiyManager()` it always returns `null`from java 24. This recipe replaces the values and enable cleanup recipes.
=> Replace `J.MethodInvocation`s with constant

rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java, rewrite-java/src/main/java/org/openrewrite/java/tree/Types.java
Add a no args constructor to Types that defaults to not using inference.
Make it easier to reuse without having to think of an explicit argument to pass in.
Considered adding a `Types.withInference()` static method instead of `new Types(true)`, but figured for the single use we see today likely not worth adding just yet.
- Follow up from https://github.com/openrewrite/rewrite/pull/5348
=> Default to no inference on Types

rewrite-java-test/src/test/java/org/openrewrite/java/RenameVariableTest.java, rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java, rewrite-java/src/main/java/org/openrewrite/java/tree/TypeUtils.java
- Fix previous https://github.com/openrewrite/rewrite/pull/5348 unintended change, which cause regression https://github.com/openrewrite/rewrite/pull/5369
- Added more tests for `RenameVariable` and fix small issue.
The original `TypeUtils.isOfType()` performed full checks (name, owner, parameters, etc.) for `JavaType.Method`, `JavaType.Variable`, and `JavaType.Annotation`. The new `Types.isOfType()` implementation normalizes these types to their expression type, aligning with `isAssignableTo` logic, to be used in `JavaTemplateSemanticallyEquals`. This causes some cases to now return `true` where the old logic returned `false`.
This change preserves backward compatibility by:
- Keeping the old behavior in `TypeUtils.isOfType()`
- Letting `Types.isOfType()` adopt the normalized type …
=> Restore TypeUtils.isOfType behaviour

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateGenericsTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateMatchTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java, rewrite-java/src/main/java/org/openrewrite/java/search/SemanticallyEqual.java
Small fixes for JavaTemplate.matches()
- Some paths didn't use the generic type information while generating the code for the template.
- Member reference was not checking the containing expressions, this lead to match but didn't capture the parameters.
=> Fix some matching scenarios

rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveDuplicateDependenciesTest.java, rewrite-maven/src/test/resources/junit-platform.properties
Use `Objects.equals` to compare classifier and type for managed dependencies, as those can occur twice with mismatched & nullable values, which led to a number of confusing issues:
- fixes https://github.com/openrewrite/rewrite/issues/4868
- https://rewriteoss.slack.com/archives/C01A843MWG5/p1746248419279009
Wondering if anything else might now fail to match because we came to rely on faulty resolve. I guess/hope not.
Fix this in `RemoveDuplicateDependencies` where this was first reported, and separately when it comes to missing managed dependency versions when parsing/downloading.
=> Fix managed dependency equality around nullable classifier & type

rewrite-java-11/build.gradle.kts, rewrite-java-17/build.gradle.kts, rewrite-java-21/build.gradle.kts, rewrite-java-8/build.gradle.kts, rewrite-java-tck/src/main/java/org/openrewrite/java/MinimumJava11.java, rewrite-java-tck/src/main/java/org/openrewrite/java/MinimumJava17.java, rewrite-java-tck/src/main/java/org/openrewrite/java/MinimumJava21.java
Drop the use of Tags to exclude tests from running on certain Java versions, in favor of JUnit's built in `@EnabledForJreRange`. 
The later also allows us to run with a max range, which could come in handy with an eye towards Java 25.
=> Adopt `@EnabledForJreRange` over `@Tag`

rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeRunCycle.java, rewrite-core/src/test/java/org/openrewrite/RecipeSchedulerTest.java
Previously an exception thrown from here would interrupt the recipe run lifecycle but not add a result to the errors data table.
Now it doesn't interrupt the recipe run and does add a result to the errors data table.
=> Capture exceptions during ScanningRecipe.generate() alongside other recipe errors

rewrite-core/src/main/java/org/openrewrite/table/RecipeRunStats.java, rewrite-core/src/test/java/org/openrewrite/table/RecipeRunStatsTest.java
Also note in the column headings that the units are in nanoseconds
=> Fix RecipeRunStats showing "0.99" in the percentile columns rather than the actual values

rewrite-java-test/src/test/java/org/openrewrite/java/ParenthesizeVisitorTest.java, rewrite-java/src/main/java/org/openrewrite/java/ParenthesizeVisitor.java
ParenthesizeVisitor to always parenthesize switch expressions, like we did in #5359 for `UnwrapParentheses`.
Address the suggestion raised in https://github.com/openrewrite/rewrite/pull/5359#issuecomment-2841782436
=> ParenthesizeVisitor to always parenthesize switch expressions

rewrite-java-tck/src/main/java/org/openrewrite/java/tree/ConstructorTest.java
Add a parser test for contructors, testing common constructors, but specifically adding tests for constructors with statement before calling `this(..)` or `super(..)`.
Research for:
- https://github.com/moderneinc/customer-requests/issues/1144
=> Added Java parser tests for constructors, with some statements before super/this

rewrite-core/src/main/java/org/openrewrite/internal/PropertyPlaceholderHelper.java, rewrite-core/src/test/java/org/openrewrite/internal/PropertyPlaceholderHelperTest.java
- #5334 
Previously not having any separation between placeholders when invoking `replacePlaceholders` on `PropertyPlaceholderHelper` would result in only the first placeholder being replaced.
- Changed the calculation of the new start index after a replacement occurs to start searching at just the new end index  (was previously adding the size of the placeholder suffix to the new end index for the search start)
=> PropertyPlaceholderHelper Not Handling Lack of Separation Between Placeholders

rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
- Fixes https://github.com/openrewrite/rewrite/issues/5387
With parsers mostly moving into this project I don't expect this to pose much of a problem downstream, especially since those already handled by the expected unmapped erroneous nodes are not affected. If I've overlooked anything let me know.
I'm not sure what even triggers that `assertContentEquals` these days, especially as that was introduced over  a year before we added errorneous handling, and setting a breakpoint and running rewrite-java-test tests does not trip that breakpoint. 🤔 
- https://github.com/openrewrite/rewrite/commit/92dbac23f4e3941c38a7e4fcf717f68264e0ba04
- #4412
=> Throw for unhandled `ParseError` in `RewriteTest` to avoid `ClassCastException`

rewrite-core/src/main/java/org/openrewrite/internal/ListUtils.java, rewrite-core/src/main/java/org/openrewrite/text/PlainText.java, rewrite-core/src/test/java/org/openrewrite/config/DeclarativeRecipeTest.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/Assertions.java
In order to support the changes made here, I am also preparing `withToolingApi` support. 
However, to add a clean unit test for this in the gradle-tooling module, I need to have the Assertions available. 
Furthermore, there is a bug I think in the PlainText. 
When the adapted for loop in RewriteTest executes for a plainText file, instead of updating the map, it adds the new one. 
This is because the equals contract is not the same as CompilationUnit's. 
adapted that also in this PR
Lastly, I made the flatMap method Function parameter adhere to the contract of the method which it is delegating to. 
If the flatmap function returns null, the entry will be deleted. 
However, the function does not support null, the bifunction which gets called does.
@sambsnyd
=> Paving the core concepts for LockFile creation recipe

rewrite-java-lombok/src/main/java/org/openrewrite/java/lombok/LombokSupport.java
Added a fallback when loading `lombok.launch.ShadowClassLoader` with the parserClassLoader fails
Lombok integration seemingly not working with Maven
=> Add fallback when attempting to load `lombok.launch.ShadowClassLoader`

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTypeTest.java, rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java
Quite surprised we didn't mark these before; we only looked at interfaces. it seems.
=> Mark methods overridden from classes as `isOverride()`

rewrite-core/src/main/java/org/openrewrite/Result.java
Adding a try-catch around print for `isLocalAndHasNoChanges`.
To fix the broken recipe runs for Javascript code:
```
java.lang.UnsupportedOperationException: TODO decide how we will instantiate the JavaScriptRewriteRPC process
org.openrewrite.javascript.tree.JS$CompilationUnit.printer(JS.java:198)
org.openrewrite.Tree.print(Tree.java:81)
org.openrewrite.SourceFile.printAll(SourceFile.java:102)
org.openrewrite.SourceFile.printAll(SourceFile.java:98)
org.openrewrite.SourceFile.printAll(SourceFile.java:106)
org.openrewrite.Result.isLocalAndHasNoChanges(Result.java:274)
org.openrewrite.Result.getTimeSavings(Result.java:142)
```
The time-savings is somewhat secondary feature and the failure to calculate the savings, shouldn't break the whole flow.
=> catching exceptions in isLocalAndHasNoChanges

rewrite-gradle/src/main/java/org/openrewrite/gradle/DependencyConstraintToRule.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/DependencyConstraintToRuleTest.java
Added checks to prevent DependencyContraintToRule recipe to touch the `builtscript` section
The recipe to transform dependency constraints to resolution strategies made updates to resulution strategies in the `builtscript` section. This caused bugs in other recipes.
=> Added checks to leave builtscript alone in DependencyConstraintToRule

rewrite-javascript/rewrite/src/util.ts, rewrite-javascript/rewrite/test/util.test.ts
Changing `mapAsync` implementation to one which guarantees order of execution.
Otherwise the Javascript visitors get invalid `cursor` data when traversing an LST. As `mapAsync` is heavily used in visitors.
The current code of `mapAsync` is not as nicely functional as it used to be. I don't know how to write it in a cleaner way.
=> mapAsync to enforce order of execution

rewrite-javascript/rewrite/src/javascript/parser.ts, rewrite-javascript/rewrite/src/javascript/rpc.ts, rewrite-javascript/rewrite/src/javascript/tree.ts, rewrite-javascript/rewrite/src/javascript/visitor.ts
Removing the `imports` field in `JS.CompilationUnit`.
It's misleading as:
- its value is always empty
- the actual imports are parsed into `JS.CompilationUnit.statements` as per: https://github.com/openrewrite/rewrite/blob/cd550f67587817376df79c6a09cb15bd709a495b/rewrite-javascript/rewrite/src/javascript/parser.ts#L282-L283
The field serves no real purpose.
=> Removing imports field in JS.CompilationUnit

rewrite-javascript/rewrite/src/java/visitor.ts, rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/src/javascript/visitor.ts, rewrite-javascript/rewrite/test/java/visitor.test.ts
Changing the visitor logic in JavaScript to make sure the `visitStatement` method is also called for subclasses of `Statement`.
- to provide feature parity in this aspect with Java
- avoid confusion, otherwise `visitStatement` doesn't do anything (as it's never called)
The code has been written for one of the cases. And then multiplied with ChatGPT.
Note: the same will need to be done with `Expression` and possibly other abstract classes.
=> visitStatement called in JavaScript

rewrite-maven/src/main/java/org/openrewrite/maven/internal/MavenPomDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java
The path to search for `maven-metadata.xml` when LATEST or RELEASE  is used if changed from 
`https://uri/group/subgroup/artifact/<VERSION/LATEST/RELEASE>/maven-metadata.xml`
to 
`https://uri/group/subgroup/artifact/maven-metadata.xml`
- Fixes #4983
I do not think we have to do this for the local m2 cache files also as we want to know latest/release version from the "latest" updates. 
==> my formatter made more changes, but reverted these as I only want the focus on the functional change during this review
=> Resolve managed dependency with 'RELEASE' or 'LATEST' versions.

rewrite-yaml/src/main/java/org/openrewrite/yaml/UnfoldProperties.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/UnfoldPropertiesTest.java
When breaking single line declarations in a yaml file into parts we reiterate over sub-declaration when we find matches.
The recipe only matched entire keys.
When matching 
`a.b.c.d` agains `$..[a.b][c.d]` the recipe now takes in account that when $..[a.b] is matched we then need to delve deeper matching `c.d` against [c.d] to actually find the exclusion for a single line key.
The solution does introduce some more recursion, but since this recipe only target yaml properties line by line I don't believe it will be a problem.
=> Add support for partially unfolding single line yaml properties with exclusions in UnfoldProperties

rewrite-maven/src/main/java/org/openrewrite/maven/AddDependency.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddDependencyTest.java
Added a unit test for `AddDependency` recipe to not add a transitive dependency when managed by a bom, with `acceptTransitive` set to true. This test is failing.
In the below test spring-boot-starter-web is managed by spring-boot-dependencies and transitively uses spring-webmvc, so the recipe should not add it.
@timtebeek. I am not sure if any other argument to the recipe must be used for this case, so let me know. 
No, but do let me know if this can be done in any other way.
=> Do not `AddDependency` for transitive dependency managed by a bom, even if `onlyIfUsing == null`

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateDependencyLock.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/LockDependencyVersionsTest.java
I used to completely write the lockfile based on the marker, but did miss that configurations can be ignored for locking. Even artifacts themselves can be ignored. 
This fix addresses to make sure we only put the lock if:
- The configuration was in the lockfile before
- The GroupArtifact was locked before
This way we will address issues like [this repo's lockfile](https://github.com/atlassian/aws-infrastructure/blob/master/gradle.lockfile) not being wrongfully updated to contain locks [for excluded configurations](https://github.com/atlassian/aws-infrastructure/blob/master/build.gradle.kts#L21-L23).
@shanman190 I think this is one quick-win yet big improvement to the "wrongfully updating the lockfile"
@sambsnyd Shannon reached out to mention we might have been to fast. Rather than rolling …
=> Only allow gradle dependency locking for already locked configurations/artifacts

rewrite-java-test/src/test/java/org/openrewrite/java/AddImportTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddImport.java
PR #5439 introduced logic to handle import ambiguity by using fully qualified names when conflicting usages are present. However, this led to regressions in cases where such conflicts only existed temporarily during multi-step recipe transformations.
When multiple recipes are applied, intermediate steps may introduce conflicting usages. But at the end might all such usage can be safely replaced to shortend names.
To handle this, updated AddImport to shorten existing fullyqualified names for the type or member for which import is being added.
Validated the fix by running all tests in the rewrite-testing-frameworks.
=> Enhance AddImport to shorten fully qualified names

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
Fixed some regression introduced by moving the `updatesPerProject` to an accumulatro -> 1 run of visitor would upgrade all of the scanned newVersions resulting in the because being the same. 
We only update if the recipe is for the provided group/artifact BUT we keep adding the new version in scanner so that other recipes can use 1 grouped accumulator.
=> Fixed the scanner being executed in a loop that then causes all scans to be updated in a single run.

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11Parser.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17Parser.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21Parser.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8Parser.java
Since type attribution is a best-effort, we continue it even in the presence of errors. But in a current implementation for `JavaCompiler#attribute(Queue)`, it will be stopped in case of error, and not all entries in a queue will be processed.
In the fix, the attribution will be continued for the rest entries in `compiler.todo`
- Fix https://github.com/openrewrite/rewrite/issues/5227
Kudos [@Knut-Ove](https://github.com/Knut-Ove) for the finding and a fix
=> Continue type attribution in a case of exception

rewrite-javascript/rewrite/src/java/visitor.ts, rewrite-javascript/rewrite/test/java/visitor.test.ts
Amending the Javascript visitor to call `visitStatement` also for method invocations and method declarations.
Otherwise, a visitor implementing `visitStatement` might miss them.
=> Making sure visitStatement is also called for methodInvocations and methodDeclarations

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/test/javascript/format/blank-lines-visitor.test.ts
Amending the BlankLinesVisitor in Javascript.
It can now add (more) line breaks in a minified JS/TS program.
- it's probably useful by itself or will be at some point
- but the trigger is I need it for `TabsAndIndentsVisitor` work
=> Adding more newlines in BlankLinesVisitor

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateDependencyLock.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/LockDependencyVersionsTest.java
- do not touch the locked lines that are there for unexisting configurations as they might have been put there by a plugin
- transitive upgrade constraints are only bumping the spring managed dependency and not bringing their transitive dependencies according to the lockfile resolution when the spring boot plugin is being used.
We've seen that the lockfile is wrong without these changes. This will be already less wrong than it was before without properly working out: 
- https://github.com/openrewrite/rewrite/issues/5446
=> Fixed 2 things in the lockfile

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/test/javascript/format/minimum-viable-space-visitor.test.ts
Minor amendment to `SpacesVisitor` in Javascript.
Adding a mandatory space after `throw`.
Otherwise the following code change is observed:
```diff
-     throw new Error("test");
+     thrownew Error("test");
```
=> SpacesVisitor - make sure there's a space after `throw`

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/test/javascript/format/tabs-and-indents-visitor.test.ts
Amending `TabsAndIndentsVisitor` in Javascript - not to crash on undefined prefixes.
Otherwise it crashes for some real-life files with:
```
Error: TypeError: Cannot read properties of undefined (reading 'whitespace')
at /Users/greg/git/rewrite/rewrite-javascript/rewrite/src/javascript/format.ts:965:30
at Immer2.produce (/Users/greg/git/rewrite/rewrite-javascript/rewrite/node_modules/immer/src/core/immerClass.ts:97:14)
at TabsAndIndentsVisitor.<anonymous> (/Users/greg/git/rewrite/rewrite-javascript/rewrite/src/javascript/format.ts:961:23)
at Generator.next (<anonymous>)
at fulfilled (/Users/greg/git/rewrite/rewrite-javascript/rewrite/src/javascript/format.ts:5:58)
at processTicksAndRejections (node:internal/process/task_queues:105:5)
at TabsAndIndentsVisitor.<anonymous> …
```
=> Handling undefined prefix in TabsAndIndentsVisitor

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/src/javascript/visitor.ts, rewrite-javascript/rewrite/test/javascript/format/spaces-visitor.test.ts
Fixing Autoformatting in Javascript not to collapse mandatory spaces in `import` and `export` declarations.
Otherwise invalid code is produced, e.g.
```
importbazfrom'baz.js'
```
=> Fixing handling of spaces in Import and Export declarations in Javascript

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/test/javascript/format/spaces-visitor.test.ts
Adding support for handling the `SpacesStyle.within.es6ImportExportBraces` setting.
- Fuller support for autoformatting.
- Although it's not the default in IntelliJ, the settings seems popularly enabled in TS open source code.
=> Honoring es6ImportExportBraces style setting in Javascript

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java
It seems that when I launch (with cli, but same beahviour in platform) the recipe without the onlyForConfigurations option set it takes it as an empty list.
Did anything change with the way arguments are passed? We do not see this issue with FindAndFixVuln as that one uses code to set that value to null. With a null value present, the constraintConfiguration is being returned and we can successfully run the recipe.
Running the recipe directly, triggers the recipe with an empty list causing [this line](https://github.com/openrewrite/rewrite/blob/v8.52.0/rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java#L208) to return null. I could very easily adapt [this line](https://github.com/openrewrite/rewrite/blob/v8.52.0/rewrite-gradle/src/main/java/org/open …
=> The onlyForConfigurations can also be an empty list

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/test/javascript/format/format.test.ts
Fix for Javascript's SpacesVisitor wrt `extends` in class declaration.
Invalid code is produced.
=> Javascript - space around extends

rewrite-xml/src/main/java/org/openrewrite/xml/XPathMatcher.java, rewrite-xml/src/test/java/org/openrewrite/xml/ChangeTagAttributeTest.java
ensuring EE10 migration recipes (e.g. JavaxXmlToJakartaXmlXJCBinding) reliably match intended elements, regardless of whitespace.
* Updated the regular expression logic in XPathMatcher to correctly handle whitespace before and after the = sign in XPath predicate conjunctions.
* Added a regression test for ChangeTagAttribute to ensure correct behavior when spaces are present around = in XPath predicates.
The previous implementation of XPathMatcher failed to match such predicates, which made the official recipe
org.openrewrite.java.migrate.jakarta.JavaxXmlToJakartaXmlXJCBinding unusable in certain scenarios (e.g., when targeting attributes like version="1.0").
Please verify that the regular expression change in XPathMatcher does not cause regressions for other XPath patterns.
No specific …
=> Fix XPathMatcher: correctly handle spaces around '=' in predicates with conjunctions

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/test/javascript/format/format.test.ts, rewrite-javascript/rewrite/test/javascript/format/minimum-viable-space-visitor.test.ts
Fixing Javascript Autoformatting wrt type declarations.
Broken code is produced.
=> Fixing spaces for type declarations in Javascript Autoformatting

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/test/javascript/format/minimum-viable-space-visitor.test.ts, rewrite-javascript/rewrite/test/javascript/format/spaces-visitor.test.ts
Fixing more cases of mandatory spaces in various Javascript syntaxes.
Invalid code is produced.
=> Fixing more mandatory space issues in Javascript Autoformatting

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/test/javascript/format/format.test.ts, rewrite-javascript/rewrite/test/javascript/format/spaces-visitor.test.ts
Amending the AutoformatVisitor in Javascript wrt spaces around assignment operators and alikes.
To honor the desired formatting style closer.
=> Fixing formatting around assignment operators in Javascript

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/src/test/rewrite-test.ts, rewrite-javascript/rewrite/test/javascript/format/format.test.ts, rewrite-javascript/rewrite/test/javascript/format/minimum-viable-space-visitor.test.ts
Changing how `MinimumViableSpaceVisitor` works. I.e. making it not remove any whitespace.
In general, applying the objective of:
> - MinimumViableSpaceVisitor runs before SpacesVisitor
> - MVSV never removes any whitespace; it adds required ones (i.e. these without which the code is invalid), but not excessively - comments are enough
> - SpacesVisitor applies the style for selected syntax structures, incl. removing some whitespace
- Addressing the feedback.
- Also making the impl closer to the Java implementation.
=> Javascript - MinimumViableSpaceVisitor not to remove spaces

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
This PR fixes an issue in the Javadoc parser where whitespace between a type name and its generic type parameter (e.g. `Optional <String>`) inside Javadoc.
Fixing https://github.com/openrewrite/rewrite/issues/5444
@timtebeek (already commented the issue)
It's my first contribution to the Rewrite project 👋
=> Fix whitespace handling in Javadoc

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11JavadocVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17JavadocVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21JavadocVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8JavadocVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/JavadocTest.java
Updated the `DocCommentTree` parser to handle both one-line (``) and multiline (``) comments by reusing the existing visitText() logic when processing `DCComment` nodes.
Fixing https://github.com/openrewrite/rewrite/issues/5411 
@MBoegers as reporter
In the Javadoc parser, both one-line (``) and multiline (``) HTML comments are represented as `DCComment`.
Currently,  `Tree visitComment(CommentTree node, List<Javadoc> body)`  handles these nodes but converts them into `Javadoc.Text` anyway.
As fix, I propose to reuse the existing `List<Javadoc> visitText(String node)` logic when processing `DCComment` within the `DocCommentTree`. It handles the multiline text well.
As an alternative, the Javadoc model could be extended to introduce a dedicated node type, like Javadoc.HtmlComment and handle …
=> Fixing multiline html comment

rewrite-yaml/src/main/java/org/openrewrite/yaml/UnfoldProperties.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/UnfoldPropertiesTest.java
The UnfoldProperties recipe has a new option where you can define JsonPath selectors to which properties you only want to apply the changes.
Customer request.
I implemented this feature at the final stage of processing: once it’s determined which parts should have a nested entry, I check whether those parts exist in the `applyTo` list.
This approach offers a small bonus—you can now combine `exclusions` with `applyTo`. While I doubt many users will take advantage of that, it's a nice extra.
=> Add an `applyTo` option to the UnfoldProperties recipe

rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/test/javascript/format/tabs-and-indents-visitor.test.ts
Simplifying the logic of handling block end whitespace in `TabsAndIndents` JavaScript visitor.
- Not to add extra newline.
=> Not adding newline in TabsAndIndents block end handling in Javascript

rewrite-maven/src/main/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactId.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactId.java, rewrite-maven/src/main/java/org/openrewrite/maven/ChangePluginGroupIdAndArtifactId.java, rewrite-maven/src/main/java/org/openrewrite/maven/MavenVisitor.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeDependencyVersion.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangeManagedDependencyGroupIdAndArtifactIdTest.java
The "ChangeDependencyGroupIdAndArtifactId" and "ChangeManagedDependencyGroupIdAndArtifactId" recipes now handle a value change for the version tag including cases where a property is used.
- https://github.com/openrewrite/rewrite/issues/4527
I moved the logic of the property resolvent out of the "UpgradeDependencyVersion" and into the "MavenVisitor" (and used it in the other recipes). Is this a good solution?
=> Generalize changing of properties in Maven recipes

rewrite-maven/src/main/java/org/openrewrite/maven/utilities/MavenArtifactDownloader.java, rewrite-maven/src/test/java/org/openrewrite/maven/utilities/MavenArtifactDownloaderTest.java
Giving fllowing pom.xml, the depdency chould be download normally.
```xml
<dependency>
<groupId>net.sf.json-lib</groupId>
<artifactId>json-lib</artifactId>
<version>2.4</version>
<classifier>jdk15</classifier>
</dependency>
```
In pom.xml, dependency with classifier will cause `MavenDownloadingException(Unable to download dependency xxx. Response was 404)`
=> Support classifier when downloading Maven artifacts

rewrite-core/src/main/java/org/openrewrite/scheduling/RecipeRunCycle.java, rewrite-core/src/main/java/org/openrewrite/table/RecipeRunStats.java, rewrite-core/src/test/java/org/openrewrite/table/RecipeRunStatsTest.java
When the same recipe is executed several times with different parameters, the `tag("name", recipe.getName())` will be the same, and it will produce wrong (n-times bigger) stats for `source-files` ("The number of source files the recipe ran over") in  `RecipeRunStats`.
As a fix, a HashSet was introduced to track all visited sources.
=> RecipeRunStats several times counts the same recipe runs with different params

rewrite-javascript/rewrite/src/java/print.ts, rewrite-javascript/rewrite/src/javascript/print.ts, rewrite-javascript/rewrite/src/json/print.ts, rewrite-javascript/rewrite/src/parse-error.ts, rewrite-javascript/rewrite/src/print.ts, rewrite-javascript/rewrite/src/text/print.ts
Javascript TreePrinters not to re-use printers. Instead it requests a new instance every time.
Fix a concurrency bug.
LST Visitors in Javascript are not thread-safe. A single tree printer instance cannot be safely used to print multiple source files in parallel. When running several in parallel, they give unexpected errors (what's even more peculiar they mostly work, but blunder in some specific cases).
A spontaneous test-case of parsing and printing multiple source files in parallel.
=> Javascript TreePrinters not to re-use printers

rewrite-java-tck/src/main/java/org/openrewrite/java/tree/LiteralTest.java, rewrite-java/src/main/java/org/openrewrite/java/tree/J.java
Saw a pattern on https://github.com/openrewrite/rewrite-migrate-java/pull/714 that had bugged me previously, where it's cumbersome to check if a literal contains null. This small change makes that easier, as demonstrated in the test.
=> Allow to more easily check for a null literal value

rewrite-javascript/rewrite/src/test/rewrite-test.ts
In Javascript recipe test harness, allowing for `beforeRecipe` and `afterRecipe` mixins to be async functions returning void.
Currently it allows for async returning `T` or non-async void, but the other combination is not allowed.
I needed it for my local tests.
=> In Javascript - allow for beforeRecipe or afterRecipe to be async with void return type

rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
Not a perfect solution just yet, as I saw some more shortcomings when
1. Array attribute initialized not with an array but with a single value, which then fails to append new items
2. duplication between named and value attributes
- Fixes #5526
=> Handle non-literal arguments in AddOrUpdateAnnotationAttribute

rewrite-yaml/src/main/java/org/openrewrite/yaml/DeleteKey.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/DeleteKeyTest.java
This solves that the YAML `DeleteKey` recipe doesn't always remove unused parent keys, specifically in combination with a regex match and sequence entries. 
I encountered the issue in the following scenario:
**When** the `DeleteKey` recipe is used with  a JSON path that matches using a regex on a child value of a YAML sequence entry
**And** this results in the sequence becoming empty
**Then** the sequence key and any empty parent keys are not removed
**However** I expected them to be removed, because this does happen when you use an exact match on the child value
The added `deleteSequenceEntriesUsingChildRegexMatchRemovingUnusedKeysRecursively` unit test method shows the expected behavior. Without this fix the `after` looks like this:
```yaml
a: a-value
b:
c:
```
=> Fixed that the YAML DeleteKey does not remove unused parent keys in all situations

rewrite-javascript/rewrite/src/java/type.ts, rewrite-javascript/rewrite/src/javascript/type-mapping.ts, rewrite-javascript/rewrite/test/javascript/parser/unique-symbol.test.ts
An amendment to Javascript type attribution/mapping. Adding support for [Unique Symbols](https://www.typescriptlang.org/docs/handbook/symbols.html)
Fewer gaps in type attribution.
=> Javascript - type mapping for Unique Symbols

rewrite-gradle/src/main/java/org/openrewrite/gradle/search/DependencyInsight.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/search/DependencyInsightTest.java, rewrite-maven/src/main/java/org/openrewrite/maven/search/DependencyInsight.java, rewrite-maven/src/main/java/org/openrewrite/maven/table/DependenciesInUse.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedDependency.java
Improved the logic of Gradle `DependencyInsight`, added the parent/direct dependency which cause the row to show up and wrote 2 tests that show the issue. 
EG. 
When `ResolvedDependency dep = resolvedDependency.findDependency(groupIdPattern, artifactIdPattern);`
would run using a searchPattern for `spring-boot` group and artifact `*` pattern and the dependency declared matched this pattern, transitive dependencies of that one would not be in the insight result list as 
```java
if (matchesGlob(getGroupId(), groupId) && matchesGlob(getArtifactId(), artifactId)) {
return this;
}
```
would just return `this`. That dependency would then be added to the insights report, but all nested ones (which might also match the search would not be searched. 
Similarly: if you have a dependency for …
=> Fixed some detection logic for DependencyInsight in gradle.

rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenResolutionResult.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
When we get back a stack trace like this one it can be really hard, without a lot of debugging, to figure out exactly where the problem actually originates:
```
Caused by: java.lang.IllegalArgumentException: Circular placeholder reference 'project.version' in property definitions
at org.openrewrite.internal.PropertyPlaceholderHelper.parseStringValue (PropertyPlaceholderHelper.java:94)
at org.openrewrite.internal.PropertyPlaceholderHelper.parseStringValue (PropertyPlaceholderHelper.java:115)
at org.openrewrite.internal.PropertyPlaceholderHelper.replacePlaceholders (PropertyPlaceholderHelper.java:74)
at org.openrewrite.maven.tree.ResolvedPom.getValue (ResolvedPom.java:285)
at org.openrewrite.maven.tree.ResolvedPom.getValues (ResolvedPom.java:362)
at …
```
=> Include specifics when non-downloading failures occur during pom resolution

rewrite-core/src/main/java/org/openrewrite/internal/PropertyPlaceholderHelper.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/tree/ResolvedPomTest.java
Solving problems recursively resolving `${project.version}`.
=> Circular Maven `${project.version}` resolution

rewrite-javascript/rewrite/src/javascript/comparator.ts, rewrite-javascript/rewrite/src/javascript/format.ts, rewrite-javascript/rewrite/src/javascript/parser.ts, rewrite-javascript/rewrite/src/javascript/print.ts, rewrite-javascript/rewrite/src/javascript/rpc.ts, rewrite-javascript/rewrite/src/javascript/tree.ts, rewrite-javascript/rewrite/src/javascript/visitor.ts, rewrite-javascript/rewrite/test/javascript/parser/import.test.ts, rewrite-javascript/src/main/java/org/openrewrite/javascript/JavaScriptVisitor.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/rpc/JavaScriptReceiver.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/rpc/JavaScriptSender.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/tree/JS.java
Following #5569:
- removing the notion of `ScopedVariableDeclarations.scope` as let/const/var was already moved to VariableDeclarations.modifier
- now adopting a new LST model for what used to be called Import scope
To meet the design decision of "remove that import scope and instead update the model of JS.Import to cover that case".
=> Javascript - removing the notion of scope in variable declarations

rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/tree/ResolvedPomTest.java
We're struggling to identify how a Maven circular `${project.version}` reference can exist in a dependency version. By returning a version we know can't resolve, we'll pinpoint the dependency that starts this chain reaction.
=> Don't throw SOE on circular `${project.version}` reference

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateTest5Test.java, rewrite-java-test/src/test/java/org/openrewrite/java/format/WrappingAndBracesTest.java, rewrite-java/src/main/java/org/openrewrite/java/format/WrappingAndBracesVisitor.java
Comment wrapping should be left intact as part of annotation wrapping
[Failing CI on rewrite-spring](https://ge.openrewrite.org/s/rbreyz3vrjt4i/tests/task/:testWithSpringBoot_2_1/details/org.openrewrite.java.spring.framework.BeanMethodsNotPublicTest/removePublicModifierFromBeanMethods()?top-execution=1)
=> Annotation wrapping: Leave comments in tact

rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedDependency.java
Made a previously introduced method private as it was originally intended not to be exposed. 
People should not be calling this one directly but the public 2-args one.
=> private internal findDependencies for ResolvedDependency

rewrite-xml/src/main/java/org/openrewrite/xml/internal/XmlParserVisitor.java, rewrite-xml/src/main/java/org/openrewrite/xml/tree/Xml.java, rewrite-xml/src/test/java/org/openrewrite/xml/XmlParserTest.java
Reverts openrewrite/rewrite#5581
as it's causing downstream problems, e.g.
```
/home/runner/work/rewrite-java-security/rewrite-java-security/src/main/java/org/openrewrite/java/security/xml/ExternalDTDAccumulator.java:32: error: incompatible types: Content cannot be converted to Element
for (Xml.Element element : docTypeDecl.getExternalSubsets().getElements()) {
```
Also this comment:
https://github.com/openrewrite/rewrite/pull/5581#issuecomment-2957716271
needs to be addressed.
=> Revert "Correctly parse comments in doctype declarations"

rewrite-gradle/src/main/java/org/openrewrite/gradle/search/DependencyInsight.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/search/DependencyInsightTest.java, rewrite-maven/src/main/java/org/openrewrite/maven/search/DependencyInsight.java, rewrite-maven/src/main/java/org/openrewrite/maven/table/DependenciesInUse.java
Datatable should not have the direct column
**AFAICT, I will also need to followup release in rewrite-java-dependencies as that one also uses the constructor [here](https://github.com/openrewrite/rewrite-java-dependencies/blob/f6d1cff5be4c865fa3ef4b09ff612394655d482b/src/main/java/org/openrewrite/java/dependencies/search/FindMinimumDependencyVersion.java#L176)**
=> Datatable should not have the direct column

rewrite-maven/src/main/java/org/openrewrite/maven/MavenSecuritySettings.java, rewrite-maven/src/main/java/org/openrewrite/maven/MavenSettings.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenSettingsTest.java
fixes https://github.com/moderneinc/customer-requests/issues/1155
We decrypt the passwords if we are loading the Maven files from disk but we don't decrypt the settings if loaded from parsing.
- consistent behaviour when loading the Maven `settings.xml`
- fix customer issue where they are using a `security-setting.xml` to encrypt their passwords
approach?
=> Enhance MavenSettings to handle password decryption

rewrite-core/src/main/java/org/openrewrite/text/FindAndReplace.java, rewrite-core/src/test/java/org/openrewrite/text/FindAndReplaceTest.java
- Use `String#replace(CharSequence, CharSequence)` when possible
- Don't call `Matcher#find()` first, because `replaceAll()` resets the `Matcher` anyway and calling `find()` is just extra overhead
=> Slightly optimize `FindAndReplace`

rewrite-java-11/src/main/java/org/openrewrite/java/isolated/ReloadableJava11ParserVisitor.java, rewrite-java-17/src/main/java/org/openrewrite/java/isolated/ReloadableJava17ParserVisitor.java, rewrite-java-21/src/main/java/org/openrewrite/java/isolated/ReloadableJava21ParserVisitor.java, rewrite-java-8/src/main/java/org/openrewrite/java/ReloadableJava8ParserVisitor.java, rewrite-java-tck/src/main/java/org/openrewrite/java/tree/AnnotationTest.java
For the following case: `@C Object @B []` 
Currently the `annotationPosTable` in `visitAnnotatedType` method contains only 1 annotation: 
```
annotationPosTable = {HashMap@5269}  size = 1
{Integer@5275} 365 -> {JCTree$JCAnnotation@5276} "@B"
```
which makes `leadingAnnotations` to be empty (`size = 0`). That's wrong for `JCAnnotatedType` like `@C Object`
Adding annotation to the `annotationPosTable` when handling `JCAnnotatedType`.
- Fixes https://github.com/openrewrite/rewrite/issues/5329 
Not.
=> Fix: handle nested type annotations on array

rewrite-javascript/rewrite/src/javascript/comparator.ts, rewrite-javascript/rewrite/src/javascript/parser-utils.ts, rewrite-javascript/rewrite/src/javascript/parser.ts, rewrite-javascript/rewrite/src/javascript/print.ts, rewrite-javascript/rewrite/src/javascript/rpc.ts, rewrite-javascript/rewrite/src/javascript/tree.ts, rewrite-javascript/rewrite/src/javascript/visitor.ts, rewrite-javascript/src/main/java/org/openrewrite/javascript/JavaScriptIsoVisitor.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/JavaScriptVisitor.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/rpc/JavaScriptReceiver.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/rpc/JavaScriptSender.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/rpc/JavaScriptValidator.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/tree/JS.java
Renaming the Javascript's `ObjectBindingDeclarations` to `ObjectBindingPattern`.
> That would make it both consistent with the ArrayBindingPattern name as well as with the name in the TS Compiler API.
=> Refactoring, rename ObjectBindingDeclarations to ObjectBindingPattern

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java
1) For anonymous class instantiations like `new ArrayList<Map<String, String>>() {}`, we now call `visitTypeParameterizations` with `classNode.getUnresolvedSuperClass().getGenericsTypes()` instead of `classNode.getGenericsTypes()` which is `null` in this case. 
2) After adding a test case for `new ArrayList<>() {}` - it failed as well. It turned out that  `ctor.getNodeMetaData(StaticTypesMarker.INFERRED_TYPE)` was not sufficient to detect inferred generics. Looks like Groovy doesn't always set this metadata? 
To address this, I introduced private helper method `isInferred(ConstructorCallExpression)` that detects inferred generic usage (e.g., diamond operator).
- Fixes https://github.com/openrewrite/rewrite/issues/5296
=> Fix parsing of generics in anonymous class in Groovy

rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
The AddOrUpdateAnnotationAttribute recipe does not add a new attribute if an oldAttributeValue (to match against) is provided.
Especially for Spring `@Bean` annotations they sometimes need a `name`, but most of the time they don't. Without this check changing a name would result in all `@Bean` annotation without a name getting the same name.
=> Added check for missing attributeName, but attributeValue requirement in `AddOrUpdateAnnotationAttribute`

rewrite-maven/src/test/java/org/openrewrite/maven/UpdateMavenWrapperTest.java
Patch update from 3.8.8 -> 3.8.9.
The apache maven project released https://maven.apache.org/docs/3.8.9/release-notes.html, which caused our build to fail.
=> Let UpdateMavenWrapperTest use version 3.8.9 of apache-maven

rewrite-maven/src/main/java/org/openrewrite/maven/UseMavenCompilerPluginReleaseConfiguration.java, rewrite-maven/src/test/java/org/openrewrite/maven/UseMavenCompilerPluginReleaseConfigurationTest.java
Refined the logic that would determine if Maven compiler plugin needs to be updated based on the existing configuration.
Given the following Maven project that configures Java 17 for the source/target compatibility via the Maven compiler plugin.
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>com.example</groupId>
<artifactId>demo</artifactId>
<version>0.0.1-SNAPSHOT</version>
<build>
<plugins>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<version>3.14.0</version>
<configuration> …
```
=> Skip update if existing compiler plugin version config is newer

rewrite-javascript/rewrite/test/javascript/completeness.test.ts
Adding a test in Javascript codebase to ensure completeness of the LST tree elements for Javascript. Enforcing the rule that there should be a Java class counterpart for every LST interface on TS side.
That's one of the expectations needed for RPC to work properly.
=> Javascript - comparing javascript/tree.ts with JS.java

rewrite-maven/src/main/java/org/openrewrite/maven/ChangeParentPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangeParentPomTest.java
=> Cleanup: ChangeParentPom recipe

rewrite-maven/src/main/java/org/openrewrite/maven/ChangeProjectVersion.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangeProjectVersionTest.java
This PR fixes an issue where the ChangeProjectVersion recipe would incorrectly attempt to update Maven CI-friendly version placeholder properties (`${revision}`, `${sha1}`, and `${changelist}`) when they were used in the version tag, causing circular reference errors.
The fix adds these placeholders to the list of implicitly defined version properties that should not be updated, and adds an additional check to skip processing when the current version tag value already matches the new version.
This enables proper support for Maven CI-friendly versioning workflows where projects use these standard placeholders for version management.
- Fixes #5667
=> Fix ChangeProjectVersion to ignore Maven CI-friendly version placeholders

rewrite-javascript/rewrite/test/javascript/completeness.test.ts
Adding more checks to `completeness.test.ts`
Prevent even more mistakes in JS LST elements.
=> Javascript - adding more completeness checks

rewrite-gradle/build.gradle.kts, rewrite-java-11/build.gradle.kts, rewrite-java-17/build.gradle.kts, rewrite-java-21/build.gradle.kts, rewrite-java-tck/build.gradle.kts, rewrite-java-test/build.gradle.kts, rewrite-java/build.gradle.kts, rewrite-javascript/build.gradle.kts, rewrite-javascript/rewrite/package.json, rewrite-javascript/rewrite/tsconfig.build.json, rewrite-maven/build.gradle.kts, rewrite-xml/build.gradle.kts
Gradle build cleanup.
Before: 1m 58s
After: 18s
Get to actually having Gradle do work sooner
rewrite-javascript had a bit of restructuring, but is fundamentally the same. It should be reviewed carefully though.
Several of the previous rewrite-javascript tasks were using the node-gradle plugin's internal Gradle rule (ie. `npm_*` which resulted in eager task creation).
Anybody
N/A
There are additional pieces that can be cleaned up. There are several plugins -- the license plugin being the worst offender -- that still eagerly create tasks and we could investigate next enabling configuration cache as well.
=> Polish the Gradle build's configuration phase

rewrite-test/build.gradle.kts
Pinning the JUnit version to 5 major.
JUnit has just released `6.0.0-M1` an hour ago. And these versions require Java 17, which we are not ready to take.
=> Pin JUnit to 5.+

rewrite-core/src/main/java/org/openrewrite/semver/XRange.java, rewrite-core/src/test/java/org/openrewrite/semver/XRangeTest.java
- Changed the `isValid` check for `XRange` back to calling the `super`'s version of the method first, so if you're on `3.5.0` and trying to upgrade to `3.6.x`, if there are `3.6.1-SNAPSHOT` and `3.6.0` available, it will take `3.6.0`.
=> Adjusting the `isValid` check for `XRange` so that it doesn't allow for going from release to pre-release versions when upgrading.

rewrite-java-test/src/test/java/org/openrewrite/java/AddOrUpdateAnnotationAttributeTest.java, rewrite-java/src/main/java/org/openrewrite/java/AddOrUpdateAnnotationAttribute.java
- Restore the intention of the `addOnly` property. It's meant to enable a "AddAnnotationAttribute recipe" mode; this mode guarantees existing annotation parameters are not changed. _It should not be mingled with another option, which makes it hard to understand, thus hard to use well._
- With the `appendArray` option:
-  **off or disabled**: the recipe will replace the current initializer expressions with the new expressions. This is in line with the non-array annotation attributes, which also will totally replace the old value with the new attributeValue (albeit a single value). 
- **enabled**: the recipe will not replace the current initializer expressions with the new expressions, but will extend the list of expressions with the given attributeValue(s).
- Array annotation attributes …
=> Untangle the `addOnly` and `appendArray` options for AddOrUpdateAnnotationAttribute recipe

rewrite-javascript/rewrite/src/javascript/print.ts, rewrite-javascript/rewrite/test/javascript/parser/method.test.ts
Adding the logic to print out the `*` for generator methods with computed property name.
Similar to what we have for functions and methods.
It was missing. Thus parsing was not idempotent.
=> JavaScript - printing out the missing Generator asterisk for ComputedPropertyMethods

rewrite-gradle/src/test/java/org/openrewrite/gradle/GradleParserTest.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/GroovyParserTest.java
Added support for trailing comma in GroovyParser. Using `Marker.TrailingComma` as suggested in the original issue.
- Fixes https://github.com/openrewrite/rewrite/issues/4614
Usage of the `Marker`
=> Support trailing comma in GroovyParser

rewrite-java-test/src/test/java/org/openrewrite/java/JavaTemplateAnnotationTest.java, rewrite-java/src/main/java/org/openrewrite/java/internal/template/JavaTemplateJavaExtension.java
Removed `autoFormat` when processing annotations as it was causing broader indentation issues downstream
=> Reverting `autoFormat` in `JavaTemplateJavaExtension` that was causing unnecessary extra indentation for annotations.

rewrite-maven/src/test/java/org/openrewrite/maven/search/DoesNotIncludeDependencyTest.java
Re enabled and brought back into shape the `DoesNotIncludeDependencyTest` tests
Some work is being done on a Gradle variant so good to have a maven example
=> Re enable `DoesNotIncludeDependencyTest` tests

rewrite-javascript/rewrite/src/test/rewrite-test.ts
Adding an additional check to the `spec.rewriteRun` test framework in JavaScript.
Namely to validate that neither `before` and `after` has non-whitespace characters in their whitespace elements.
To catch parsing and recipe errors.
Similar to what we have in Java in `WhitespaceValidationService`.
=> JavaScript - adding ValidateWhitespaceVisitor to test

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/MethodInvocationTest.java
Fixes https://github.com/openrewrite/rewrite/issues/5729
Added `boolean implicitCall` which checks if the method that is being invoked (e.g. "call") is not actually present at the current cursor position in the source.
Groovy allows implicit invocation of closures using syntax like `foo { }()`, which look like `foo({}).call()`. 
In these cases, `visitMethodCallExpression(MethodCallExpression call)` gets `call = "call"` and tries to extract the method name from the source using substring, which caused `StringIndexOutOfBoundsException` - because the `call` identifier is not present in the source.
Another way would be just to hardcode the `call` name, like:
```
if("call".equals(methodNameExpression))
```
=> Fix: handle implicit closure call in Groovy

.github/workflows/nightly-ci.yml
fix nightly ci?
Its been failing for approximately 2 weeks.
the CI workflow works and when i compare the two workflows i noticed the node auth token was missing.
☝️
=> nightly-ci was missing node_auth_token

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java
The UpgradeTransitiveDependencyVersion recipe does support properties:
- defined in a properties file
- defined in the `ext` block in the settings.gradle file (Groovy DSL only)
Improvement of thie recipe, just like https://github.com/openrewrite/rewrite/commit/c323d4cced0815c17dbcd9c34af34300c924c81c did for the UpgradeDependencyVersion recipe.
At one point we should consider to either introduce utility methods or merge this recipe with UpgradeDependencyVersion, as both recipes have a lot of common code. For now I just improved this recipe, so it does support external properties without relying on other components.
=> Support for external properties for UpgradeTransitiveDependencyVersion recipe

rewrite-java-test/src/test/java/org/openrewrite/java/format/MinimumViableSpacingTest.java, rewrite-java/src/main/java/org/openrewrite/java/format/MinimumViableSpacingVisitor.java
- Added test for `implements` and `extends`
- Fixed a bug when dealing with classes extending
=> MinimalViableSpacing recipe does not handle `extends` correctly

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/ConstructorTest.java
Diamond operators (`<>`) are now correctly supported when creating new generic instances like `new ArrayList<>()`.
Previously, using `new ArrayList<>()` would incorrectly render as `new ArrayList<>()>()`, due to missing type inference information.
We did already support `new HashMap<>()`; this was only because the Groovy compiler happened to set the `StaticTypesMarker.INFERRED_TYPE` flag in that case. However, this flag is not consistently applied. This change ensures support even when the flag is missing by also checking if the generic type list is empty.
Interestingly, when the flag is present, the generic types are populated, which means we need to handle both cases: either rely on the flag or detect when the generics are empty.
=> Add support for diamond operator in Groovy Parser

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/LambdaTest.java
Lambda's within curly braces are supported.
Parser failed with:
```groovy
assertThrows(IllegalArgumentException.class, () -> {
// some statement
})
```
=> Groovy parser supports lambda's with curly braces

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyPrinter.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/tree/G.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/BinaryTest.java
The `**`, `**=`, `===` and `!==` operators are supported.
Improve groovy parser completeness.
=> Add identical and power operators to Groovy Parser

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateJavaCompatibility.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateJavaCompatibilityTest.java
- Shorthand [jvmToolchain](https://kotlinlang.org/docs/gradle-configure-project.html#gradle-java-toolchains-support) is updated.
- Support for [JavaLanguageVersion.of(‹string›)](https://docs.gradle.org/current/javadoc/org/gradle/jvm/toolchain/JavaLanguageVersion.html#of(java.lang.String)).
Code like 
```kotlin
kotlinVersion = '1.9.21'
kotlin {
jvmToolchain(11)
}
```
was not picked up to be upgraded to a newer version.
=> `UpdateJavaCompatibility` supports `jvmToolchain` shorthand

.claude/settings.local.json, rewrite-javascript/rewrite/src/javascript/parser.ts, rewrite-javascript/rewrite/src/javascript/print.ts, rewrite-javascript/rewrite/src/javascript/rpc.ts, rewrite-javascript/rewrite/src/javascript/tree.ts, rewrite-javascript/rewrite/src/javascript/visitor.ts, rewrite-javascript/rewrite/test/javascript/parser/jsx.test.ts, rewrite-javascript/src/integTest/java/org/openrewrite/javascript/JavaScriptParserTest.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/JavaScriptVisitor.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/rpc/JavaScriptReceiver.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/internal/rpc/JavaScriptSender.java, rewrite-javascript/src/main/java/org/openrewrite/javascript/tree/JSX.java
Adding support for generics in JSX tags.
It was missed when JSX supported was added. And people use this feature, so why not?
=> Javascript - add support for generics in JSX/TSX tags

rewrite-yaml/src/main/java/org/openrewrite/yaml/CoalesceProperties.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/CoalescePropertiesVisitor.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/UnfoldProperties.java, rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlVisitor.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/CoalescePropertiesTest.java
The CoalesceProperties recipe now supports two additional options: exclusions and applyTo.
With the introduction and growing use of the UnfoldProperties recipe, which acts as the counterpart to CoalesceProperties, the two recipes became slightly unbalanced in terms of functionality. By adding these two new options, the CoalesceProperties recipe now aligns more closely with its counterpart.
The UnfoldProperties recipe supports certain features of JsonPath Plus syntax. This was essential for that recipe to handle dotted keys correctly, as it would not function without that capability. However, this is not the case for CoalesceProperties, which can operate without dot support. Therefore, I opted to keep this version simpler and limited the enhancement to elevating the JsonPathMatcher.
=> Add `exclusions` and `applyTo` options to CoalesceProperties

rewrite-java-test/src/test/java/org/openrewrite/java/RenameVariableTest.java, rewrite-java/src/main/java/org/openrewrite/java/RenameVariable.java
This PR fixes an issue in the `RenameVariable` recipe where class literal references (e.g., `SomeClass.class`) were not correctly detected, potentially causing incorrect renaming. The detection logic now checks if the parent AST node is a `J.FieldAccess` whose name is `"class"`, which is the canonical OpenRewrite representation of a class literal.
Fixes incorrect renaming of variables when encountering class literal references. This ensures that class literals are not affected by the rename operation. (No linked issue, but discovered during recipe usage and test coverage.)
- Closes https://github.com/openrewrite/rewrite/issues/5843
Please review the logic in `RenameVariable.RenameVariableVisitor#isClassLiteralReference` and the associated unit test …
=>  fix: prevent variable renaming in class literal references

rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
Error message "The recipe generated source files the test did not expect" is always shown when needed.
When the `after` result is null and a test-fail message should be reported, it throwed a npe. Also the report was wrong when the `after` result was not null, as the after source was used as before source.
=> Fix the error message when a recipe test generates source files the test does not expect

rewrite-maven/src/main/java/org/openrewrite/maven/tree/MavenResolutionResult.java, rewrite-maven/src/test/java/org/openrewrite/maven/RemoveLog4JBomTest.java
Thanks for the helpful reproducers @xLitil 
By only `put`ting if absent, the resulting `Map` now contains the requested pom of the level in the hierarchy and not the deeper nested ones. As we make changes to the pom itself and not to the child's parent references, the update marker was failing to resolve due to a child's requested pom overwriting the parent requested pom.
- Fixes https://github.com/openrewrite/rewrite/issues/5673
Should we rework the code to update all the child's parent references when removing dependency? I think this should suffice as the parents references are update in a later stage to the newly calculated parent. We just had to be able to calculate the parent which was failing. 
Now I also wonder if we can ever come in the situation where we do not start from the …
=> Avoid overwriting parent pom from marker when going in child.

rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java, rewrite-maven/src/test/java/org/openrewrite/maven/ChangeDependencyGroupIdAndArtifactIdTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/MavenParserTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeDependencyVersionTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/cleanup/PrefixlessExpressionsTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/utilities/PrintMavenAsDotTest.java
Using a `Map<GroupArtifact, DependencyAndDependent>` instead of a `List<DependencyAndDependent>` we can use the `put` method to overwrite earlier occurring requested `DependencyAndDependent` objects in the pom. 
**TODO**: verify with @sambsnyd if we do not want to use the `merge` method and introduce a ResolutionStrategy to differentiate between Maven's last-wins and Gradle's latest-wins.
Maven resolves duplicate dependencies by using the last declaration. Previously, our parser did not follow this behavior, causing issues where only the first occurrence was updated by recipes, but the effective version was still determined by the last. This change updates the parser logic to ensure that, when multiple dependencies with the same coordinates are declared, the last one takes precedence, …
=> Ensure Maven parser uses last-wins strategy for duplicate dependencies

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java, rewrite-maven/src/main/java/org/openrewrite/maven/UpgradeTransitiveDependencyVersion.java
When the GradleDependencyConfiguration is compared, it should not take the version into account. This PR replaces by a `c.allExtendsFrom().contains(config)` call to a loop where only the _name_ is used for comparison.
With the change of
- https://github.com/openrewrite/rewrite/pull/5794
the recipe turned into a scanning recipe, which means when in the scanning phase, no changes to the code have been made. If this recipe is run multiple times by another recipe (so still one recipe run), this has an impact on the resolution. Instead of the versions already been upgraded, it can differ between runs and scans.
=> UpgradeTransitiveDependencyVersion should only compare name when comparing the config with the GradleDependencyConfiguration

rewrite-maven/src/main/java/org/openrewrite/maven/utilities/PrintMavenAsDot.java, rewrite-maven/src/test/java/org/openrewrite/maven/utilities/PrintMavenAsDotTest.java
We were seeing some flaky tests lately, possibly following:
- https://github.com/openrewrite/rewrite/pull/5821
=> Stable label order for `PrintMavenAsDot`

rewrite-java/src/main/java/org/openrewrite/java/AddCommentToImport.java, rewrite-java/src/test/java/org/openrewrite/java/AddCommentToImportTest.java
Added recipe to allow you to add a comment to an import or multiple imports depending on the pattern provided.
There are some scenarios where we're not going to be able to provide an adequate migration for the usage of a class (like `HttpParams` for example, because it can be populated by any number of things and has been replaced with multiple different classes depending on the usage context). In these cases, we might want to add a comment to imports of the class with some helpful links on how they might be manually replaced instead.
=> Adding recipe for adding comments to import statements

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyTemplate.java, rewrite-java/src/main/java/org/openrewrite/java/JavaTemplate.java, rewrite-kotlin/src/main/java/org/openrewrite/kotlin/KotlinTemplate.java, rewrite-kotlin/src/test/java/org/openrewrite/kotlin/KotlinTemplateTest.java
This makes `KotlinTemplate#parser()` public so the parser can be set externally.  Does some, admittedly tangential, clean up to reduce duplication between `KotlinTemplate` and `JavaTemplate`.
This fixes 
- #5889
=> Make the parser settable on KotlinTemplate

rewrite-java-test/src/test/java/org/openrewrite/java/RemoveObjectsIsNullTest.java, rewrite-java/src/main/java/org/openrewrite/java/RemoveObjectsIsNull.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Dependency.java
- Fixes https://github.com/openrewrite/rewrite/issues/4031
=> Call `UnnecessaryParenthesesVisitor` on parent after `RemoveObjectsIsNull`

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Prevents the downgrade of a dependency version defined in Settings file by the org.openrewrite.gradle.UpgradeDependencyVersion recipe if referenced from `buildscript` via extra property.
Given the following build script:
```
buildscript {
repositories {
mavenCentral()
}
dependencies {
classpath "com.fasterxml.jackson.core:jackson-databind:${gradle.jackson}"
}
}
```
and the settings file with the following contents:
```
gradle.ext {
jackson = '2.13.3'
}
```
A run of the org.openrewrite.gradle.UpgradeDependencyVersion with a lower version
```
$ mod run . --recipe org.openrewrite.gradle.UpgradeDependencyVersion --recipe-option "groupId=com.fasterxml.jackson.core" --recipe-option "artifactId=jackson-databind" --recipe-option "newVersion=2.13.2"
```
should not downgrade the version. The recipe …
=> Prevent version downgrade in Settings file referenced by buildscript

rewrite-gradle/src/main/java/org/openrewrite/gradle/marker/GradleDependencyConfiguration.java, rewrite-maven/src/main/java/org/openrewrite/maven/tree/Dependency.java
This is required for existing models, which haven't been updated yet since this feature was added.
```
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because the return value of "org.openrewrite.maven.attributes.Attributed.getAttributes()" is null
org.openrewrite.maven.attributes.Attributed.findAttribute(Attributed.java:40)
org.openrewrite.gradle.marker.GradleDependencyConfiguration$LazyResolutionContext.resolve(GradleDependencyConfiguration.java:185)
org.openrewrite.gradle.marker.GradleDependencyConfiguration.getDirectResolved(GradleDependencyConfiguration.java:103)
org.openrewrite.gradle.marker.GradleDependencyConfiguration.getResolved(GradleDependencyConfiguration.java:112)
org.openrewrite.gradle.trait.GradleDependency$Matcher.test(GradleDependency.java:154) …
```
=> Make sure `Attributed#getAttributes()` does not return `null`

rewrite-gradle/src/main/java/org/openrewrite/gradle/marker/GradleDependencyConfiguration.java
This is for backwards compatibility.
=> Mark `GradleDependencyConfiguration#constraints` as nullable

rewrite-java/src/main/java/org/openrewrite/java/AddCommentToMethodInvocations.java, rewrite-java/src/test/java/org/openrewrite/java/AddCommentToMethodInvocationsTest.java
When provided with a method pattern like `com.example.Something <constructor>(..)` it will now also match those
Need this for another PR related to usages of a class that does not have a migration path
=> Extending `AddCommentToMethodInvocations` to handle constructors as well

rewrite-gradle-tooling-model/model/build.gradle.kts
Atm, publishing of the last release (the first one with this module) is happening to the `org.openrewrite` group. 
This clashes with the existing group and might make users unaware of new available versions. 
We still have a big version jump from 3.x to 8.x, but that's not really something we can fix right now, i guess.
You can see that the original code also had this property applied by applying it on all subprojects: https://github.com/openrewrite/rewrite-gradle-tooling-model/blob/main/build.gradle.kts#L5
During move, it was only set on the plugin section, not the model.
=> Set group and description for rewrite-gradle-tooling-model

rewrite-maven/src/main/java/org/openrewrite/maven/tree/ResolvedPom.java
```
Caused by: java.lang.IllegalStateException: Unable to get values of org.jspecify:jspecify:1.0.0
at org.openrewrite.maven.tree.ResolvedPom.getValues(ResolvedPom.java:1227)
at org.openrewrite.maven.tree.ResolvedPom.resolveDependencies(ResolvedPom.java:1011)
at org.openrewrite.maven.tree.ResolvedPom.resolveDependencies(ResolvedPom.java:984)
at org.openrewrite.maven.tree.MavenResolutionResult.resolveDependencies(MavenResolutionResult.java:189)
... 18 common frames omitted
Caused by: java.util.ConcurrentModificationException: null
at java.base/java.util.ArrayList.sort(ArrayList.java:1723)
at org.openrewrite.maven.tree.ResolvedPom.getDependencyManagement(ResolvedPom.java:145)
at org.openrewrite.maven.tree.ResolvedPom.getManagedDependency(ResolvedPom.java:379)
at …
```
=> Fix concurrent modification exception on sorting

rewrite-java/src/main/java/org/openrewrite/java/InlineMe.java, rewrite-java/src/main/java/org/openrewrite/java/InlineMethodCalls.java, rewrite-java/src/test/java/org/openrewrite/java/InlineMethodCallsTest.java
Add an annotation and associated recipe, which supports any recipe with the same structure: our own, Google's or a library specific one, much like `@Nullable` can come from a variety of libraries
Allow folks to easily mark methods for replacement with an argument template. We have these use cases internally for our libraries any moment we expand a constructor with a new nullable argument, or when deprecating a method with a clear one to one replacement using (some of) the same arguments.
It's already used in libraries like Guava, where we can now do such replacements just from having the library on the classpath.
Would we want to support and promote this going forward?
- Instead of `@InlineMe` I've considered `@ReplaceWith`, to more clearly state that it's not just for inlining. We can …
=> Add `@InlineMe` and `InlineMethodCalls` recipe to replace annotated methods

rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java, rewrite.yml
As discovered on
- https://github.com/openrewrite/rewrite-static-analysis/pull/727#discussion_r2309690738
Before we had
https://github.com/openrewrite/rewrite/blob/8ce5308a9557dd6ca91253a5c8fb7e6c34a0ef5a/rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java#L1563-L1572
Which then led to calling equals on the `declaringType` first, which for `FullyQualified.Class` looks like:
https://github.com/openrewrite/rewrite/blob/8ce5308a9557dd6ca91253a5c8fb7e6c34a0ef5a/rewrite-java/src/main/java/org/openrewrite/java/tree/JavaType.java#L576-L583
Whereas the `name` is just a String that we can more cheaply compare and reject, making it unnecessary to do name comparisons first in
https://github.com/openrewrite/rewrite-static-analysis/blob/232339c63ac81a5e47275a093beb845154b6f745/src/main/j …
=> Compare `JavaType.Method.name` before `declaringType` in `equals(Object)`

rewrite-benchmarks/src/jmh/java/org/openrewrite/benchmarks/java/ChangeMethodTargetToStaticBenchmark.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/ChangeDependencyTest.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/ChangePluginTest.java, rewrite-java-test/src/test/java/org/openrewrite/java/ChangeMethodTargetToStaticTest.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.InlineMethodCalls?organizationId=QUxML09wZW4gU291cmNlL09wZW5SZXdyaXRl
=> Replace deprecated constructors with their suggestions

rewrite-yaml/src/main/java/org/openrewrite/yaml/YamlParser.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/tree/MappingTest.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/tree/SequenceTest.java
rewrite-yaml's parsing of anchored maps within a sequence, as described by my issue 
- #5924
The parsing of valid yaml containing an anchored map within a sequence would result in the `-` being dropped in the output - which is invalid yaml in some cases.
I was unsure why `fmt` was being reevaluated within the anchoring block, as the motivation was not commented and was the source of this bug. I've removed the fmt and resolved the handling of the `-` and anchor prefix.
n/a
=> fix(yaml): handle anchored map within sequence

rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java
As reported via Slack this helps recipes written in Kotlin; follows on from:
- https://github.com/openrewrite/rewrite/pull/5595
=> `RewriteTest` should load recipes through `RecipeLoader`, not `RecipeIntrospectionUtils`

rewrite-core/src/main/java/org/openrewrite/marker/OperatingSystemProvenance.java, rewrite-core/src/test/java/org/openrewrite/marker/OperatingSystemProvenanceTest.java
Removing the constants for particular OSes in `OperatingSystemProvenance`, replacing it with lazy-loaded private map.
- Fix a concurrency bug in `OperatingSystemProvenance` and its inner classes
- ... which led to Moderne CLI dead-lock when deserializing LSTs coming from various sources (i.e. some built on Linux in Moderne SaaS, some built locally on my Mac laptop)
- Although we are adding lazy-init logic for these subclass instances (e.g. Linux). We don't care that much if they are not singletons - i.e. something (e.g. Jackson deserialization of LSTs) creates multiple instances of Linux.
- What we are optimizing here is not to have a deadlock during class init.
=> Fix against a deadlock when concurrently creating OperatingSystemProvenance markers

rewrite-gradle/src/main/java/org/openrewrite/gradle/util/GradleWrapper.java
Ensure usage of `currentDistributionUrl` with respect to dynamically listing versions from a private Artifactory is limited to HTTP(S) and a path beginning with `/artifactory`. This ensures that we can reach the Artifactory REST API for listing versions without being inadvertently redirected to the HTML directory listing that Artifactory also supports.
Fixes #5994.
N/A
N/A
We could add logic to parse the HTML as was suggested via #5995, but this runs the risk of being pretty fragile.
N/A
=> Only trigger Artifactory private listing when using HTTP(S) and the path beginning with Artifactory

rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeTransitiveDependencyVersionTest.java, rewrite-maven/src/main/java/org/openrewrite/maven/AddManagedDependency.java, rewrite-maven/src/test/java/org/openrewrite/maven/AddManagedDependencyTest.java, rewrite-maven/src/test/java/org/openrewrite/maven/UpgradeTransitiveDependencyVersionTest.java
Changes the logic in the AddManagedDependency recipe to prevent version downgrade for transitive dependencies.
A Maven build defines two dependencies with transitive dependencies on com.fasterxml.jackson.core:jackson-databind. The transitive dependency versions are different.
- jackson-dataformat-xml:2.18.0 → jackson-databind:2.18.0
- jackson-datatype-jsr310:2.15.3 → jackson-databind:2.15.3
Requesting a lower version than 2.18.0, downgrades the transitive dependency com.fasterxml.jackson.core:jackson-databind which should not be allowed.
The same behavior cannot be observed for a Gradle build.
=> UpgradeTransitiveDependencyVersion should not downgrade a transitive dependency version if lower than resolved version

rewrite-core/src/main/java/org/openrewrite/semver/CaretRange.java, rewrite-core/src/main/java/org/openrewrite/semver/HyphenRange.java, rewrite-core/src/main/java/org/openrewrite/semver/LatestRelease.java, rewrite-core/src/main/java/org/openrewrite/semver/SetRange.java, rewrite-core/src/main/java/org/openrewrite/semver/TildeRange.java, rewrite-core/src/main/java/org/openrewrite/semver/XRange.java, rewrite-core/src/test/java/org/openrewrite/semver/CaretRangeTest.java, rewrite-core/src/test/java/org/openrewrite/semver/HyphenRangeTest.java, rewrite-core/src/test/java/org/openrewrite/semver/LatestIntegrationTest.java, rewrite-core/src/test/java/org/openrewrite/semver/LatestMinorTest.java, rewrite-core/src/test/java/org/openrewrite/semver/LatestPatchTest.java, rewrite-core/src/test/java/org/openrewrite/semver/SetRangeTest.java, rewrite-core/src/test/java/org/openrewrite/semver/TildeRangeTest.java, rewrite-core/src/test/java/org/openrewrite/semver/XRangeTest.java
- `CaretRange` incorrect upper bound
- Add support for comparison of a `CaretRange` boundary when within an existing `CaretRange`
- Add support for comparison of a `HyphenRange` boundary when within an existing `HyphenRange`
- Add support for comparison of a `SetRange` boundary when within an existing `SetRange`
- Add support for comparison of a `TildeRange` boundary when within an existing `TildeRange`
- Add support for comparison of an `XRange` boundary when within an existing `XRange`
I'm reanalyzing the `SemVer` semantics because I have a use case within `UpdateGradleWrapper` in which I want to take the user supplied pattern and use that as a comparison against the current Gradle version discovered from the `BuildTool` marker. By enabling patterns to be compared within the same class, …
=> Introduce support for pattern matching within the `Semver` type classes

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/main/java/org/openrewrite/groovy/internal/Delimiter.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/EnumTest.java
- Similar to #6009.
Fixing the handling of closures as arguments to enums in Groovy.
A bug resulting in an infinite loop in parsing such Groovy files.
- https://github.com/allegro/axion-release-plugin/blob/5b331e64544a84fe4d81f2625ce31b0d2a8abb53/src/main/groovy/pl/allegro/tech/build/axion/release/domain/TagNameSerializer.groovy#L9
=> Groovy - handling closures `{}` in enums

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpdateGradleWrapper.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpdateGradleWrapperTest.java
In the current state, the recipe was always attempting to list the available versions, then compare these resolved versions against the current version to decide if there was any work to be done. However, as of the advent of dynamic SemVer resolution against private Artifactory distribution sources, these sources may not contain the requested Gradle distributions for a myriad of reasons -- because they were pruned as unused, were never brought in due to manual processes, etc -- so as a result the recipe would error out because it was unable to find _any_ versions that matched the requested pattern. 
By using recent changes in the `org.openrewrite.semver` package, we can now compare the requested SemVer version pattern against the current `BuildTool` version. By doing so, this enables us …
=> Retrieve available Gradle versions only when requested would result in a possible update

rewrite-core/src/main/java/org/openrewrite/FindSourceFiles.java, rewrite-core/src/main/java/org/openrewrite/table/SourcesFiles.java
Added encoding column to `SourceFiles` data table as part of `FindSourceFiles` recipe.
Character encoding tends to come up from time to time as an issue encountered with a source file contained within an LST. By including it in the data table, we can now observe the detected encoding across numerous repositories. This can also be informative for an organization when considering a migration from Java versions prior to Java 18 with respect to the new default character set is now universally UTF-8.
=> Add charset to `FindSourceFiles` data table

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java, rewrite-groovy/src/test/java/org/openrewrite/groovy/tree/EnumTest.java
In Groovy handling double-quoted arguments (i.e. Strings) in enum arguments in a different way than the other arguments. Here we shouldn't use the `sourceBefore()` hack which is designed to handle whitespace. Manual `cursor` advancement instead.
- fixes #6015
=> Groovy - special handling of double-quote values in enum arguments

rewrite-yaml/src/main/java/org/openrewrite/yaml/UnfoldProperties.java, rewrite-yaml/src/test/java/org/openrewrite/yaml/UnfoldPropertiesTest.java
Fixed the following bug.
When unfolding yaml: 
```yaml
logging.level.com.example: DEBUG
management.test:
a.b:
value: c
```
expected
```yaml
logging:
level:
com:
example: DEBUG
management:
test:
a:
b:
value: c
```
actual
```yaml
logging:
level:
com:
example: DEBUG
management:
test:
a:
b:
value: c
```
=> Fixed a bug where root entries with newlines in front would have the entire entry be indented after unfolding.

rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java
Added a guard for now -> a solution for proper parsing is being worked on 
- https://github.com/openrewrite/rewrite/pull/5293
Instead of throwing a `GroovyParsingException` the code will now properly flow into this handling https://github.com/openrewrite/rewrite/blob/765ad965581a5868e341d13096092a3e17e8dbe3/rewrite-groovy/src/main/java/org/openrewrite/groovy/GroovyParserVisitor.java#L1649-L1652 which gives a informational message on what's going on
I did verify with a test but that test remains failing so there's no sense in adding it
```
Caused by: org.openrewrite.groovy.GroovyParsingException: Failed to parse file.groovy at cursor position 17. The surrounding characters in the original source are:
tag = '0.0.0'
def~cursor~> (major, minor, patch) = tag.tokenize('.')
at …
```
=> Groovy: Guard against NPE when coming across a multi variable assignment

rewrite-gradle/src/main/java/org/openrewrite/gradle/UpgradeDependencyVersion.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/UpgradeDependencyVersionTest.java
Adds support for parsing the property name when using the following APIs:
- [Project#property(String)](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#property(java.lang.String))
- [Project#findProperty(String)](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#findProperty(java.lang.String))
- [Project#getProperties()](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#getProperties())
Using the `project` reference is implied in the Groovy DSL so we need to support the use with and without it. We also needed to make sure that GString interpolation works (while poor practices if just wrapped into double quotes without adding anything to the String).
A property defined in `gradle.properties` can be accessed in a variety of ways in the …
=> UpgradeDependencyVersion needs to support common Groovy property access notations

rewrite-core/src/main/java/org/openrewrite/table/RecipeRunStats.java
The only operational use of P99 is in A/B testing and we haven’t ever operated something like that for multiple versions of recipes.
=> Remove 99-percentile columns from `RecipeRunStats` data table

rewrite-core/src/main/java/org/openrewrite/RecipeRun.java, rewrite-core/src/test/java/org/openrewrite/DataTableTest.java, rewrite-test/src/main/java/org/openrewrite/test/RecipeSpec.java
Previously if multiple different instances of the same data table were created in a recipe run we'd return the results from only one of them. And it would be chosen, effectively, at random based on the iteration order of an unordered collection.
=> Fix missing rows when multiple recipes write to the same data table in the same recipe run.

rewrite-javascript/rewrite/src/javascript/index.ts, rewrite-javascript/rewrite/src/javascript/remove-import.ts, rewrite-javascript/rewrite/src/javascript/visitor.ts, rewrite-javascript/rewrite/src/visitor.ts, rewrite-javascript/rewrite/test/javascript/remove-import.test.ts
JavaScript has unique import structures, so support a general purpose `RemoveImport` visitor usable in many recipes.
=> JavaScript `RemoveImport` visitor

rewrite-gradle-tooling-model/model/src/main/java/org/openrewrite/gradle/marker/GradleProjectBuilder.java, rewrite-gradle-tooling-model/plugin/src/main/java/org/openrewrite/gradle/toolingapi/ToolingApiOpenRewriteModelPlugin.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/marker/GradleProjectTest.java
This PR changes the logic in GradleProjectBuilder mapRepositories
We are now mapping the Maven Repository "username" and "password" if they exist.
- Closes https://github.com/openrewrite/rewrite/issues/6044
=> Use Maven repository credentials in `GradleProjectBuilder`

rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePlugin.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddPluginVisitor.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/plugins/AddSettingsPluginRepository.java, rewrite-gradle/src/main/java/org/openrewrite/gradle/search/FindRepository.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddDevelocityGradlePluginTest.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/plugins/AddSettingsPluginRepositoryTest.java, rewrite-gradle/src/test/java/org/openrewrite/gradle/search/FindRepositoryTest.java
Extends the `AddSettingsPluginRepository` recipe to support Kotlin DSL settings files (`settings.gradle.kts`) in addition to the existing Groovy settings file (`settings.gradle`) support.
- **Refactored visitor hierarchy**: Changed from `GroovyIsoVisitor` to `JavaIsoVisitor` to handle both Groovy and Kotlin ASTs
- **Added K.CompilationUnit support**: Implemented separate visitor methods for both `G.CompilationUnit` (Groovy) and `K.CompilationUnit` (Kotlin)
- **Improved code generation**: Updated template code generation to produce syntax appropriate for each language (e.g., `url = "..."` for Groovy vs `url = uri("...")` for Kotlin)
- **Enhanced FindRepository**: Updated to work with both Groovy and Kotlin file types
- **Kotlin string template handling**: Added `TemplateAsString` helper …
=> Add Kotlin settings file support to AddSettingsPluginRepository
